-- Better NPC Passengers - Arabic Localization
-- ملف الترجمة العربية

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "ركاب NPC المحسّن")
language.Add("npcpassengers.settings", "الإعدادات")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "عام")
language.Add("npcpassengers.nav.autojoin", "انضمام تلقائي")
language.Add("npcpassengers.nav.passengers", "الركاب")
language.Add("npcpassengers.nav.position", "الموضع")
language.Add("npcpassengers.nav.behaviour", "السلوك")
language.Add("npcpassengers.nav.keybinds", "ربط المفاتيح")
language.Add("npcpassengers.nav.hud", "واجهة العرض")
language.Add("npcpassengers.nav.driver", "السائق")
language.Add("npcpassengers.nav.help", "مساعدة")

-- General Settings
language.Add("npcassengers.general.header", "الإعدادات العامة")
language.Add("npcpassengers.allow_multiple", "السماح بركاب متعددة")
language.Add("npcpassengers.allow_multiple.help", "يسمح لعدة من NPCs السفر في نفس المركبة.")
language.Add("npcpassengers.exit_behavior", "سلوك الخروج")
language.Add("npcpassengers.exit_behavior.help", "متى يجب على الركاب NPC مغادرة المركبة؟")
language.Add("npcassengers.exit_mode.leave_player", "مغادرة عندما يغادر اللاعب")
language.Add("npcpassengers.exit_mode.leave_attack", "مغادرة عند مهاجمة المركبة")
language.Add("npcpassengers.exit_mode.never", "لا تغادر تلقائياً")

-- Timing Settings
language.Add("npcpassengers.timing.header", "التوقيت")
language.Add("npcpassengers.max_attach_dist", "أقصى مسافة إرفاق")
language.Add("npcpassengers.max_attach_dist.help", "أقصى مسافة (وحدات) لرفق NPC بالمركبة.")
language.Add("npcpassengers.detach_delay", "تأخير الفصل")
language.Add("npcpassengers.detach_delay.help", "الثواني للانتظار قبل الفصل بعد مغادرة اللاعب.")
language.Add("npcpassengers.ai_delay", "تأخير استعادة الذكاء الاصطناعي")
language.Add("npcpassengers.ai_delay.help", "الثواني للانتظار قبل استعادة ذكاء NPC بعد الفصل.")
language.Add("npcpassengers.cooldown", "وقت التبريد")
language.Add("npcpassengers.cooldown.help", "وقت التبريد بين رفع NPCs إلى نفس المركبة.")
language.Add("npcpassengers.passenger_limit", "حد الركاب")
language.Add("npcpassengers.passenger_limit.help", "أقصى عدد من NPCs المسموح بهم في المركبة.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "انضمام تلقائي (سلوك الفريق)")
language.Add("npcpassengers.autojoin.desc", "الـ NPCs الودوديون سيركبون تلقائياً مركبتك عندما تدخلها، تماماً مثل آلية الفريق في Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "تفعيل الانضمام التلقائي")
language.Add("npcpassengers.autojoin.enable.help", "الـ NPCs الودوديون القريبون سيركبون تلقائياً عندما تدخل مركبة.")
language.Add("npcpassengers.autojoin.range", "نطاق الانضمام التلقائي")
language.Add("npcpassengers.autojoin.range.help", "أقصى مسافة للعثور على NPCs للانضمام التلقائي.")
language.Add("npcpassengers.autojoin.max", "أقصى NPCs للانضمام التلقائي")
language.Add("npcpassengers.autojoin.max.help", "الحد الأقصى من NPCs التي يمكنها الانضمام تلقائياً في وقت واحد.")
language.Add("npcpassengers.autojoin.squad_only", "أعضاء الفريق فقط")
language.Add("npcpassengers.autojoin.squad_only.help", "فقط NPCs مع اسم فريق سينضمام تلقائياً (للفرق نمط HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "الـ NPCs الودوديون القريبون سيركبون تلقائياً مركبتك عندما تدخلها، تماماً مثل آلية الفريق في Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "التحكم في الركاب")
language.Add("npcpassengers.panel.passengers.desc", "إدارة الركاب النشطين، تصفية بالاسم/الفئة/الحالة، نسخ معلومات التصحيح، إعادة تعيين المقاعد، وفصل الركاب دون مغادرة لوحة الإعدادات.")
language.Add("npcpassengers.panel.position.desc", "ضبط موضع NPCs في المركبات بدقة. استخدم هذا لإصلاح مشاكل الطفو أو التداخل.")
language.Add("npcpassengers.panel.angle.desc", "ضبط دوران NPCs في المركبات.")
language.Add("npcpassengers.panel.speech.desc", "تكوين كيفية نطق الـ NPCs أثناء السفر في المركبات. أصوات مواطن نمط HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "إزاحات الموضع")
language.Add("npcpassengers.position.desc", "ضبط موضع NPCs في المركبات بدقة. استخدم هذا لإصلاح مشاكل الطفو أو التداخل.")
language.Add("npcpassengers.height_offset", "إزاحة الارتفاع")
language.Add("npcpassengers.forward_offset", "إزاحة الأمام")
language.Add("npcpassengers.right_offset", "إزاحة اليمين")
language.Add("npcpassengers.angle.header", "إزاحات الزاوية")
language.Add("npcpassengers.angle.desc", "ضبط دوران NPCs في المركبات.")
language.Add("npcpassengers.yaw_offset", "اليس (الدوران)")
language.Add("npcpassengers.pitch_offset", "الملام (الميل الأمامي)")
language.Add("npcpassengers.roll_offset", "التمهيل (الميل الجانبي)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "صوت NPC (متقدم)")
language.Add("npcpassengers.behaviour.desc", "تكوين كيفية نطق الـ NPCs أثناء السفر في المركبات. أصوات مواطن نمط HL2!")
language.Add("npcpassengers.speech_enable", "تفعيل صوت NPC")
language.Add("npcpassengers.speech_enable.help", "التبديل الرئيسي لجميع صوت NPC. قم بإيقافه لجعل الركاب صامتين تماماً.")
language.Add("npcpassengers.speech_volume", "حجم الصوت")
language.Add("npcpassengers.speech_volume.help", "مدى صوت NPCs (0 = صامت، 100 = حجم كامل).")
language.add("npcpassengers.pitch_variation", "تغير درجة الصوت (+/-)")
language.Add("npcpassengers.pitch_variation.help", "تغيير عشوائي في درجة الصوت لأصوات أكثر طبيعية. 0 = أحادي، أعلى = المزيد من التنوع.")
language.Add("npcpassengers.crash.header", "ردود التصادم")
language.Add("npcpassengers.crash_enable", "تفعيل أصوات التصادم")
language.Add("npcpassengers.crash_enable.help", "الـ NPCs يئنون/يصرخون عندما تتباطأ المركبة بشدة (تصادم، فرملة شديدة).")
language.Add("npcpassengers.crash_threshold", "حساسية التصادم")
language.Add("npcpassengers.crash_threshold.help", "التباط المطلوب لتحري أصوات التصادم. أقل = أكثر حساسية.")
language.Add("npcpassengers.crash_cooldown", "تبريد صوت التصادم")
language.Add("npcpassengers.crash_cooldown.help", "الحد الأدنى للثواني بين أصوات التصادم لكل NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "تفعيل الدردشة غير النشطة")
language.add("npcpassengers.speech_board", "تفعيل أصوات الصعود/النزول")
language.Add("npcpassengers.ambient_sounds", "تفعيل الأصوات المحيطة")
language.Add("npcpassengers.head_look", "تفعيل النظر للرأس/العين")
language.Add("npcpassengers.blink", "تفعيل الرمش")
language.Add("npcpassengers.breathing", "تفعيل التنفس")
language.Add("npcpassengers.talking_gestures", "تفعيل إيماءات الكلام")
language.Add("npcpassengers.crash_flinch", "تفعيل رد الفعل للتصادم")
language.Add("npcpassengers.body_sway", "تفعيل تمايل الجسم")
language.Add("npcpassengers.threat_awareness", "تفعيل وعي التهديد")
language.Add("npcpassengers.combat_alert", "تنبيه القتال")
language.Add("npcpassengers.passenger_combat", "الـ NPCs يطلقون من المركبات (تجريبي)")
language.Add("npcpassengers.passenger_interaction", "تفاعل الركاب")
language.Add("npcpassengers.fear_reactions", "تفعيل ردود الخوف")
language.Add("npcassengers.drowsiness", "تفعيل النعاس")
language.Add("npcpassengers.hide_in_tanks", "إخفاء NPCs في المركبات المغلقة")
language.Add("npcpassengers.eject_stuck_check", "طرد تلقائي للـ NPCs العالقين")
language.Add("npcpassengers.detach_no_collide", "لا تصادم مع المركبة بعد الفصل")
language.Add("npcpassengers.die_with_vehicle", "قتل الركاب عندما تنفجر المركبة")
language.Add("npcpassengers.driver_enabled", "تفعيل القيادة التلقائية")
language.Add("npcpassengers.turret_enabled", "تفعيل التحكم في البرج")
language.Add("npcpassengers.turret_lead_targets", "التنبؤ بالأهداف")
language.Add("npcpassengers.turret_friendly_fire", "السماح بالنيار الصديق")
language.Add("npcpassengers.turret_hold_fire", "الاحتفاظ بالنار (تعطيل إطلاق النار)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "حجم الصوت")
language.Add("npcpassengers.pitch_variation", "تغير درجة الصوت (+/-)")
language.Add("npcpassengers.crash_threshold", "حساسية التصادم")
language.Add("npcpassengers.crash_cooldown", "تبريد صوت التصادم")
language.Add("npcpassengers.speech_idle_chance", "احتمالية الدردشة")
language.Add("npcpassengers.speech_idle_interval", "فاصل الدردشة")
language.Add("npcpassengers.ambient_interval", "فاصل الصوت المحيطي")
language.Add("npcpassengers.head_smooth", "نعومة الرأس")
language.Add("npcpassengers.walk_timeout", "مهلة المشي")
language.Add("npcpassengers.gesture_chance", "احتمالية الإيماءة (%)")
language.Add("npcpassengers.gesture_interval", "فاصل الإيماءة")
language.Add("npcpassengers.crash_threshold_flinch", "حساسية التصادم")
language.Add("npcassengers.body_sway_amount", "شدة التمايل")
language.Add("npcpassengers.threat_range", "نطاق كشف التهديد")
language.Add("npcpassengers.passenger_combat_range", "نطاق قتال الركاب")
language.Add("npcpassengers.passenger_combat_accuracy", "دقة الركاب")
language.Add("npcpassengers.passenger_combat_damage", "مضاعف الضرر للركاب")
language.Add("npcpassengers.fear_speed_threshold", "عتب سرعة الخوف")
language.Add("npcpassengers.drowsy_time", "وقت النعاس")
language.Add("npcpassengers.detach_no_collide_duration", "مدة عدم التصادم (ثواني)")
language.Add("npcpassengers.tank_driver_range", "نطاق الكشف")
language.Add("npcpassengers.tank_driver_engage_distance", "مسافة الاشتباك")
language.Add("npcpassengers.tank_driver_speed", "سرعة القيادة")
language.Add("npcpassengers.tank_driver_reverse_distance", "مسافة التراجع")
language.Add("npcpassengers.turret_range", "نطاق الهدف")
language.Add("npcpassengers.turret_accuracy", "الدقة")
language.Add("npcpassengers.turret_reaction_time", "وقت الاستجابة")
language.Add("npcpassengers.turret_fire_delay", "تأخير الإطلاق")
language.Add("npcpassengers.turret_aim_speed", "سرعة التصويب")
language.Add("npcpassengers.hud_scale", "مقياس واجهة العرض")
language.Add("npcpassengers.hud_opacity", "شفافية واجهة العرض")
language.Add("npcpassengers.hud_alert_threshold", "عتب الإنذار")
language.Add("npcpassengers.hud_fear_threshold", "عتب الخوف")
language.Add("npcpassengers.hud_drowsy_threshold", "عتب النعاس")
language.Add("npcpassengers.ui_sounds_volume", "حجم أصوات واجهة المستخدم")
language.Add("npcpassengers.ui_panel_width", "عرض اللوحة")

-- Section headers
language.Add("npcpassengers.section.animation", "الأنيميشن والسلوك")
language.Add("npcpassengers.section.realism", "واقعية متقدمة")
language.Add("npcpassengers.section.hud_position", "موقع ونمط واجهة العرض")
language.Add("npcpassengers.section.emotion_thresholds", "عتبات العاطفة")
language.Add("npcpassengers.section.emotion_actions", "إجراءات العاطفة")
language.Add("npcpassengers.section.vehicle_control", "التحكم في المركبة")
language.Add("npcpassengers.section.hud_controls", "عناصر التحكم في واجهة العرض")
language.Add("npcpassengers.section.debug_controls", "عناصر التحكم في التصحيح")
language.Add("npcassengers.section.passenger_status", "التحكم في حالة الركاب")
language.Add("npcpassengers.section.quick_test", "أزرار الاختبار السريع")
language.Add("npcpassengers.section.driver_system", "نظام السائق NPC")
language.Add("npcpassengers.section.ui_sounds", "إعدادات أصوات واجهة المستخدم")
language.Add("npcpassengers.section.appearance", "المظهر")
language.Add("npcpassengers.section.context_menu", "خيارات القائمة السياقية")
language.Add("npcpassengers.section.panel_preferences", "تفضيلات لوحة الإعدادات")
language.Add("npcpassengers.section.performance", "الأداء والتقنية")
language.Add("npcpassengers.section.simulation", "نظام المحاكاة")
language.Add("npcpassengers.section.modules", "نظام الوحدات")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "تعيين مقعد")
language.Add("npcpassengers.btn.detach", "فصل")
language.Add("npcpassengers.btn.copy_summary", "نسخ الملخص")
language.Add("npcpassengers.btn.copy_debug", "نسخ التصحيح")
language.Add("npcpassengers.btn.enable_all_speech", "تفعيل كل الصوت")
language.Add("npcpassengers.btn.disable_all_speech", "تعطيل كل الصوت")
language.Add("npcpassengers.btn.show_current_vehicle", "عرض المركبة الحالية فقط")
language.Add("npcpassengers.btn.auto_refresh", "تحديث تلقائي للقائمة المرئية")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "لم يتم اكتشاف مركبة حالي. اجلس في مركبة أو قم بتعطيل فلتر المركبة الحالية.")
language.Add("npcpassengers.status.no_match_filter", "لا يوجد ركاب يطابق فلترك. جرب اسماً أو فئة أو رقم مقعد أو حالة أو فئة مركبة.")
language.Add("npcpassengers.status.no_passengers_vehicle", "لم يتم العثور على ركاب في مركبتك الحالية.")
language.Add("npcpassengers.status.no_passengers", "لم يتم العثور على ركاب. يجب أن يكون الـ NPCs مسافرين في مركبة قبل أن يمكن إدارتهم هنا.")
language.Add("npcpassengers.status.all_passengers", "جميع الركاب")
language.Add("npcpassengers.status.current_vehicle_only", "المركبة الحالية فقط")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F للتركيز على البحث")
language.Add("npcengers.status.no_matches", "لا توجد إعدادات مطابقة")
language.Add("npcpassengers.status.showing_matches", "عرض %d الأوائل من %d مطابقة")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "فتح الإعدادات")
language.Add("npcpassengers.menu.reset_all", "إعادة تعيين جميع الإعدادات")

-- Button states
language.Add("npcpassengers.state.on", "مفعّل")
language.Add("npcpassengers.state.off", "معطّل")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "الانضمام التلقائي")
language.Add("npcpassengers.chat.hud_status", "واجهة العرض للركاب")
language.Add("npcpassengers.chat.hud_position", "موقع واجهة العرض")
language.Add("npcpassengers.chat.target_debug", "تصحيح الهدف")
language.Add("npcpassengers.chat.turret_gunners", "مدفعلي البرج")
language.Add("npcpassengers.chat.turret_holding", "الاحتفاظ بالنار")
language.Add("npcpassengers.chat.turret_fire", "فتح النار")
language.Add("npcpassengers.chat.unknown", "غير معروف")
language.Add("npcpassengers.chat.nothing_copy", "لا شيء للنسخ.")
language.Add("npcpassengers.chat.clipboard_unavailable", "الوصول إلى الحافظة غير متاح في هذه النسخة.")
language.Add("npcpassengers.chat.copied_clipboard", "نسخ إلى الحافظة.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "اجلس في نفس المركبة لإعادة تعيين هذا الراكب.")
language.Add("npcpassengers.chat.no_visible_passengers", "لا يوجد ركاب مرئي للنسخ.")
language.Add("npcpassengers.chat.need_vehicle", "يجب أن تكون في مركبة لاستخدام هذا.")
language.Add("npcpassengers.chat.keybinds_applied", "تم تطبيق روابط المفاتيح الموصى بها.")
language.Add("npcpassengers.chat.keybinds_cleared", "تم مسح جميع روابط المفاتيح.")
language.Add("npcpassengers.chat.context_enabled", "تم تفعيل جميع خيارات القائمة السياقية.")
language.Add("npcpassengers.chat.context_hidden", "تم إخفاء جميع خيارات القائمة السياقية.")
language.Add("npcpassengers.chat.panel_compact", "تم تعيين حجم اللوحة على مضغوط.")
language.Add("npcpassengers.chat.panel_default", "تم تعيين حجم اللوحة على الافتراضي.")
language.Add("npcpassengers.chat.panel_large", "تم تعيين حجم اللوحة على كبير.")
language.Add("npcpassengers.chat.panel_centered", "تم توسيط اللوحة.")
language.Add("npcpassengers.chat.settings_reset", "تم إعادة تعيين جميع إعدادات واجهة المستخدم إلى القيم الافتراضية!")
language.Add("npcpassengers.chat.npc_selected", "تم تحديد NPC! الآن انقر بزر الماوس على مركبة واختر 'إضافة الـ NPC المحدد'")
language.Add("npcpassengers.chat.adding_npc", "إضافة الـ NPC إلى المركبة...")
language.Add("npcpassengers.chat.selection_cancelled", "تم إلغاء اختيار NPC")
language.Add("npcassengers.chat.summary_copied", "تم نسخ ملخص الركاب.")
language.Add("npcpassengers.chat.debug_copied", "تم نسخ معلومات تصحيح الركاب.")
language.Add("npcpassengers.chat.no_passengers_found", "لم يتم العثور على ركاب. يجب أن يكون الـ NPCs في مركبة.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "شدة الحالة %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "تصفية الركاب...")
language.Add("npcpassengers.ui.press_key", "اضغط على مفتاح...")
language.Add("npcpassengers.ui.work_in_progress", "قيد العمل")
language.Add("npcpassengers.ui.under_development", "هذه الميزة قيد التطوير حاليًا")
language.Add("npcpassengers.ui.check_back_later", "تحقق في تحديث مستقبلي!")
language.Add("npcpassengers.ui.search_desc_passengers", "تصفية الركاب النشطين بالاسم والفئة والمقعد والحالة أو المركبة.")
language.Add("npcpassengers.ui.search_desc_sort", "ترتيب القائمة المرئية للركاب حسب المركبة والاسم والمقعد والصحة أو الحالة.")
language.Add("npcpassengers.ui.search_label_filter", "فلتر الركاب")
language.Add("npcpassengers.ui.search_label_sort", "ترتيب الركاب")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "كيف أضيف NPCs إلى مركبتي؟")
language.Add("npcassengers.faq.add_npc.answer", "استخدم القائمة السياقية (انقر بزر الماوس على NPC) واختر 'جعل راكباً'. أو استخدم ربط 'رفق الـ NPC الأقرب'. يجب أن يكون الـ NPCs ودوديين معك.")
language.Add("npcpassengers.faq.remove_npc", "كيف أزيل الركاب من مركبتي؟")
language.Add("npcpassengers.faq.remove_npc.answer", "اذهب إلى تبويب الركاب في الإعدادات، حدد الراكب وانقر على فصل. أو استخدم ربط 'فصل جميع الركاب'.")
language.Add("npcpassengers.faq.position", "الـ NPCs يطفون/يمرون عبر المقاعد!")
language.Add("npcpassengers.faq.position.answer", "اذهب إلى تبويب الموضع واضبط إزاحات الارتفاع/الأمام/اليمين. كل نموذج مركبة مختلف، لذا قد تحتاج إلى تعديل هذه القيم. استخدم لوحة التصحيح لاختبار المواقع في الوقت الفعلي.")
language.Add("npcpassengers.faq.speech", "الـ NPCs لا يتحدثون!")
language.Add("npcpassengers.faq.speech.answer", "تحقق من تبويب السلوك وتأكد من أن 'تفعيل صوت NPC' مفعل. تحقق أيضًا من أن حجم الصوت أعلى من 0. قد لا تكون بعض نماذج الـ NPC لديها خطوط صوت متاحة.")
language.Add("npcpassengers.faq.autojoin", "كيف يعمل الانضمام التلقائي؟")
language.Add("npcpassengers.faq.autojoin.answer", "عند تفعيله في تبويب الانضمام التلقائي، سيركب الـ NPCs الودوديون القريبون تلقائياً عندما تدخل، تماماً مثل آلية الفريق في Half-Life 2! يمكنك تعيين نطاق الكشف وتحديد عدد الـ NPCs التي يمكنها الانضمام تلقائياً.")
language.Add("npcassengers.faq.death", "ماذا يحدث عندما يموت الركاب؟")
language.Add("npcpassengers.faq.death.answer", "الركاب الموتى سيعرضون تأثير توهج أحمر وسيظهرون أيقونة جمجمة في واجهة العرض. اقترب من مركبتك واضغط R لإزالة أجسامهم. سيتم إخراج الأجسام مع الفيزياء.")
language.Add("npcpassengers.faq.status", "ماذا تعني حالات الركاب؟")
language.Add("npcpassengers.faq.status.answer", "هادئ: مسترخ، لا تهددات قريبة. إنذار: تم اكتشاف عدو. خوف: قيادة خطيرة (سرعة عالية، تصادم). نعسان: رحلة طويلة وهادئة. ميت: الصحة وصلت إلى الصفر.")
language.Add("npcpassengers.faq.keybinds", "روابط المفاتيح الخاصة بي لا تعمل!")
language.Add("npcpassengers.faq.keybinds.answer", "اذهب إلى تبويب روابط المفاتيح وتأكد من أنك قمت بالفعل روابط المفاتيح (لم يتم تعيينها افتراضيًا). انقر على الزر بجانب كل إجراء واضغط المفتاح المطلوب. انقر بزر الماوس لإلغاء الربط.")
language.Add("npcpassengers.faq.errors", "الإضافة لا تعمل على الإطلاق / أتلقى أخطاء!")
language.Add("npcpassengers.faq.errors.answer", "تأكد من تشغيل أحدث إصدار من Garry's Mod. تحقق من وحدة التحكم للأخطاء (مفتاح التيلدة ~). حاول تعطيل الإضافات المتضاربة.")
language.Add("npcpassengers.faq.combat", "هل يمكن للركاب إطلاق من المركبات؟")
language.Add("npcpassengers.faq.combat.answer", "حاليًا لا. الـ NPCs سيتتبعون الأعداء وسيكونون ردودًا للتهديدات، لكن لن يطلقوا أسلحة أثناء الجلوس. قد تضاف هذه الميزة في التحديثات المستقبلية.")
language.Add("npcpassengers.faq.stop_autojoin", "كيف أوقف الـ NPCs من الانضمام تلقائياً؟")
language.Add("npcpassengers.faq.stop_autojoin.answer", "ألغلق خانة 'تفعيل الانضمام التلقائي' في تبويب الانضمام التلقائي، أو استخدم ربط 'تبديل الانضمام التلقائي'.")
language.Add("npcpassengers.faq.settings", "أين يتم حفظ الإعدادات؟")
language.Add("npcassengers.faq.settings.answer", "جميع الإعدادات يتم حفظها كـ ConVars في تكوين GMod الخاصة بك. تستمر بين الجلسات وهي خاصة بعميلك.")
language.Add("npcpassengers.faq.vehicles", "هل يعمل هذا مع جميع المركبات؟")
language.Add("npcassengers.faq.vehicles.answer", "يعمل مع معظم المركبات التي لديها فيزياء. الدباب، APCs، سيارات، قوارب، إلخ. بعض المركبات المعدلة قد تتطلب تعديلات الموضع.")
language.Add("npcpassengers.faq.multiple", "هل يمكنني الحصول على عدة NPCs في مركبة واحدة؟")
language.Add("npcpassengers.faq.multiple.answer", "نعم! اضبط 'حد الركاب' في الإعدادات العامة. سيوزع الإضافة الـ NPCs تلقائيًا حول المركبة. لمواقع المقاعد المحددة، اضبط الإزاحات في تبويب الموضع.")
language.Add("npcpassengers.faq.crashes", "الـ NPCs يتصرفون بشكل غريب بعد التصادم!")
language.Add("npcpassengers.faq.crashes.answer", "هذا طبيعي - يتفاعلون بالخوف مع القيادة الخطرة. قلل عتب الخوف في إعدادات واجهة العرض إذا تريد أن يكونوا أقل تفاعلاً.")
language.Add("npcpassengers.faq.reset_setting", "كيف أعيد تعيين إعداد واحد فقط؟")
language.Add("npcassengers.faq.reset_setting.answer", "استخدم أمر وحدة التحكم لهذا الإعداد المحدد. تبدأ جميع الأوامر بـ 'nai_npc_'. اكتب 'find nai_npc' في وحدة التحكم لرؤية جميع الأوام المتاحة.")
language.Add("npcpassengers.faq.multiplayer", "هل يعمل هذا في اللعب المتعدد؟")
language.Add("npcpassengers.faq.multiplayer.answer", "نعم! الإضافة تعمل على كل من خواد اللعب الفردي والمتعدد. كل لاعب يتحكم في ركابه الخاصة.")
language.Add("npcpassengers.faq.lvs", "هل يعمل هذا مع مركبات LVS؟")
language.Add("npcpassengers.faq.lvs.answer", "نعم! الإضافة لديه دعم كامل لمركبات LVS (Lua Vehicle System). يمكن لـ NPCs السفر كركاب ويمكنهم حتى قيادة مركبات LVS إذا كان وضع السائق NPC مفعلًا.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "هذه الإعدادات تتحكم في سلوك واجهة المستخدم للإضافة")
language.Add("npcpassengers.panel.performance_note1", "تغييرات حجم اللوحة تتطلب إغلاق وإعادة فتح القائمة")
language.Add("npcpassengers.panel.performance_note2", "تعطيل الأصوات أو الأنيمات قد يحسن الأداء على الأنظمة منخفضة")
language.Add("npcpassengers.panel.performance_title", "معلومات تكوين واجهة المستخدم")
language.Add("npcpassengers.help.console_title", "أوامر وحدة التحكم للتصحيح:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- تفعيل وضع التصحيح لرؤية معلومات مفصلة")
language.Add("npcpassengers.about.title", "حول")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")
language.Add("npcpassengers.lang.changed_portuguese", "Idioma alterado para português. O painel será atualizado automaticamente.")
language.Add("npcpassengers.lang.changed_german", "Sprache auf Deutsch geändert. Das Panel wird automatisch aktualisiert.")
language.Add("npcpassengers.lang.changed_french", "Langue changée en français. Le panneau s'actualisera automatiquement.")
language.Add("npcpassengers.lang.changed_japanese", "言語が日本語に変更されました。パネルは自動的に更新されます。")
language.Add("npcpassengers.lang.changed_arabic", "تم تغيير اللغة إلى العربية. سيتم تحديث اللوحة تلقائياً.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "مرحباً!")
language.Add("npcpassengers.welcome.msg1 "، قبل الشكوى من أن الراكاب يجلس على المركبة،\nيرجى فتح الإعدادات. يمكنك فعل ذلك، أؤمن بك.")
language.Add("npcpassengers.welcome.msg2", "هذه الإضافة لا تزال بعيدة عن كمالها، لا تتردد في\nالإبلاغ عن الأخطاق واقترح ميزات جديدة. أقرأف جميع تعليقاتك!")
language.Add("npcpassengers.welcome.changelog", "سجل التغييرات")
language.Add("npcpassengers.welcome.got_it", "فهمت!")
language.Add("npcpassengers.welcome.console_cmd", "أو استخدم أمر وحدة التحكم: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "فئات NPC القائمة السوداء")
language.Add("npcassengers.ui.blacklist_help", "قائمة مفصولة بفواصل لأسماء فئات NPC التي لا يمكنها استخدام البرج. استخدم أمر وحدة التحكم 'getnpcblacklist' لرؤية القائمة السوداء الحالية.")
language.Add("npcpassengers.ui.hud_position", "موقع واجهة العرض")
language.Add("npcpassengers.ui.not_bound", "غير مربوط")
language.Add("npcpassengers.ui.keybind_tip", "نصيحة: انقر بزر الماوس على ربط لفكه. اضغط ESC أثناء الربط للإلغاء.")
language.Add("npcpassengers.ui.dont_show_again", "لا تظهر هذا مرة أخرى")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "عمليات الركاب")
language.Add("npcpassengers.hud.filter_prefix", "فلتر: ")
language.Add("npcpassengers.hud.sort_prefix", "ترتيب: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  تحديث تلقائي: ")
language.Add("npcpassengers.hud.vehicle_prefix", "المركبة: ")
language.Add("npcpassengers.hud.speed_prefix", "السرعة: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "مفعّل")
language.Add("npcpassengers.hud.off", "معطّل")
language.Add("npcpassengers.hud.passengers", "الركاب")
language.Add("npcpassengers.hud.npc_driver", "السائق NPC")
language.Add("npcpassengers.hud.total_prefix", "المجموع: ")
language.Add("npcpassengers.hud.showing_prefix", "عرض: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "المركبة الحالية: ")
language.Add("npcpassengers.hud.hidden_prefix", "مخفي: ")
language.Add("npcpassengers.hud.dead_prefix", "ميت: ")
language.Add("npcpassengers.hud.scared_prefix", "خائف: ")
language.Add("npcpassengers.hud.drowsy_prefix", "نعسان: ")

-- Status labels
language.Add("npcpassengers.status.calm", "هادئ")
language.Add("npcpassengers.status.alert", "إنذار")
language.Add("npcpassengers.status.scared", "خائف")
language.Add("npcpassengers.status.drowsy", "نعسان")
language.Add("npcpassengers.status.dead", "ميت")
language.Add("npcpassengers.status.unknown", "غير معروف")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "مواطن")
language.Add("npcpassengers.npc.alyx", "أليكس")
language.Add("npcpassengers.npc.barney "، "بارني")
language.Add("npcpassengers.npc.monk", "الأب غريغوري")
language.Add("npcpassengers.npc.vortigaunt", "فورتوجانت")
language.Add("npcpassengers.npc.eli", "إيلي")
language.Add("npcpassengers.npc.kleiner", "د. كلاينر")
language.Add("npcpassengers.npc.mossman", "د. موسمان")
language.Add("npcpassengers.npc.breen", "د. برين")
language.Add("npcpassengers.npc.dog", "كلب")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "المركبة")
language.Add("npcassengers.sort.name", "الاسم")
language.Add("npcpassengers.sort.seat", "المقعد")
language.Add("npcpassengers.sort.health", "الصحة")
language.Add("npcpassengers.sort.status", "الحالة")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "المركبة أولاً")
language.Add("npcpassengers.sort.name_az", "الاسم أ-ي")
language.Add("npcpassengers.sort.seat_number", "رقم المقعد")
language.Add("npcpassengers.sort.highest_health", "أعلى صحة")
language.Add("npcpassengers.sort.status_priority", "أولوية الحالة")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "المركبة: غير معروف")
language.Add("npcpassengers.ui.seat_prefix", "المقعد ")
language.Add("npcpassengers.ui.same_vehicle", "نفس المركبة")
language.Add("npcpassengers.ui.other_vehicle", "مركبة أخرى")
language.Add("npcpassengers.ui.hidden", "مخفي")
language.Add("npcpassengers.ui.visible", "مرئي")
language.Add("npcpassengers.ui.health_format", "الصحة %d / %d")
language.Add("npcpassengers.ui.refresh_list", "تحديث قائمة الركاب")
language.Add("npcpassengers.ui.copy_list", "نسخ القائمة المرئية للركاب")
language.Add("npcpassengers.ui.make_exit", "جعل ركاب المركبة الحالية يخرجون")
language.Add("npcpassengers.ui.reset_pos", "إعادة تعيين الموضع والزوايا")
language.Add("npcpassengers.ui.crash_reactions", "ردود التصادم")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "أصوات الصعود/النزول")
language.Add("npcpassengers.section.ambient_sounds", "الأصوات المحيطة")
language.Add("npcpassengers.section.gesture_animations", "إيماءات الإيماءة")
language.Add("npcpassengers.section.threat_awareness", "وعي التهديد")
language.Add("npcpassengers.section.emotional_states", "الحالات العاطفية")
language.Add("npcpassengers.section.turret_control", "التحكم في البرج (تجريبي)")
language.Add("npcpassengers.section.turret_blacklist", "القائمة السوداء لـ NPC البرج")
language.Add("npcpassengers.section.idle_chatter", "الدردشة غير النشطة")
language.Add("npcpassengers.section.body_physics", "فيزياء الجسم")
language.Add("npcpassengers.section.npc_auto_driver", "السائق التلقائي لـ NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "اليسار السفلي")
language.Add("npcpassengers.hud.bottom_right", "اليمين السفلي")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "تفعيل واجهة العرض للركاب")
language.Add("npcpassengers.ui.cover_face", "تغطية الوجه")
language.Add("npcpassengers.ui.apply_keybinds", "تطبيق روابط المفاتيح الموصى بها")
language.Add("npcpassengers.ui.clear_keybinds", "مسح جميع روابط المفاتيح")

-- Debugging buttons
language.add("npcpassengers.ui.test_flinch", "اختبار إيماءة الفلينش")
language.Add("npcpassengers.ui.test_random", "اختبار إيماءة عشوائية")
language.Add("npcpassengers.ui.reset_states", "إعادة تعيين جميع الحالات")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "تفعيل جميع خيارات القائمة السياقية")
language.Add("npcpassengers.ui.hide_context", "إخفاء جميع خيارات القائمة السياقية")
language.Add("npcpassengers.ui.set_compact", "تعيين حجم لوحة مضغوط")
language.Add("npcpassengers.ui.set_default", "تعيين حجم لوحة افتراضي")
language.Add("npcpassengers.ui.set_large", "تعيين حجم لوحة كبير")
language.Add("npcpassengers.ui.center_panel", "توسيط اللوحة الآن")
language.Add("npcpassengers.ui.reset_ui", "إعادة تعيين جميع إعدادات واجهة المستخدم إلى الافتراضي")

-- Role names
language.Add("npcpassengers.role.citizen_female", "مواطن (أنثى)")
language.Add("npcpassengers.role.citizen_male", "مواطن (ذكر)")
language.Add("npcpassengers.role.medic", "طبيب")
language.Add("npcpassengers.role.rebel", "متمرد")
language.Add("npcpassengers.role.passenger", "راكب")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "عرض فقط عند وجودك في المركبة")
language.Add("npcpassengers.hud.show_calm", "عرض الركاب الهادئين")
language.Add("npcpassengers.hud.show_hints", "عرض تلميحات السياق")
language.Add("npcpassengers.hud.show_target_debug", "عرض تصحيح الهدف")
language.Add("npcpassengers.hud.play_cues", "تشغيل إشارات النجاح/الفشل")
language.Add("npcpassengers.debug.enable_mode", "تفعيل وضع التصحيح")
language.Add("npcpassengers.ui.enable_sounds", "تفعيل أصوات واجهة المستخدم")
language.Add("npcpassengers.ui.hover_sounds", "أصوات التمرير")
language.Add("npcpassengers.ui.click_sounds", "أصوات النقر")
language.Add("npcpassengers.ui.enable_animations", "تفعيل رسوم متحركة واجهة المستخدم")
language.Add("npcpassengers.ui.show_tooltips", "عرض التلميحات")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "إخفاء شريط التمرير تلقائياً")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "سلاسة تمرير الشريط الجانبي")
language.Add("npcpassengers.ui.color_theme", "نظام الألوان")
language.Add("npcpassengers.ui.font_scale", "مقياس الخط")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "إلغاء اختيار NPC")
language.Add("npcpassengers.context.remove_passenger", "إزالة الراكب")
language.Add("npcpassengers.context.blacklist_passenger", "إضافة إلى القائمة السوداء")
language.Add("npcpassengers.context.whitelist_passenger", "إضافة إلى القائمة البيضاء")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "روابط المفاتيح")
language.Add("npcpassengers.keybinds.desc", "تكوين اختصارات لوحة المفاتيح للإجراءات سريعة.")
language.Add("npcpassengers.keybind.attach", "رفق الـ NPC الأقرب")
language.Add("npcpassengers.keybind.attach.help", "يربط أقرب NPC ودودي بمركبتك.")
language.Add("npcpassengers.keybind.detach_all", "فصل جميع الـ NPCs")
language.Add("npcpassengers.keybind.detach_all.help", "يزيل جميع الركاب من مركبتك.")
language.Add("npcpassengers.keybind.toggle_autojoin", "تبديل الانضمام التلقائي")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "تفعيل/يعطل بسرعة الانضمام التلقائي.")
language.Add("npcpassengers.keybind.menu", "فتح قائمة الإعدادات")
language.Add("npcpassengers.keybind.menu.help", "يفتح لوحة الإعدادات.")
language.Add("npcpassengers.keybind.exit_all", "جميع الركاب يخرجون")
language.Add("npcpassengers.keybind.exit_all.help", "يجعل جميع الركاب يغادرون من المركبة.")
language.Add("npcpassengers.keybind.toggle_hud", "تبديل واجهة العرض")
language.Add("npcpassengers.keybind.toggle_hud.help", "يظهر/يخفي واجهة العرض للركاب.")
language.Add("npcpassengers.keybind.quick_attach", "وضع الرفق السريع")
language.Add("npcpassengers.keybind.quick_attach.help", "اضغط لرفع الـ NPCs التي تنظر إليهم بسرعة")
language.Add("npcpassengers.keybind.hold_fire", "الـ NPCs يحتفظون النار")
language.Add("npcpassengers.keybind.hold_fire.help", "أخبر المدفعليين الـ NPCs بالتوقف عن الإطلاق")
language.Add("npcpassengers.keybind.open_fire", "الـ NPCs يفتحون النار")
language.Add("npcpassengers.keybind.open_fire.help", "أخبر المدفعليين الـ NPCs بإنجاز الأهداف")
language.Add("npcpassengers.keybind.cycle_view", "دورة عرض الراكب")
language.Add("npcpassengers.keybind.cycle_view.help", "دور الكاميرا عبر الركاب")
language.Add("npcpassengers.keybind_cycle_hud_position", "دورة موقع واجهة العرض")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "حرك واجهة العرض للركاب عبر الزوايا الأرب")
language.Add("npcpassengers.keybind.toggle_debug", "تبديل تصحيح الهدف")
language.Add("npcpassengers.keybind.toggle_debug.help", "بدّل التراكب الصغيرة لتصحيح الهدف")
language.Add("npcpassengers.keybind.test_gesture", "اختبار إيماءة عشوائية")
language.Add("npcpassengers.keybind.test_gesture.help", "تشغيل إيماءة عشوائية على الراكب الأقرب")
language.Add("npcpassengers.keybind.reset_all", "إعادة تعيين جميع الـ NPCs")
language.Add("npcpassengers.keybind.reset_all.help", "إعادة تعيين حالات الأنيمات لجميع الركاب")

-- HUD Settings
language.Add("npcassengers.hud.header", "إعدادات واجهة العرض")
language.Add("npcpassengers.hud.enable", "تفعيل واجهة العرض")
language.Add("npcpassengers.hud.enable.help", "يعرض تراكب حالة الركاب على الشاشة.")
language.Add("npcpassengers.hud.position", "موقع واجهة العرض")
language.Add("npcpassengers.hud.position.help", "أين يظهر واجهة العرض على الشاشة.")
language.Add("npcpassengers.hud.position.topleft", "أعلى اليسار")
language.Add("npcpassengers.hud.position.topright", "أعلى اليمين")
language.Add("npcpassengers.hud.position.bottomleft", "أسفل اليسار")
language.Add("npcpassengers.hud.position.bottomright", "أسفل اليمين")
language.Add("npcpassengers.hud.scale", "مقياس واجهة العرض")
language.Add("npcpassengers.hud.scale.help", "مضاعف الحجم لواجهة العرض.")
language.Add("npcpassengers.hud.opacity", "شفافية واجهة العرض")
language.Add("npcpassengers.hud.opacity.help", "شفافية الخلفية (0 = غير مرئي، 1 = صلب).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "السائق NPC")
language.Add("npcpassengers.driver.desc", "اسمح الـ NPCs بقيادة المركبات لك.")
language.Add("npcpassengers.driver.enable", "تفعيل السائقين NPC")
language.Add("npcpassengers.driver.enable.help", "يسمح لـ NPCs بالتحكم في المركبات.")
language.Add("npcpassengers.driver.behavior", "سلوك القيادة")
language.Add("npcpassengers.driver.behavior.help", "كيف يقود الـ NPC المركبة.")
language.Add("npcpassengers.driver.behavior.cruise", "جولة عشوائية")
language.Add("npcpassengers.driver.behavior.follow", "متابعة اللاعب")
language.Add("npcpassengers.driver.behavior.patrol", "دورية")
language.Add("npcpassengers.driver.behavior.flee", "هروب")
language.Add("npcpassengers.driver.behavior.parked", "موقوف")

-- Help / FAQ
language.Add("npcpassengers.help.header", "الأسئلة الشائعة")
language.Add("npcpassengers.help.desc", "إجابات سريعة للأسئلة الشائعة واستكشاف المشاكل.")
language.Add("npcpassengers.help.still_need", "لا تزال بحاجة للمساعدة؟")
language.Add("npcpassengers.help.community", "انضم مجتمع Discord الخاص بنا للحصول على الدعم!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "دبابة/LVS")
language.Add("npcpassengers.nav.debugging", "تصحيح")
language.Add("npcpassengers.nav.driver", "السائق NPC")
language.Add("npcpassengers.nav.interface", "واجهة المستخدم")
language.Add("npcassengers.nav.simulate", "محاكاة")
language.Add("npcpassengers.nav.modules", "الوحدات")
language.Add("npcpassengers.nav.about", "حول")
language.Add("npcpassengers.search.placeholder", "البحث في الإعدادات...")

-- About page
language.Add("npcpassengers.about.description", "نظام ركاب متقدم مع ذكاء عاطفي وفيزياء واقعية")
language.Add("npcassengers.about.feature_status", "نظام الحالة: هادئ / إنذار / خوف / نعسان / ميت")
language.Add("npcpassengers.about.feature_performance", "الأداء: تخزين المقاعد، مؤقتات محدودة، خطاف عميل محسنة")
language.Add("npcpassengers.about.feature_filtering", "تصفية المركبات، تبريد إعادة المحاولة، انضمام تلقائي فقط للفرق")
language.Add("npcpassengers.about.actions", "الإجراءات")
language.Add("npcassengers.about.show_welcome", "عرض شاشة الترحيب")
language.Add("npcpassengers.about.open_github", "فتح صفحة GitHub")
language.Add("npcpassengers.about.reset_settings", "إعادة تعيين جميع الإعدادات إلى الافتراضي")

-- Status messages
language.Add("npcpassengers.status.calm", "هادئ")
language.Add("npcpassengers.status.alert", "إنذار")
language.Add("npcpassengers.status.scared", "خائف")
language.Add("npcpassengers.status.drowsy", "نعسان")
language.Add("npcpassengers.status.dead", "ميت")
language.Add("npcpassengers.status.calm.desc", "مسترخ، لا تهددات قريبة")
language.Add("npcpassengers.status.alert.desc", "تم اكتشاف عدو، الـ NPC يتابع التهديدات")
language.Add("npcpassengers.status.scared.desc", "قيادة خطيرة (سرعة عالية، تصادم)")
language.Add("npcpassengers.status.drowsy.desc", "رحلة طويلة وهادئة، الـ NPCs يصبح نعسان")
language.Add("npcpassengers.status.dead.desc", "الصحة وصلت إلى الصفر")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "الانضمام التلقائي: مفعل")
language.Add("npcpassengers.chat.autojoin_off", "الانضمام التلقائي: معطل")
language.Add("npcpassengers.chat.hud_on", "واجهة العرض: مفعل")
language.Add("npcpassengers.chat.hud_off", "واجهة العرض: معطل")
language.Add("npcpassengers.chat.prefix", "[ركاب NPC المحسّن]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "لا مركبة قريبة")
language.Add("npcpassengers.error.no_npc", "لا NPC قريب")
language.Add("npcpassengers.error.vehicle_full", "المركبة ممتلئة")
language.Add("npcpassengers.error.too_far", "NPC بعيد جدًا عن المركبة")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "تغيير اللغة")
language.Add("npcpassengers.tooltip.minimize", "تصغير اللوحة")
language.Add("npcpassengers.tooltip.expand", "توسيع اللوحة")
language.Add("npcpassengers.tooltip.welcome", "عرض شاشة الترحيب")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "التبديل الرئيسي لجميع صوت NPC. قم بإيقافه لجعل الركاب صامتين تماماً.")
language.Add("npcpassengers.speech_volume.help", "مدى صوت NPCs (0 = صامت، 100 = حجم كامل).")
language.Add("npcpassengers.pitch_variation.help", "تغيير عشوائي في درجة الصوت لأصوات أكثر طبيعية. 0 = أحادي، أعلى = المزيد من التنوع.")
language.Add("npcpassengers.crash_enable.help", "الـ NPCs يئنون/يصرخون عندما تتباطأ المركبة بشدة (تصادم، فرملة شديدة).")
language.Add("npcpassengers.crash_threshold.help", "التباط المطلوب لتحري أصوات التصادم. أقل = أكثر حساسية.")
language.Add("npcpassengers.crash_cooldown.help", "الحد الأدنى للثواني بين أصوات التصادم لكل NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "الـ NPCs يتحدثون أحيانًا أثناء السفر - تعليقات، أسئلة، ملاحظات.")
language.Add("npcpassengers.speech_idle_chance.help", "احتمالية الدردشة لكل فحص. 0 = أبدًا، 1 = يحاول دائما التحدث.")
language.Add("npcpassengers.speech_idle_interval.help", "الحد الأدنى للثواني بين محاولات الدردشة غير النشطة.")
language.Add("npcpassengers.speech_board.help", "الـ NPCs يتحدثون عند الدخول والخروج من المركبات.")
language.Add("npcpassengers.ambient_sounds_help", "سعال متقطع، تنهيدات، همهم - أصوات حياة خلفية.")
language.Add("npcpassengers.ambient_interval.help", "الثواني المتوسط بين الأصوات المحيطة.")
language.Add("npcpassengers.animation.help", "ضبط بدقة أنيمات NPC وحركة الرأس.")
language.Add("npcpassengers.head_look.help", "الـ NPCs ينظرون طبيعيًا حولهم، إلى اللاعب، عبر النوافذ، إلخ.")
language.Add("npcpassengers.head_smooth.help", "مدى نعومة حركة الرأس. أقل = أسرع، أعلى = أكثر طفو.")
language.Add("npcpassengers.blink.help", "الـ NPCs يرمشون بشكل واقعي أثناء الجلوس.")
language.Add("npcpassengers.breathing.help", "إيماءة تنفس خفية على رؤوس الـ NPCs.")
language.Add("npcpassengers.walk_timeout.help", "ثواني قبل أن يتخلى الـ NPC المشي نحو المركبة.")
language.Add("npcpassengers.realism.help", "ردود قائم على الفيزي وأنظمة الوعي لغاية الغمر.")
language.Add("npcpassengers.talking_gestures.help", "الـ NPCs يشغلون إيماءات أيدي وعشو جسدية عشوائية أثناء السفر.")
language.Add("npcpassengers.gesture_chance.help", "نسبة مئوية لعب إيماءة لكل فاصل.")
language.Add("npcpassengers.gesture_interval.help", "ثواني بين فحصات فرصة الإيماءة.")
language.Add("npcpassengers.crash_flinch.help", "الـ NPCs يفلشون ويتقدمون للأمام عندما تصطدم المركبة أو تفرمل بشدة.")
language.Add("npcpassengers.crash_threshold_flinch.help", "تغير السرعة المطلوبة لتحريز الفلنش (أقل = أكثر حساسية).")
language.Add("npcpassengers.body_sway.help", "الـ NPCs يميلون في المنعطفات، يدعمون أثناء التسارع/الفرملة.")
language.Add("npcpassengers.body_sway_amount.help "، "مدى تتمايل الـ NPCs مع حركة المركبة.")
language.Add("npcpassengers.threat_awareness.help", "الـ NPCs ينظرون تلقائياً نحو الأعداء القريبين.")
language.Add("npcpassengers.threat_range.help", "مدى يمكن للـ NPCs كشف التهديد لتتبع الرأس.")
language.Add("npcpassengers.combat_alert.help", "الـ NPCs يصبحون متوترين ورد فاعلين عندما يكون الأعداء قريب.")
language.Add("npcpassengers.passenger_combat.help", "معطلق افتراضي. فعّل هذا للسماح للركاب المسلحين بإطلاق من داخل المركبات.")
language.Add("npcpassengers.passenger_combat_range.help", "مدى يمكن للركاب المسلحين الحصول على الأهداف.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "القيم الأعلى تضيق انتشار الإطلاق للركاب المسلحين.")
language.Add("npcpassengers.passenger_combat.damage.help", "يقيس الضرر الناتج من إطلاق الركاب.")
language.Add("npcpassengers.passenger_interaction.help", "عدة ركاب ينظرون ويحينًا يتحدثون مع بعضهم البعض.")
language.Add("npcpassengers.fear_reactions.help", "الـ NPCs يخافون من القيادة الخطيرة - عيون مفتوحة، أصوات الذعر.")
language.Add("npcpassengers.fear_speed_threshold.help", "السرعة (وحدات/ثانية) التي يبدأ الـ NPCs في أن يصبحون عصبيًا.")
language.Add("npcpassengers.drowsiness.help", "الـ NPCs يصبحون نعسان في رحلات طويلة وهادئة - رمش بطيء، هز الرأس.")
language.Add("npcpassengers.drowsy_time.help", "ثواني من القيادة الهادئة قبل أن يبدأ النعاس.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "إعدادات للدبابات، APCs، ومركبات LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "يجعل ركاب الـ NPCs غير مرئية عندما يكونون داخل الدبابات وـ APCs.")
language.Add("npcpassengers.eject_stuck_check.help", "يدفع الـ NPCs خارج المركبات تلقائياً عندما يعانون أثناء الخروج. يمنع الـ NPCs من المرور عبر المركبات عند الخروج.")
language.Add("npcpassengers.detach_no_collide.help", "بعد الفصل، يمر الـ NPCs مؤقتاً عبر المركبة بحيث يمكنهم المشي بعيدًا بدون تصادم أو تعلق.")
language.Add("npcpassengers.detach_no_collide_duration.help، "، "كم من الوقت يهمل الـ NPCs تصادم تصادم المركبة بعد الفصل.")
language.Add("npcpassengers.die_with_vehicle.help", "يموت ركاب الـ NPC عندما يتم تدمير مركبهم بالانفجار أو حريق (أكثر غمراً من خروجهم من الحطام دون أذى).")
language.Add("npcpassengers.tank_driver.help", "يسمح لـ NPCs في مقعد السائق بالقيادة تلقائياً نحو الأعداء.")
language.Add("npcpassengers.tank_driver_range.help", "الحد الأقصى للسائق للكشف الأعداء.")
language.Add("npcpassengers.tank_driver_distance.help", "المسافة للحفاظها من الأعداء.")
language.Add("npcpassengers.tank_driver_throttle.help", "كمية الخانق (0.1 = بطيء، 1 = سرعة كاملة).")
language.Add("npcpassengers.tank_driver_reverse.help", "المسافة للتراجع بعيدًا عن الأعداء.")
language.Add("npcpassengers.tank_turret.help", "يسمح لـ NPCs التحكم في البرج على مركبات LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "يعرض حالة الركاب (العواطف، إنذار) على الشاشة أثناء القيادة.")
language.Add("npcpassengers.hud_show_calm.help", "عند التعطيل، يعرض فقط الركاب بحالة غير هادئة.")
language.Add("npcpassengers.hud_thresholds.desc", "عندما تتجاوز مستويات العاطف هذه العتبات، يعرض الركاب تلك الحالة في واجهة العرض.")
language.Add("npcpassengers.hud_alert_threshold.help", "مستوى الإنذار المطلوب لعرض حالة 'إنذار' (تم اكتشاف عدو).")
language.Add("npcpassengers.hud_fear_threshold.help", "مستوى الخوف المطلوب لعرض حالة 'خوف' (قيادة خطيرة).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "نسبة الوقت الهادئ المطلوب لعرض حالة 'نعسان' (رحلة طويلة وهادئة).")
language.Add("npcpassengers.hud_actions.desc", "اختر أي إجراء يتخذه الركاب عند experiencing كل حالة عاطفية.")
language.Add("npcpassengers.hud_actions_note", "ملاحظة: بعض الإجراءات قد لا تكون مرئية حسب دعم نموذج الـ NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "تحديد روابط مخصصة لإجراءات الركاب. انقر على زر واضغط مفتاحاً للربط.")
language.Add("npcpassengers.keybinds_hud.desc", "عناصر تحكم سريع لواجهة العرض لعرض وتحريك تراكب الركاب.")
language.Add("npcpassengers.keybinds_debug_note", "روابط التصحيح تعمل فقط عندما يكون وضع التصحيح مفعل.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "أدوات تصحيح متقدمة لاختبار سلوك الـ NPC. فعّل وضع التصحيح في الإعدادات أولاً.")
language.Add("npcpassengers.debug_mode.help", "يعرض أزرار اختبار التصحيح وتمكين أوامر التصحيح.")
language.Add("npcpassengers.debug_status.help", "تعيين يدويً حالة الراكب للاختبار. انقر على 'تحديث القائمة' لرؤية الركاب الحاليين.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "تكوين تأثيرات صوتية للأزرار، صناديق مربعات، وعناصر UI أخرى")
language.Add("npcpassengers.ui_sounds_enabled.help", "التبديل الرئيسي لجميع تأثيرات صوت UI")
language.Add("npcpassengers.ui_sounds_volume.help", "مضاعف حجم لأصوات UI (1.0 = عادي، 2.0 = ضعف)")
language.Add("npcpassengers.ui_hover_enabled.help", "تشغيل صوت عند التمرير فوق الأزرار")
language.Add("npcpassengers.ui_click_enabled.help", "تشغيل صوت عند النقر على الأزرار وصناديق مربعات")
language.Add("npcpassengers.context_menu.desc", "اختر أي خيارات تظهر عند النقر بزر الماوس على الـ NPCs")
language.Add("npcpassengers.context_make_passenger.help", "يضيف الـ NPC كراكب إلى مركبتك الحالية")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "يضيف الـ NPC إلى مركبة محددة (انقر على NPC، ثم المركبة)")
language.Add("npcpassengers.context_detach.help", "يزيل الـ NPC من المركبة")
language.Add("npcpassengers.ui_show_welcome.help", "عرض لوحة الترحيب عند تحديث الإضافة إلى إصدار جديد")
language.Add("npcpassengers.ui_panel_width.help", "عرض لوحة الإعدادات")
language.Add("npcpassengers.ui_panel_height.help", "ارتفاع لوحة الإعدادات")
language.Add("npcpassengers.ui_animations.help", "انتقالات سلسة وتأثيرات التمرير (قد يؤثر على الأداء)")
language.Add("npcpassengers.ui_tooltips.help", "عرض تلميات مفيدة عند التمرير فوق الإعدادات")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "عرض شريط التمرير فقط أثناء التمرير أو التمرير فوقه.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "ملاحظة: تصبح اللوحة 70% شفاف عند سحب أي منزلق لتعرض المحتوى في الخلفية.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "قيم أقل = أكثر نعومة لكن أبطأ (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "اختر نظام ألوان لوحة الإعدادات. يتم تطبيق التغييرات فوراً.")
language.Add("npcpassengers.ui_font_scale.help", "يضرب جميع أحجام خط واجهة المستخدم. 1.0 = افتراضي، 0.5 = نصف الحجم، 2.0 = حجم مضاعف.")

print("[Better NPC Passengers] Arabic localization loaded!")
