-- Better NPC Passengers - Chinese Localization
-- 中文本地化文件

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "更好的 NPC 乘客")
language.Add("npcpassengers.settings", "设置")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "常规")
language.Add("npcpassengers.nav.autojoin", "自动加入")
language.Add("npcpassengers.nav.passengers", "乘客")
language.Add("npcpassengers.nav.position", "位置")
language.Add("npcpassengers.nav.behaviour", "行为")
language.Add("npcpassengers.nav.keybinds", "按键绑定")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "驾驶员")
language.Add("npcpassengers.nav.help", "帮助")

-- General Settings
language.Add("npcpassengers.general.header", "常规设置")
language.Add("npcpassengers.allow_multiple", "允许多个乘客")
language.Add("npcpassengers.allow_multiple.help", "允许多个 NPC 乘坐同一辆载具。")
language.Add("npcpassengers.exit_behavior", "退出行为")
language.Add("npcpassengers.exit_behavior.help", "NPC 乘客应该在何时离开载具？")
language.Add("npcpassengers.exit_mode.leave_player", "玩家离开时退出")
language.Add("npcpassengers.exit_mode.leave_attack", "载具被攻击时退出")
language.Add("npcpassengers.exit_mode.never", "永不自动退出")

-- Timing Settings
language.Add("npcpassengers.timing.header", "时间设置")
language.Add("npcpassengers.max_attach_dist", "最大附加距离")
language.Add("npcpassengers.max_attach_dist.help", "将 NPC 附加到载具的最大距离（单位）。")
language.Add("npcpassengers.detach_delay", "分离延迟")
language.Add("npcpassengers.detach_delay.help", "玩家离开后等待多少秒再分离 NPC。")
language.Add("npcpassengers.ai_delay", "AI 恢复延迟")
language.Add("npcpassengers.ai_delay.help", "分离后等待多少秒再恢复 NPC AI。")
language.Add("npcpassengers.cooldown", "冷却时间")
language.Add("npcpassengers.cooldown.help", "将 NPC 附加到同一载具之间的冷却时间。")
language.Add("npcpassengers.passenger_limit", "乘客限制")
language.Add("npcpassengers.passenger_limit.help", "载具中允许的最大 NPC 数量。")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "自动加入（小队行为）")
language.Add("npcpassengers.autojoin.desc", "友方 NPC 会在你进入载具时自动上车 - 就像 Half-Life 2 中的小队机制！")
language.Add("npcpassengers.autojoin.enable", "启用自动加入")
language.Add("npcpassengers.autojoin.enable.help", "附近的友方 NPC 会在你进入载具时自动加入。")
language.Add("npcpassengers.autojoin.range", "自动加入范围")
language.Add("npcpassengers.autojoin.range.help", "寻找 NPC 进行自动加入的最大距离。")
language.Add("npcpassengers.autojoin.max", "最大自动加入 NPC 数")
language.Add("npcpassengers.autojoin.max.help", "一次可以自动加入的最大 NPC 数量。")
language.Add("npcpassengers.autojoin.squad_only", "仅限小队成员")
language.Add("npcpassengers.autojoin.squad_only.help", "只有拥有小队名称的 NPC 才会自动加入（适用于 HL2 风格的小队）。")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "友方 NPC 会在你进入载具时自动上车 - 就像 Half-Life 2 中的小队机制！")
language.Add("npcpassengers.panel.passengers.header", "乘客控制")
language.Add("npcpassengers.panel.passengers.desc", "管理活跃乘客，按名称/类别/状态过滤，复制调试信息，重新分配座位，无需离开设置面板即可分离乘客。")
language.Add("npcpassengers.panel.position.desc", "微调载具中 NPC 的位置。使用这些设置来修复悬浮或穿模问题。")
language.Add("npcpassengers.panel.angle.desc", "调整载具中 NPC 的旋转。")
language.Add("npcpassengers.panel.speech.desc", "配置 NPC 在载具中行驶时的发声方式。HL2 风格的市民声音！")

-- Position Settings
language.Add("npcpassengers.position.header", "位置偏移")
language.Add("npcpassengers.position.desc", "微调载具中 NPC 的位置。使用这些设置来修复悬浮或穿模问题。")
language.Add("npcpassengers.height_offset", "高度偏移")
language.Add("npcpassengers.forward_offset", "前方偏移")
language.Add("npcpassengers.right_offset", "右侧偏移")
language.Add("npcpassengers.angle.header", "角度偏移")
language.Add("npcpassengers.angle.desc", "调整载具中 NPC 的旋转。")
language.Add("npcpassengers.yaw_offset", "偏航（旋转）")
language.Add("npcpassengers.pitch_offset", "俯仰（向前倾斜）")
language.Add("npcpassengers.roll_offset", "翻滚（向侧面倾斜）")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPC 语音（高级）")
language.Add("npcpassengers.behaviour.desc", "配置 NPC 在载具中行驶时的发声方式。HL2 风格的市民声音！")
language.Add("npcpassengers.speech_enable", "启用 NPC 语音")
language.Add("npcpassengers.speech_enable.help", "所有 NPC 语音的主开关。禁用以完全静音乘客。")
language.Add("npcpassengers.speech_volume", "语音音量")
language.Add("npcpassengers.speech_volume.help", "NPC 语音的音量（0 = 静音，100 = 最大音量）。")
language.Add("npcpassengers.pitch_variation", "音调变化（+/-）")
language.Add("npcpassengers.pitch_variation.help", "随机音调变化以获得更自然的声音。0 = 单调，越高 = 变化越多。")
language.Add("npcpassengers.crash.header", "碰撞反应")
language.Add("npcpassengers.crash_enable", "启用碰撞声音")
language.Add("npcpassengers.crash_enable.help", "当载具急剧减速时（碰撞、急刹车），NPC 会发出呻吟/尖叫。")
language.Add("npcpassengers.crash_threshold", "碰撞敏感度")
language.Add("npcpassengers.crash_threshold.help", "触发碰撞声音所需的减速度。越低 = 越敏感。")
language.Add("npcpassengers.crash_cooldown", "碰撞声音冷却")
language.Add("npcpassengers.crash_cooldown.help", "每个 NPC 碰撞声音之间的最小秒数。")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "启用闲聊")
language.Add("npcpassengers.speech_board", "启用上/下车声音")
language.Add("npcpassengers.ambient_sounds", "启用环境声音")
language.Add("npcpassengers.head_look", "启用头部/眼睛注视")
language.Add("npcpassengers.blink", "启用眨眼")
language.Add("npcpassengers.breathing", "启用呼吸")
language.Add("npcpassengers.talking_gestures", "启用说话手势")
language.Add("npcpassengers.crash_flinch", "启用碰撞畏缩")
language.Add("npcpassengers.body_sway", "启用身体晃动")
language.Add("npcpassengers.threat_awareness", "启用威胁感知")
language.Add("npcpassengers.combat_alert", "战斗警觉")
language.Add("npcpassengers.passenger_combat", "NPC 从载具中射击（实验性）")
language.Add("npcpassengers.passenger_interaction", "乘客互动")
language.Add("npcpassengers.fear_reactions", "启用恐惧反应")
language.Add("npcpassengers.drowsiness", "启用困倦")
language.Add("npcpassengers.hide_in_tanks", "在封闭载具中隐藏 NPC")
language.Add("npcpassengers.eject_stuck_check", "自动弹出卡住的 NPC")
language.Add("npcpassengers.detach_no_collide", "分离后与载具无碰撞")
language.Add("npcpassengers.die_with_vehicle", "载具爆炸时杀死乘客")
language.Add("npcpassengers.driver_enabled", "启用自动驾驶")
language.Add("npcpassengers.turret_enabled", "启用炮塔控制")
language.Add("npcpassengers.turret_lead_targets", "预判目标")
language.Add("npcpassengers.turret_friendly_fire", "允许友军误伤")
language.Add("npcpassengers.turret_hold_fire", "停止射击（禁用射击）")

-- Slider labels
language.Add("npcpassengers.speech_volume", "语音音量")
language.Add("npcpassengers.pitch_variation", "音调变化（+/-）")
language.Add("npcpassengers.crash_threshold", "碰撞敏感度")
language.Add("npcpassengers.crash_cooldown", "碰撞声音冷却")
language.Add("npcpassengers.speech_idle_chance", "闲聊几率")
language.Add("npcpassengers.speech_idle_interval", "闲聊间隔")
language.Add("npcpassengers.ambient_interval", "环境声音间隔")
language.Add("npcpassengers.head_smooth", "头部平滑度")
language.Add("npcpassengers.walk_timeout", "行走超时")
language.Add("npcpassengers.gesture_chance", "手势几率（%）")
language.Add("npcpassengers.gesture_interval", "手势间隔")
language.Add("npcpassengers.crash_threshold_flinch", "碰撞敏感度")
language.Add("npcpassengers.body_sway_amount", "晃动强度")
language.Add("npcpassengers.threat_range", "威胁检测范围")
language.Add("npcpassengers.passenger_combat_range", "乘客战斗范围")
language.Add("npcpassengers.passenger_combat_accuracy", "乘客精度")
language.Add("npcpassengers.passenger_combat_damage", "乘客伤害倍数")
language.Add("npcpassengers.fear_speed_threshold", "恐惧速度阈值")
language.Add("npcpassengers.drowsy_time", "困倦时间")
language.Add("npcpassengers.detach_no_collide_duration", "无碰撞持续时间（秒）")
language.Add("npcpassengers.tank_driver_range", "检测范围")
language.Add("npcpassengers.tank_driver_engage_distance", "交战距离")
language.Add("npcpassengers.tank_driver_speed", "行驶速度")
language.Add("npcpassengers.tank_driver_reverse_distance", "倒车距离")
language.Add("npcpassengers.turret_range", "目标范围")
language.Add("npcpassengers.turret_accuracy", "精度")
language.Add("npcpassengers.turret_reaction_time", "反应时间")
language.Add("npcpassengers.turret_fire_delay", "射击延迟")
language.Add("npcpassengers.turret_aim_speed", "瞄准速度")
language.Add("npcpassengers.hud_scale", "HUD 缩放")
language.Add("npcpassengers.hud_opacity", "HUD 不透明度")
language.Add("npcpassengers.hud_alert_threshold", "警觉阈值")
language.Add("npcpassengers.hud_fear_threshold", "恐惧阈值")
language.Add("npcpassengers.hud_drowsy_threshold", "困倦阈值")
language.Add("npcpassengers.ui_sounds_volume", "UI 声音音量")
language.Add("npcpassengers.ui_panel_width", "面板宽度")

-- Section headers
language.Add("npcpassengers.section.animation", "动画与行为")
language.Add("npcpassengers.section.realism", "高级真实感")
language.Add("npcpassengers.section.hud_position", "HUD 位置与样式")
language.Add("npcpassengers.section.emotion_thresholds", "情绪阈值")
language.Add("npcpassengers.section.emotion_actions", "情绪动作")
language.Add("npcpassengers.section.vehicle_control", "载具控制")
language.Add("npcpassengers.section.hud_controls", "HUD 控制")
language.Add("npcpassengers.section.debug_controls", "调试控制")
language.Add("npcpassengers.section.passenger_status", "乘客状态控制")
language.Add("npcpassengers.section.quick_test", "快速测试按钮")
language.Add("npcpassengers.section.driver_system", "NPC 驾驶员系统")
language.Add("npcpassengers.section.ui_sounds", "UI 声音设置")
language.Add("npcpassengers.section.appearance", "外观")
language.Add("npcpassengers.section.context_menu", "上下文菜单选项")
language.Add("npcpassengers.section.panel_preferences", "设置面板首选项")
language.Add("npcpassengers.section.performance", "性能与技术")
language.Add("npcpassengers.section.simulation", "模拟系统")
language.Add("npcpassengers.section.modules", "模块系统")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "分配座位")
language.Add("npcpassengers.btn.detach", "分离")
language.Add("npcpassengers.btn.copy_summary", "复制摘要")
language.Add("npcpassengers.btn.copy_debug", "复制调试")
language.Add("npcpassengers.btn.enable_all_speech", "启用所有语音")
language.Add("npcpassengers.btn.disable_all_speech", "禁用所有语音")
language.Add("npcpassengers.btn.show_current_vehicle", "仅显示当前载具")
language.Add("npcpassengers.btn.auto_refresh", "自动刷新可见列表")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "未检测到当前载具。坐在载具中或禁用当前载具过滤器。")
language.Add("npcpassengers.status.no_match_filter", "没有乘客匹配您的过滤器。尝试名称、类别、座位号、状态或载具类别。")
language.Add("npcpassengers.status.no_passengers_vehicle", "在您的当前载具中未找到乘客。")
language.Add("npcpassengers.status.no_passengers", "未找到乘客。NPC 需要在载具中行驶后才能在此处管理。")
language.Add("npcpassengers.status.all_passengers", "所有乘客")
language.Add("npcpassengers.status.current_vehicle_only", "仅当前载具")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F 聚焦搜索")
language.Add("npcpassengers.status.no_matches", "没有匹配的设置")
language.Add("npcpassengers.status.showing_matches", "显示前 %d / %d 个匹配项")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "打开设置")
language.Add("npcpassengers.menu.reset_all", "重置所有设置")

-- Button states
language.Add("npcpassengers.state.on", "开")
language.Add("npcpassengers.state.off", "关")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "自动加入")
language.Add("npcpassengers.chat.hud_status", "乘客 HUD")
language.Add("npcpassengers.chat.hud_position", "HUD 位置")
language.Add("npcpassengers.chat.target_debug", "目标调试")
language.Add("npcpassengers.chat.turret_gunners", "炮塔炮手")
language.Add("npcpassengers.chat.turret_holding", "停止射击")
language.Add("npcpassengers.chat.turret_fire", "开火")
language.Add("npcpassengers.chat.unknown", "未知")
language.Add("npcpassengers.chat.nothing_copy", "没有可复制的内容。")
language.Add("npcpassengers.chat.clipboard_unavailable", "此版本中无法访问剪贴板。")
language.Add("npcpassengers.chat.copied_clipboard", "已复制到剪贴板。")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "坐在同一载具中以重新分配此乘客。")
language.Add("npcpassengers.chat.no_visible_passengers", "没有可见乘客可复制。")
language.Add("npcpassengers.chat.need_vehicle", "您需要在载具中才能使用此功能。")
language.Add("npcpassengers.chat.keybinds_applied", "已应用推荐的按键绑定。")
language.Add("npcpassengers.chat.keybinds_cleared", "已清除所有按键绑定。")
language.Add("npcpassengers.chat.context_enabled", "已启用所有上下文菜单选项。")
language.Add("npcpassengers.chat.context_hidden", "已隐藏所有上下文菜单选项。")
language.Add("npcpassengers.chat.panel_compact", "面板大小设置为紧凑。")
language.Add("npcpassengers.chat.panel_default", "面板大小设置为默认。")
language.Add("npcpassengers.chat.panel_large", "面板大小设置为大型。")
language.Add("npcpassengers.chat.panel_centered", "面板已居中。")
language.Add("npcpassengers.chat.settings_reset", "所有 UI 设置已重置为默认值！")
language.Add("npcpassengers.chat.npc_selected", "已选择 NPC！现在右键单击载具并选择"添加选定的 NPC"")
language.Add("npcpassengers.chat.adding_npc", "正在将 NPC 添加到载具...")
language.Add("npcpassengers.chat.selection_cancelled", "已取消 NPC 选择")
language.Add("npcpassengers.chat.summary_copied", "乘客摘要已复制。")
language.Add("npcpassengers.chat.debug_copied", "乘客调试信息已复制。")
language.Add("npcpassengers.chat.no_passengers_found", "未找到乘客。NPC 必须在载具中。")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "状态强度 %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "筛选乘客...")
language.Add("npcpassengers.ui.press_key", "按键...")
language.Add("npcpassengers.ui.work_in_progress", "开发中")
language.Add("npcpassengers.ui.under_development", "此功能目前正在开发中")
language.Add("npcpassengers.ui.check_back_later", "请在未来的更新中查看！")
language.Add("npcpassengers.ui.search_desc_passengers", "按名称、类别、座位、状态或载具筛选活跃乘客。")
language.Add("npcpassengers.ui.search_desc_sort", "按载具、名称、座位、健康或状态排序可见乘客列表。")
language.Add("npcpassengers.ui.search_label_filter", "乘客筛选")
language.Add("npcpassengers.ui.search_label_sort", "乘客排序")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "如何将 NPC 添加到我的载具？")
language.Add("npcpassengers.faq.add_npc.answer", "使用上下文菜单（右键单击 NPC）并选择"设为乘客"。或使用"附加最近的 NPC"按键绑定。NPC 必须对您友好。")
language.Add("npcpassengers.faq.remove_npc", "如何从我的载具中移除乘客？")
language.Add("npcpassengers.faq.remove_npc.answer", "转到设置中的乘客选项卡，选择乘客，然后单击分离。或使用"分离所有乘客"按键绑定。")
language.Add("npcpassengers.faq.position", "NPC 悬浮/穿过座位！")
language.Add("npcpassengers.faq.position.answer", "转到位置选项卡并调整高度/前方/右侧偏移。每个载具模型都不同，因此您可能需要微调这些值。使用调试面板实时测试位置。")
language.Add("npcpassengers.faq.speech", "NPC 不说话！")
language.Add("npcpassengers.faq.speech.answer", "检查行为选项卡并确保"启用 NPC 语音"已打开。还要验证语音音量高于 0。某些 NPC 模型可能没有可用的语音行。")
language.Add("npcpassengers.faq.autojoin", "自动加入如何工作？")
language.Add("npcpassengers.faq.autojoin.answer", "在自动加入选项卡中启用后，附近的友方 NPC 会在你进入载具时自动上车 - 就像 Half-Life 2 中的小队机制。您可以设置检测范围并限制可以自动加入的 NPC 数量。")
language.Add("npcpassengers.faq.death", "乘客死亡时会发生什么？")
language.Add("npcpassengers.faq.death.answer", "死亡的乘客将显示红色发光效果并在 HUD 上显示骷髅图标。靠近您的载具并按住 R 以移除他们的尸体。尸体将被弹出并具有物理效果。")
language.Add("npcpassengers.faq.status", "乘客状态意味着什么？")
language.Add("npcpassengers.faq.status.answer", "平静：放松，没有威胁。警觉：检测到敌人。恐惧：危险驾驶。困倦：长时间平静行驶。死亡：健康归零。")
language.Add("npcpassengers.faq.keybinds", "我的按键绑定不起作用！")
language.Add("npcpassengers.faq.keybinds.answer", "转到按键选项卡并确保您实际设置了按键绑定（默认情况下未绑定）。单击每个操作旁边的按钮并按所需的键。右键单击以取消绑定。")
language.Add("npcpassengers.faq.errors", "插件根本不起作用 / 我收到错误！")
language.Add("npcpassengers.faq.errors.answer", "确保您运行的是最新版本的 Garry's Mod。检查控制台是否有错误（波浪号键 ~）。尝试禁用冲突的插件。")
language.Add("npcpassengers.faq.combat", "乘客可以从载具中射击吗？")
language.Add("npcpassengers.faq.combat.answer", "目前不能。NPC 将跟踪敌人并对威胁做出反应，但坐下时不会发射武器。此功能可能在未来的更新中添加。")
language.Add("npcpassengers.faq.stop_autojoin", "如何阻止 NPC 自动加入？")
language.Add("npcpassengers.faq.stop_autojoin.answer", "禁用自动加入选项卡中的"启用自动加入"复选框，或使用"切换自动加入"按键绑定。")
language.Add("npcpassengers.faq.settings", "设置保存在哪里？")
language.Add("npcpassengers.faq.settings.answer", "所有设置都作为 ConVar 保存在您的 GMod 配置中。它们在会话之间保持不变，并且特定于您的客户端。")
language.Add("npcpassengers.faq.vehicles", "这适用于所有载具吗？")
language.Add("npcpassengers.faq.vehicles.answer", "它适用于大多数具有物理效果的载具。坦克、APC、汽车、船只等。某些模组载具可能需要位置调整。")
language.Add("npcpassengers.faq.multiple", "我可以在一辆载具中有多个 NPC 吗？")
language.Add("npcpassengers.faq.multiple.answer", "可以！在常规设置中设置"乘客限制"。插件将自动在载具周围分配 NPC。对于特定座位位置，请在位置选项卡中调整偏移。")
language.Add("npcpassengers.faq.crashes", "碰撞后 NPC 表现怪异！")
language.Add("npcpassengers.faq.crashes.answer", "这是正常的 - 他们对危险驾驶做出恐惧反应。如果您希望他们的反应较少，请在 HUD 设置中降低恐惧阈值。")
language.Add("npcpassengers.faq.reset_setting", "如何仅重置一个设置？")
language.Add("npcpassengers.faq.reset_setting.answer", "使用该特定设置的控制台命令。所有命令都以"nai_npc_"开头。在控制台中键入"find nai_npc"以查看所有可用命令。")
language.Add("npcpassengers.faq.multiplayer", "这在多人游戏中有效吗？")
language.Add("npcpassengers.faq.multiplayer.answer", "是的！该插件在单人游戏和多人游戏服务器上都有效。每个玩家控制自己的乘客。")
language.Add("npcpassengers.faq.lvs", "这适用于 LVS 载具吗？")
language.Add("npcpassengers.faq.lvs.answer", "是的！该插件完全支持 LVS（Lua Vehicle System）载具。NPC 可以作为乘客乘坐，如果启用了 NPC 驾驶员模式，甚至可以驾驶 LVS 载具。")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "这些设置控制插件的用户界面行为")
language.Add("npcpassengers.panel.performance_note1", "更改面板大小需要关闭并重新打开菜单")
language.Add("npcpassengers.panel.performance_note2", "禁用声音或动画可以提高低端系统的性能")
language.Add("npcpassengers.panel.performance_title", "界面设置信息")
language.Add("npcpassengers.help.console_title", "用于调试的控制台命令：")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- 启用调试模式以查看详细信息")
language.Add("npcpassengers.about.title", "关于")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "语言已更改为英语。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "你好！")
language.Add("npcpassengers.welcome.msg1", "在抱怨乘客坐在载具顶部之前，\n请打开设置。你可以做到的，我相信你。")
language.Add("npcpassengers.welcome.msg2", "这个插件还远未达到完美，请不要犹豫\n报告错误并建议新功能。我会阅读你的所有评论！")
language.Add("npcpassengers.welcome.changelog", "更新日志")
language.Add("npcpassengers.welcome.got_it", "明白了！")
language.Add("npcpassengers.welcome.console_cmd", "或使用控制台命令：nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "NPC 类别黑名单")
language.Add("npcpassengers.ui.blacklist_help", "逗号分隔的 NPC 类别名称列表，这些类别不能使用炮塔。使用"getnpcblacklist"控制台命令查看当前黑名单。")
language.Add("npcpassengers.ui.hud_position", "HUD 位置")
language.Add("npcpassengers.ui.not_bound", "未绑定")
language.Add("npcpassengers.ui.keybind_tip", "提示：右键单击按键绑定以取消绑定。绑定时按 ESC 取消。")
language.Add("npcpassengers.ui.dont_show_again", "不再显示")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "乘客操作")
language.Add("npcpassengers.hud.filter_prefix", "筛选：")
language.Add("npcpassengers.hud.sort_prefix", "排序：")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  自动刷新：")
language.Add("npcpassengers.hud.vehicle_prefix", "载具：")
language.Add("npcpassengers.hud.speed_prefix", "速度：")
language.Add("npcpassengers.hud.npc_prefix", "NPC：")
language.Add("npcpassengers.hud.on", "开")
language.Add("npcpassengers.hud.off", "关")
language.Add("npcpassengers.hud.passengers", "乘客")
language.Add("npcpassengers.hud.npc_driver", "NPC 驾驶员")
language.Add("npcpassengers.hud.total_prefix", "总计：")
language.Add("npcpassengers.hud.showing_prefix", "显示：")
language.Add("npcpassengers.hud.current_vehicle_prefix", "当前载具：")
language.Add("npcpassengers.hud.hidden_prefix", "隐藏：")
language.Add("npcpassengers.hud.dead_prefix", "死亡：")
language.Add("npcpassengers.hud.scared_prefix", "恐惧：")
language.Add("npcpassengers.hud.drowsy_prefix", "困倦：")

-- Status labels
language.Add("npcpassengers.status.calm", "平静")
language.Add("npcpassengers.status.alert", "警觉")
language.Add("npcpassengers.status.scared", "恐惧")
language.Add("npcpassengers.status.drowsy", "困倦")
language.Add("npcpassengers.status.dead", "死亡")
language.Add("npcpassengers.status.unknown", "未知")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "市民")
language.Add("npcpassengers.npc.alyx", "阿莱克斯")
language.Add("npcpassengers.npc.barney", "巴尼")
language.Add("npcpassengers.npc.monk", "格里戈里神父")
language.Add("npcpassengers.npc.vortigaunt", "弗地冈人")
language.Add("npcpassengers.npc.eli", "伊莱")
language.Add("npcpassengers.npc.kleiner", "克莱纳博士")
language.Add("npcpassengers.npc.mossman", "莫斯曼博士")
language.Add("npcpassengers.npc.breen", "布林博士")
language.Add("npcpassengers.npc.dog", "道格")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "载具")
language.Add("npcpassengers.sort.name", "名称")
language.Add("npcpassengers.sort.seat", "座位")
language.Add("npcpassengers.sort.health", "健康")
language.Add("npcpassengers.sort.status", "状态")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "载具优先")
language.Add("npcpassengers.sort.name_az", "名称 A-Z")
language.Add("npcpassengers.sort.seat_number", "座位号")
language.Add("npcpassengers.sort.highest_health", "最高健康")
language.Add("npcpassengers.sort.status_priority", "状态优先")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "载具：未知")
language.Add("npcpassengers.ui.seat_prefix", "座位")
language.Add("npcpassengers.ui.same_vehicle", "同一载具")
language.Add("npcpassengers.ui.other_vehicle", "其他载具")
language.Add("npcpassengers.ui.hidden", "隐藏")
language.Add("npcpassengers.ui.visible", "可见")
language.Add("npcpassengers.ui.health_format", "健康 %d / %d")
language.Add("npcpassengers.ui.refresh_list", "刷新乘客列表")
language.Add("npcpassengers.ui.copy_list", "复制可见乘客列表")
language.Add("npcpassengers.ui.make_exit", "使当前载具乘客离开")
language.Add("npcpassengers.ui.reset_pos", "重置位置和角度")
language.Add("npcpassengers.ui.crash_reactions", "碰撞反应")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "上/下车声音")
language.Add("npcpassengers.section.ambient_sounds", "环境声音")
language.Add("npcpassengers.section.gesture_animations", "手势动画")
language.Add("npcpassengers.section.threat_awareness", "威胁感知")
language.Add("npcpassengers.section.emotional_states", "情绪状态")
language.Add("npcpassengers.section.turret_control", "炮塔控制（实验性）")
language.Add("npcpassengers.section.turret_blacklist", "炮塔 NPC 黑名单")
language.Add("npcpassengers.section.idle_chatter", "空闲闲聊")
language.Add("npcpassengers.section.body_physics", "身体物理")
language.Add("npcpassengers.section.npc_auto_driver", "NPC 自动驾驶")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "左下角")
language.Add("npcpassengers.hud.bottom_right", "右下角")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "启用乘客 HUD")
language.Add("npcpassengers.ui.cover_face", "遮挡脸部")
language.Add("npcpassengers.ui.apply_keybinds", "应用推荐的按键绑定")
language.Add("npcpassengers.ui.clear_keybinds", "清除所有按键绑定")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "测试畏缩手势")
language.Add("npcpassengers.ui.test_random", "测试随机手势")
language.Add("npcpassengers.ui.reset_states", "重置所有状态")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "启用所有上下文菜单选项")
language.Add("npcpassengers.ui.hide_context", "隐藏所有上下文菜单选项")
language.Add("npcpassengers.ui.set_compact", "设置紧凑面板大小")
language.Add("npcpassengers.ui.set_default", "设置默认面板大小")
language.Add("npcpassengers.ui.set_large", "设置大型面板大小")
language.Add("npcpassengers.ui.center_panel", "立即居中面板")
language.Add("npcpassengers.ui.reset_ui", "将所有 UI 设置重置为默认值")

-- Role names
language.Add("npcpassengers.role.citizen_female", "市民（女）")
language.Add("npcpassengers.role.citizen_male", "市民（男）")
language.Add("npcpassengers.role.medic", "医疗兵")
language.Add("npcpassengers.role.rebel", "反抗军")
language.Add("npcpassengers.role.passenger", "乘客")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "仅在载具中时显示")
language.Add("npcpassengers.hud.show_calm", "显示平静乘客")
language.Add("npcpassengers.hud.show_hints", "显示上下文提示")
language.Add("npcpassengers.hud.show_target_debug", "显示目标调试")
language.Add("npcpassengers.hud.play_cues", "播放成功/失败提示音")
language.Add("npcpassengers.debug.enable_mode", "启用调试模式")
language.Add("npcpassengers.ui.enable_sounds", "启用 UI 声音")
language.Add("npcpassengers.ui.hover_sounds", "按钮悬停声音")
language.Add("npcpassengers.ui.click_sounds", "按钮点击声音")
language.Add("npcpassengers.ui.enable_animations", "启用 UI 动画")
language.Add("npcpassengers.ui.show_tooltips", "显示工具提示")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "自动隐藏滚动条")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "侧边栏滚动平滑度")
language.Add("npcpassengers.ui.color_theme", "颜色主题")
language.Add("npcpassengers.ui.font_scale", "字体缩放")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "取消 NPC 选择")
language.Add("npcpassengers.context.remove_passenger", "移除乘客")
language.Add("npcpassengers.context.blacklist_passenger", "将乘客加入黑名单")
language.Add("npcpassengers.context.whitelist_passenger", "将乘客加入白名单")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "按键绑定")
language.Add("npcpassengers.keybinds.desc", "为快速操作配置键盘快捷键。")
language.Add("npcpassengers.keybind.attach", "附加最近的 NPC")
language.Add("npcpassengers.keybind.attach.help", "将最近的友方 NPC 附加到您的载具。")
language.Add("npcpassengers.keybind.detach_all", "分离所有 NPC")
language.Add("npcpassengers.keybind.detach_all.help", "从您的载具中移除所有乘客。")
language.Add("npcpassengers.keybind.toggle_autojoin", "切换自动加入")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "快速启用/禁用自动加入。")
language.Add("npcpassengers.keybind.menu", "打开设置菜单")
language.Add("npcpassengers.keybind.menu.help", "打开设置面板。")
language.Add("npcpassengers.keybind.exit_all", "所有乘客退出")
language.Add("npcpassengers.keybind.exit_all.help", "使所有乘客离开载具。")
language.Add("npcpassengers.keybind.toggle_hud", "切换 HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "显示/隐藏乘客 HUD。")
language.Add("npcpassengers.keybind.quick_attach", "快速附加模式")
language.Add("npcpassengers.keybind.quick_attach.help", "按住以快速附加您正在看的 NPC")
language.Add("npcpassengers.keybind.hold_fire", "NPC 停止射击")
language.Add("npcpassengers.keybind.hold_fire.help", "告诉炮手 NPC 停止射击")
language.Add("npcpassengers.keybind.open_fire", "NPC 开火")
language.Add("npcpassengers.keybind.open_fire.help", "告诉炮手 NPC 攻击目标")
language.Add("npcpassengers.keybind.cycle_view", "循环乘客视角")
language.Add("npcpassengers.keybind.cycle_view.help", "在乘客之间循环切换相机")
language.Add("npcpassengers.keybind.cycle_hud_position", "循环 HUD 位置")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "将乘客 HUD 移动到所有四个角落")
language.Add("npcpassengers.keybind.toggle_debug", "切换目标调试")
language.Add("npcpassengers.keybind.toggle_debug.help", "切换小型目标调试覆盖层")
language.Add("npcpassengers.keybind.test_gesture", "测试随机手势")
language.Add("npcpassengers.keybind.test_gesture.help", "在最近的乘客上播放随机手势")
language.Add("npcpassengers.keybind.reset_all", "重置所有 NPC")
language.Add("npcpassengers.keybind.reset_all.help", "重置所有乘客的动画状态")

-- HUD Settings
language.Add("npcpassengers.hud.header", "HUD 设置")
language.Add("npcpassengers.hud.enable", "启用 HUD")
language.Add("npcpassengers.hud.enable.help", "在屏幕上显示乘客状态覆盖层。")
language.Add("npcpassengers.hud.position", "HUD 位置")
language.Add("npcpassengers.hud.position.help", "HUD 在屏幕上的显示位置。")
language.Add("npcpassengers.hud.position.topleft", "左上角")
language.Add("npcpassengers.hud.position.topright", "右上角")
language.Add("npcpassengers.hud.position.bottomleft", "左下角")
language.Add("npcpassengers.hud.position.bottomright", "右下角")
language.Add("npcpassengers.hud.scale", "HUD 缩放")
language.Add("npcpassengers.hud.scale.help", "HUD 的尺寸倍数。")
language.Add("npcpassengers.hud.opacity", "HUD 不透明度")
language.Add("npcpassengers.hud.opacity.help", "背景透明度（0 = 不可见，1 = 实心）。")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC 驾驶员")
language.Add("npcpassengers.driver.desc", "允许 NPC 为您驾驶载具。")
language.Add("npcpassengers.driver.enable", "启用 NPC 驾驶员")
language.Add("npcpassengers.driver.enable.help", "允许 NPC 控制载具。")
language.Add("npcpassengers.driver.behavior", "驾驶行为")
language.Add("npcpassengers.driver.behavior.help", "NPC 如何驾驶载具。")
language.Add("npcpassengers.driver.behavior.cruise", "随机巡航")
language.Add("npcpassengers.driver.behavior.follow", "跟随玩家")
language.Add("npcpassengers.driver.behavior.patrol", "巡逻")
language.Add("npcpassengers.driver.behavior.flee", "逃跑")
language.Add("npcpassengers.driver.behavior.parked", "保持停车")

-- Help / FAQ
language.Add("npcpassengers.help.header", "常见问题")
language.Add("npcpassengers.help.desc", "常见问题和故障排除的快速答案。")
language.Add("npcpassengers.help.still_need", "仍需要帮助？")
language.Add("npcpassengers.help.community", "加入我们的 Discord 社区获取支持！")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "坦克/LVS")
language.Add("npcpassengers.nav.debugging", "调试")
language.Add("npcpassengers.nav.driver", "NPC 驾驶员")
language.Add("npcpassengers.nav.interface", "界面")
language.Add("npcpassengers.nav.simulate", "模拟")
language.Add("npcpassengers.nav.modules", "模块")
language.Add("npcpassengers.nav.about", "关于")
language.Add("npcpassengers.search.placeholder", "搜索设置...")

-- About page
language.Add("npcpassengers.about.description", "具有情感 AI 和逼真物理的高级乘客系统")
language.Add("npcpassengers.about.feature_status", "状态系统：平静 / 警觉 / 恐惧 / 困倦 / 死亡")
language.Add("npcpassengers.about.feature_performance", "性能：座位缓存、限制计时器、优化的客户端钩子")
language.Add("npcpassengers.about.feature_filtering", "载具筛选、登船重试冷却、仅限小队自动加入")
language.Add("npcpassengers.about.actions", "操作")
language.Add("npcpassengers.about.show_welcome", "显示欢迎屏幕")
language.Add("npcpassengers.about.open_github", "打开 GitHub 页面")
language.Add("npcpassengers.about.reset_settings", "将所有设置重置为默认值")

-- Status messages
language.Add("npcpassengers.status.calm", "平静")
language.Add("npcpassengers.status.alert", "警觉")
language.Add("npcpassengers.status.scared", "恐惧")
language.Add("npcpassengers.status.drowsy", "困倦")
language.Add("npcpassengers.status.dead", "死亡")
language.Add("npcpassengers.status.calm.desc", "放松，附近没有威胁")
language.Add("npcpassengers.status.alert.desc", "检测到敌人，NPC 正在跟踪威胁")
language.Add("npcpassengers.status.scared.desc", "危险驾驶（高速、碰撞）")
language.Add("npcpassengers.status.drowsy.desc", "长时间平静行驶，NPC 正在变得困倦")
language.Add("npcpassengers.status.dead.desc", "健康归零")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "自动加入：开")
language.Add("npcpassengers.chat.autojoin_off", "自动加入：关")
language.Add("npcpassengers.chat.hud_on", "HUD：开")
language.Add("npcpassengers.chat.hud_off", "HUD：关")
language.Add("npcpassengers.chat.prefix", "[更好的 NPC 乘客]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "附近没有载具")
language.Add("npcpassengers.error.no_npc", "附近没有 NPC")
language.Add("npcpassengers.error.vehicle_full", "载具已满")
language.Add("npcpassengers.error.too_far", "NPC 距离载具太远")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "更改语言")
language.Add("npcpassengers.tooltip.minimize", "最小化面板")
language.Add("npcpassengers.tooltip.expand", "展开面板")
language.Add("npcpassengers.tooltip.welcome", "显示欢迎屏幕")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "所有 NPC 语音的主开关。禁用以完全静音乘客。")
language.Add("npcpassengers.speech_volume.help", "NPC 语音的音量（0 = 静音，100 = 最大音量）。")
language.Add("npcpassengers.pitch_variation.help", "随机音调变化以获得更自然的声音。0 = 单调，越高 = 变化越多。")
language.Add("npcpassengers.crash_enable.help", "当载具急剧减速时（碰撞、急刹车），NPC 会发出呻吟/尖叫。")
language.Add("npcpassengers.crash_threshold.help", "触发碰撞声音所需的减速度。越低 = 越敏感。")
language.Add("npcpassengers.crash_cooldown.help", "每个 NPC 碰撞声音之间的最小秒数。")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPC 在行驶时偶尔说话 - 评论、问题、观察。")
language.Add("npcpassengers.speech_idle_chance.help", "每次检查的闲聊概率。0 = 从不，1 = 总是尝试说话。")
language.Add("npcpassengers.speech_idle_interval.help", "闲聊尝试之间的最小秒数。")
language.Add("npcpassengers.speech_board.help", "NPC 在进入和离开载具时说话。")
language.Add("npcpassengers.ambient_sounds.help", "偶尔的咳嗽、叹息、哼声 - 背景生活声音。")
language.Add("npcpassengers.ambient_interval.help", "环境声音之间的平均秒数。")
language.Add("npcpassengers.animation.help", "微调 NPC 动画和头部运动。")
language.Add("npcpassengers.head_look.help", "NPC 自然地环顾四周，看着玩家，看着窗外等。")
language.Add("npcpassengers.head_smooth.help", "头部移动的平滑程度。越低 = 越灵敏，越高 = 越漂浮。")
language.Add("npcpassengers.blink.help", "NPC 坐着时逼真地眨眼。")
language.Add("npcpassengers.breathing.help", "NPC 头部上的微妙呼吸动画。")
language.Add("npcpassengers.walk_timeout.help", "NPC 放弃走向载具前的秒数。")
language.Add("npcpassengers.realism.help", "基于物理的反应和感知系统，以获得最大的沉浸感。")
language.Add("npcpassengers.talking_gestures.help", "NPC 在行驶时随机播放手势和身体动画。")
language.Add("npcpassengers.gesture_chance.help", "每个间隔播放手势的百分比几率。")
language.Add("npcpassengers.gesture_interval.help", "手势机会检查之间的秒数。")
language.Add("npcpassengers.crash_flinch.help", "当载具碰撞或急刹车时，NPC 会畏缩并向前冲。")
language.Add("npcpassengers.crash_threshold_flinch.help", "触发畏缩所需的速度变化（越低 = 越敏感）。")
language.Add("npcpassengers.body_sway.help", "NPC 在转弯时倾斜，在加速/刹车时支撑。")
language.Add("npcpassengers.body_sway_amount.help", "NPC 随载具移动晃动的程度。")
language.Add("npcpassengers.threat_awareness.help", "NPC 自动看向附近的敌人。")
language.Add("npcpassengers.threat_range.help", "NPC 可以检测威胁进行头部跟踪的距离。")
language.Add("npcpassengers.combat_alert.help", "当敌人附近时，NPC 变得紧张和反应。")
language.Add("npcpassengers.passenger_combat.help", "默认禁用。启用此功能以允许武装乘客从载具内部射击。")
language.Add("npcpassengers.passenger_combat_range.help", "武装乘客可以获取目标的距离。")
language.Add("npcpassengers.passenger_combat_accuracy.help", "较高的值会收紧武装乘客的射击扩散。")
language.Add("npcpassengers.passenger_combat_damage.help", "缩放乘客射击造成的伤害。")
language.Add("npcpassengers.passenger_interaction.help", "多个乘客互相注视并偶尔互相交谈。")
language.Add("npcpassengers.fear_reactions.help", "NPC 对危险驾驶感到恐惧 - 眼睛睁大，恐慌的声音。")
language.Add("npcpassengers.fear_speed_threshold.help", "NPC 开始感到紧张的速度（单位/秒）。")
language.Add("npcpassengers.drowsiness.help", "NPC 在长时间平静的行驶中变得困倦 - 缓慢眨眼，点头。")
language.Add("npcpassengers.drowsy_time.help", "困倦开始前的平静行驶秒数。")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "坦克、APC 和 LVS 载具的设置。")
language.Add("npcpassengers.hide_in_tanks.help", "当 NPC 在坦克和 APC 内部时使其不可见。")
language.Add("npcpassengers.eject_stuck_check.help", "当 NPC 在退出时卡住时，自动将其推出载具。防止 NPC 在退出时穿模到载具中。")
language.Add("npcpassengers.detach_no_collide.help", "分离后，NPC 暂时穿过载具，以便他们可以走开而不会穿模或卡住。")
language.Add("npcpassengers.detach_no_collide_duration.help", "NPC 在分离后忽略载具碰撞的时间。")
language.Add("npcpassengers.die_with_vehicle.help", "当 NPC 的载具被爆炸或火灾摧毁时，NPC 乘客死亡（比他们毫发无损地走出残骸更具沉浸感）。")
language.Add("npcpassengers.tank_driver.help", "允许驾驶座上的 NPC 自动驶向敌人。")
language.Add("npcpassengers.tank_driver_range.help", "驾驶员检测敌人的最大距离。")
language.Add("npcpassengers.tank_driver_distance.help", "与敌人保持的距离。")
language.Add("npcpassengers.tank_driver_throttle.help", "油门量（0.1 = 慢，1 = 全速）。")
language.Add("npcpassengers.tank_driver_reverse.help", "远离敌人的距离。")
language.Add("npcpassengers.tank_turret.help", "允许 NPC 控制 LVS 载具上的炮塔。")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "在行驶时在屏幕上显示乘客状态（情绪、警觉）。")
language.Add("npcpassengers.hud_show_calm.help", "禁用时，仅显示非平静状态的乘客。")
language.Add("npcpassengers.hud_thresholds.desc", "当情绪水平超过这些阈值时，乘客在 HUD 中显示该状态。")
language.Add("npcpassengers.hud_alert_threshold.help", "显示"警觉"状态所需的警觉水平（检测到威胁）。")
language.Add("npcpassengers.hud_fear_threshold.help", "显示"恐惧"状态所需的恐惧水平（危险驾驶）。")
language.Add("npcpassengers.hud_drowsy_threshold.help", "显示"困倦"状态所需的平静时间比率（长时间平静行驶）。")
language.Add("npcpassengers.hud_actions.desc", "选择乘客在经历每种情绪状态时采取的行动。")
language.Add("npcpassengers.hud_actions_note", "注意：某些操作可能不可见，具体取决于 NPC 模型支持。")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "为 NPC 乘客操作设置自定义按键绑定。单击按钮并按键以绑定。")
language.Add("npcpassengers.keybinds_hud.desc", "用于显示、移动和调试乘客覆盖层的快速 HUD 控制。")
language.Add("npcpassengers.keybinds_debug_note", "调试按键绑定仅在启用调试模式时有效。")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "用于测试 NPC 行为的高级调试工具。首先在设置中启用调试模式。")
language.Add("npcpassengers.debug_mode.help", "显示调试测试按钮并启用调试命令。")
language.Add("npcpassengers.debug_status.help", "手动设置乘客状态以进行测试。单击"刷新列表"以查看当前乘客。")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "为按钮、复选框和其他 UI 元素配置声音效果")
language.Add("npcpassengers.ui_sounds_enabled.help", "所有 UI 声音效果的主开关")
language.Add("npcpassengers.ui_sounds_volume.help", "UI 声音的音量倍数（1.0 = 正常，2.0 = 双倍）")
language.Add("npcpassengers.ui_hover_enabled.help", "悬停在按钮上时播放声音")
language.Add("npcpassengers.ui_click_enabled.help", "单击按钮和复选框时播放声音")
language.Add("npcpassengers.context_menu.desc", "选择右键单击 NPC 时出现的选项")
language.Add("npcpassengers.context_make_passenger.help", "将 NPC 作为乘客添加到您的当前载具")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "将 NPC 添加到特定载具（单击 NPC，然后载具）")
language.Add("npcpassengers.context_detach.help", "从载具中移除 NPC")
language.Add("npcpassengers.ui_show_welcome.help", "当插件更新到新版本时显示欢迎面板")
language.Add("npcpassengers.ui_panel_width.help", "设置面板的宽度")
language.Add("npcpassengers.ui_panel_height.help", "设置面板的高度")
language.Add("npcpassengers.ui_animations.help", "平滑过渡和悬停效果（可能会影响性能）")
language.Add("npcpassengers.ui_tooltips.help", "悬停在设置上时显示有用的工具提示")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "仅在您滚动或悬停时显示滚动条。")
language.Add("npcpassengers.ui_scroll_smoothness_note", "注意：拖动任何滑块时面板变为 70% 透明，以便查看背景中的内容。")
language.Add("npcpassengers.ui_scroll_smoothness.help", "较低的值 = 更平滑但更慢的滚动（0.01-1）")
language.Add("npcpassengers.ui_color_theme.help", "选择设置面板的颜色主题。更改立即生效。")
language.Add("npcpassengers.ui_font_scale.help", "缩放所有 UI 字体大小。1.0 = 默认，0.5 = 一半大小，2.0 = 双倍大小。")

print("[Better NPC Passengers] Chinese localization loaded!")
