-- Better NPC Passengers - English Localization
-- This file contains all translatable strings for the addon

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Settings")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "General")
language.Add("npcpassengers.nav.autojoin", "Auto-Join")
language.Add("npcpassengers.nav.passengers", "Passengers")
language.Add("npcpassengers.nav.position", "Position")
language.Add("npcpassengers.nav.behaviour", "Behaviour")
language.Add("npcpassengers.nav.keybinds", "Keybinds")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Driver")
language.Add("npcpassengers.nav.help", "Help")

-- General Settings
language.Add("npcpassengers.general.header", "General Settings")
language.Add("npcpassengers.allow_multiple", "Allow Multiple Passengers")
language.Add("npcpassengers.allow_multiple.help", "Let multiple NPCs ride in the same vehicle.")
language.Add("npcpassengers.exit_behavior", "Exit Behavior")
language.Add("npcpassengers.exit_behavior.help", "When should NPC passengers exit the vehicle?")
language.Add("npcpassengers.exit_mode.leave_player", "Leave when player exits")
language.Add("npcpassengers.exit_mode.leave_attack", "Leave when vehicle is attacked")
language.Add("npcpassengers.exit_mode.never", "Never leave automatically")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Timing")
language.Add("npcpassengers.max_attach_dist", "Max Attach Distance")
language.Add("npcpassengers.max_attach_dist.help", "Maximum distance (units) to attach NPC to vehicle.")
language.Add("npcpassengers.detach_delay", "Detach Delay")
language.Add("npcpassengers.detach_delay.help", "Seconds to wait before detaching after player leaves.")
language.Add("npcpassengers.ai_delay", "AI Restore Delay")
language.Add("npcpassengers.ai_delay.help", "Seconds to wait before restoring NPC AI after detaching.")
language.Add("npcpassengers.cooldown", "Cooldown Time")
language.Add("npcpassengers.cooldown.help", "Cooldown between attaching NPCs to same vehicle.")
language.Add("npcpassengers.passenger_limit", "Passenger Limit")
language.Add("npcpassengers.passenger_limit.help", "Max NPCs allowed in vehicle.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Auto-Join (Squad Behavior)")
language.Add("npcpassengers.autojoin.desc", "Friendly NPCs will automatically board your vehicle when you enter it - just like squad mechanics in Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Enable Auto-Join")
language.Add("npcpassengers.autojoin.enable.help", "Nearby friendly NPCs will automatically join when you enter a vehicle.")
language.Add("npcpassengers.autojoin.range", "Auto-Join Range")
language.Add("npcpassengers.autojoin.range.help", "Maximum distance to find NPCs for auto-joining.")
language.Add("npcpassengers.autojoin.max", "Max Auto-Join NPCs")
language.Add("npcpassengers.autojoin.max.help", "Maximum number of NPCs that can auto-join at once.")
language.Add("npcpassengers.autojoin.squad_only", "Squad Members Only")
language.Add("npcpassengers.autojoin.squad_only.help", "Only NPCs with a squad name will auto-join (for HL2-style squads).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Friendly NPCs will automatically board your vehicle when you enter it - just like squad mechanics in Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Passenger Controls")
language.Add("npcpassengers.panel.passengers.desc", "Manage active passengers, filter by name/class/status, copy debug info, reassign seats, and detach riders without leaving the settings panel.")
language.Add("npcpassengers.panel.position.desc", "Fine-tune NPC positioning in vehicles. Use these to fix floating or clipping issues.")
language.Add("npcpassengers.panel.angle.desc", "Adjust NPC rotation in vehicles.")
language.Add("npcpassengers.panel.speech.desc", "Configure how NPCs vocalize while riding in vehicles. HL2-style citizen voices!")

-- Position Settings
language.Add("npcpassengers.position.header", "Position Offsets")
language.Add("npcpassengers.position.desc", "Fine-tune NPC positioning in vehicles. Use these to fix floating or clipping issues.")
language.Add("npcpassengers.height_offset", "Height Offset")
language.Add("npcpassengers.forward_offset", "Forward Offset")
language.Add("npcpassengers.right_offset", "Right Offset")
language.Add("npcpassengers.angle.header", "Angle Offsets")
language.Add("npcpassengers.angle.desc", "Adjust NPC rotation in vehicles.")
language.Add("npcpassengers.yaw_offset", "Yaw (Rotation)")
language.Add("npcpassengers.pitch_offset", "Pitch (Tilt Forward)")
language.Add("npcpassengers.roll_offset", "Roll (Tilt Sideways)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPC Speech (Advanced)")
language.Add("npcpassengers.behaviour.desc", "Configure how NPCs vocalize while riding in vehicles. HL2-style citizen voices!")
language.Add("npcpassengers.speech_enable", "Enable NPC Speech")
language.Add("npcpassengers.speech_enable.help", "Master toggle for all NPC speech. Disable to silence passengers completely.")
language.Add("npcpassengers.speech_volume", "Speech Volume")
language.Add("npcpassengers.speech_volume.help", "How loud NPC voices are (0 = silent, 100 = full volume).")
language.Add("npcpassengers.pitch_variation", "Pitch Variation (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Random pitch variation for more natural voices. 0 = monotone, higher = more variety.")
language.Add("npcpassengers.crash.header", "Crash Reactions")
language.Add("npcpassengers.crash_enable", "Enable Crash Sounds")
language.Add("npcpassengers.crash_enable.help", "NPCs grunt/yelp when vehicle decelerates sharply (crashes, hard braking).")
language.Add("npcpassengers.crash_threshold", "Crash Sensitivity")
language.Add("npcpassengers.crash_threshold.help", "Deceleration needed to trigger crash sounds. Lower = more sensitive.")
language.Add("npcpassengers.crash_cooldown", "Crash Sound Cooldown")
language.Add("npcpassengers.crash_cooldown.help", "Minimum seconds between crash sounds per NPC.")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Keybinds")
language.Add("npcpassengers.keybinds.desc", "Configure keyboard shortcuts for quick actions.")
language.Add("npcpassengers.keybind.attach", "Attach Nearest NPC")
language.Add("npcpassengers.keybind.attach.help", "Attach the nearest friendly NPC to your vehicle.")
language.Add("npcpassengers.keybind.detach_all", "Detach All NPCs")
language.Add("npcpassengers.keybind.detach_all.help", "Remove all passengers from your vehicle.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Toggle Auto-Join")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Quickly enable/disable auto-join.")
language.Add("npcpassengers.keybind.menu", "Open Settings Menu")
language.Add("npcpassengers.keybind.menu.help", "Open the settings panel.")
language.Add("npcpassengers.keybind.exit_all", "Exit All Passengers")
language.Add("npcpassengers.keybind.exit_all.help", "Make all passengers leave the vehicle.")
language.Add("npcpassengers.keybind.toggle_hud", "Toggle HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Show/hide the passenger HUD.")

-- HUD Settings
language.Add("npcpassengers.hud.header", "HUD Settings")
language.Add("npcpassengers.hud.enable", "Enable HUD")
language.Add("npcpassengers.hud.enable.help", "Show passenger status overlay on screen.")
language.Add("npcpassengers.hud.position", "HUD Position")
language.Add("npcpassengers.hud.position.help", "Where the HUD appears on screen.")
language.Add("npcpassengers.hud.position.topleft", "Top Left")
language.Add("npcpassengers.hud.position.topright", "Top Right")
language.Add("npcpassengers.hud.position.bottomleft", "Bottom Left")
language.Add("npcpassengers.hud.position.bottomright", "Bottom Right")
language.Add("npcpassengers.hud.scale", "HUD Scale")
language.Add("npcpassengers.hud.scale.help", "Size multiplier for the HUD.")
language.Add("npcpassengers.hud.opacity", "HUD Opacity")
language.Add("npcpassengers.hud.opacity.help", "Background transparency (0 = invisible, 1 = solid).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC Driver")
language.Add("npcpassengers.driver.desc", "Allow NPCs to drive vehicles for you.")
language.Add("npcpassengers.driver.enable", "Enable NPC Drivers")
language.Add("npcpassengers.driver.enable.help", "Allow NPCs to take control of vehicles.")
language.Add("npcpassengers.driver.behavior", "Driving Behavior")
language.Add("npcpassengers.driver.behavior.help", "How the NPC drives the vehicle.")
language.Add("npcpassengers.driver.behavior.cruise", "Random Cruise")
language.Add("npcpassengers.driver.behavior.follow", "Follow Player")
language.Add("npcpassengers.driver.behavior.patrol", "Patrol")
language.Add("npcpassengers.driver.behavior.flee", "Flee")
language.Add("npcpassengers.driver.behavior.parked", "Stay Parked")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Frequently Asked Questions")
language.Add("npcpassengers.help.desc", "Quick answers to common questions and troubleshooting.")
language.Add("npcpassengers.help.still_need", "Still Need Help?")
language.Add("npcpassengers.help.community", "Join our Discord community for support!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Tank/LVS")
language.Add("npcpassengers.nav.debugging", "Debugging")
language.Add("npcpassengers.nav.driver", "NPC Driver")
language.Add("npcpassengers.nav.interface", "Interface")
language.Add("npcpassengers.nav.simulate", "Simulate")
language.Add("npcpassengers.nav.modules", "Modules")
language.Add("npcpassengers.nav.about", "About")
language.Add("npcpassengers.search.placeholder", "Search settings...")

-- About page
language.Add("npcpassengers.about.description", "Advanced passenger system with emotional AI and realistic physics")
language.Add("npcpassengers.about.feature_status", "Status System: CALM / ALERT / SCARED / DROWSY / DEAD")
language.Add("npcpassengers.about.feature_performance", "Performance: seat caching, throttled timers, optimized client hooks")
language.Add("npcpassengers.about.feature_filtering", "Vehicle filtering, boarding retry cooldown, squad-only auto-join")
language.Add("npcpassengers.about.actions", "Actions")
language.Add("npcpassengers.about.show_welcome", "Show Welcome Screen")
language.Add("npcpassengers.about.open_github", "Open GitHub Page")
language.Add("npcpassengers.about.reset_settings", "Reset ALL Settings to Defaults")

-- Status messages
language.Add("npcpassengers.status.calm", "CALM")
language.Add("npcpassengers.status.alert", "ALERT")
language.Add("npcpassengers.status.scared", "SCARED")
language.Add("npcpassengers.status.drowsy", "DROWSY")
language.Add("npcpassengers.status.dead", "DEAD")
language.Add("npcpassengers.status.calm.desc", "Relaxed, no threats nearby")
language.Add("npcpassengers.status.alert.desc", "Enemy detected, NPC is tracking threats")
language.Add("npcpassengers.status.scared.desc", "Dangerous driving (high speed, crashes)")
language.Add("npcpassengers.status.drowsy.desc", "Long calm ride, NPC is getting sleepy")
language.Add("npcpassengers.status.dead.desc", "Health reached zero")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Auto-Join: ON")
language.Add("npcpassengers.chat.autojoin_off", "Auto-Join: OFF")
language.Add("npcpassengers.chat.hud_on", "HUD: ON")
language.Add("npcpassengers.chat.hud_off", "HUD: OFF")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "No vehicle nearby")
language.Add("npcpassengers.error.no_npc", "No NPC nearby")
language.Add("npcpassengers.error.vehicle_full", "Vehicle is full")
language.Add("npcpassengers.error.too_far", "NPC too far from vehicle")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Change language")
language.Add("npcpassengers.tooltip.minimize", "Minimize panel")
language.Add("npcpassengers.tooltip.expand", "Expand panel")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Master toggle for all NPC speech. Disable to silence passengers completely.")
language.Add("npcpassengers.speech_volume.help", "How loud NPC voices are (0 = silent, 100 = full volume).")
language.Add("npcpassengers.pitch_variation.help", "Random pitch variation for more natural voices. 0 = monotone, higher = more variety.")
language.Add("npcpassengers.crash_enable.help", "NPCs grunt/yelp when vehicle decelerates sharply (crashes, hard braking).")
language.Add("npcpassengers.crash_threshold.help", "Deceleration needed to trigger crash sounds. Lower = more sensitive.")
language.Add("npcpassengers.crash_cooldown.help", "Minimum seconds between crash sounds per NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPCs occasionally speak while riding - comments, questions, observations.")
language.Add("npcpassengers.speech_idle_chance.help", "Probability of chatter per check. 0 = never, 1 = always tries to speak.")
language.Add("npcpassengers.speech_idle_interval.help", "Minimum seconds between idle chatter attempts.")
language.Add("npcpassengers.speech_board.help", "NPCs speak when entering and exiting vehicles.")
language.Add("npcpassengers.ambient_sounds.help", "Occasional coughs, sighs, hums - background life sounds.")
language.Add("npcpassengers.ambient_interval.help", "Average seconds between ambient sounds.")
language.Add("npcpassengers.animation.help", "Fine-tune NPC animations and head movement.")
language.Add("npcpassengers.head_look.help", "NPCs naturally look around, at the player, out windows, etc.")
language.Add("npcpassengers.head_smooth.help", "How smoothly the head moves. Lower = snappier, higher = floaty.")
language.Add("npcpassengers.blink.help", "NPCs blink realistically while sitting.")
language.Add("npcpassengers.breathing.help", "Subtle breathing animation on NPC heads.")
language.Add("npcpassengers.walk_timeout.help", "Seconds before NPC gives up walking to vehicle.")
language.Add("npcpassengers.realism.help", "Physics-based reactions and awareness systems for ultimate immersion.")
language.Add("npcpassengers.talking_gestures.help", "NPCs randomly play hand gestures and body animations while riding.")
language.Add("npcpassengers.gesture_chance.help", "Percent chance to play a gesture each interval.")
language.Add("npcpassengers.gesture_interval.help", "Seconds between gesture opportunity checks.")
language.Add("npcpassengers.crash_flinch.help", "NPCs flinch and lurch forward when vehicle crashes or brakes hard.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Velocity change needed to trigger flinch (lower = more sensitive).")
language.Add("npcpassengers.body_sway.help", "NPCs lean into turns, brace during acceleration/braking.")
language.Add("npcpassengers.body_sway_amount.help", "How much NPCs sway with vehicle movement.")
language.Add("npcpassengers.threat_awareness.help", "NPCs automatically look toward nearby enemies.")
language.Add("npcpassengers.threat_range.help", "How far NPCs can detect threats for head tracking.")
language.Add("npcpassengers.combat_alert.help", "NPCs become tense and reactive when enemies are near.")
language.Add("npcpassengers.passenger_combat.help", "Disabled by default. Enable this to let armed passengers fire from inside vehicles.")
language.Add("npcpassengers.passenger_combat_range.help", "How far armed passengers can acquire targets.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Higher values tighten shot spread for armed passengers.")
language.Add("npcpassengers.passenger_combat_damage.help", "Scales the damage dealt by passenger-fired shots.")
language.Add("npcpassengers.passenger_interaction.help", "Multiple passengers look at and occasionally chat with each other.")
language.Add("npcpassengers.fear_reactions.help", "NPCs get scared by dangerous driving - wide eyes, panicked sounds.")
language.Add("npcpassengers.fear_speed_threshold.help", "Speed (units/sec) at which NPCs start getting nervous.")
language.Add("npcpassengers.drowsiness.help", "NPCs get sleepy on long, calm rides - slow blinks, head nods.")
language.Add("npcpassengers.drowsy_time.help", "Seconds of calm riding before drowsiness kicks in.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Settings for tanks, APCs, and LVS vehicles.")
language.Add("npcpassengers.hide_in_tanks.help", "Make NPC passengers invisible when inside tanks and APCs.")
language.Add("npcpassengers.eject_stuck_check.help", "Automatically push NPCs out of vehicles when they get stuck during ejection. Prevents NPCs from clipping into vehicles when exiting.")
language.Add("npcpassengers.detach_no_collide.help", "After detaching, NPCs temporarily pass through the vehicle so they can walk away without clipping or getting stuck.")
language.Add("npcpassengers.detach_no_collide_duration.help", "How long NPCs ignore the vehicle's collision after detaching.")
language.Add("npcpassengers.die_with_vehicle.help", "NPC passengers die when their vehicle is destroyed by explosion or fire (more immersive than them walking out of a wreck unharmed).")
language.Add("npcpassengers.tank_driver.help", "Allow NPCs in driver seat to automatically drive toward enemies.")
language.Add("npcpassengers.tank_driver_range.help", "Maximum range for driver to detect enemies.")
language.Add("npcpassengers.tank_driver_distance.help", "Distance to maintain from enemies.")
language.Add("npcpassengers.tank_driver_throttle.help", "Throttle amount (0.1 = slow, 1 = full speed).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distance at which to reverse away from enemies.")
language.Add("npcpassengers.tank_turret.help", "Allow NPCs to control turrets on LVS vehicles.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Shows passenger status (emotions, alertness) on screen while driving.")
language.Add("npcpassengers.hud_show_calm.help", "When disabled, only shows passengers with non-calm status.")
language.Add("npcpassengers.hud_thresholds.desc", "When emotion levels exceed these thresholds, passengers show that status in the HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Alert level needed to show 'ALERT' status (threat detected).")
language.Add("npcpassengers.hud_fear_threshold.help", "Fear level needed to show 'SCARED' status (dangerous driving).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Calm time ratio needed to show 'DROWSY' status (long calm ride).")
language.Add("npcpassengers.hud_actions.desc", "Choose what action passengers take when experiencing each emotional state.")
language.Add("npcpassengers.hud_actions_note", "Note: Some actions may not be visible depending on NPC model support.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Set custom keybinds for NPC passenger actions. Click a button and press a key to bind.")
language.Add("npcpassengers.keybinds_hud.desc", "Quick HUD controls for showing, moving, and debugging the passenger overlay.")
language.Add("npcpassengers.keybinds_debug_note", "Debug keybinds only work when Debug Mode is enabled.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Advanced debugging tools for testing NPC behavior. Enable Debug Mode in settings first.")
language.Add("npcpassengers.debug_mode.help", "Shows debug test buttons and enables debug commands.")
language.Add("npcpassengers.debug_status.help", "Manually set passenger status for testing. Click 'Refresh List' to see current passengers.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configure sound effects for buttons, checkboxes, and other UI elements")
language.Add("npcpassengers.ui_sounds_enabled.help", "Master switch for all UI sound effects")
language.Add("npcpassengers.ui_sounds_volume.help", "Volume multiplier for UI sounds (1.0 = normal, 2.0 = double)")
language.Add("npcpassengers.ui_hover_enabled.help", "Play sound when hovering over buttons")
language.Add("npcpassengers.ui_click_enabled.help", "Play sound when clicking buttons and checkboxes")
language.Add("npcpassengers.context_menu.desc", "Choose which options appear when right-clicking NPCs")
language.Add("npcpassengers.context_make_passenger.help", "Add NPC as passenger to your current vehicle")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Add NPC to a specific vehicle (click NPC, then vehicle)")
language.Add("npcpassengers.context_detach.help", "Remove NPC from vehicle")
language.Add("npcpassengers.ui_show_welcome.help", "Display welcome panel when addon is updated to a new version")
language.Add("npcpassengers.ui_default_font.help", "Switch the UI to Garry's Mod default fonts if you prefer cleaner fallback rendering.")
language.Add("npcpassengers.ui_custom_font.help", "Select a custom font. Add .ttf files to resource/fonts/ and use the actual font name (e.g., 'Roboto', 'Arial'). Changes apply immediately.")
language.Add("npcpassengers.ui_panel_width.help", "Width of the settings panel")
language.Add("npcpassengers.ui_panel_height.help", "Height of the settings panel")
language.Add("npcpassengers.ui_animations.help", "Smooth transitions and hover effects (may impact performance)")
language.Add("npcpassengers.ui_tooltips.help", "Display helpful tooltips when hovering over settings")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Only show the scrollbar while you're scrolling or hovering it.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Note: Panel becomes 70% transparent when dragging any slider to see content in background.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Lower values = smoother but slower scrolling (0.01-1)")

print("[Better NPC Passengers] English localization loaded")
