-- Better NPC Passengers - English Localization
-- This file contains all translatable strings for the addon

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Settings")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "General")
language.Add("npcpassengers.nav.autojoin", "Auto-Join")
language.Add("npcpassengers.nav.passengers", "Passengers")
language.Add("npcpassengers.nav.position", "Position")
language.Add("npcpassengers.nav.behaviour", "Behaviour")
language.Add("npcpassengers.nav.keybinds", "Keybinds")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Driver")
language.Add("npcpassengers.nav.help", "Help")

-- General Settings
language.Add("npcpassengers.general.header", "General Settings")
language.Add("npcpassengers.allow_multiple", "Allow Multiple Passengers")
language.Add("npcpassengers.allow_multiple.help", "Let multiple NPCs ride in the same vehicle.")
language.Add("npcpassengers.exit_behavior", "Exit Behavior")
language.Add("npcpassengers.exit_behavior.help", "When should NPC passengers exit the vehicle?")
language.Add("npcpassengers.exit_mode.leave_player", "Leave when player exits")
language.Add("npcpassengers.exit_mode.leave_attack", "Leave when vehicle is attacked")
language.Add("npcpassengers.exit_mode.never", "Never leave automatically")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Timing")
language.Add("npcpassengers.max_attach_dist", "Max Attach Distance")
language.Add("npcpassengers.max_attach_dist.help", "Maximum distance (units) to attach NPC to vehicle.")
language.Add("npcpassengers.detach_delay", "Detach Delay")
language.Add("npcpassengers.detach_delay.help", "Seconds to wait before detaching after player leaves.")
language.Add("npcpassengers.ai_delay", "AI Restore Delay")
language.Add("npcpassengers.ai_delay.help", "Seconds to wait before restoring NPC AI after detaching.")
language.Add("npcpassengers.cooldown", "Cooldown Time")
language.Add("npcpassengers.cooldown.help", "Cooldown between attaching NPCs to same vehicle.")
language.Add("npcpassengers.passenger_limit", "Passenger Limit")
language.Add("npcpassengers.passenger_limit.help", "Max NPCs allowed in vehicle.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Auto-Join (Squad Behavior)")
language.Add("npcpassengers.autojoin.desc", "Friendly NPCs will automatically board your vehicle when you enter it - just like squad mechanics in Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Enable Auto-Join")
language.Add("npcpassengers.autojoin.enable.help", "Nearby friendly NPCs will automatically join when you enter a vehicle.")
language.Add("npcpassengers.autojoin.range", "Auto-Join Range")
language.Add("npcpassengers.autojoin.range.help", "Maximum distance to find NPCs for auto-joining.")
language.Add("npcpassengers.autojoin.max", "Max Auto-Join NPCs")
language.Add("npcpassengers.autojoin.max.help", "Maximum number of NPCs that can auto-join at once.")
language.Add("npcpassengers.autojoin.squad_only", "Squad Members Only")
language.Add("npcpassengers.autojoin.squad_only.help", "Only NPCs with a squad name will auto-join (for HL2-style squads).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Friendly NPCs will automatically board your vehicle when you enter it - just like squad mechanics in Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Passenger Controls")
language.Add("npcpassengers.panel.passengers.desc", "Manage active passengers, filter by name/class/status, copy debug info, reassign seats, and detach riders without leaving the settings panel.")
language.Add("npcpassengers.panel.position.desc", "Fine-tune NPC positioning in vehicles. Use these to fix floating or clipping issues.")
language.Add("npcpassengers.panel.angle.desc", "Adjust NPC rotation in vehicles.")
language.Add("npcpassengers.panel.speech.desc", "Configure how NPCs vocalize while riding in vehicles. HL2-style citizen voices!")

-- Position Settings
language.Add("npcpassengers.position.header", "Position Offsets")
language.Add("npcpassengers.position.desc", "Fine-tune NPC positioning in vehicles. Use these to fix floating or clipping issues.")
language.Add("npcpassengers.height_offset", "Height Offset")
language.Add("npcpassengers.forward_offset", "Forward Offset")
language.Add("npcpassengers.right_offset", "Right Offset")
language.Add("npcpassengers.angle.header", "Angle Offsets")
language.Add("npcpassengers.angle.desc", "Adjust NPC rotation in vehicles.")
language.Add("npcpassengers.yaw_offset", "Yaw (Rotation)")
language.Add("npcpassengers.pitch_offset", "Pitch (Tilt Forward)")
language.Add("npcpassengers.roll_offset", "Roll (Tilt Sideways)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPC Speech (Advanced)")
language.Add("npcpassengers.behaviour.desc", "Configure how NPCs vocalize while riding in vehicles. HL2-style citizen voices!")
language.Add("npcpassengers.speech_enable", "Enable NPC Speech")
language.Add("npcpassengers.speech_enable.help", "Master toggle for all NPC speech. Disable to silence passengers completely.")
language.Add("npcpassengers.speech_volume", "Speech Volume")
language.Add("npcpassengers.speech_volume.help", "How loud NPC voices are (0 = silent, 100 = full volume).")
language.Add("npcpassengers.pitch_variation", "Pitch Variation (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Random pitch variation for more natural voices. 0 = monotone, higher = more variety.")
language.Add("npcpassengers.crash.header", "Crash Reactions")
language.Add("npcpassengers.crash_enable", "Enable Crash Sounds")
language.Add("npcpassengers.crash_enable.help", "NPCs grunt/yelp when vehicle decelerates sharply (crashes, hard braking).")
language.Add("npcpassengers.crash_threshold", "Crash Sensitivity")
language.Add("npcpassengers.crash_threshold.help", "Deceleration needed to trigger crash sounds. Lower = more sensitive.")
language.Add("npcpassengers.crash_cooldown", "Crash Sound Cooldown")
language.Add("npcpassengers.crash_cooldown.help", "Minimum seconds between crash sounds per NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Enable Idle Chatter")
language.Add("npcpassengers.speech_board", "Enable Board/Exit Sounds")
language.Add("npcpassengers.ambient_sounds", "Enable Ambient Sounds")
language.Add("npcpassengers.head_look", "Enable Head/Eye Looking")
language.Add("npcpassengers.blink", "Enable Blinking")
language.Add("npcpassengers.breathing", "Enable Breathing")
language.Add("npcpassengers.talking_gestures", "Enable Talking Gestures")
language.Add("npcpassengers.crash_flinch", "Enable Crash Flinch")
language.Add("npcpassengers.body_sway", "Enable Body Sway")
language.Add("npcpassengers.threat_awareness", "Enable Threat Awareness")
language.Add("npcpassengers.combat_alert", "Combat Alertness")
language.Add("npcpassengers.passenger_combat", "NPCs shoot from vehicles (Experimental)")
language.Add("npcpassengers.passenger_interaction", "Passenger Interaction")
language.Add("npcpassengers.fear_reactions", "Enable Fear Reactions")
language.Add("npcpassengers.drowsiness", "Enable Drowsiness")
language.Add("npcpassengers.hide_in_tanks", "Hide NPCs in Enclosed Vehicles")
language.Add("npcpassengers.eject_stuck_check", "Auto-Eject Stuck NPCs")
language.Add("npcpassengers.detach_no_collide", "No-Collide With Vehicle After Detach")
language.Add("npcpassengers.die_with_vehicle", "Kill Passengers When Vehicle Explodes")
language.Add("npcpassengers.driver_enabled", "Enable Auto-Drive")
language.Add("npcpassengers.turret_enabled", "Enable Turret Control")
language.Add("npcpassengers.turret_lead_targets", "Lead Targets")
language.Add("npcpassengers.turret_friendly_fire", "Allow Friendly Fire")
language.Add("npcpassengers.turret_hold_fire", "Hold Fire (Disable Firing)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Speech Volume")
language.Add("npcpassengers.pitch_variation", "Pitch Variation (+/-)")
language.Add("npcpassengers.crash_threshold", "Crash Sensitivity")
language.Add("npcpassengers.crash_cooldown", "Crash Sound Cooldown")
language.Add("npcpassengers.speech_idle_chance", "Chatter Chance")
language.Add("npcpassengers.speech_idle_interval", "Chatter Interval")
language.Add("npcpassengers.ambient_interval", "Ambient Sound Interval")
language.Add("npcpassengers.head_smooth", "Head Smoothness")
language.Add("npcpassengers.walk_timeout", "Walk Timeout")
language.Add("npcpassengers.gesture_chance", "Gesture Chance (%)")
language.Add("npcpassengers.gesture_interval", "Gesture Interval")
language.Add("npcpassengers.crash_threshold_flinch", "Crash Sensitivity")
language.Add("npcpassengers.body_sway_amount", "Sway Intensity")
language.Add("npcpassengers.threat_range", "Threat Detection Range")
language.Add("npcpassengers.passenger_combat_range", "Passenger Combat Range")
language.Add("npcpassengers.passenger_combat_accuracy", "Passenger Accuracy")
language.Add("npcpassengers.passenger_combat_damage", "Passenger Damage Multiplier")
language.Add("npcpassengers.fear_speed_threshold", "Fear Speed Threshold")
language.Add("npcpassengers.drowsy_time", "Drowsy Time")
language.Add("npcpassengers.detach_no_collide_duration", "No-Collide Duration (seconds)")
language.Add("npcpassengers.tank_driver_range", "Detection Range")
language.Add("npcpassengers.tank_driver_engage_distance", "Engage Distance")
language.Add("npcpassengers.tank_driver_speed", "Drive Speed")
language.Add("npcpassengers.tank_driver_reverse_distance", "Reverse Distance")
language.Add("npcpassengers.turret_range", "Target Range")
language.Add("npcpassengers.turret_accuracy", "Accuracy")
language.Add("npcpassengers.turret_reaction_time", "Reaction Time")
language.Add("npcpassengers.turret_fire_delay", "Fire Delay")
language.Add("npcpassengers.turret_aim_speed", "Aim Speed")
language.Add("npcpassengers.hud_scale", "HUD Scale")
language.Add("npcpassengers.hud_opacity", "HUD Opacity")
language.Add("npcpassengers.hud_alert_threshold", "Alert Threshold")
language.Add("npcpassengers.hud_fear_threshold", "Fear Threshold")
language.Add("npcpassengers.hud_drowsy_threshold", "Drowsy Threshold")
language.Add("npcpassengers.ui_sounds_volume", "UI Sounds Volume")
language.Add("npcpassengers.ui_panel_width", "Panel Width")

-- Section headers
language.Add("npcpassengers.section.animation", "Animation & Behavior")
language.Add("npcpassengers.section.realism", "Advanced Realism")
language.Add("npcpassengers.section.hud_position", "HUD Position & Style")
language.Add("npcpassengers.section.emotion_thresholds", "Emotion Thresholds")
language.Add("npcpassengers.section.emotion_actions", "Emotion Actions")
language.Add("npcpassengers.section.vehicle_control", "Vehicle Control")
language.Add("npcpassengers.section.hud_controls", "HUD Controls")
language.Add("npcpassengers.section.debug_controls", "Debug Controls")
language.Add("npcpassengers.section.passenger_status", "Passenger Status Control")
language.Add("npcpassengers.section.quick_test", "Quick Test Buttons")
language.Add("npcpassengers.section.driver_system", "NPC Driver System")
language.Add("npcpassengers.section.ui_sounds", "UI Sound Settings")
language.Add("npcpassengers.section.context_menu", "Context Menu Options")
language.Add("npcpassengers.section.panel_preferences", "Settings Panel Preferences")
language.Add("npcpassengers.section.performance", "Performance & Technical")
language.Add("npcpassengers.section.simulation", "Simulation System")
language.Add("npcpassengers.section.modules", "Modules System")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Assign Seat")
language.Add("npcpassengers.btn.detach", "Detach")
language.Add("npcpassengers.btn.copy_summary", "Copy Summary")
language.Add("npcpassengers.btn.copy_debug", "Copy Debug")
language.Add("npcpassengers.btn.enable_all_speech", "Enable All Speech")
language.Add("npcpassengers.btn.disable_all_speech", "Disable All Speech")
language.Add("npcpassengers.btn.show_current_vehicle", "Show Current Vehicle Only")
language.Add("npcpassengers.btn.auto_refresh", "Auto Refresh Visible List")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "No current vehicle detected. Sit in a vehicle or disable the current-vehicle filter.")
language.Add("npcpassengers.status.no_match_filter", "No passengers matched your filter. Try a name, class, seat number, status, or vehicle class.")
language.Add("npcpassengers.status.no_passengers_vehicle", "No passengers found in your current vehicle.")
language.Add("npcpassengers.status.no_passengers", "No passengers found. NPCs need to be riding in a vehicle before they can be managed here.")
language.Add("npcpassengers.status.all_passengers", "All passengers")
language.Add("npcpassengers.status.current_vehicle_only", "Current vehicle only")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F to focus search")
language.Add("npcpassengers.status.no_matches", "No matching settings")
language.Add("npcpassengers.status.showing_matches", "Showing top %d of %d matches")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Open Settings")
language.Add("npcpassengers.menu.reset_all", "Reset All Settings")

-- Button states
language.Add("npcpassengers.state.on", "ON")
language.Add("npcpassengers.state.off", "OFF")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Auto-Join")
language.Add("npcpassengers.chat.hud_status", "Passenger HUD")
language.Add("npcpassengers.chat.hud_position", "HUD Position")
language.Add("npcpassengers.chat.target_debug", "Target Debug")
language.Add("npcpassengers.chat.turret_gunners", "Turret gunners")
language.Add("npcpassengers.chat.turret_holding", "HOLDING FIRE")
language.Add("npcpassengers.chat.turret_fire", "OPEN FIRE")
language.Add("npcpassengers.chat.unknown", "Unknown")
language.Add("npcpassengers.chat.nothing_copy", "Nothing to copy.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Clipboard access is not available in this build.")
language.Add("npcpassengers.chat.copied_clipboard", "Copied to clipboard.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Sit in the same vehicle to reassign this passenger.")
language.Add("npcpassengers.chat.no_visible_passengers", "No visible passengers to copy.")
language.Add("npcpassengers.chat.need_vehicle", "You need to be in a vehicle to use this.")
language.Add("npcpassengers.chat.keybinds_applied", "Recommended keybinds applied.")
language.Add("npcpassengers.chat.keybinds_cleared", "All keybinds cleared.")
language.Add("npcpassengers.chat.context_enabled", "All context menu options enabled.")
language.Add("npcpassengers.chat.context_hidden", "All context menu options hidden.")
language.Add("npcpassengers.chat.panel_compact", "Panel size set to compact.")
language.Add("npcpassengers.chat.panel_default", "Panel size set to default.")
language.Add("npcpassengers.chat.panel_large", "Panel size set to large.")
language.Add("npcpassengers.chat.panel_centered", "Panel centered.")
language.Add("npcpassengers.chat.settings_reset", "All UI settings reset to defaults!")
language.Add("npcpassengers.chat.npc_selected", "NPC selected! Now right-click on a vehicle and select 'Add Selected NPC'")
language.Add("npcpassengers.chat.adding_npc", "Adding NPC to vehicle...")
language.Add("npcpassengers.chat.selection_cancelled", "NPC selection cancelled")
language.Add("npcpassengers.chat.summary_copied", "Passenger summary copied.")
language.Add("npcpassengers.chat.debug_copied", "Passenger debug info copied.")
language.Add("npcpassengers.chat.no_passengers_found", "No passengers found. NPCs must be in a vehicle.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Status intensity %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filter passengers...")
language.Add("npcpassengers.ui.press_key", "Press a key...")
language.Add("npcpassengers.ui.work_in_progress", "Work In Progress")
language.Add("npcpassengers.ui.under_development", "This feature is currently under development")
language.Add("npcpassengers.ui.check_back_later", "Check back in a future update!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filter active passengers by name, class, seat, status, or vehicle.")
language.Add("npcpassengers.ui.search_desc_sort", "Sort the visible passenger list by vehicle, name, seat, health, or status.")
language.Add("npcpassengers.ui.search_label_filter", "Passenger Filter")
language.Add("npcpassengers.ui.search_label_sort", "Passenger Sort")

-- Keybind names
language.Add("npcpassengers.keybind.attach", "Attach Nearest NPC")
language.Add("npcpassengers.keybind.detach_all", "Detach All Passengers")
language.Add("npcpassengers.keybind.menu", "Open Settings Menu")
language.Add("npcpassengers.keybind.quick_attach", "Quick Attach Mode")
language.Add("npcpassengers.keybind.exit_all", "NPCs Exit Vehicle")
language.Add("npcpassengers.keybind.hold_fire", "NPCs Hold Fire")
language.Add("npcpassengers.keybind.open_fire", "NPCs Open Fire")
language.Add("npcpassengers.keybind.cycle_view", "Cycle Passenger View")
language.Add("npcpassengers.keybind.toggle_hud", "Toggle Passenger HUD")
language.Add("npcpassengers.keybind.cycle_hud_position", "Cycle HUD Position")
language.Add("npcpassengers.keybind.toggle_debug", "Toggle Target Debug")
language.Add("npcpassengers.keybind.test_gesture", "Test Random Gesture")
language.Add("npcpassengers.keybind.reset_all", "Reset All NPCs")

-- Keybind descriptions
language.Add("npcpassengers.keybind.attach.desc", "Attach the nearest friendly NPC to your vehicle")
language.Add("npcpassengers.keybind.detach_all.desc", "Remove all NPCs from your vehicle")
language.Add("npcpassengers.keybind.menu.desc", "Open the Better NPC Passengers settings panel")
language.Add("npcpassengers.keybind.quick_attach.desc", "Hold to quickly attach NPCs you're looking at")
language.Add("npcpassengers.keybind.exit_all.desc", "Command all passengers to exit the vehicle")
language.Add("npcpassengers.keybind.hold_fire.desc", "Tell gunner NPCs to stop firing")
language.Add("npcpassengers.keybind.open_fire.desc", "Tell gunner NPCs to engage targets")
language.Add("npcpassengers.keybind.cycle_view.desc", "Cycle camera through passengers")
language.Add("npcpassengers.keybind.toggle_hud.desc", "Show or hide the passenger status HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.desc", "Move the passenger HUD through all four corners")
language.Add("npcpassengers.keybind.toggle_debug.desc", "Toggle the small target debug overlay")
language.Add("npcpassengers.keybind.test_gesture.desc", "Play a random gesture on nearest passenger")
language.Add("npcpassengers.keybind.reset_all.desc", "Reset animation states for all passengers")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "How do I add NPCs to my vehicle?")
language.Add("npcpassengers.faq.add_npc.answer", "Use the context menu (right-click on an NPC) and select 'Make Passenger'. Or use the 'Attach Nearest NPC' keybind. NPCs must be friendly to you.")
language.Add("npcpassengers.faq.remove_npc", "How do I remove passengers from my vehicle?")
language.Add("npcpassengers.faq.remove_npc.answer", "Go to the Passengers tab in settings, select the passenger, and click Detach. Or use the 'Detach All Passengers' keybind.")
language.Add("npcpassengers.faq.position", "NPCs are floating/clip through seats!")
language.Add("npcpassengers.faq.position.answer", "Go to the Position tab and adjust the Height/Forward/Right offsets. Each vehicle model is different, so you may need to fine-tune these values. Use the debugging panel to test positions in real-time.")
language.Add("npcpassengers.faq.speech", "NPCs aren't talking!")
language.Add("npcpassengers.faq.speech.answer", "Check the Behaviour tab and make sure 'Enable NPC Speech' is turned on. Also verify that Speech Volume is above 0. Some NPC models may not have voice lines available.")
language.Add("npcpassengers.faq.autojoin", "How does Auto-Join work?")
language.Add("npcpassengers.faq.autojoin.answer", "When enabled in the Auto-Join tab, nearby friendly NPCs will automatically board your vehicle when you enter it - just like squad mechanics in Half-Life 2. You can set the detection range and limit how many NPCs can auto-join.")
language.Add("npcpassengers.faq.death", "What happens when passengers die?")
language.Add("npcpassengers.faq.death.answer", "Dead passengers will show a red glow effect and display a skull icon on the HUD. Get close to your vehicle and hold R to remove their bodies. The bodies will be ejected with physics.")
language.Add("npcpassengers.faq.status", "What do the passenger statuses mean?")
language.Add("npcpassengers.faq.status.answer", "CALM: Relaxed, no threats. ALERT: Enemy detected. SCARED: Dangerous driving. DROWSY: Long calm ride. DEAD: Health reached zero.")
language.Add("npcpassengers.faq.keybinds", "My keybinds aren't working!")
language.Add("npcpassengers.faq.keybinds.answer", "Go to the Keybinds tab and make sure you've actually set the keybinds (they're unbound by default). Click the button next to each action and press your desired key. Right-click to unbind.")
language.Add("npcpassengers.faq.errors", "The addon isn't working at all / I'm getting errors!")
language.Add("npcpassengers.faq.errors.answer", "Make sure you're running the latest version of Garry's Mod. Check the console for errors (tilde key ~). Try disabling conflicting addons.")
language.Add("npcpassengers.faq.combat", "Can passengers shoot from vehicles?")
language.Add("npcpassengers.faq.combat.answer", "Not currently. NPCs will track enemies and react to threats, but won't fire weapons while seated. This feature may be added in future updates.")
language.Add("npcpassengers.faq.stop_autojoin", "How do I stop NPCs from auto-joining?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Disable the 'Enable Auto-Join' checkbox in the Auto-Join tab, or use the 'Toggle Auto-Join' keybind.")
language.Add("npcpassengers.faq.settings", "Where are the settings saved?")
language.Add("npcpassengers.faq.settings.answer", "All settings are saved as ConVars in your GMod config. They persist between sessions and are specific to your client.")
language.Add("npcpassengers.faq.vehicles", "Does this work with all vehicles?")
language.Add("npcpassengers.faq.vehicles.answer", "It works with most vehicles that have physics. Tanks, APCs, cars, boats, etc. Some modded vehicles may require position adjustments.")
language.Add("npcpassengers.faq.multiple", "Can I have multiple NPCs in one vehicle?")
language.Add("npcpassengers.faq.multiple.answer", "Yes! Set the 'Passenger Limit' in General settings. The addon will distribute NPCs around the vehicle automatically. For specific seat positions, adjust offsets in the Position tab.")
language.Add("npcpassengers.faq.crashes", "NPCs are acting weird after crashes!")
language.Add("npcpassengers.faq.crashes.answer", "This is normal - they react with fear to dangerous driving. Lower the Fear Threshold in HUD settings if you want them less reactive.")
language.Add("npcpassengers.faq.reset_setting", "How do I reset just one setting?")
language.Add("npcpassengers.faq.reset_setting.answer", "Use the console command for that specific setting. All commands start with 'nai_npc_'. Type 'find nai_npc' in console to see all available commands.")
language.Add("npcpassengers.faq.multiplayer", "Does this work in multiplayer?")
language.Add("npcpassengers.faq.multiplayer.answer", "Yes! The addon works on both singleplayer and multiplayer servers. Each player controls their own passengers.")
language.Add("npcpassengers.faq.lvs", "Does this work with LVS vehicles?")
language.Add("npcpassengers.faq.lvs.answer", "Yes! The addon has full support for LVS (Lua Vehicle System) vehicles. NPCs can ride as passengers and can even drive LVS vehicles if NPC Driver mode is enabled.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "These settings control the addon's user interface behavior")
language.Add("npcpassengers.panel.performance_note1", "Changes to panel size require closing and reopening the menu")
language.Add("npcpassengers.panel.performance_note2", "Disabling sounds or animations can improve performance on low-end systems")
language.Add("npcpassengers.panel.performance_title", "Interface Settings Info")
language.Add("npcpassengers.help.console_title", "Console Commands for Debugging:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Enable debug mode to see detailed info")
language.Add("npcpassengers.about.title", "About")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Hey there!")
language.Add("npcpassengers.welcome.msg1", "Before complaining about the passenger sitting on top of vehicle,\nplease open the settings. You can do it, I believe in you.")
language.Add("npcpassengers.welcome.msg2", "This addon is still far from being PERFECT, please do not hesitate to\nreport bugs and suggest new features. I read all of your comments!")
language.Add("npcpassengers.welcome.changelog", "Update Changelog")
language.Add("npcpassengers.welcome.got_it", "Got it!")
language.Add("npcpassengers.welcome.console_cmd", "Or use console command: nai_passengers_menu")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Keybinds")
language.Add("npcpassengers.keybinds.desc", "Configure keyboard shortcuts for quick actions.")
language.Add("npcpassengers.keybind.attach", "Attach Nearest NPC")
language.Add("npcpassengers.keybind.attach.help", "Attach the nearest friendly NPC to your vehicle.")
language.Add("npcpassengers.keybind.detach_all", "Detach All NPCs")
language.Add("npcpassengers.keybind.detach_all.help", "Remove all passengers from your vehicle.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Toggle Auto-Join")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Quickly enable/disable auto-join.")
language.Add("npcpassengers.keybind.menu", "Open Settings Menu")
language.Add("npcpassengers.keybind.menu.help", "Open the settings panel.")
language.Add("npcpassengers.keybind.exit_all", "Exit All Passengers")
language.Add("npcpassengers.keybind.exit_all.help", "Make all passengers leave the vehicle.")
language.Add("npcpassengers.keybind.toggle_hud", "Toggle HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Show/hide the passenger HUD.")

-- HUD Settings
language.Add("npcpassengers.hud.header", "HUD Settings")
language.Add("npcpassengers.hud.enable", "Enable HUD")
language.Add("npcpassengers.hud.enable.help", "Show passenger status overlay on screen.")
language.Add("npcpassengers.hud.position", "HUD Position")
language.Add("npcpassengers.hud.position.help", "Where the HUD appears on screen.")
language.Add("npcpassengers.hud.position.topleft", "Top Left")
language.Add("npcpassengers.hud.position.topright", "Top Right")
language.Add("npcpassengers.hud.position.bottomleft", "Bottom Left")
language.Add("npcpassengers.hud.position.bottomright", "Bottom Right")
language.Add("npcpassengers.hud.scale", "HUD Scale")
language.Add("npcpassengers.hud.scale.help", "Size multiplier for the HUD.")
language.Add("npcpassengers.hud.opacity", "HUD Opacity")
language.Add("npcpassengers.hud.opacity.help", "Background transparency (0 = invisible, 1 = solid).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC Driver")
language.Add("npcpassengers.driver.desc", "Allow NPCs to drive vehicles for you.")
language.Add("npcpassengers.driver.enable", "Enable NPC Drivers")
language.Add("npcpassengers.driver.enable.help", "Allow NPCs to take control of vehicles.")
language.Add("npcpassengers.driver.behavior", "Driving Behavior")
language.Add("npcpassengers.driver.behavior.help", "How the NPC drives the vehicle.")
language.Add("npcpassengers.driver.behavior.cruise", "Random Cruise")
language.Add("npcpassengers.driver.behavior.follow", "Follow Player")
language.Add("npcpassengers.driver.behavior.patrol", "Patrol")
language.Add("npcpassengers.driver.behavior.flee", "Flee")
language.Add("npcpassengers.driver.behavior.parked", "Stay Parked")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Frequently Asked Questions")
language.Add("npcpassengers.help.desc", "Quick answers to common questions and troubleshooting.")
language.Add("npcpassengers.help.still_need", "Still Need Help?")
language.Add("npcpassengers.help.community", "Join our Discord community for support!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Tank/LVS")
language.Add("npcpassengers.nav.debugging", "Debugging")
language.Add("npcpassengers.nav.driver", "NPC Driver")
language.Add("npcpassengers.nav.interface", "Interface")
language.Add("npcpassengers.nav.simulate", "Simulate")
language.Add("npcpassengers.nav.modules", "Modules")
language.Add("npcpassengers.nav.about", "About")
language.Add("npcpassengers.search.placeholder", "Search settings...")

-- About page
language.Add("npcpassengers.about.description", "Advanced passenger system with emotional AI and realistic physics")
language.Add("npcpassengers.about.feature_status", "Status System: CALM / ALERT / SCARED / DROWSY / DEAD")
language.Add("npcpassengers.about.feature_performance", "Performance: seat caching, throttled timers, optimized client hooks")
language.Add("npcpassengers.about.feature_filtering", "Vehicle filtering, boarding retry cooldown, squad-only auto-join")
language.Add("npcpassengers.about.actions", "Actions")
language.Add("npcpassengers.about.show_welcome", "Show Welcome Screen")
language.Add("npcpassengers.about.open_github", "Open GitHub Page")
language.Add("npcpassengers.about.reset_settings", "Reset ALL Settings to Defaults")

-- Status messages
language.Add("npcpassengers.status.calm", "CALM")
language.Add("npcpassengers.status.alert", "ALERT")
language.Add("npcpassengers.status.scared", "SCARED")
language.Add("npcpassengers.status.drowsy", "DROWSY")
language.Add("npcpassengers.status.dead", "DEAD")
language.Add("npcpassengers.status.calm.desc", "Relaxed, no threats nearby")
language.Add("npcpassengers.status.alert.desc", "Enemy detected, NPC is tracking threats")
language.Add("npcpassengers.status.scared.desc", "Dangerous driving (high speed, crashes)")
language.Add("npcpassengers.status.drowsy.desc", "Long calm ride, NPC is getting sleepy")
language.Add("npcpassengers.status.dead.desc", "Health reached zero")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Auto-Join: ON")
language.Add("npcpassengers.chat.autojoin_off", "Auto-Join: OFF")
language.Add("npcpassengers.chat.hud_on", "HUD: ON")
language.Add("npcpassengers.chat.hud_off", "HUD: OFF")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "No vehicle nearby")
language.Add("npcpassengers.error.no_npc", "No NPC nearby")
language.Add("npcpassengers.error.vehicle_full", "Vehicle is full")
language.Add("npcpassengers.error.too_far", "NPC too far from vehicle")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Change language")
language.Add("npcpassengers.tooltip.minimize", "Minimize panel")
language.Add("npcpassengers.tooltip.expand", "Expand panel")
language.Add("npcpassengers.tooltip.welcome", "Show welcome screen")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Master toggle for all NPC speech. Disable to silence passengers completely.")
language.Add("npcpassengers.speech_volume.help", "How loud NPC voices are (0 = silent, 100 = full volume).")
language.Add("npcpassengers.pitch_variation.help", "Random pitch variation for more natural voices. 0 = monotone, higher = more variety.")
language.Add("npcpassengers.crash_enable.help", "NPCs grunt/yelp when vehicle decelerates sharply (crashes, hard braking).")
language.Add("npcpassengers.crash_threshold.help", "Deceleration needed to trigger crash sounds. Lower = more sensitive.")
language.Add("npcpassengers.crash_cooldown.help", "Minimum seconds between crash sounds per NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPCs occasionally speak while riding - comments, questions, observations.")
language.Add("npcpassengers.speech_idle_chance.help", "Probability of chatter per check. 0 = never, 1 = always tries to speak.")
language.Add("npcpassengers.speech_idle_interval.help", "Minimum seconds between idle chatter attempts.")
language.Add("npcpassengers.speech_board.help", "NPCs speak when entering and exiting vehicles.")
language.Add("npcpassengers.ambient_sounds.help", "Occasional coughs, sighs, hums - background life sounds.")
language.Add("npcpassengers.ambient_interval.help", "Average seconds between ambient sounds.")
language.Add("npcpassengers.animation.help", "Fine-tune NPC animations and head movement.")
language.Add("npcpassengers.head_look.help", "NPCs naturally look around, at the player, out windows, etc.")
language.Add("npcpassengers.head_smooth.help", "How smoothly the head moves. Lower = snappier, higher = floaty.")
language.Add("npcpassengers.blink.help", "NPCs blink realistically while sitting.")
language.Add("npcpassengers.breathing.help", "Subtle breathing animation on NPC heads.")
language.Add("npcpassengers.walk_timeout.help", "Seconds before NPC gives up walking to vehicle.")
language.Add("npcpassengers.realism.help", "Physics-based reactions and awareness systems for ultimate immersion.")
language.Add("npcpassengers.talking_gestures.help", "NPCs randomly play hand gestures and body animations while riding.")
language.Add("npcpassengers.gesture_chance.help", "Percent chance to play a gesture each interval.")
language.Add("npcpassengers.gesture_interval.help", "Seconds between gesture opportunity checks.")
language.Add("npcpassengers.crash_flinch.help", "NPCs flinch and lurch forward when vehicle crashes or brakes hard.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Velocity change needed to trigger flinch (lower = more sensitive).")
language.Add("npcpassengers.body_sway.help", "NPCs lean into turns, brace during acceleration/braking.")
language.Add("npcpassengers.body_sway_amount.help", "How much NPCs sway with vehicle movement.")
language.Add("npcpassengers.threat_awareness.help", "NPCs automatically look toward nearby enemies.")
language.Add("npcpassengers.threat_range.help", "How far NPCs can detect threats for head tracking.")
language.Add("npcpassengers.combat_alert.help", "NPCs become tense and reactive when enemies are near.")
language.Add("npcpassengers.passenger_combat.help", "Disabled by default. Enable this to let armed passengers fire from inside vehicles.")
language.Add("npcpassengers.passenger_combat_range.help", "How far armed passengers can acquire targets.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Higher values tighten shot spread for armed passengers.")
language.Add("npcpassengers.passenger_combat_damage.help", "Scales the damage dealt by passenger-fired shots.")
language.Add("npcpassengers.passenger_interaction.help", "Multiple passengers look at and occasionally chat with each other.")
language.Add("npcpassengers.fear_reactions.help", "NPCs get scared by dangerous driving - wide eyes, panicked sounds.")
language.Add("npcpassengers.fear_speed_threshold.help", "Speed (units/sec) at which NPCs start getting nervous.")
language.Add("npcpassengers.drowsiness.help", "NPCs get sleepy on long, calm rides - slow blinks, head nods.")
language.Add("npcpassengers.drowsy_time.help", "Seconds of calm riding before drowsiness kicks in.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Settings for tanks, APCs, and LVS vehicles.")
language.Add("npcpassengers.hide_in_tanks.help", "Make NPC passengers invisible when inside tanks and APCs.")
language.Add("npcpassengers.eject_stuck_check.help", "Automatically push NPCs out of vehicles when they get stuck during ejection. Prevents NPCs from clipping into vehicles when exiting.")
language.Add("npcpassengers.detach_no_collide.help", "After detaching, NPCs temporarily pass through the vehicle so they can walk away without clipping or getting stuck.")
language.Add("npcpassengers.detach_no_collide_duration.help", "How long NPCs ignore the vehicle's collision after detaching.")
language.Add("npcpassengers.die_with_vehicle.help", "NPC passengers die when their vehicle is destroyed by explosion or fire (more immersive than them walking out of a wreck unharmed).")
language.Add("npcpassengers.tank_driver.help", "Allow NPCs in driver seat to automatically drive toward enemies.")
language.Add("npcpassengers.tank_driver_range.help", "Maximum range for driver to detect enemies.")
language.Add("npcpassengers.tank_driver_distance.help", "Distance to maintain from enemies.")
language.Add("npcpassengers.tank_driver_throttle.help", "Throttle amount (0.1 = slow, 1 = full speed).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distance at which to reverse away from enemies.")
language.Add("npcpassengers.tank_turret.help", "Allow NPCs to control turrets on LVS vehicles.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Shows passenger status (emotions, alertness) on screen while driving.")
language.Add("npcpassengers.hud_show_calm.help", "When disabled, only shows passengers with non-calm status.")
language.Add("npcpassengers.hud_thresholds.desc", "When emotion levels exceed these thresholds, passengers show that status in the HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Alert level needed to show 'ALERT' status (threat detected).")
language.Add("npcpassengers.hud_fear_threshold.help", "Fear level needed to show 'SCARED' status (dangerous driving).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Calm time ratio needed to show 'DROWSY' status (long calm ride).")
language.Add("npcpassengers.hud_actions.desc", "Choose what action passengers take when experiencing each emotional state.")
language.Add("npcpassengers.hud_actions_note", "Note: Some actions may not be visible depending on NPC model support.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Set custom keybinds for NPC passenger actions. Click a button and press a key to bind.")
language.Add("npcpassengers.keybinds_hud.desc", "Quick HUD controls for showing, moving, and debugging the passenger overlay.")
language.Add("npcpassengers.keybinds_debug_note", "Debug keybinds only work when Debug Mode is enabled.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Advanced debugging tools for testing NPC behavior. Enable Debug Mode in settings first.")
language.Add("npcpassengers.debug_mode.help", "Shows debug test buttons and enables debug commands.")
language.Add("npcpassengers.debug_status.help", "Manually set passenger status for testing. Click 'Refresh List' to see current passengers.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configure sound effects for buttons, checkboxes, and other UI elements")
language.Add("npcpassengers.ui_sounds_enabled.help", "Master switch for all UI sound effects")
language.Add("npcpassengers.ui_sounds_volume.help", "Volume multiplier for UI sounds (1.0 = normal, 2.0 = double)")
language.Add("npcpassengers.ui_hover_enabled.help", "Play sound when hovering over buttons")
language.Add("npcpassengers.ui_click_enabled.help", "Play sound when clicking buttons and checkboxes")
language.Add("npcpassengers.context_menu.desc", "Choose which options appear when right-clicking NPCs")
language.Add("npcpassengers.context_make_passenger.help", "Add NPC as passenger to your current vehicle")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Add NPC to a specific vehicle (click NPC, then vehicle)")
language.Add("npcpassengers.context_detach.help", "Remove NPC from vehicle")
language.Add("npcpassengers.ui_show_welcome.help", "Display welcome panel when addon is updated to a new version")
language.Add("npcpassengers.ui_default_font.help", "Switch the UI to Garry's Mod default fonts if you prefer cleaner fallback rendering.")
language.Add("npcpassengers.ui_custom_font.help", "Select a custom font. Add .ttf files to resource/fonts/ and use the actual font name (e.g., 'Roboto', 'Arial'). Changes apply immediately.")
language.Add("npcpassengers.ui_panel_width.help", "Width of the settings panel")
language.Add("npcpassengers.ui_panel_height.help", "Height of the settings panel")
language.Add("npcpassengers.ui_animations.help", "Smooth transitions and hover effects (may impact performance)")
language.Add("npcpassengers.ui_tooltips.help", "Display helpful tooltips when hovering over settings")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Only show the scrollbar while you're scrolling or hovering it.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Note: Panel becomes 70% transparent when dragging any slider to see content in background.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Lower values = smoother but slower scrolling (0.01-1)")

print("[Better NPC Passengers] English localization loaded")
