-- Better NPC Passengers - French Localization
-- Fichier de localisation en français

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Meilleurs Passagers PNJ")
language.Add("npcpassengers.settings", "Paramètres")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Général")
language.Add("npcpassengers.nav.autojoin", "Rejoindre Automatique")
language.Add("npcpassengers.nav.passengers", "Passagers")
language.Add("npcpassengers.nav.position", "Position")
language.Add("npcpassengers.nav.behaviour", "Comportement")
language.Add("npcpassengers.nav.keybinds", "Raccourcis Clavier")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Conducteur")
language.Add("npcpassengers.nav.help", "Aide")

-- General Settings
language.Add("npcassengers.general.header", "Paramètres Généraux")
language.Add("npcpassengers.allow_multiple", "Autoriser Plusieurs Passagers")
language.Add("npcpassengers.allow_multiple.help", "Permet à plusieurs PNJ de voyager dans le même véhicule.")
language.Add("npcpassengers.exit_behavior", "Comportement de Sortie")
language.Add("npcpassengers.exit_behavior.help", "Quand les passagers PNJ doivent-ils quitter le véhicule?")
language.Add("npcassengers.exit_mode.leave_player", "Quitter quand le joueur sort")
language.Add("npcpassengers.exit_mode.leave_attack", "Quitter quand le véhicule est attaqué")
language.Add("npcpassengers.exit_mode.never", "Ne jamais quitter automatiquement")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Minutage")
language.Add("npcpassengers.max_attach_dist", "Distance Maximale d'Attachement")
language.Add("npcpassengers.max_attach_dist.help", "Distance maximale (unités) pour attacher un PNJ au véhicule.")
language.Add("npcpassengers.detach_delay", "Délai de Détachement")
language.Add("npcpassengers.detach_delay.help", "Secondes à attendre avant de détacher après que le joueur sorte.")
language.Add("npcpassengers.ai_delay", "Délai de Restauration de l'IA")
language.Add("npcpassengers.ai_delay.help", "Secondes à attendre avant de restaurer l'IA du PNJ après détachement.")
language.Add("npcpassengers.cooldown", "Temps de Recharge")
language.Add("npcpassengers.cooldown.help", "Temps de recharge entre l'attachement de PNJ au même véhicule.")
language.Add("npcpassengers.passenger_limit", "Limite de Passagers")
language.Add("npcpassengers.passenger_limit.help", "Maximum de PNJ autorisés dans le véhicule.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Rejoindre Automatique (Comportement d'Escouade)")
language.Add("npcpassengers.autojoin.desc", "Les PNJ amicaux monteront automatiquement dans votre véhicule quand vous y entrerez, tout comme la mécanique d'escouade dans Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Activer le Rejoindre Automatique")
language.Add("npcpassengers.autojoin.enable.help", "Les PNJ amicaux proches monteront automatiquement quand vous entrerez dans un véhicule.")
language.Add("npcpassengers.autojoin.range", "Portée de Rejoindre Automatique")
language.Add("npcpassengers.autojoin.range.help", "Distance maximale pour trouver des PNJ pour le rejoindre automatique.")
language.Add("npcpassengers.autojoin.max", "Maximum de PNJ de Rejoindre Automatique")
language.Add("npcpassengers.autojoin.max.help", "Nombre maximum de PNJ qui peuvent rejoindre automatiquement à la fois.")
language.Add("npcpassengers.autojoin.squad_only", "Seulement Membres d'Escouade")
language.Add("npcpassengers.autojoin.squad_only.help", "Seuls les PNJ avec un nom d'escouade rejoindront automatiquement (pour les escouades style HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Les PNJ amicaux monteront automatiquement dans votre véhicule quand vous y entrerez, tout comme la mécanique d'escouade dans Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Contrôle des Passagers")
language.Add("npcpassengers.panel.passengers.desc", "Gérez les passagers actifs, filtrez par nom/classe/état, copiez les informations de débogage, réassignez les sièges et détachez les passagers sans quitter le panneau de paramètres.")
language.Add("npcpassengers.panel.position.desc", "Ajustez finement la position des PNJ dans les véhicules. Utilisez ceci pour corriger les problèmes de flottement ou de chevauchement.")
language.Add("npcpassengers.panel.angle.desc", "Ajustez la rotation des PNJ dans les véhicules.")
language.Add("npcpassengers.panel.speech.desc", "Configurez comment les PNJ vocalisent pendant qu'ils voyagent dans les véhicules. Voix de citoyens style HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Décalages de Position")
language.Add("npcpassengers.position.desc", "Ajustez finement la position des PNJ dans les véhicules. Utilisez ceci pour corriger les problèmes de flottement ou de chevauchement.")
language.Add("npcpassengers.height_offset", "Décalage de Hauteur")
language.Add("npcpassengers.forward_offset", "Décalage Avant")
language.Add("npcpassengers.right_offset", "Décalage Droite")
language.Add("npcpassengers.angle.header", "Décalages d'Angle")
language.Add("npcpassengers.angle.desc", "Ajustez la rotation des PNJ dans les véhicules.")
language.Add("npcpassengers.yaw_offset", "Lacet (Rotation)")
language.Add("npcpassengers.pitch_offset", "Tangage (Inclinaison Avant)")
language.Add("npcpassengers.roll_offset", "Roulis (Inclinaison Latérale)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Voix PNJ (Avancé)")
language.Add("npcpassengers.behaviour.desc", "Configurez comment les PNJ vocalisent pendant qu'ils voyagent dans les véhicules. Voix de citoyens style HL2!")
language.Add("npcpassengers.speech_enable", "Activer la Voix PNJ")
language.Add("npcpassengers.speech_enable.help", "Interrupteur principal pour toute la voix PNJ. Désactivez pour rendre les passagers complètement silencieux.")
language.Add("npcpassengers.speech_volume", "Volume de la Voix")
language.Add("npcpassengers.speech_volume.help", "À quel point les voix des PNJ sont fortes (0 = silencieux, 100 = volume complet).")
language.Add("npcpassengers.pitch_variation", "Variation de Hauteur (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Variation aléatoire de hauteur pour des voix plus naturelles. 0 = monotone, plus élevé = plus de variété.")
language.Add("npcpassengers.crash.header", "Réactions aux Collisions")
language.Add("npcpassengers.crash_enable", "Activer les Sons de Collision")
language.Add("npcpassengers.crash_enable.help", "Les PNJ grognent/geignent quand le véhicule décélère brusquement (collisions, freinage brusque).")
language.Add("npcpassengers.crash_threshold", "Sensibilité aux Collisions")
language.Add("npcpassengers.crash_threshold.help", "Décélération nécessaire pour déclencher les sons de collision. Plus bas = plus sensible.")
language.Add("npcpassengers.crash_cooldown", "Recharge du Son de Collision")
language.Add("npcpassengers.crash_cooldown.help", "Secondes minimum entre les sons de collision par PNJ.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Activer les Bavardages Inactifs")
language.Add("npcpassengers.speech_board", "Activer les Sons d'Embarquement/Débarquement")
language.Add("npcpassengers.ambient_sounds", "Activer les Sons Ambiants")
language.Add("npcpassengers.head_look", "Activer le Regard de Tête/Yeux")
language.Add("npcpassengers.blink", "Activer le Clignement")
language.Add("npcpassengers.breathing", "Activer la Respiration")
language.Add("npcpassengers.talking_gestures", "Activer les Gestes en Parlant")
language.Add("npcpassengers.crash_flinch", "Activer le Sursaut de Collision")
language.Add("npcpassengers.body_sway", "Activer le Balancement du Corps")
language.Add("npcpassengers.threat_awareness", "Activer la Conscience des Menaces")
language.Add("npcpassengers.combat_alert", "Alerte de Combat")
language.Add("npcpassengers.passenger_combat", "Les PNJ tirent des véhicules (Expérimental)")
language.Add("npcpassengers.passenger_interaction", "Interaction des Passagers")
language.Add("npcpassengers.fear_reactions", "Activer les Réactions de Peur")
language.Add("npcassengers.drowsiness", "Activer la Somnolence")
language.Add("npcpassengers.hide_in_tanks", "Masquer les PNJ dans les Véhicules Fermés")
language.Add("npcpassengers.eject_stuck_check", "Éjection Automatique des PNJ Coincés")
language.Add("npcpassengers.detach_no_collide", "Pas de Collision avec Véhicule Après Détachement")
language.Add("npcpassengers.die_with_vehicle", "Tuer les Passagers Quand le Véhicule Explose")
language.Add("npcpassengers.driver_enabled", "Activer la Conduite Automatique")
language.Add("npcpassengers.turret_enabled", "Activer le Contrôle de Tourelle")
language.Add("npcpassengers.turret_lead_targets", "Prédire les Cibles")
language.Add("npcpassengers.turret_friendly_fire", "Autoriser le Tir Ami")
language.Add("npcpassengers.turret_hold_fire", "Maintenir le Feu (Désactiver le Tir)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Volume de la Voix")
language.Add("npcpassengers.pitch_variation", "Variation de Hauteur (+/-)")
language.Add("npcpassengers.crash_threshold", "Sensibilité aux Collisions")
language.Add("npcpassengers.crash_cooldown", "Recharge du Son de Collision")
language.Add("npcpassengers.speech_idle_chance", "Probabilité de Bavardage")
language.Add("npcpassengers.speech_idle_interval", "Intervalle de Bavardage")
language.Add("npcpassengers.ambient_interval", "Intervalle de Son Ambient")
language.Add("npcpassengers.head_smooth", "Douceur de Tête")
language.Add("npcpassengers.walk_timeout", "Délai d'Expiration de Marche")
language.Add("npcpassengers.gesture_chance", "Probabilité de Geste (%)")
language.Add("npcpassengers.gesture_interval", "Intervalle de Geste")
language.Add("npcpassengers.crash_threshold_flinch", "Sensibilité aux Collisions")
language.Add("npcassengers.body_sway_amount", "Intensité de Balancement")
language.Add("npcpassengers.threat_range", "Portée de Détection des Menaces")
language.Add("npcpassengers.passenger_combat_range", "Portée de Combat des Passagers")
language.Add("npcpassengers.passenger_combat_accuracy", "Précision des Passagers")
language.Add("npcpassengers.passenger_combat_damage", "Multiplicateur de Dégâts des Passagers")
language.Add("npcpassengers.fear_speed_threshold", "Seuil de Vitesse de Peur")
language.Add("npcpassengers.drowsy_time", "Temps de Somnolence")
language.Add("npcpassengers.detach_no_collide_duration", "Durée Sans Collision (secondes)")
language.Add("npcpassengers.tank_driver_range", "Portée de Détection")
language.Add("npcpassengers.tank_driver_engage_distance", "Distance d'Engagement")
language.Add("npcpassengers.tank_driver_speed", "Vitesse de Conduite")
language.Add("npcpassengers.tank_driver_reverse_distance", "Distance de Marche Arrière")
language.Add("npcpassengers.turret_range", "Portée de Cible")
language.Add("npcpassengers.turret_accuracy", "Précision")
language.Add("npcpassengers.turret_reaction_time", "Temps de Réaction")
language.Add("npcpassengers.turret_fire_delay", "Délai de Tir")
language.Add("npcpassengers.turret_aim_speed", "Vitesse de Visée")
language.Add("npcpassengers.hud_scale", "Échelle du HUD")
language.Add("npcpassengers.hud_opacity", "Opacité du HUD")
language.Add("npcpassengers.hud_alert_threshold", "Seuil d'Alerte")
language.Add("npcpassengers.hud_fear_threshold", "Seuil de Peur")
language.Add("npcpassengers.hud_drowsy_threshold", "Seuil de Somnolence")
language.Add("npcpassengers.ui_sounds_volume", "Volume des Sons UI")
language.Add("npcpassengers.ui_panel_width", "Largeur du Panneau")

-- Section headers
language.Add("npcpassengers.section.animation", "Animation et Comportement")
language.Add("npcpassengers.section.realism", "Réalisme Avancé")
language.Add("npcpassengers.section.hud_position", "Position et Style du HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Seuils d'Émotion")
language.Add("npcpassengers.section.emotion_actions", "Actions d'Émotion")
language.Add("npcpassengers.section.vehicle_control", "Contrôle du Véhicule")
language.Add("npcpassengers.section.hud_controls", "Contrôles du HUD")
language.Add("npcpassengers.section.debug_controls", "Contrôles de Débogage")
language.Add("npcassengers.section.passenger_status", "Contrôle de l'État des Passagers")
language.Add("npcpassengers.section.quick_test", "Boutons de Test Rapide")
language.Add("npcpassengers.section.driver_system", "Système de Conducteur PNJ")
language.Add("npcpassengers.section.ui_sounds", "Paramètres des Sons UI")
language.Add("npcpassengers.section.appearance", "Apparence")
language.Add("npcpassengers.section.context_menu", "Options du Menu Contextuel")
language.Add("npcpassengers.section.panel_preferences", "Préférences du Panneau de Paramètres")
language.Add("npcpassengers.section.performance", "Performance et Technique")
language.Add("npcpassengers.section.simulation", "Système de Simulation")
language.Add("npcpassengers.section.modules", "Système de Modules")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Attribuer un Siège")
language.Add("npcpassengers.btn.detach", "Détacher")
language.Add("npcpassengers.btn.copy_summary", "Copier le Résumé")
language.Add("npcpassengers.btn.copy_debug", "Copier le Débogage")
language.Add("npcpassengers.btn.enable_all_speech", "Activer Toute la Voix")
language.Add("npcpassengers.btn.disable_all_speech", "Désactiver Toute la Voix")
language.Add("npcpassengers.btn.show_current_vehicle", "Afficher Seulement le Véhicule Actuel")
language.Add("npcpassengers.btn.auto_refresh", "Actualisation Automatique de la Liste Visible")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Aucun véhicule actuel détecté. Asseyez-vous dans un véhicule ou désactivez le filtre de véhicule actuel.")
language.Add("npcpassengers.status.no_match_filter", "Aucun passager ne correspond à votre filtre. Essayez un nom, une classe, un numéro de siège, un état ou une classe de véhicule.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Aucun passager trouvé dans votre véhicule actuel.")
language.Add("npcpassengers.status.no_passengers", "Aucun passager trouvé. Les PNJ doivent voyager dans un véhicule avant de pouvoir être gérés ici.")
language.Add("npcpassengers.status.all_passengers", "Tous les Passagers")
language.Add("npcpassengers.status.current_vehicle_only", "Seulement Véhicule Actuel")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F pour focaliser la recherche")
language.Add("npcengers.status.no_matches", "Aucun paramètre correspondant")
language.Add("npcpassengers.status.showing_matches", "Affichage de %d meilleurs sur %d correspondances")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Ouvrir les Paramètres")
language.Add("npcpassengers.menu.reset_all", "Réinitialiser Tous les Paramètres")

-- Button states
language.Add("npcpassengers.state.on", "ACTIVÉ")
language.Add("npcpassengers.state.off", "DÉSACTIVÉ")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Rejoindre Automatique")
language.Add("npcpassengers.chat.hud_status", "HUD des Passagers")
language.Add("npcpassengers.chat.hud_position", "Position du HUD")
language.Add("npcpassengers.chat.target_debug", "Débogage de Cible")
language.Add("npcpassengers.chat.turret_gunners", "Tireurs de Tourelle")
language.Add("npcpassengers.chat.turret_holding", "MAINTENIR LE FEU")
language.Add("npcpassengers.chat.turret_fire", "OUVRIR LE FEU")
language.Add("npcpassengers.chat.unknown", "Inconnu")
language.Add("npcpassengers.chat.nothing_copy", "Rien à copier.")
language.Add("npcpassengers.chat.clipboard_unavailable", "L'accès au presse-papiers n'est pas disponible dans cette version.")
language.Add("npcpassengers.chat.copied_clipboard", "Copié dans le presse-papiers.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Asseyez-vous dans le même véhicule pour réattribuer ce passager.")
language.Add("npcpassengers.chat.no_visible_passengers", "Aucun passager visible à copier.")
language.Add("npcpassengers.chat.need_vehicle", "Vous devez être dans un véhicule pour utiliser ceci.")
language.Add("npcpassengers.chat.keybinds_applied", "Raccourcis recommandés appliqués.")
language.Add("npcpassengers.chat.keybinds_cleared", "Tous les raccourcis effacés.")
language.Add("npcpassengers.chat.context_enabled", "Toutes les options du menu contextuel activées.")
language.Add("npcpassengers.chat.context_hidden", "Toutes les options du menu contextuel masquées.")
language.Add("npcpassengers.chat.panel_compact", "Taille du panneau définie sur compacte.")
language.Add("npcpassengers.chat.panel_default", "Taille du panneau définie sur par défaut.")
language.Add("npcpassengers.chat.panel_large", "Taille du panneau définie sur grande.")
language.Add("npcpassengers.chat.panel_centered", "Panneau centré.")
language.Add("npcpassengers.chat.settings_reset", "Tous les paramètres UI réinitialisés aux valeurs par défaut!")
language.Add("npcpassengers.chat.npc_selected", "PNJ sélectionné! Maintenant faites un clic droit sur un véhicule et sélectionnez 'Ajouter le PNJ Sélectionné'")
language.Add("npcpassengers.chat.adding_npc", "Ajout du PNJ au véhicule...")
language.Add("npcpassengers.chat.selection_cancelled", "Sélection du PNJ annulée")
language.Add("npcassengers.chat.summary_copied", "Résumé des passagers copié.")
language.Add("npcpassengers.chat.debug_copied", "Informations de débogage des passagers copiées.")
language.Add("npcpassengers.chat.no_passengers_found", "Aucun passager trouvé. Les PNJ doivent être dans un véhicule.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Intensité de l'état %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filtrer les passagers...")
language.Add("npcpassengers.ui.press_key", "Appuyez sur une touche...")
language.Add("npcpassengers.ui.work_in_progress", "En Cours")
language.Add("npcpassengers.ui.under_development", "Cette fonctionnalité est actuellement en développement")
language.Add("npcpassengers.ui.check_back_later", "Revenez vérifier dans une mise à jour future!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtre les passagers actifs par nom, classe, siège, état ou véhicule.")
language.Add("npcpassengers.ui.search_desc_sort", "Trie la liste visible des passagers par véhicule, nom, siège, santé ou état.")
language.Add("npcpassengers.ui.search_label_filter", "Filtre de Passagers")
language.Add("npcpassengers.ui.search_label_sort", "Ordre des Passagers")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Comment ajouter des PNJ à mon véhicule?")
language.Add("npcpassengers.faq.add_npc.answer", "Utilisez le menu contextuel (clic droit sur un PNJ) et sélectionnez 'Rendre Passager'. Ou utilisez le raccourci 'Attacher le PNJ le Plus Proche'. Les PNJ doivent être amicaux avec vous.")
language.Add("npcpassengers.faq.remove_npc", "Comment supprimer les passagers de mon véhicule?")
language.Add("npcpassengers.faq.remove_npc.answer", "Allez à l'onglet Passagers dans les paramètres, sélectionnez le passager et cliquez sur Détacher. Ou utilisez le raccourci 'Détacher Tous les Passagers'.")
language.Add("npcpassengers.faq.position", "Les PNJ flottent/passent à travers les sièges!")
language.Add("npcpassengers.faq.position.answer", "Allez à l'onglet Position et ajustez les décalages de Hauteur/Avant/Droite. Chaque modèle de véhicule est différent, vous devrez peut-être ajuster ces valeurs. Utilisez le panneau de débogage pour tester les positions en temps réel.")
language.Add("npcpassengers.faq.speech", "Les PNJ ne parlent pas!")
language.Add("npcpassengers.faq.speech.answer", "Vérifiez l'onglet Comportement et assurez-vous que 'Activer la Voix PNJ' est activé. Vérifiez également que le Volume de la Voix est supérieur à 0. Certains modèles de PNJ peuvent ne pas avoir de lignes vocales disponibles.")
language.Add("npcpassengers.faq.autojoin", "Comment fonctionne le Rejoindre Automatique?")
language.Add("npcpassengers.faq.autojoin.answer", "Quand activé dans l'onglet Rejoindre Automatique, les PNJ amicaux proches monteront automatiquement quand vous entrerez dans un véhicule, tout comme la mécanique d'escouade dans Half-Life 2! Vous pouvez définir la portée de détection et limiter combien de PNJ peuvent rejoindre automatiquement.")
language.Add("npcassengers.faq.death", "Que se passe-t-il quand les passagers meurent?")
language.Add("npcpassengers.faq.death.answer", "Les passagers morts montreront un effet de lueur rouge et afficheront une icône de crâne dans le HUD. Approchez votre véhicule et maintenez R pour retirer leurs corps. Les corps seront éjectés avec physique.")
language.Add("npcpassengers.faq.status", "Que signifient les états des passagers?")
language.Add("npcpassengers.faq.status.answer", "CALME: Détendu, aucune menace proche. ALERTE: Ennemi détecté. PEUR: Conduite dangereuse. SOMNOLENT: Long trajet calme. MORT: Santé atteint zéro.")
language.Add("npcpassengers.faq.keybinds", "Mes raccourcis ne fonctionnent pas!")
language.Add("npcpassengers.faq.keybinds.answer", "Allez à l'onglet Raccourcis et assurez-vous que vous avez réellement défini les raccourcis (ils ne sont pas assignés par défaut). Cliquez sur le bouton à côté de chaque action et appuyez sur la touche souhaitée. Clic droit pour dissocier.")
language.Add("npcpassengers.faq.errors", "L'addon ne fonctionne pas du tout / Je reçois des erreurs!")
language.Add("npcpassengers.faq.errors.answer", "Assurez-vous d'exécuter la dernière version de Garry's Mod. Vérifiez la console pour les erreurs (touche tilde ~). Essayez de désactiver les addons en conflit.")
language.Add("npcpassengers.faq.combat", "Les passagers peuvent-ils tirer des véhicules?")
language.Add("npcpassengers.faq.combat.answer", "Actuellement non. Les PNJ suivront les ennemis et réagiront aux menaces, mais ne tireront pas d'armes assis. Cette fonctionnalité pourrait être ajoutée dans les mises à jour futures.")
language.Add("npcpassengers.faq.stop_autojoin", "Comment arrêter les PNJ de rejoindre automatiquement?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Désactivez la case 'Activer le Rejoindre Automatique' dans l'onglet Rejoindre Automatique, ou utilisez le raccourci 'Basculer le Rejoindre Automatique'.")
language.Add("npcpassengers.faq.settings", "Où les paramètres sont-ils sauvegardés?")
language.Add("npcpassengers.faq.settings.answer", "Tous les paramètres sont sauvegardés comme ConVars dans votre configuration GMod. Ils persistent entre les sessions et sont spécifiques à votre client.")
language.Add("npcpassengers.faq.vehicles", "Cela fonctionne-t-il avec tous les véhicules?")
language.Add("npcassengers.faq.vehicles.answer", "Cela fonctionne avec la plupart des véhicules qui ont de la physique. Chars, APC, voitures, bateaux, etc. Certains véhicules moddés peuvent nécessiter des ajustements de position.")
language.Add("npcpassengers.faq.multiple", "Puis-je avoir plusieurs PNJ dans un véhicule?")
language.Add("npcpassengers.faq.multiple.answer", "Oui! Définissez la 'Limite de Passagers' dans les paramètres généraux. L'addon distribuera automatiquement les PNJ autour du véhicule. Pour des positions de siège spécifiques, ajustez les décalages dans l'onglet Position.")
language.Add("npcpassengers.faq.crashes", "Les PNJ se comportent bizarrement après les collisions!")
language.Add("npcpassengers.faq.crashes.answer", "C'est normal - ils réagissent avec peur à la conduite dangereuse. Abaissez le Seuil de Peur dans les paramètres HUD si vous voulez qu'ils soient moins réactifs.")
language.Add("npcpassengers.faq.reset_setting", "Comment réinitialiser un seul paramètre?")
language.Add("npcpassengers.faq.reset_setting.answer", "Utilisez la commande de console pour ce paramètre spécifique. Toutes les commandes commencent par 'nai_npc_'. Tapez 'find nai_npc' dans la console pour voir toutes les commandes disponibles.")
language.Add("npcpassengers.faq.multiplayer", "Cela fonctionne-t-il en multijoueur?")
language.Add("npcpassengers.faq.multiplayer.answer", "Oui! L'addon fonctionne à la fois sur les serveurs solo et multijoueur. Chaque joueur contrôle ses propres passagers.")
language.Add("npcpassengers.faq.lvs", "Cela fonctionne-t-il avec les véhicules LVS?")
language.Add("npcpassengers.faq.lvs.answer", "Oui! L'addon a un support complet pour les véhicules LVS (Lua Vehicle System). Les PNJ peuvent voyager comme passagers et peuvent même conduire des véhicules LVS si le mode de Conducteur PNJ est activé.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Ces paramètres contrôlent le comportement de l'interface utilisateur de l'addon")
language.Add("npcpassengers.panel.performance_note1", "Les changements de taille du panneau nécessitent de fermer et de rouvrir le menu")
language.Add("npcpassengers.panel.performance_note2", "Désactiver les sons ou animations peut améliorer la performance sur les systèmes bas de gamme")
language.Add("npcpassengers.panel.performance_title", "Informations sur la Configuration de l'Interface")
language.Add("npcpassengers.help.console_title", "Commandes de Console pour le Débogage:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Activez le mode débogage pour voir des informations détaillées")
language.Add("npcpassengers.about.title", "À Propos")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")
language.Add("npcpassengers.lang.changed_portuguese", "Idioma alterado para português. O painel será atualizado automaticamente.")
language.Add("npcpassengers.lang.changed_german", "Sprache auf Deutsch geändert. Das Panel wird automatisch aktualisiert.")
language.Add("npcpassengers.lang.changed_french", "Langue changée en français. Le panneau s'actualisera automatiquement.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Salut!")
language.Add("npcpassengers.welcome.msg1", "Avant de vous plaindre que le passager est assis sur le véhicule,\ns'il vous plaît ouvrez les paramètres. Vous pouvez le faire, je crois en vous.")
language.Add("npcpassengers.welcome.msg2", "Cet addon est encore loin d'être PARFAIT, n'hésitez pas à\nsignaler des bugs et suggérer de nouvelles fonctionnalités. Je lis tous vos commentaires!")
language.Add("npcpassengers.welcome.changelog", "Journal des Modifications")
language.Add("npcpassengers.welcome.got_it", "Compris!")
language.Add("npcpassengers.welcome.console_cmd", "Ou utilisez la commande de console: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Classes de PNJ sur la Liste Noire")
language.Add("npcpassengers.ui.blacklist_help", "Liste séparée par des virgules des noms de classes de PNJ qui ne peuvent pas utiliser les tourelles. Utilisez la commande de console 'getnpcblacklist' pour voir la liste noire actuelle.")
language.Add("npcpassengers.ui.hud_position", "Position du HUD")
language.Add("npcpassengers.ui.not_bound", "Non Assigné")
language.Add("npcpassengers.ui.keybind_tip", "Astuce: Clic droit sur un raccourci pour le dissocier. Appuyez sur ESC lors de l'assignation pour annuler.")
language.Add("npcpassengers.ui.dont_show_again", "Ne plus afficher ceci")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Opérations des Passagers")
language.Add("npcpassengers.hud.filter_prefix", "Filtre: ")
language.Add("npcpassengers.hud.sort_prefix", "Trier: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Actualisation Automatique: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Véhicule: ")
language.Add("npcpassengers.hud.speed_prefix", "Vitesse: ")
language.Add("npcpassengers.hud.npc_prefix", "PNJ: ")
language.Add("npcpassengers.hud.on", "ACTIVÉ")
language.Add("npcpassengers.hud.off", "DÉSACTIVÉ")
language.Add("npcpassengers.hud.passengers", "Passagers")
language.Add("npcpassengers.hud.npc_driver", "Conducteur PNJ")
language.Add("npcpassengers.hud.total_prefix", "Total: ")
language.Add("npcpassengers.hud.showing_prefix", "Affichage: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Véhicule Actuel: ")
language.Add("npcpassengers.hud.hidden_prefix", "Masqué: ")
language.Add("npcpassengers.hud.dead_prefix", "Morts: ")
language.Add("npcpassengers.hud.scared_prefix", "Effrayés: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Somnolents: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Calme")
language.Add("npcpassengers.status.alert", "Alerte")
language.Add("npcpassengers.status.scared", "Effrayé")
language.Add("npcpassengers.status.drowsy", "Somnolent")
language.Add("npcpassengers.status.dead", "Mort")
language.Add("npcpassengers.status.unknown", "Inconnu")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Citoyen")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Père Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dr. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Chien")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Véhicule")
language.Add("npcassengers.sort.name", "Nom")
language.Add("npcpassengers.sort.seat", "Siège")
language.Add("npcpassengers.sort.health", "Santé")
language.Add("npcpassengers.sort.status", "État")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Véhicule d'Abord")
language.Add("npcpassengers.sort.name_az", "Nom A-Z")
language.Add("npcpassengers.sort.seat_number", "Numéro de Siège")
language.Add("npcpassengers.sort.highest_health", "Santé la Plus Élevée")
language.Add("npcpassengers.sort.status_priority", "Priorité d'État")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Véhicule: Inconnu")
language.Add("npcpassengers.ui.seat_prefix", "Siège ")
language.Add("npcpassengers.ui.same_vehicle", "Même Véhicule")
language.Add("npcpassengers.ui.other_vehicle", "Autre Véhicule")
language.Add("npcpassengers.ui.hidden", "Masqué")
language.Add("npcpassengers.ui.visible", "Visible")
language.Add("npcpassengers.ui.health_format", "Santé %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Actualiser la Liste des Passagers")
language.Add("npcpassengers.ui.copy_list", "Copier la Liste Visible des Passagers")
language.Add("npcpassengers.ui.make_exit", "Faire Sortir les Passagers du Véhicule Actuel")
language.Add("npcpassengers.ui.reset_pos", "Réinitialiser la Position et les Angles")
language.Add("npcpassengers.ui.crash_reactions", "Réactions aux Collisions")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Sons d'Embarquement/Débarquement")
language.Add("npcpassengers.section.ambient_sounds", "Sons Ambiants")
language.Add("npcpassengers.section.gesture_animations", "Animations de Gestes")
language.Add("npcpassengers.section.threat_awareness", "Conscience des Menaces")
language.Add("npcpassengers.section.emotional_states", "États Émotionnels")
language.Add("npcpassengers.section.turret_control", "Contrôle de Tourelle (Expérimental)")
language.Add("npcpassengers.section.turret_blacklist", "Liste Noire des PNJ de Tourelle")
language.Add("npcpassengers.section.idle_chatter", "Bavardage Inactif")
language.Add("npcpassengers.section.body_physics", "Physique du Corps")
language.Add("npcpassengers.section.npc_auto_driver", "Conducteur Automatique PNJ")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "En Bas à Gauche")
language.Add("npcpassengers.hud.bottom_right", "En Bas à Droite")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Activer le HUD des Passagers")
language.Add("npcpassengers.ui.cover_face", "Couvrir le Visage")
language.Add("npcpassengers.ui.apply_keybinds", "Appliquer les Raccourcis Recommandés")
language.Add("npcpassengers.ui.clear_keybinds", "Effacer Tous les Raccourcis")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Tester le Geste de Sursaut")
language.Add("npcpassengers.ui.test_random", "Tester un Geste Aléatoire")
language.Add("npcpassengers.ui.reset_states", "Réinitialiser Tous les États")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Activer Toutes les Options du Menu Contextuel")
language.Add("npcpassengers.ui.hide_context", "Masquer Toutes les Options du Menu Contextuel")
language.Add("npcpassengers.ui.set_compact", "Définir la Taille Compacte du Panneau")
language.Add("npcpassengers.ui.set_default", "Définir la Taille par Défaut du Panneau")
language.Add("npcpassengers.ui.set_large", "Définir la Taille Grande du Panneau")
language.Add("npcpassengers.ui.center_panel", "Centrer le Panneau Maintenant")
language.Add("npcpassengers.ui.reset_ui", "Réinitialiser Tous les Paramètres UI aux Valeurs par Défaut")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Citoyen (F)")
language.Add("npcpassengers.role.citizen_male", "Citoyen (M)")
language.Add("npcpassengers.role.medic", "Médecin")
language.Add("npcpassengers.role.rebel", "Rebelle")
language.Add("npcpassengers.role.passenger", "Passager")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Afficher Seulement Quand dans le Véhicule")
language.Add("npcpassengers.hud.show_calm", "Afficher les Passagers Calmes")
language.Add("npcpassengers.hud.show_hints", "Afficher les Indices Contextuels")
language.Add("npcpassengers.hud.show_target_debug", "Afficher le Débogage de Cible")
language.Add("npcpassengers.hud.play_cues", "Jouer les Signaux de Succès/Échec")
language.Add("npcpassengers.debug.enable_mode", "Activer le Mode Débogage")
language.Add("npcpassengers.ui.enable_sounds", "Activer les Sons UI")
language.Add("npcpassengers.ui.hover_sounds", "Sons au Survol")
language.Add("npcpassengers.ui.click_sounds", "Sons au Clic")
language.Add("npcpassengers.ui.enable_animations", "Activer les Animations UI")
language.Add("npcpassengers.ui.show_tooltips", "Afficher les Infobulles")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Masquer Automatiquement la Barre de Défilement")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Fluidité de Défilement de la Barre Latérale")
language.Add("npcpassengers.ui.color_theme", "Thème de Couleur")
language.Add("npcpassengers.ui.font_scale", "Échelle de Police")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Annuler la Sélection du PNJ")
language.Add("npcpassengers.context.remove_passenger", "Supprimer le Passager")
language.Add("npcpassengers.context.blacklist_passenger", "Ajouter à la Liste Noire")
language.Add("npcpassengers.context.whitelist_passenger", "Ajouter à la Liste Blanche")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Raccourcis Clavier")
language.Add("npcpassengers.keybinds.desc", "Configurez les raccourcis clavier pour des actions rapides.")
language.Add("npcpassengers.keybind.attach", "Attacher le PNJ le Plus Proche")
language.Add("npcpassengers.keybind.attach.help", "Attache le PNJ amical le plus proche à votre véhicule.")
language.Add("npcpassengers.keybind.detach_all", "Détacher Tous les PNJ")
language.Add("npcpassengers.keybind.detach_all.help", "Retire tous les passagers de votre véhicule.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Basculer le Rejoindre Automatique")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Active/désactive rapidement le rejoindre automatique.")
language.Add("npcpassengers.keybind.menu", "Ouvrir le Menu des Paramètres")
language.Add("npcpassengers.keybind.menu.help", "Ouvre le panneau des paramètres.")
language.Add("npcpassengers.keybind.exit_all", "Tous les Passagers Sortent")
language.Add("npcpassengers.keybind.exit_all.help", "Fait sortir tous les passagers du véhicule.")
language.Add("npcpassengers.keybind.toggle_hud", "Basculer le HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Affiche/masque le HUD des passagers.")
language.Add("npcpassengers.keybind.quick_attach", "Mode d'Attachement Rapide")
language.Add("npcpassengers.keybind.quick_attach.help", "Maintenez pour attacher rapidement les PNJ que vous regardez")
language.Add("npcpassengers.keybind.hold_fire", "Les PNJ Maintiennent le Feu")
language.Add("npcpassengers.keybind.hold_fire.help", "Dites aux tireurs PNJ d'arrêter de tirer")
language.Add("npcpassengers.keybind.open_fire", "Les PNJ Ouvrent le Feu")
language.Add("npcpassengers.keybind.open_fire.help", "Dites aux tireurs PNJ d'engager les cibles")
language.Add("npcpassengers.keybind.cycle_view", "Cycler la Vue des Passagers")
language.Add("npcpassengers.keybind.cycle_view.help", "Cycle la caméra à travers les passagers")
language.Add("npcpassengers.keybind.cycle_hud_position", "Cycler la Position du HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Déplace le HUD des passagers à travers les quatre coins")
language.Add("npcpassengers.keybind.toggle_debug", "Basculer le Débogage de Cible")
language.Add("npcpassengers.keybind.toggle_debug.help", "Bascule la petite superposition de débogage de cible")
language.Add("npcpassengers.keybind.test_gesture", "Tester un Geste Aléatoire")
language.Add("npcpassengers.keybind.test_gesture.help", "Joue un geste aléatoire sur le passager le plus proche")
language.Add("npcpassengers.keybind.reset_all", "Réinitialiser Tous les PNJ")
language.Add("npcpassengers.keybind.reset_all.help", "Réinitialise les états d'animation pour tous les passagers")

-- HUD Settings
language.Add("npcassengers.hud.header", "Paramètres du HUD")
language.Add("npcpassengers.hud.enable", "Activer le HUD")
language.Add("npcpassengers.hud.enable.help", "Affiche la superposition d'état des passagers à l'écran.")
language.Add("npcpassengers.hud.position", "Position du HUD")
language.Add("npcpassengers.hud.position.help", "Où le HUD apparaît à l'écran.")
language.Add("npcpassengers.hud.position.topleft", "En Haut à Gauche")
language.Add("npcpassengers.hud.position.topright", "En Haut à Droite")
language.Add("npcpassengers.hud.position.bottomleft", "En Bas à Gauche")
language.Add("npcpassengers.hud.position.bottomright", "En Bas à Droite")
language.Add("npcpassengers.hud.scale", "Échelle du HUD")
language.Add("npcpassengers.hud.scale.help", "Multiplicateur de taille pour le HUD.")
language.Add("npcpassengers.hud.opacity", "Opacité du HUD")
language.Add("npcpassengers.hud.opacity.help", "Transparence de fond (0 = invisible, 1 = solide).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Conducteur PNJ")
language.Add("npcpassengers.driver.desc", "Permet aux PNJ de conduire des véhicules pour vous.")
language.Add("npcpassengers.driver.enable", "Activer les Conducteurs PNJ")
language.Add("npcpassengers.driver.enable.help", "Permet aux PNJ de prendre le contrôle des véhicules.")
language.Add("npcpassengers.driver.behavior", "Comportement de Conduite")
language.Add("npcpassengers.driver.behavior.help", "Comment le PNJ conduit le véhicule.")
language.Add("npcpassengers.driver.behavior.cruise", "Croisière Aléatoire")
language.Add("npcpassengers.driver.behavior.follow", "Suivre le Joueur")
language.Add("npcpassengers.driver.behavior.patrol", "Patrouille")
language.Add("npcpassengers.driver.behavior.flee", "Fuir")
language.Add("npcpassengers.driver.behavior.parked", "Rester Stationné")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Questions Fréquentes")
language.Add("npcpassengers.help.desc", "Réponses rapides aux questions courantes et dépannage.")
language.Add("npcpassengers.help.still_need", "Avez-vous encore besoin d'aide?")
language.Add("npcpassengers.help.community", "Rejoignez notre communauté Discord pour le support!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Char/LVS")
language.Add("npcpassengers.nav.debugging", "Débogage")
language.Add("npcpassengers.nav.driver", "Conducteur PNJ")
language.Add("npcpassengers.nav.interface", "Interface")
language.Add("npcassengers.nav.simulate", "Simuler")
language.Add("npcpassengers.nav.modules", "Modules")
language.Add("npcpassengers.nav.about", "À Propos")
language.Add("npcpassengers.search.placeholder", "Rechercher des paramètres...")

-- About page
language.Add("npcpassengers.about.description", "Système de passagers avancé avec IA émotionnelle et physique réaliste")
language.Add("npcpassengers.about.feature_status", "Système d'État: CALME / ALERTE / PEUR / SOMNOLENT / MORT")
language.Add("npcpassengers.about.feature_performance", "Performance: cache de sièges, minuteurs limités, hooks client optimisés")
language.Add("npcpassengers.about.feature_filtering", "Filtrage de véhicules, recharge de nouvelle tentative d'embarquement, rejoindre automatique seulement pour les escouades")
language.Add("npcpassengers.about.actions", "Actions")
language.Add("npcpassengers.about.show_welcome", "Afficher l'Écran de Bienvenue")
language.Add("npcpassengers.about.open_github", "Ouvrir la Page GitHub")
language.Add("npcpassengers.about.reset_settings", "Réinitialiser TOUS les Paramètres aux Valeurs par Défaut")

-- Status messages
language.Add("npcpassengers.status.calm", "CALME")
language.Add("npcpassengers.status.alert", "ALERTE")
language.Add("npcpassengers.status.scared", "PEUR")
language.Add("npcpassengers.status.drowsy", "SOMNOLENT")
language.Add("npcpassengers.status.dead", "MORT")
language.Add("npcpassengers.status.calm.desc", "Détendu, aucune menace proche")
language.Add("npcpassengers.status.alert.desc", "Ennemi détecté, le PNJ suit les menaces")
language.Add("npcpassengers.status.scared.desc", "Conduite dangereuse (haute vitesse, collisions)")
language.Add("npcpassengers.status.drowsy.desc", "Long trajet calme, le PNJ devient somnolent")
language.Add("npcpassengers.status.dead.desc", "Santé atteint zéro")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Rejoindre Automatique: ACTIVÉ")
language.Add("npcpassengers.chat.autojoin_off", "Rejoindre Automatique: DÉSACTIVÉ")
language.Add("npcpassengers.chat.hud_on", "HUD: ACTIVÉ")
language.Add("npcpassengers.chat.hud_off", "HUD: DÉSACTIVÉ")
language.Add("npcpassengers.chat.prefix", "[Meilleurs Passagers PNJ]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Aucun véhicule proche")
language.Add("npcpassengers.error.no_npc", "Aucun PNJ proche")
language.Add("npcpassengers.error.vehicle_full", "Le véhicule est plein")
language.Add("npcpassengers.error.too_far", "PNJ trop loin du véhicule")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Changer la langue")
language.Add("npcpassengers.tooltip.minimize", "Minimiser le panneau")
language.Add("npcpassengers.tooltip.expand", "Agrandir le panneau")
language.Add("npcpassengers.tooltip.welcome", "Afficher l'écran de bienvenue")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Interrupteur principal pour toute la voix PNJ. Désactivez pour rendre les passagers complètement silencieux.")
language.Add("npcpassengers.speech_volume.help", "À quel point les voix des PNJ sont fortes (0 = silencieux, 100 = volume complet).")
language.Add("npcpassengers.pitch_variation.help", "Variation aléatoire de hauteur pour des voix plus naturelles. 0 = monotone, plus élevé = plus de variété.")
language.Add("npcpassengers.crash_enable.help", "Les PNJ grognent/geignent quand le véhicule décélère brusquement (collisions, freinage brusque).")
language.Add("npcpassengers.crash_threshold.help", "Décélération nécessaire pour déclencher les sons de collision. Plus bas = plus sensible.")
language.Add("npcpassengers.crash_cooldown.help", "Secondes minimum entre les sons de collision par PNJ.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "Les PNJ parlent occasionnellement pendant qu'ils voyagent - commentaires, questions, observations.")
language.Add("npcpassengers.speech_idle_chance.help", "Probabilité de bavardage par vérification. 0 = jamais, 1 = essaie toujours de parler.")
language.Add("npcpassengers.speech_idle_interval.help", "Secondes minimum entre les tentatives de bavardage inactif.")
language.Add("npcpassengers.speech_board.help", "Les PNJ parlent quand ils entrent et sortent des véhicules.")
language.Add("npcpassengers.ambient_sounds.help", "Toux occasionnelles, soupirs, murmures - sons de vie de fond.")
language.Add("npcpassengers.ambient_interval.help", "Secondes moyennes entre les sons ambiants.")
language.Add("npcpassengers.animation.help", "Ajustez finement les animations PNJ et le mouvement de tête.")
language.Add("npcpassengers.head_look.help", "Les PNJ regardent naturellement autour, vers le joueur, par les fenêtres, etc.")
language.Add("npcpassengers.head_smooth.help", "À quel point la tête bouge doucement. Plus bas = plus rapide, plus élevé = plus flottant.")
language.Add("npcpassengers.blink.help", "Les PNJ clignent de manière réaliste pendant qu'ils sont assis.")
language.Add("npcpassengers.breathing.help", "Animation de respiration subtile sur les têtes des PNJ.")
language.Add("npcpassengers.walk_timeout.help", "Secondes avant que le PNJ n'abandonne la marche vers le véhicule.")
language.Add("npcpassengers.realism.help", "Réactions basées sur la physique et systèmes de conscience pour une immersion maximale.")
language.Add("npcpassengers.talking_gestures.help", "Les PNJ jouent aléatoirement des gestes de mains et des animations corporelles pendant qu'ils voyagent.")
language.Add("npcpassengers.gesture_chance.help", "Pourcentage de chance de jouer un geste à chaque intervalle.")
language.Add("npcpassengers.gesture_interval.help", "Secondes entre les vérifications d'opportunité de geste.")
language.Add("npcpassengers.crash_flinch.help", "Les PNJ sursautent et se projettent vers l'avant quand le véhicule percute ou freine brusquement.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Changement de vitesse nécessaire pour déclencher le sursaut (plus bas = plus sensible).")
language.Add("npcpassengers.body_sway.help", "Les PNJ se penchent dans les virages, s'appuient pendant l'accélération/freinage.")
language.Add("npcpassengers.body_sway_amount.help", "À quel point les PNJ balancent avec le mouvement du véhicule.")
language.Add("npcpassengers.threat_awareness.help", "Les PNJ regardent automatiquement vers les ennemis proches.")
language.Add("npcpassengers.threat_range.help", "À quelle distance les PNJ peuvent détecter les menaces pour le suivi de tête.")
language.Add("npcpassengers.combat_alert.help", "Les PNJ deviennent tendus et réactifs quand les ennemis sont proches.")
language.Add("npcpassengers.passenger_combat.help", "Désactivé par défaut. Activez ceci pour permettre aux passagers armés de tirer depuis l'intérieur des véhicules.")
language.Add("npcpassengers.passenger_combat_range.help", "À quelle distance les passagers armés peuvent acquérir des cibles.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Des valeurs plus élevées resserrent la dispersion des tirs pour les passagers armés.")
language.Add("npcpassengers.passenger_combat_damage.help", "Met à l'échelle les dégâts causés par les tirs des passagers.")
language.Add("npcpassengers.passenger_interaction.help", "Plusieurs passagers se regardent et bavardent occasionnellement entre eux.")
language.Add("npcpassengers.fear_reactions.help", "Les PNJ ont peur de la conduite dangereuse - yeux écarquillés, sons de panique.")
language.Add("npcpassengers.fear_speed_threshold.help", "Vitesse (unités/sec) à laquelle les PNJ commencent à devenir nerveux.")
language.Add("npcpassengers.drowsiness.help", "Les PNJ deviennent somnolents sur les longs trajets calmes - clignements lents, hochements de tête.")
language.Add("npcpassengers.drowsy_time.help", "Secondes de conduite calme avant que la somnolence ne commence.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Paramètres pour les chars, APC et véhicules LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Rend les passagers PNJ invisibles quand ils sont à l'intérieur des chars et APC.")
language.Add("npcpassengers.eject_stuck_check.help", "Pousse automatiquement les PNJ hors des véhicules quand ils coincident pendant l'éjection. Empêche les PNJ de passer à travers les véhicules en sortant.")
language.Add("npcpassengers.detach_no_collide.help", "Après détachement, les PNJ passent temporairement à travers le véhicule pour qu'ils puissent s'éloigner sans chevauchement ou coincement.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Combien de temps les PNJ ignorent la collision du véhicule après détachement.")
language.Add("npcpassengers.die_with_vehicle.help", "Les passagers PNJ meurent quand leur véhicule est détruit par explosion ou feu (plus immersif que de sortir indemne des débris).")
language.Add("npcpassengers.tank_driver.help", "Permet aux PNJ dans le siège du conducteur de conduire automatiquement vers les ennemis.")
language.Add("npcpassengers.tank_driver_range.help", "Portée maximale pour le conducteur de détecter les ennemis.")
language.Add("npcpassengers.tank_driver_distance.help", "Distance à maintenir des ennemis.")
language.Add("npcpassengers.tank_driver_throttle.help", "Quantité d'accélérateur (0.1 = lent, 1 = vitesse complète).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distance à laquelle reculer loin des ennemis.")
language.Add("npcpassengers.tank_turret.help", "Permet aux PNJ de contrôler les tourelles sur les véhicules LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Affiche l'état des passagers (émotions, alerte) à l'écran pendant la conduite.")
language.Add("npcpassengers.hud_show_calm.help", "Quand désactivé, affiche seulement les passagers avec un état non calme.")
language.Add("npcpassengers.hud_thresholds.desc", "Quand les niveaux d'émotion dépassent ces seuils, les passagers affichent cet état dans le HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Niveau d'alerte nécessaire pour afficher l'état 'ALERTE' (menace détectée).")
language.Add("npcpassengers.hud_fear_threshold.help", "Niveau de peur nécessaire pour afficher l'état 'PEUR' (conduite dangereuse).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Rapport de temps calme nécessaire pour afficher l'état 'SOMNOLENT' (long trajet calme).")
language.Add("npcpassengers.hud_actions.desc", "Choisissez quelle action les passagers prennent quand ils éprouvent chaque état émotionnel.")
language.Add("npcpassengers.hud_actions_note", "Note: Certaines actions peuvent ne pas être visibles selon le support du modèle PNJ.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Définissez des raccourcis personnalisés pour les actions des passagers. Cliquez sur un bouton et appuyez sur une touche pour assigner.")
language.Add("npcpassengers.keybinds_hud.desc", "Contrôles rapides du HUD pour afficher, déplacer et déboguer la superposition des passagers.")
language.Add("npcpassengers.keybinds_debug_note", "Les raccourcis de débogage ne fonctionnent que lorsque le Mode Débogage est activé.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Outils avancés de débogage pour tester le comportement des PNJ. Activez d'abord le Mode Débogage dans les paramètres.")
language.Add("npcpassengers.debug_mode.help", "Affiche les boutons de test de débogage et active les commandes de débogage.")
language.Add("npcpassengers.debug_status.help", "Définit manuellement l'état du passager pour les tests. Cliquez sur 'Actualiser la Liste' pour voir les passagers actuels.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configurez les effets sonores pour les boutons, cases à cocher et autres éléments UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Interrupteur principal pour tous les effets sonores UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Multiplicateur de volume pour les sons UI (1.0 = normal, 2.0 = double)")
language.Add("npcpassengers.ui_hover_enabled.help", "Joue un son au survol des boutons")
language.Add("npcpassengers.ui_click_enabled.help", "Joue un son au clic sur les boutons et cases à cocher")
language.Add("npcpassengers.context_menu.desc", "Choisissez quelles options apparaissent au clic droit sur les PNJ")
language.Add("npcpassengers.context_make_passenger.help", "Ajoute le PNJ comme passager à votre véhicule actuel")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Ajoute le PNJ à un véhicule spécifique (cliquez sur le PNJ, puis sur le véhicule)")
language.Add("npcpassengers.context_detach.help", "Retire le PNJ du véhicule")
language.Add("npcpassengers.ui_show_welcome.help", "Affiche le panneau de bienvenue quand l'addon est mis à jour vers une nouvelle version")
language.Add("npcpassengers.ui_panel_width.help", "Largeur du panneau des paramètres")
language.Add("npcpassengers.ui_panel_height.help", "Hauteur du panneau des paramètres")
language.Add("npcpassengers.ui_animations.help", "Transitions douces et effets de survol (peut impacter la performance)")
language.Add("npcpassengers.ui_tooltips.help", "Affiche des infobulles utiles au survol des paramètres")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Affiche la barre de défilement seulement pendant que vous faites défiler ou la survolez.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Note: Le panneau devient 70% transparent lors du glissement de n'importe quel curseur pour voir le contenu en arrière-plan.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Des valeurs plus basses = plus doux mais plus lent (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Choisissez un thème de couleur pour le panneau des paramètres. Les changements sont appliqués immédiatement.")
language.Add("npcpassengers.ui_font_scale.help", "Met à l'échelle toutes les tailles de police UI. 1.0 = par défaut, 0.5 = demi-taille, 2.0 = taille double.")

print("[Better NPC Passengers] French localization loaded!")
