-- Better NPC Passengers - French Localization
-- Traduction française

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Paramètres")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Général")
language.Add("npcpassengers.nav.autojoin", "Rejoindre Auto")
language.Add("npcpassengers.nav.passengers", "Passagers")
language.Add("npcpassengers.nav.position", "Position")
language.Add("npcpassengers.nav.behaviour", "Comportement")
language.Add("npcpassengers.nav.keybinds", "Raccourcis")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Conducteur")
language.Add("npcpassengers.nav.help", "Aide")

-- General Settings
language.Add("npcpassengers.general.header", "Paramètres Généraux")
language.Add("npcpassengers.allow_multiple", "Autoriser plusieurs passagers")
language.Add("npcpassengers.allow_multiple.help", "Permet à plusieurs NPC de voyager dans le même véhicule.")
language.Add("npcpassengers.exit_behavior", "Comportement de sortie")
language.Add("npcpassengers.exit_behavior.help", "Quand les passagers NPC doivent-ils quitter le véhicule ?")
language.Add("npcpassengers.exit_mode.leave_player", "Quitter quand le joueur sort")
language.Add("npcpassengers.exit_mode.leave_attack", "Quitter quand le véhicule est attaqué")
language.Add("npcpassengers.exit_mode.never", "Ne jamais quitter automatiquement")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Paramètres de timing")
language.Add("npcpassengers.max_attach_dist", "Distance max d'embarquement")
language.Add("npcpassengers.max_attach_dist.help", "Distance maximale (unités) pour qu'un NPC embarque dans le véhicule.")
language.Add("npcpassengers.detach_delay", "Délai de sortie")
language.Add("npcpassengers.detach_delay.help", "Secondes d'attente avant que le NPC ne sorte après que le joueur ait quitté le véhicule.")
language.Add("npcpassengers.ai_delay", "Délai de récupération IA")
language.Add("npcpassengers.ai_delay.help", "Secondes d'attente avant de restaurer l'IA du NPC après la sortie.")
language.Add("npcpassengers.cooldown", "Temps de recharge")
language.Add("npcpassengers.cooldown.help", "Temps de recharge entre les embarquements de NPC dans le même véhicule.")
language.Add("npcpassengers.passenger_limit", "Limite de passagers")
language.Add("npcpassengers.passenger_limit.help", "Maximum de NPC dans le véhicule.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Rejoindre Auto (Comportement d'escouade)")
language.Add("npcpassengers.autojoin.desc", "Les NPC amis rejoindront automatiquement votre véhicule lorsque vous y entrerez, comme la mécanique d'escouade dans Half-Life 2 !")
language.Add("npcpassengers.autojoin.enable", "Activer le rejoindre auto")
language.Add("npcpassengers.autojoin.enable.help", "Les NPC amis proches rejoindront automatiquement lorsque vous entrerez dans un véhicule.")
language.Add("npcpassengers.autojoin.range", "Portée de rejoindre auto")
language.Add("npcpassengers.autojoin.range.help", "Distance maximale pour rechercher des NPC pour le rejoindre auto.")
language.Add("npcpassengers.autojoin.max", "Max NPC pour rejoindre auto")
language.Add("npcpassengers.autojoin.max.help", "Nombre maximum de NPC qui peuvent rejoindre automatiquement à la fois.")
language.Add("npcpassengers.autojoin.squad_only", "Seulement membres d'escouade")
language.Add("npcpassengers.autojoin.squad_only.help", "Seuls les NPC avec un nom d'escouade rejoindront automatiquement (pour les escouades style HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Les NPC amis rejoindront automatiquement votre véhicule lorsque vous y entrerez, comme la mécanique d'escouade dans Half-Life 2 !")
language.Add("npcpassengers.panel.passengers.header", "Gestion des passagers")
language.Add("npcpassengers.panel.passengers.desc", "Gérez les passagers actifs, filtrez par nom/classe/état, copiez les infos de débogage, réassignez les sièges et faites sortir les passagers sans quitter le panneau de paramètres.")
language.Add("npcpassengers.panel.position.desc", "Ajustement fin de la position des NPC dans le véhicule. Utilisez ceci pour corriger les problèmes de flottement ou de clipping.")
language.Add("npcpassengers.panel.angle.desc", "Ajustement de la rotation des NPC dans le véhicule.")
language.Add("npcpassengers.panel.speech.desc", "Configurez comment les NPC vocalisent pendant qu'ils voyagent dans le véhicule. Voix de citoyens style HL2 !")

-- Position Settings
language.Add("npcpassengers.position.header", "Décalages de position")
language.Add("npcpassengers.position.desc", "Ajustement fin de la position des NPC dans le véhicule. Utilisez ceci pour corriger les problèmes de flottement ou de clipping.")
language.Add("npcpassengers.height_offset", "Décalage de hauteur")
language.Add("npcpassengers.forward_offset", "Décalage avant")
language.Add("npcpassengers.right_offset", "Décalage droit")
language.Add("npcpassengers.angle.header", "Décalages d'angle")
language.Add("npcpassengers.angle.desc", "Ajustement de la rotation des NPC dans le véhicule.")
language.Add("npcpassengers.yaw_offset", "Lacet (Rotation)")
language.Add("npcpassengers.pitch_offset", "Tangage (Inclinaison avant)")
language.Add("npcpassengers.roll_offset", "Roulis (Inclinaison latérale)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Voix NPC (Avancé)")
language.Add("npcpassengers.behaviour.desc", "Configurez comment les NPC vocalisent pendant qu'ils voyagent dans le véhicule. Voix de citoyens style HL2 !")
language.Add("npcpassengers.speech_enable", "Activer la voix NPC")
language.Add("npcpassengers.speech_enable.help", "Interrupteur principal pour toute la voix NPC. Désactivez pour rendre les passagers complètement silencieux.")
language.Add("npcpassengers.speech_volume", "Volume de voix")
language.Add("npcpassengers.speech_volume.help", "À quel point les NPC parlent fort (0 = silencieux, 100 = volume complet).")
language.Add("npcpassengers.pitch_variation", "Variation de ton (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Variation aléatoire de ton pour des voix plus naturelles. 0 = monotone, plus haut = plus de variété.")
language.Add("npcpassengers.crash.header", "Réactions aux accidents")
language.Add("npcpassengers.crash_enable", "Activer les sons d'accident")
language.Add("npcpassengers.crash_enable.help", "Les NPC gémissent/crient lorsque le véhicule décélère brusquement (accidents, freinage brusque).")
language.Add("npcpassengers.crash_threshold", "Sensibilité aux accidents")
language.Add("npcpassengers.crash_threshold.help", "Décélération nécessaire pour déclencher les sons d'accident. Plus bas = plus sensible.")
language.Add("npcpassengers.crash_cooldown", "Recharge des sons d'accident")
language.Add("npcpassengers.crash_cooldown.help", "Secondes minimum entre les sons d'accident par NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Activer le bavardage")
language.Add("npcpassengers.speech_board", "Activer les sons d'embarquement/sortie")
language.Add("npcpassengers.ambient_sounds", "Activer les sons ambiants")
language.Add("npcpassengers.head_look", "Activer le regard tête/yeux")
language.Add("npcpassengers.blink", "Activer le clignement")
language.Add("npcpassengers.breathing", "Activer la respiration")
language.Add("npcpassengers.talking_gestures", "Activer les gestes de parole")
language.Add("npcpassengers.crash_flinch", "Activer le sursaut d'accident")
language.Add("npcpassengers.body_sway", "Activer le balancement du corps")
language.Add("npcpassengers.threat_awareness", "Activer la conscience des menaces")
language.Add("npcpassengers.combat_alert", "Alerte de combat")
language.Add("npcpassengers.passenger_combat", "NPC tirent depuis le véhicule (Expérimental)")
language.Add("npcpassengers.passenger_interaction", "Interaction des passagers")
language.Add("npcpassengers.fear_reactions", "Activer les réactions de peur")
language.Add("npcpassengers.drowsiness", "Activer la somnolence")
language.Add("npcpassengers.hide_in_tanks", "Cacher les NPC dans les véhicules fermés")
language.Add("npcpassengers.eject_stuck_check", "Éjection automatique des NPC coincés")
language.Add("npcpassengers.detach_no_collide", "Pas de collision avec le véhicule après la sortie")
language.Add("npcpassengers.die_with_vehicle", "Tuer les passagers lors de l'explosion du véhicule")
language.Add("npcpassengers.driver_enabled", "Activer la conduite auto")
language.Add("npcpassengers.turret_enabled", "Activer le contrôle de tourelle")
language.Add("npcpassengers.turret_lead_targets", "Anticipation des cibles")
language.Add("npcpassengers.turret_friendly_fire", "Autoriser les tirs amis")
language.Add("npcpassengers.turret_hold_fire", "Maintenir le feu (Désactiver le tir)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Volume de voix")
language.Add("npcpassengers.pitch_variation", "Variation de ton (+/-)")
language.Add("npcpassengers.crash_threshold", "Sensibilité aux accidents")
language.Add("npcpassengers.crash_cooldown", "Recharge des sons d'accident")
language.Add("npcpassengers.speech_idle_chance", "Probabilité de bavardage")
language.Add("npcpassengers.speech_idle_interval", "Intervalle de bavardage")
language.Add("npcpassengers.ambient_interval", "Intervalle de sons ambiants")
language.Add("npcpassengers.head_smooth", "Fluidité de tête")
language.Add("npcpassengers.walk_timeout", "Délai de marche")
language.Add("npcpassengers.gesture_chance", "Probabilité de gestes (%)")
language.Add("npcpassengers.gesture_interval", "Intervalle de gestes")
language.Add("npcpassengers.crash_threshold_flinch", "Sensibilité aux accidents")
language.Add("npcpassengers.body_sway_amount", "Intensité de balancement")
language.Add("npcpassengers.threat_range", "Portée de détection des menaces")
language.Add("npcpassengers.passenger_combat_range", "Portée de combat des passagers")
language.Add("npcpassengers.passenger_combat_accuracy", "Précision des passagers")
language.Add("npcpassengers.passenger_combat_damage", "Multiplicateur de dégâts des passagers")
language.Add("npcpassengers.fear_speed_threshold", "Seuil de vitesse de peur")
language.Add("npcpassengers.drowsy_time", "Temps de somnolence")
language.Add("npcpassengers.detach_no_collide_duration", "Durée sans collision (secondes)")
language.Add("npcpassengers.tank_driver_range", "Portée de détection")
language.Add("npcpassengers.tank_driver_engage_distance", "Distance d'engagement")
language.Add("npcpassengers.tank_driver_speed", "Vitesse de conduite")
language.Add("npcpassengers.tank_driver_reverse_distance", "Distance de marche arrière")
language.Add("npcpassengers.turret_range", "Portée de cible")
language.Add("npcpassengers.turret_accuracy", "Précision")
language.Add("npcpassengers.turret_reaction_time", "Temps de réaction")
language.Add("npcpassengers.turret_fire_delay", "Délai de tir")
language.Add("npcpassengers.turret_aim_speed", "Vitesse de visée")
language.Add("npcpassengers.hud_scale", "Échelle HUD")
language.Add("npcpassengers.hud_opacity", "Opacité HUD")
language.Add("npcpassengers.hud_alert_threshold", "Seuil d'alerte")
language.Add("npcpassengers.hud_fear_threshold", "Seuil de peur")
language.Add("npcpassengers.hud_drowsy_threshold", "Seuil de somnolence")
language.Add("npcpassengers.ui_sounds_volume", "Volume des sons UI")
language.Add("npcpassengers.ui_panel_width", "Largeur du panneau")

-- Section headers
language.Add("npcpassengers.section.animation", "Animation et comportement")
language.Add("npcpassengers.section.realism", "Réalisme avancé")
language.Add("npcpassengers.section.hud_position", "Position et style HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Seuils d'émotion")
language.Add("npcpassengers.section.emotion_actions", "Actions d'émotion")
language.Add("npcpassengers.section.vehicle_control", "Contrôle du véhicule")
language.Add("npcpassengers.section.hud_controls", "Contrôles HUD")
language.Add("npcpassengers.section.debug_controls", "Contrôles de débogage")
language.Add("npcpassengers.section.passenger_status", "Gestion de l'état des passagers")
language.Add("npcpassengers.section.quick_test", "Boutons de test rapide")
language.Add("npcpassengers.section.driver_system", "Système de conducteur NPC")
language.Add("npcpassengers.section.ui_sounds", "Paramètres des sons UI")
language.Add("npcpassengers.section.appearance", "Apparence")
language.Add("npcpassengers.section.context_menu", "Options du menu contextuel")
language.Add("npcpassengers.section.panel_preferences", "Préférences du panneau de paramètres")
language.Add("npcpassengers.section.performance", "Performance et technique")
language.Add("npcpassengers.section.simulation", "Système de simulation")
language.Add("npcpassengers.section.modules", "Système de modules")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Assigner siège")
language.Add("npcpassengers.btn.detach", "Détacher")
language.Add("npcpassengers.btn.copy_summary", "Copier le résumé")
language.Add("npcpassengers.btn.copy_debug", "Copier le débogage")
language.Add("npcpassengers.btn.enable_all_speech", "Activer toute la voix")
language.Add("npcpassengers.btn.disable_all_speech", "Désactiver toute la voix")
language.Add("npcpassengers.btn.show_current_vehicle", "Afficher uniquement le véhicule actuel")
language.Add("npcpassengers.btn.auto_refresh", "Actualisation auto de la liste visible")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Véhicule actuel non détecté. Entrez dans un véhicule ou désactivez le filtre de véhicule actuel.")
language.Add("npcpassengers.status.no_match_filter", "Les passagers ne correspondent pas à votre filtre. Essayez le nom, la classe, le numéro de siège, l'état ou la classe de véhicule.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Aucun passager trouvé dans votre véhicule actuel.")
language.Add("npcpassengers.status.no_passengers", "Aucun passager trouvé. Les NPC doivent être dans un véhicule avant de pouvoir être gérés ici.")
language.Add("npcpassengers.status.all_passengers", "Tous les passagers")
language.Add("npcpassengers.status.current_vehicle_only", "Véhicule actuel uniquement")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F pour focus recherche")
language.Add("npcpassengers.status.no_matches", "Aucun paramètre correspondant")
language.Add("npcpassengers.status.showing_matches", "Affichage %d sur %d correspondances")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Ouvrir les paramètres")
language.Add("npcpassengers.menu.reset_all", "Réinitialiser tous les paramètres")

-- Button states
language.Add("npcpassengers.state.on", "ON")
language.Add("npcpassengers.state.off", "OFF")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Rejoindre Auto")
language.Add("npcpassengers.chat.hud_status", "HUD des passagers")
language.Add("npcpassengers.chat.hud_position", "Position HUD")
language.Add("npcpassengers.chat.target_debug", "Débogage de cible")
language.Add("npcpassengers.chat.turret_gunners", "Artilleurs de tourelle")
language.Add("npcpassengers.chat.turret_holding", "MAINTENANT LE FEU")
language.Add("npcpassengers.chat.turret_fire", "FEU OUVERT")
language.Add("npcpassengers.chat.unknown", "Inconnu")
language.Add("npcpassengers.chat.nothing_copy", "Rien à copier.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Accès au presse-papiers non disponible dans cette version.")
language.Add("npcpassengers.chat.copied_clipboard", "Copié dans le presse-papiers.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Asseyez-vous dans le même véhicule pour réassigner ce passager.")
language.Add("npcpassengers.chat.no_visible_passengers", "Aucun passager visible à copier.")
language.Add("npcpassengers.chat.need_vehicle", "Vous devez être dans un véhicule pour utiliser ceci.")
language.Add("npcpassengers.chat.keybinds_applied", "Raccourcis recommandés appliqués.")
language.Add("npcpassengers.chat.keybinds_cleared", "Tous les raccourcis effacés.")
language.Add("npcpassengers.chat.context_enabled", "Toutes les options du menu contextuel activées.")
language.Add("npcpassengers.chat.context_hidden", "Toutes les options du menu contextuel masquées.")
language.Add("npcpassengers.chat.panel_compact", "Taille du panneau définie sur compact.")
language.Add("npcpassengers.chat.panel_default", "Taille du panneau définie sur par défaut.")
language.Add("npcpassengers.chat.panel_large", "Taille du panneau définie sur grand.")
language.Add("npcpassengers.chat.panel_centered", "Panneau centré.")
language.Add("npcpassengers.chat.settings_reset", "Tous les paramètres UI réinitialisés aux valeurs par défaut !")
language.Add("npcpassengers.chat.npc_selected", "NPC sélectionné ! Maintenant faites un clic droit sur le véhicule et sélectionnez 'Ajouter le NPC sélectionné'")
language.Add("npcpassengers.chat.adding_npc", "Ajout du NPC au véhicule...")
language.Add("npcpassengers.chat.selection_cancelled", "Sélection NPC annulée")
language.Add("npcpassengers.chat.summary_copied", "Résumé des passagers copié.")
language.Add("npcpassengers.chat.debug_copied", "Infos de débogage du passager copiées.")
language.Add("npcpassengers.chat.no_passengers_found", "Aucun passager trouvé. Les NPC doivent être dans un véhicule.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Intensité d'état %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filtrer les passagers...")
language.Add("npcpassengers.ui.press_key", "Appuyez sur une touche...")
language.Add("npcpassengers.ui.work_in_progress", "En développement")
language.Add("npcpassengers.ui.under_development", "Cette fonction est en développement")
language.Add("npcpassengers.ui.check_back_later", "Vérifiez dans une future mise à jour !")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtrer les passagers actifs par nom, classe, siège, état ou véhicule.")
language.Add("npcpassengers.ui.search_desc_sort", "Trier la liste visible des passagers par véhicule, nom, siège, santé ou état.")
language.Add("npcpassengers.ui.search_label_filter", "Filtre des passagers")
language.Add("npcpassengers.ui.search_label_sort", "Tri des passagers")

-- Additional keybind names and descriptions
language.Add("npcpassengers.keybind.quick_attach", "Embarquement rapide")
language.Add("npcpassengers.keybind.hold_fire", "NPC maintiennent le feu")
language.Add("npcpassengers.keybind.open_fire", "NPC ouvrent le feu")
language.Add("npcpassengers.keybind.cycle_view", "Cycle caméra passagers")
language.Add("npcpassengers.keybind.cycle_hud_position", "Cycle position HUD")
language.Add("npcpassengers.keybind.toggle_debug", "Basculer le débogage de cible")
language.Add("npcpassengers.keybind.test_gesture", "Tester geste aléatoire")
language.Add("npcpassengers.keybind.reset_all", "Réinitialiser tous les NPC")
language.Add("npcpassengers.keybind.quick_attach.help", "Maintenez pour embarquer rapidement les NPC que vous regardez")
language.Add("npcpassengers.keybind.hold_fire.help", "Dire aux artilleurs NPC d'arrêter de tirer")
language.Add("npcpassengers.keybind.open_fire.help", "Dire aux artilleurs NPC d'attaquer les cibles")
language.Add("npcpassengers.keybind.cycle_view.help", "Faire défiler la caméra entre les passagers")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Déplacer le HUD des passagers dans les quatre coins")
language.Add("npcpassengers.keybind.toggle_debug.help", "Basculer la petite superposition de débogage de cible")
language.Add("npcpassengers.keybind.test_gesture.help", "Jouer un geste aléatoire sur le passager le plus proche")
language.Add("npcpassengers.keybind.reset_all.help", "Réinitialiser les états d'animation pour tous les passagers")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Comment ajouter un NPC à mon véhicule ?")
language.Add("npcpassengers.faq.add_npc.answer", "Utilisez le menu contextuel (clic droit sur NPC) et sélectionnez 'Rendre passager'. Ou utilisez le raccourci 'Embarquer NPC le plus proche'. Les NPC doivent être amicaux envers vous.")
language.Add("npcpassengers.faq.remove_npc", "Comment supprimer des passagers de mon véhicule ?")
language.Add("npcpassengers.faq.remove_npc.answer", "Allez à l'onglet Passagers dans les paramètres, sélectionnez un passager et cliquez sur Détacher. Ou utilisez le raccourci 'Détacher tous les NPC'.")
language.Add("npcpassengers.faq.position", "Les NPC flottent ou traversent les sièges !")
language.Add("npcpassengers.faq.position.answer", "Allez à l'onglet Position et ajustez les décalages Hauteur/Avant/Droite. Chaque modèle de véhicule est différent, vous devrez peut-être ajuster les valeurs avec précision. Utilisez le panneau de débogage pour tester les positions en temps réel.")
language.Add("npcpassengers.faq.speech", "Les NPC ne parlent pas !")
language.Add("npcpassengers.faq.speech.answer", "Vérifiez l'onglet Comportement et assurez-vous que 'Activer la voix NPC' est activé. Assurez-vous également que le Volume de voix est supérieur à 0. Certains modèles de NPC peuvent ne pas avoir de lignes vocales disponibles.")
language.Add("npcpassengers.faq.autojoin", "Comment fonctionne le rejoindre auto ?")
language.Add("npcpassengers.faq.autojoin.answer", "Lorsqu'il est activé dans l'onglet Rejoindre Auto, les NPC amis proches rejoindront automatiquement votre véhicule lorsque vous y entrerez, comme la mécanique d'escouade dans Half-Life 2. Vous pouvez définir la portée de détection et limiter combien de NPC peuvent rejoindre automatiquement.")
language.Add("npcpassengers.faq.death", "Que se passe-t-il lorsque les passagers meurent ?")
language.Add("npcpassengers.faq.death.answer", "Les passagers morts afficheront un effet de lueur rouge et une icône de crâne sur le HUD. Approchez-vous de votre véhicule et maintenez R pour supprimer leurs corps. Les corps seront éjectés avec de la physique.")
language.Add("npcpassengers.faq.status", "Que signifient les états des passagers ?")
language.Add("npcpassengers.faq.status.answer", "CALME : Détendu, aucune menace proche. ALERTE : Ennemi détecté. PEUR : Conduite dangereuse. SOMNOLENCE : Long voyage calme. MORT : Santé atteint zéro.")
language.Add("npcpassengers.faq.keybinds", "Mes raccourcis ne fonctionnent pas !")
language.Add("npcpassengers.faq.keybinds.answer", "Allez à l'onglet Raccourcis et assurez-vous que vous avez réellement défini les raccourcis (ils ne sont pas liés par défaut). Cliquez sur le bouton à côté de chaque action et appuyez sur la touche souhaitée. Clic droit pour délier.")
language.Add("npcpassengers.faq.errors", "L'addon ne fonctionne pas du tout / Je reçois des erreurs !")
language.Add("npcpassengers.faq.errors.answer", "Assurez-vous que vous utilisez la dernière version de Garry's Mod. Vérifiez la console pour les erreurs (touche tilde ~). Essayez de désactiver les addons en conflit.")
language.Add("npcpassengers.faq.combat", "Les passagers peuvent-ils tirer depuis le véhicule ?")
language.Add("npcpassengers.faq.combat.answer", "Actuellement non. Les NPC suivront les ennemis et réagiront aux menaces, mais ne tireront pas depuis les armes tant qu'ils sont assis. Cette fonction pourrait être ajoutée dans de futures mises à jour.")
language.Add("npcpassengers.faq.stop_autojoin", "Comment empêcher les NPC de rejoindre automatiquement ?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Désactivez la case 'Activer le rejoindre auto' dans l'onglet Rejoindre Auto, ou utilisez le raccourci 'Basculer le rejoindre auto'.")
language.Add("npcpassengers.faq.settings", "Où sont enregistrés les paramètres ?")
language.Add("npcpassengers.faq.settings.answer", "Tous les paramètres sont enregistrés sous forme de ConVars dans votre configuration GMod. Ils persistent entre les sessions et sont spécifiques à votre client.")
language.Add("npcpassengers.faq.vehicles", "Cela fonctionne-t-il avec tous les véhicules ?")
language.Add("npcpassengers.faq.vehicles.answer", "Cela fonctionne avec la plupart des véhicules qui ont de la physique. Chars, APC, voitures, bateaux, etc. Certains véhicules moddés peuvent nécessiter des ajustements de position.")
language.Add("npcpassengers.faq.multiple", "Puis-je avoir plusieurs NPC dans un véhicule ?")
language.Add("npcpassengers.faq.multiple.answer", "Oui ! Définissez la 'Limite de passagers' dans les paramètres généraux. L'addon distribuera automatiquement les NPC autour du véhicule. Pour des positions de siège spécifiques, ajustez les décalages dans l'onglet Position.")
language.Add("npcpassengers.faq.crashes", "Les NPC se comportent bizarrement après les accidents !")
language.Add("npcpassengers.faq.crashes.answer", "C'est normal : ils réagissent avec peur à la conduite dangereuse. Réduisez le Seuil de peur dans les paramètres HUD si vous voulez qu'ils soient moins réactifs.")
language.Add("npcpassengers.faq.reset_setting", "Comment réinitialiser un seul paramètre ?")
language.Add("npcpassengers.faq.reset_setting.answer", "Utilisez la commande de console pour ce paramètre spécifique. Toutes les commandes commencent par 'nai_npc_'. Tapez 'find nai_npc' dans la console pour voir toutes les commandes disponibles.")
language.Add("npcpassengers.faq.multiplayer", "Cela fonctionne-t-il en multijoueur ?")
language.Add("npcpassengers.faq.multiplayer.answer", "Oui ! L'addon fonctionne sur les serveurs solo et multijoueur. Chaque joueur contrôle ses propres passagers.")
language.Add("npcpassengers.faq.lvs", "Cela fonctionne-t-il avec les véhicules LVS ?")
language.Add("npcpassengers.faq.lvs.answer", "Oui ! L'addon a un support complet pour les véhicules LVS (Lua Vehicle System). Les NPC peuvent voyager comme passagers et peuvent même conduire des véhicules LVS si le mode conducteur NPC est activé.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Ces paramètres contrôlent le comportement de l'interface utilisateur de l'addon")
language.Add("npcpassengers.panel.performance_note1", "Les changements de taille du panneau nécessitent de fermer et de rouvrir le menu")
language.Add("npcpassengers.panel.performance_note2", "Désactiver les sons ou les animations peut améliorer les performances sur les systèmes bas de gamme")
language.Add("npcpassengers.panel.performance_title", "Infos des paramètres d'interface")
language.Add("npcpassengers.help.console_title", "Commandes de console pour le débogage :")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Activer le mode débogage pour voir des infos détaillées")
language.Add("npcpassengers.about.title", "À propos")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Langue changée en anglais. Le panneau s'actualisera automatiquement.")
language.Add("npcpassengers.lang.changed_russian", "Langue changée en russe. Le panneau s'actualisera automatiquement.")
language.Add("npcpassengers.lang.changed_chinese", "Langue changée en chinois. Le panneau s'actualisera automatiquement.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Salut !")
language.Add("npcpassengers.welcome.msg1", "Avant de vous plaindre que le passager soit assis sur le véhicule,\ns'il vous plaît ouvrez les paramètres. Vous pouvez le faire, je crois en vous.")
language.Add("npcpassengers.welcome.msg2", "Cet addon est encore loin d'être PARFAIT, s'il vous plaît n'hésitez pas à\nsignaler des bugs et suggérer de nouvelles fonctionnalités. Je lis tous vos commentaires !")
language.Add("npcpassengers.welcome.changelog", "Journal des modifications")
language.Add("npcpassengers.welcome.got_it", "Compris !")
language.Add("npcpassengers.welcome.console_cmd", "Ou utilisez la commande de console : nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Classes de NPC sur liste noire")
language.Add("npcpassengers.ui.blacklist_help", "Liste séparée par des virgules de noms de classes de NPC qui ne peuvent pas utiliser les tourelles. Utilisez la commande de console 'getnpcblacklist' pour voir la liste noire actuelle.")
language.Add("npcpassengers.ui.hud_position", "Position HUD")
language.Add("npcpassengers.ui.not_bound", "Non lié")
language.Add("npcpassengers.ui.keybind_tip", "Astuce : Clic droit sur un raccourci pour le délier. Appuyez sur ESC pendant la liaison pour annuler.")
language.Add("npcpassengers.ui.dont_show_again", "Ne plus afficher")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Opérations de passagers")
language.Add("npcpassengers.hud.filter_prefix", "Filtre : ")
language.Add("npcpassengers.hud.sort_prefix", "Tri : ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Actualisation auto : ")
language.Add("npcpassengers.hud.vehicle_prefix", "Véhicule : ")
language.Add("npcpassengers.hud.speed_prefix", "Vitesse : ")
language.Add("npcpassengers.hud.npc_prefix", "NPC : ")
language.Add("npcpassengers.hud.on", "ON")
language.Add("npcpassengers.hud.off", "OFF")
language.Add("npcpassengers.hud.passengers", "Passagers")
language.Add("npcpassengers.hud.npc_driver", "Conducteur NPC")
language.Add("npcpassengers.hud.total_prefix", "Total : ")
language.Add("npcpassengers.hud.showing_prefix", "Affichage : ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Véhicule actuel : ")
language.Add("npcpassengers.hud.hidden_prefix", "Masqué : ")
language.Add("npcpassengers.hud.dead_prefix", "Morts : ")
language.Add("npcpassengers.hud.scared_prefix", "Effrayés : ")
language.Add("npcpassengers.hud.drowsy_prefix", "Somnolents : ")

-- Status labels
language.Add("npcpassengers.status.calm", "Calme")
language.Add("npcpassengers.status.alert", "Alerte")
language.Add("npcpassengers.status.scared", "Effrayé")
language.Add("npcpassengers.status.drowsy", "Somnolent")
language.Add("npcpassengers.status.dead", "Mort")
language.Add("npcpassengers.status.unknown", "Inconnu")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Citoyen")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Père Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dr. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Chien")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Véhicule")
language.Add("npcpassengers.sort.name", "Nom")
language.Add("npcpassengers.sort.seat", "Siège")
language.Add("npcpassengers.sort.health", "Santé")
language.Add("npcpassengers.sort.status", "État")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Véhicule d'abord")
language.Add("npcpassengers.sort.name_az", "Nom A-Z")
language.Add("npcpassengers.sort.seat_number", "Numéro de siège")
language.Add("npcpassengers.sort.highest_health", "Santé la plus élevée")
language.Add("npcpassengers.sort.status_priority", "Priorité d'état")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Véhicule : Inconnu")
language.Add("npcpassengers.ui.seat_prefix", "Siège ")
language.Add("npcpassengers.ui.same_vehicle", "Même véhicule")
language.Add("npcpassengers.ui.other_vehicle", "Autre véhicule")
language.Add("npcpassengers.ui.hidden", "Masqué")
language.Add("npcpassengers.ui.visible", "Visible")
language.Add("npcpassengers.ui.health_format", "Santé %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Actualiser la liste des passagers")
language.Add("npcpassengers.ui.copy_list", "Copier la liste visible des passagers")
language.Add("npcpassengers.ui.make_exit", "Faire sortir les passagers du véhicule actuel")
language.Add("npcpassengers.ui.reset_pos", "Réinitialiser la position et les angles")
language.Add("npcpassengers.ui.crash_reactions", "Réactions aux accidents")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Sons d'embarquement/sortie")
language.Add("npcpassengers.section.ambient_sounds", "Sons ambiants")
language.Add("npcpassengers.section.gesture_animations", "Animations de gestes")
language.Add("npcpassengers.section.threat_awareness", "Conscience des menaces")
language.Add("npcpassengers.section.emotional_states", "États émotionnels")
language.Add("npcpassengers.section.turret_control", "Contrôle de tourelle (Expérimental)")
language.Add("npcpassengers.section.turret_blacklist", "Liste noire de tourelle NPC")
language.Add("npcpassengers.section.idle_chatter", "Bavardage inactif")
language.Add("npcpassengers.section.body_physics", "Physique du corps")
language.Add("npcpassengers.section.npc_auto_driver", "Conducteur auto NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "En bas à gauche")
language.Add("npcpassengers.hud.bottom_right", "En bas à droite")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Activer le HUD des passagers")
language.Add("npcpassengers.ui.cover_face", "Couvrir le visage")
language.Add("npcpassengers.ui.apply_keybinds", "Appliquer les raccourcis recommandés")
language.Add("npcpassengers.ui.clear_keybinds", "Effacer tous les raccourcis")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Tester le geste de sursaut")
language.Add("npcpassengers.ui.test_random", "Tester le geste aléatoire")
language.Add("npcpassengers.ui.reset_states", "Réinitialiser tous les états")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Activer toutes les options du menu contextuel")
language.Add("npcpassengers.ui.hide_context", "Masquer toutes les options du menu contextuel")
language.Add("npcpassengers.ui.set_compact", "Définir la taille du panneau sur compact")
language.Add("npcpassengers.ui.set_default", "Définir la taille du panneau sur par défaut")
language.Add("npcpassengers.ui.set_large", "Définir la taille du panneau sur grand")
language.Add("npcpassengers.ui.center_panel", "Centrer le panneau maintenant")
language.Add("npcpassengers.ui.reset_ui", "Réinitialiser tous les paramètres UI par défaut")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Citoyen (F)")
language.Add("npcpassengers.role.citizen_male", "Citoyen (M)")
language.Add("npcpassengers.role.medic", "Médecin")
language.Add("npcpassengers.role.rebel", "Rebelle")
language.Add("npcpassengers.role.passenger", "Passager")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Afficher uniquement lorsque dans le véhicule")
language.Add("npcpassengers.hud.show_calm", "Afficher les passagers calmes")
language.Add("npcpassengers.hud.show_hints", "Afficher les suggestions contextuelles")
language.Add("npcpassengers.hud.show_target_debug", "Afficher le débogage de cible")
language.Add("npcpassengers.hud.play_cues", "Jouer les signaux succès/échec")
language.Add("npcpassengers.debug.enable_mode", "Activer le mode débogage")
language.Add("npcpassengers.ui.enable_sounds", "Activer les sons UI")
language.Add("npcpassengers.ui.hover_sounds", "Sons de survol de bouton")
language.Add("npcpassengers.ui.click_sounds", "Sons de clic de bouton")
language.Add("npcpassengers.ui.enable_animations", "Activer les animations UI")
language.Add("npcpassengers.ui.show_tooltips", "Afficher les infobulles")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Masquer automatiquement la barre de défilement")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Fluidité de défilement de la barre latérale")
language.Add("npcpassengers.ui.color_theme", "Thème de couleur")
language.Add("npcpassengers.ui.font_scale", "Échelle de police")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Annuler la sélection NPC")
language.Add("npcpassengers.context.remove_passenger", "Supprimer le passager")
language.Add("npcpassengers.context.blacklist_passenger", "Mettre sur liste noire")
language.Add("npcpassengers.context.whitelist_passenger", "Mettre sur liste blanche")
language.Add("npcpassengers.context.taxi_passenger", "Assigner comme passager de taxi")

-- Tool labels
language.Add("tool.npcpassengers_taxi_station.name", "Station de taxi")
language.Add("tool.npcpassengers_taxi_station.desc", "Créer une station de taxi pour le système de taxi NPC")
language.Add("tool.npcpassengers_taxi_station.0", "Clic gauche pour placer une station de taxi. Clic droit pour supprimer.")
language.Add("tool.npcpassengers_taxi_station.left", "Placer la station")
language.Add("tool.npcpassengers_taxi_station.right", "Supprimer la station")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Raccourcis")
language.Add("npcpassengers.keybinds.desc", "Configurez les raccourcis clavier pour des actions rapides.")
language.Add("npcpassengers.keybind.attach", "Embarquer le NPC le plus proche")
language.Add("npcpassengers.keybind.attach.help", "Embarquer le NPC ami le plus proche dans votre véhicule.")
language.Add("npcpassengers.keybind.detach_all", "Détacher tous les NPC")
language.Add("npcpassengers.keybind.detach_all.help", "Supprimer tous les passagers de votre véhicule.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Basculer le rejoindre auto")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Activer/désactiver rapidement le rejoindre auto.")
language.Add("npcpassengers.keybind.menu", "Ouvrir le menu des paramètres")
language.Add("npcpassengers.keybind.menu.help", "Ouvrir le panneau des paramètres.")
language.Add("npcpassengers.keybind.exit_all", "Sortie de tous les passagers")
language.Add("npcpassengers.keybind.exit_all.help", "Faire sortir tous les passagers du véhicule.")
language.Add("npcpassengers.keybind.toggle_hud", "Basculer le HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Afficher/masquer le HUD des passagers.")
language.Add("npcpassengers.keybind.quick_attach", "Mode d'embarquement rapide")
language.Add("npcpassengers.keybind.quick_attach.help", "Maintenez pour embarquer rapidement les NPC que vous regardez")
language.Add("npcpassengers.keybind.hold_fire", "NPC maintiennent le feu")
language.Add("npcpassengers.keybind.hold_fire.help", "Dire aux artilleurs NPC d'arrêter de tirer")
language.Add("npcpassengers.keybind.open_fire", "NPC ouvrent le feu")
language.Add("npcpassengers.keybind.open_fire.help", "Dire aux artilleurs NPC d'attaquer les cibles")
language.Add("npcpassengers.keybind.cycle_view", "Cycle de vue des passagers")
language.Add("npcpassengers.keybind.cycle_view.help", "Faire défiler la caméra entre les passagers")
language.Add("npcpassengers.keybind.cycle_hud_position", "Cycle de position HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Déplacer le HUD des passagers dans les quatre coins")
language.Add("npcpassengers.keybind.toggle_debug", "Basculer le débogage de cible")
language.Add("npcpassengers.keybind.toggle_debug.help", "Basculer la petite superposition de débogage de cible")
language.Add("npcpassengers.keybind.test_gesture", "Tester le geste aléatoire")
language.Add("npcpassengers.keybind.test_gesture.help", "Jouer un geste aléatoire sur le passager le plus proche")
language.Add("npcpassengers.keybind.reset_all", "Réinitialiser tous les NPC")
language.Add("npcpassengers.keybind.reset_all.help", "Réinitialiser les états d'animation pour tous les passagers")

-- HUD Settings
language.Add("npcpassengers.hud.header", "Paramètres HUD")
language.Add("npcpassengers.hud.enable", "Activer le HUD")
language.Add("npcpassengers.hud.enable.help", "Afficher la superposition d'état des passagers sur l'écran.")
language.Add("npcpassengers.hud.position", "Position HUD")
language.Add("npcpassengers.hud.position.help", "Où le HUD apparaît sur l'écran.")
language.Add("npcpassengers.hud.position.topleft", "En haut à gauche")
language.Add("npcpassengers.hud.position.topright", "En haut à droite")
language.Add("npcpassengers.hud.position.bottomleft", "En bas à gauche")
language.Add("npcpassengers.hud.position.bottomright", "En bas à droite")
language.Add("npcpassengers.hud.scale", "Échelle HUD")
language.Add("npcpassengers.hud.scale.help", "Multiplicateur de taille pour le HUD.")
language.Add("npcpassengers.hud.opacity", "Opacité HUD")
language.Add("npcpassengers.hud.opacity.help", "Transparence du fond (0 = invisible, 1 = solide).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Conducteur NPC")
language.Add("npcpassengers.driver.desc", "Permet aux NPC de conduire des véhicules pour vous.")
language.Add("npcpassengers.driver.enable", "Activer les conducteurs NPC")
language.Add("npcpassengers.driver.enable.help", "Permet aux NPC de prendre le contrôle du véhicule.")
language.Add("npcpassengers.driver.behavior", "Comportement de conduite")
language.Add("npcpassengers.driver.behavior.help", "Comment le NPC conduit le véhicule.")
language.Add("npcpassengers.driver.behavior.cruise", "Croisière aléatoire")
language.Add("npcpassengers.driver.behavior.follow", "Suivre le joueur")
language.Add("npcpassengers.driver.behavior.patrol", "Patrouille")
language.Add("npcpassengers.driver.behavior.flee", "Fuir")
language.Add("npcpassengers.driver.behavior.parked", "Rester garé")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Questions fréquentes")
language.Add("npcpassengers.help.desc", "Réponses rapides aux questions courantes et dépannage.")
language.Add("npcpassengers.help.still_need", "Besoin encore d'aide ?")
language.Add("npcpassengers.help.community", "Rejoignez notre communauté Discord pour obtenir de l'aide !")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Char/LVS")
language.Add("npcpassengers.nav.debugging", "Débogage")
language.Add("npcpassengers.nav.driver", "Conducteur NPC")
language.Add("npcpassengers.nav.interface", "Interface")
language.Add("npcpassengers.nav.simulate", "Simuler")
language.Add("npcpassengers.nav.modules", "Modules")
language.Add("npcpassengers.nav.about", "À propos")
language.Add("npcpassengers.search.placeholder", "Rechercher des paramètres...")

-- About page
language.Add("npcpassengers.about.description", "Système de passagers avancé avec IA émotionnelle et physique réaliste")
language.Add("npcpassengers.about.feature_status", "Système d'état : CALME / ALERTE / PEUR / SOMNOLENCE / MORT")
language.Add("npcpassengers.about.feature_performance", "Performance : cache de sièges, minuteurs limités, crochets client optimisés")
language.Add("npcpassengers.about.feature_filtering", "Filtrage de véhicules, recharge des rétentives d'embarquement, rejoindre auto uniquement escouades")
language.Add("npcpassengers.about.actions", "Actions")
language.Add("npcpassengers.about.show_welcome", "Afficher l'écran de bienvenue")
language.Add("npcpassengers.about.open_github", "Ouvrir la page GitHub")
language.Add("npcpassengers.about.reset_settings", "Réinitialiser TOUS les paramètres par défaut")

-- Status messages
language.Add("npcpassengers.status.calm", "CALME")
language.Add("npcpassengers.status.alert", "ALERTE")
language.Add("npcpassengers.status.scared", "PEUR")
language.Add("npcpassengers.status.drowsy", "SOMNOLENCE")
language.Add("npcpassengers.status.dead", "MORT")
language.Add("npcpassengers.status.calm.desc", "Détendu, aucune menace proche")
language.Add("npcpassengers.status.alert.desc", "Ennemi détecté, NPC suivant les menaces")
language.Add("npcpassengers.status.scared.desc", "Conduite dangereuse (haute vitesse, accidents)")
language.Add("npcpassengers.status.drowsy.desc", "Long voyage calme, NPC devient somnolent")
language.Add("npcpassengers.status.dead.desc", "Santé atteint zéro")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Rejoindre Auto : ON")
language.Add("npcpassengers.chat.autojoin_off", "Rejoindre Auto : OFF")
language.Add("npcpassengers.chat.hud_on", "HUD : ON")
language.Add("npcpassengers.chat.hud_off", "HUD : OFF")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Aucun véhicule proche")
language.Add("npcpassengers.error.no_npc", "Aucun NPC proche")
language.Add("npcpassengers.error.vehicle_full", "Véhicule plein")
language.Add("npcpassengers.error.too_far", "NPC trop loin du véhicule")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Changer de langue")
language.Add("npcpassengers.tooltip.minimize", "Minimiser le panneau")
language.Add("npcpassengers.tooltip.expand", "Développer le panneau")
language.Add("npcpassengers.tooltip.welcome", "Afficher l'écran de bienvenue")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Interrupteur principal pour toute la voix NPC. Désactivez pour rendre les passagers complètement silencieux.")
language.Add("npcpassengers.speech_volume.help", "À quel point les NPC parlent fort (0 = silencieux, 100 = volume complet).")
language.Add("npcpassengers.pitch_variation.help", "Variation aléatoire de ton pour des voix plus naturelles. 0 = monotone, plus haut = plus de variété.")
language.Add("npcpassengers.crash_enable.help", "Les NPC gémissent/crient lorsque le véhicule décélère brusquement (accidents, freinage brusque).")
language.Add("npcpassengers.crash_threshold.help", "Décélération nécessaire pour déclencher les sons d'accident. Plus bas = plus sensible.")
language.Add("npcpassengers.crash_cooldown.help", "Secondes minimum entre les sons d'accident par NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "Les NPC parlent occasionnellement pendant le voyage : commentaires, questions, observations.")
language.Add("npcpassengers.speech_idle_chance.help", "Probabilité de bavardage par vérification. 0 = jamais, 1 = essaie toujours de parler.")
language.Add("npcpassengers.speech_idle_interval.help", "Secondes minimum entre les tentatives de bavardage.")
language.Add("npcpassengers.speech_board.help", "Les NPC parlent lorsqu'ils entrent et sortent du véhicule.")
language.Add("npcpassengers.ambient_sounds.help", "Toux occasionnelles, soupirs, murmures : sons de vie de fond.")
language.Add("npcpassengers.ambient_interval.help", "Secondes moyennes entre les sons ambiants.")
language.Add("npcpassengers.animation.help", "Ajustement fin des animations NPC et du mouvement de tête.")
language.Add("npcpassengers.head_look.help", "Les NPC regardent naturellement autour, le joueur, par les fenêtres, etc.")
language.Add("npcpassengers.head_smooth.help", "À quel point la tête bouge fluidement. Plus bas = plus rapide, plus haut = plus flottant.")
language.Add("npcpassengers.blink.help", "Les NPC clignent des yeux de manière réaliste pendant qu'ils sont assis.")
language.Add("npcpassengers.breathing.help", "Animation de respiration subtile sur les têtes des NPC.")
language.Add("npcpassengers.walk_timeout.help", "Secondes avant que le NPC n'abandonne la marche vers le véhicule.")
language.Add("npcpassengers.realism.help", "Réactions basées sur la physique et systèmes de conscience pour une immersion maximale.")
language.Add("npcpassengers.talking_gestures.help", "Les NPC jouent aléatoirement des gestes avec les mains et des animations corporelles pendant le voyage.")
language.Add("npcpassengers.gesture_chance.help", "Pourcentage de probabilité de jouer un geste chaque intervalle.")
language.Add("npcpassengers.gesture_interval.help", "Secondes entre les vérifications d'opportunité de gestes.")
language.Add("npcpassengers.crash_flinch.help", "Les NPC sursautent et se penchent vers l'avant lorsque le véhicule s'écrase ou freine brusquement.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Changement de vitesse nécessaire pour déclencher le sursaut (plus bas = plus sensible).")
language.Add("npcpassengers.body_sway.help", "Les NPC s'inclinent dans les virages, s'appuient pendant l'accélération/freinage.")
language.Add("npcpassengers.body_sway_amount.help", "À quel point les NPC se balancent avec le mouvement du véhicule.")
language.Add("npcpassengers.threat_awareness.help", "Les NPC regardent automatiquement vers les ennemis proches.")
language.Add("npcpassengers.threat_range.help", "À quelle distance les NPC peuvent détecter les menaces pour le suivi de tête.")
language.Add("npcpassengers.combat_alert.help", "Les NPC deviennent tendus et réactifs lorsque les ennemis sont proches.")
language.Add("npcpassengers.passenger_combat.help", "Désactivé par défaut. Activez ceci pour permettre aux passagers armés de tirer depuis l'intérieur du véhicule.")
language.Add("npcpassengers.passenger_combat_range.help", "À quelle distance les passagers armés peuvent acquérir des cibles.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Des valeurs plus élevées resserrent la dispersion des tir pour les passagers armés.")
language.Add("npcpassengers.passenger_combat_damage.help", "Met à l'échelle les dégâts infligés par les tirs de passagers.")
language.Add("npcpassengers.passenger_interaction.help", "Plusieurs passagers se regardent et bavardent occasionnellement entre eux.")
language.Add("npcpassengers.fear_reactions.help", "Les NPC ont peur de la conduite dangereuse : yeux écarquillés, sons de panique.")
language.Add("npcpassengers.fear_speed_threshold.help", "Vitesse (unités/sec) à laquelle les NPC commencent à être nerveux.")
language.Add("npcpassengers.drowsiness.help", "Les NPC deviennent somnolents sur les longs voyages calmes : clignements lents, hochements de tête.")
language.Add("npcpassengers.drowsy_time.help", "Secondes de voyage calme avant que la somnolence ne commence.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Paramètres pour les chars, APC et véhicules LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Rend les passagers NPC invisibles lorsqu'ils sont à l'intérieur des chars et APC.")
language.Add("npcpassengers.eject_stuck_check.help", "Expulse automatiquement les NPC du véhicule lorsqu'ils sont coincés pendant l'éjection. Empêche les NPC de se mettre dans le véhicule en sortant.")
language.Add("npcpassengers.detach_no_collide.help", "Après le détachement, les NPC passent temporairement à travers le véhicule pour qu'ils puissent s'éloigner sans clipping ou coincement.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Combien de temps les NPC ignorent la collision du véhicule après le détachement.")
language.Add("npcpassengers.die_with_vehicle.help", "Les passagers NPC meurent lorsque leur véhicule est détruit par explosion ou incendie (plus immersif que s'ils sortaient indemnes des décombres).")
language.Add("npcpassengers.tank_driver.help", "Permet aux NPC sur le siège conducteur de conduire automatiquement vers les ennemis.")
language.Add("npcpassengers.tank_driver_range.help", "Portée maximale pour que le conducteur détecte les ennemis.")
language.Add("npcpassengers.tank_driver_distance.help", "Distance à maintenir des ennemis.")
language.Add("npcpassengers.tank_driver_throttle.help", "Quantité d'accélérateur (0.1 = lent, 1 = vitesse complète).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distance à laquelle reculer des ennemis.")
language.Add("npcpassengers.tank_turret.help", "Permet aux NPC de contrôler les tourelles sur les véhicules LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Affiche l'état des passagers (émotions, alerte) sur l'écran pendant la conduite.")
language.Add("npcpassengers.hud_show_calm.help", "Lorsque désactivé, affiche uniquement les passagers avec un état non calme.")
language.Add("npcpassengers.hud_thresholds.desc", "Lorsque les niveaux d'émotion dépassent ces seuils, les passagers affichent cet état dans le HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Niveau d'alerte nécessaire pour afficher l'état 'ALERTE' (menace détectée).")
language.Add("npcpassengers.hud_fear_threshold.help", "Niveau de peur nécessaire pour afficher l'état 'PEUR' (conduite dangereuse).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Ratio de temps calme nécessaire pour afficher l'état 'SOMNOLENCE' (long voyage calme).")
language.Add("npcpassengers.hud_actions.desc", "Choisissez quelle action prennent les passagers lorsqu'ils éprouvent chaque état émotionnel.")
language.Add("npcpassengers.hud_actions_note", "Note : Certaines actions peuvent ne pas être visibles selon le support du modèle NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Définissez des raccourcis personnalisés pour les actions de passagers NPC. Cliquez sur un bouton et appuyez sur une touche pour lier.")
language.Add("npcpassengers.keybinds_hud.desc", "Contrôles rapides HUD pour afficher, déplacer et déboguer la superposition des passagers.")
language.Add("npcpassengers.keybinds_debug_note", "Les raccourcis de débogage ne fonctionnent que lorsque le mode débogage est activé.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Outils de débogage avancés pour tester le comportement NPC. Activez d'abord le mode débogage dans les paramètres.")
language.Add("npcpassengers.debug_mode.help", "Affiche les boutons de test de débogage et active les commandes de débogage.")
language.Add("npcpassengers.debug_status.help", "Définissez manuellement l'état du passager pour les tests. Cliquez sur 'Actualiser la liste' pour voir les passagers actuels.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configurez les effets sonores pour les boutons, cases à cocher et autres éléments UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Interrupteur principal pour tous les effets sonores UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Multiplicateur de volume pour les sons UI (1.0 = normal, 2.0 = double)")
language.Add("npcpassengers.ui_hover_enabled.help", "Jouer un son lors du survol des boutons")
language.Add("npcpassengers.ui_click_enabled.help", "Jouer un son lors du clic sur les boutons et cases à cocher")
language.Add("npcpassengers.context_menu.desc", "Choisissez quelles options apparaissent lors du clic droit sur les NPC")
language.Add("npcpassengers.context_make_passenger.help", "Ajouter un NPC comme passager à votre véhicule actuel")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Ajouter un NPC à un véhicule spécifique (cliquez sur NPC, puis véhicule)")
language.Add("npcpassengers.context_detach.help", "Supprimer le NPC du véhicule")
language.Add("npcpassengers.ui_show_welcome.help", "Afficher le panneau de bienvenue lorsque l'addon est mis à jour vers une nouvelle version")
language.Add("npcpassengers.ui_panel_width.help", "Largeur du panneau de paramètres")
language.Add("npcpassengers.ui_panel_height.help", "Hauteur du panneau de paramètres")
language.Add("npcpassengers.ui_animations.help", "Transitions fluides et effets de survol (peut affecter les performances)")
language.Add("npcpassengers.ui_tooltips.help", "Afficher des infobulles utiles lors du survol des paramètres")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Afficher la barre de défilement uniquement pendant que vous faites défiler ou la survolez.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Note : Le panneau devient 70% transparent lors du glissement de n'importe quel curseur pour voir le contenu en arrière-plan.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Des valeurs plus basses = plus fluide mais plus lent le défilement (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Choisissez un thème de couleur pour le panneau de paramètres. Les changements s'appliquent immédiatement.")
language.Add("npcpassengers.ui_font_scale.help", "Mettre à l'échelle toutes les tailles de police UI. 1.0 = par défaut, 0.5 = demi-taille, 2.0 = double taille.")

print("[Better NPC Passengers] French localization loaded!")
