-- Better NPC Passengers - German Localization
-- Deutsche Übersetzung

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Einstellungen")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Allgemein")
language.Add("npcpassengers.nav.autojoin", "Auto-Beitreten")
language.Add("npcpassengers.nav.passengers", "Passagiere")
language.Add("npcpassengers.nav.position", "Position")
language.Add("npcpassengers.nav.behaviour", "Verhalten")
language.Add("npcpassengers.nav.keybinds", "Tastenbelegung")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Fahrer")
language.Add("npcpassengers.nav.help", "Hilfe")

-- General Settings
language.Add("npcpassengers.general.header", "Allgemeine Einstellungen")
language.Add("npcpassengers.allow_multiple", "Mehrere Passagiere zulassen")
language.Add("npcpassengers.allow_multiple.help", "Ermöglicht mehreren NPCs, im selben Fahrzeug zu reisen.")
language.Add("npcpassengers.exit_behavior", "Ausstiegsverhalten")
language.Add("npcpassengers.exit_behavior.help", "Wann sollen NPC-Passagiere das Fahrzeug verlassen?")
language.Add("npcpassengers.exit_mode.leave_player", "Verlassen, wenn Spieler aussteigt")
language.Add("npcpassengers.exit_mode.leave_attack", "Verlassen, wenn Fahrzeug angegriffen wird")
language.Add("npcpassengers.exit_mode.never", "Niemals automatisch verlassen")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Zeiteinstellungen")
language.Add("npcpassengers.max_attach_dist", "Maximale Einsteigedistanz")
language.Add("npcpassengers.max_attach_dist.help", "Maximale Distanz (Einheiten) für den Eintritt eines NPCs in das Fahrzeug.")
language.Add("npcpassengers.detach_delay", "Ausstiegsverzögerung")
language.Add("npcpassengers.detach_delay.help", "Sekunden Wartezeit bevor der NPC aussteigt, nachdem der Spieler das Fahrzeug verlassen hat.")
language.Add("npcpassengers.ai_delay", "KI-Wiederherstellungsverzögerung")
language.Add("npcpassengers.ai_delay.help", "Sekunden Wartezeit vor der Wiederherstellung der NPC-KI nach dem Ausstieg.")
language.Add("npcpassengers.cooldown", "Abklingzeit")
language.Add("npcpassengers.cooldown.help", "Abklingzeit zwischen NPC-Einstiegen in dasselbe Fahrzeug.")
language.Add("npcpassengers.passenger_limit", "Passagierlimit")
language.Add("npcpassengers.passenger_limit.help", "Maximum an NPCs im Fahrzeug.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Auto-Beitreten (Truppenverhalten)")
language.Add("npcpassengers.autojoin.desc", "Freundliche NPCs treten automatisch Ihrem Fahrzeug bei, wenn Sie einsteigen – wie die Truppenmechanik in Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Auto-Beitreten aktivieren")
language.Add("npcpassengers.autojoin.enable.help", "Freundliche NPCs in der Nähe treten automatisch bei, wenn Sie in ein Fahrzeug einsteigen.")
language.Add("npcpassengers.autojoin.range", "Auto-Beitreten-Reichweite")
language.Add("npcpassengers.autojoin.range.help", "Maximale Distanz zur Suche nach NPCs für Auto-Beitreten.")
language.Add("npcpassengers.autojoin.max", "Max NPCs für Auto-Beitreten")
language.Add("npcpassengers.autojoin.max.help", "Maximale Anzahl an NPCs, die automatisch gleichzeitig beitreten können.")
language.Add("npcpassengers.autojoin.squad_only", "Nur Truppenmitglieder")
language.Add("npcpassengers.autojoin.squad_only.help", "Nur NPCs mit Truppennamen treten automatisch bei (für HL2-Stil Truppen).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Freundliche NPCs treten automatisch Ihrem Fahrzeug bei, wenn Sie einsteigen – wie die Truppenmechanik in Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Passagierverwaltung")
language.Add("npcpassengers.panel.passengers.desc", "Verwalten Sie aktive Passagiere, filtern Sie nach Name/Klasse/Status, kopieren Sie Debug-Informationen, weisen Sie Sitze neu und lassen Sie Passagiere aussteigen, ohne das Einstellungsmenü zu verlassen.")
language.Add("npcpassengers.panel.position.desc", "Feinabstimmung der NPC-Position im Fahrzeug. Verwenden Sie dies, um Schweb- oder Clipping-Probleme zu beheben.")
language.Add("npcpassengers.panel.angle.desc", "Anpassung der NPC-Drehung im Fahrzeug.")
language.Add("npcpassengers.panel.speech.desc", "Konfigurieren Sie, wie NPCs während der Fahrt im Fahrzeug vocalisieren. Bürgerstimmen im HL2-Stil!")

-- Position Settings
language.Add("npcpassengers.position.header", "Positionsversätze")
language.Add("npcpassengers.position.desc", "Feinabstimmung der NPC-Position im Fahrzeug. Verwenden Sie dies, um Schweb- oder Clipping-Probleme zu beheben.")
language.Add("npcpassengers.height_offset", "Höhenversatz")
language.Add("npcpassengers.forward_offset", "Vorwärtsversatz")
language.Add("npcpassengers.right_offset", "Rechter Versatz")
language.Add("npcpassengers.angle.header", "Winkelversätze")
language.Add("npcpassengers.angle.desc", "Anpassung der NPC-Drehung im Fahrzeug.")
language.Add("npcpassengers.yaw_offset", "Gier (Drehung)")
language.Add("npcpassengers.pitch_offset", "Nick (Vorwärtsneigung)")
language.Add("npcpassengers.roll_offset", "Roll (Seitwärtsneigung)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPC-Sprache (Erweitert)")
language.Add("npcpassengers.behaviour.desc", "Konfigurieren Sie, wie NPCs während der Fahrt im Fahrzeug vocalisieren. Bürgerstimmen im HL2-Stil!")
language.Add("npcpassengers.speech_enable", "NPC-Sprache aktivieren")
language.Add("npcpassengers.speech_enable.help", "Hauptschalter für die gesamte NPC-Sprache. Deaktivieren Sie dies, um Passagiere vollständig stumm zu schalten.")
language.Add("npcpassengers.speech_volume", "Sprachlautstärke")
language.Add("npcpassengers.speech_volume.help", "Wie laut NPCs sprechen (0 = stumm, 100 = volle Lautstärke).")
language.Add("npcpassengers.pitch_variation", "Tonhöhenvariation (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Zufällige Tonhöhenvariation für natürlichere Stimmen. 0 = monoton, höher = mehr Vielfalt.")
language.Add("npcpassengers.crash.header", "Unfallreaktionen")
language.Add("npcpassengers.crash_enable", "Unfallgeräusche aktivieren")
language.Add("npcpassengers.crash_enable.help", "NPCs stöhnen/schreien, wenn das Fahrzeug stark abgebremst wird (Unfälle, scharfes Bremsen).")
language.Add("npcpassengers.crash_threshold", "Unfallempfindlichkeit")
language.Add("npcpassengers.crash_threshold.help", "Verzögerung, die erforderlich ist, um Unfallgeräusche auszulösen. Niedriger = empfindlicher.")
language.Add("npcpassengers.crash_cooldown", "Unfallgeräusche-Abklingzeit")
language.Add("npcpassengers.crash_cooldown.help", "Minimale Sekunden zwischen Unfallgeräuschen pro NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Plaudern aktivieren")
language.Add("npcpassengers.speech_board", "Ein-/Ausstiegsgeräusche aktivieren")
language.Add("npcpassengers.ambient_sounds", "Umgebungsgeräusche aktivieren")
language.Add("npcpassengers.head_look", "Kopf-/Augenblick aktivieren")
language.Add("npcpassengers.blink", "Blinzeln aktivieren")
language.Add("npcpassengers.breathing", "Atmung aktivieren")
language.Add("npcpassengers.talking_gestures", "Sprechgesten aktivieren")
language.Add("npcpassengers.crash_flinch", "Unfallzucken aktivieren")
language.Add("npcpassengers.body_sway", "Körperschwanken aktivieren")
language.Add("npcpassengers.threat_awareness", "Bedrohungsbewusstsein aktivieren")
language.Add("npcpassengers.combat_alert", "Kampfbereitschaft")
language.Add("npcpassengers.passenger_combat", "NPCs schießen aus Fahrzeug (Experimentell)")
language.Add("npcpassengers.passenger_interaction", "Passagierinteraktion")
language.Add("npcpassengers.fear_reactions", "Angstreaktionen aktivieren")
language.Add("npcpassengers.drowsiness", "Schläfrigkeit aktivieren")
language.Add("npcpassengers.hide_in_tanks", "NPCs in geschlossenen Fahrzeugen verstecken")
language.Add("npcpassengers.eject_stuck_check", "Automatisches Ausstoßen festsitzender NPCs")
language.Add("npcpassengers.detach_no_collide", "Keine Kollision mit Fahrzeug nach Ausstieg")
language.Add("npcpassengers.die_with_vehicle", "Passagiere bei Fahrzeugexplosion töten")
language.Add("npcpassengers.driver_enabled", "Autofahren aktivieren")
language.Add("npcpassengers.turret_enabled", "Turmsteuerung aktivieren")
language.Add("npcpassengers.turret_lead_targets", "Ziele vorwegnehmen")
language.Add("npcpassengers.turret_friendly_fire", "Freundlichen Feuer zulassen")
language.Add("npcpassengers.turret_hold_fire", "Feuer halten (Schießen deaktivieren)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Sprachlautstärke")
language.Add("npcpassengers.pitch_variation", "Tonhöhenvariation (+/-)")
language.Add("npcpassengers.crash_threshold", "Unfallempfindlichkeit")
language.Add("npcpassengers.crash_cooldown", "Unfallgeräusche-Abklingzeit")
language.Add("npcpassengers.speech_idle_chance", "Plauderwahrscheinlichkeit")
language.Add("npcpassengers.speech_idle_interval", "Plauderintervall")
language.Add("npcpassengers.ambient_interval", "Umgebungsgeräuschintervall")
language.Add("npcpassengers.head_smooth", "Kopfglättung")
language.Add("npcpassengers.walk_timeout", "Gehzeitüberschreitung")
language.Add("npcpassengers.gesture_chance", "Gestenwahrscheinlichkeit (%)")
language.Add("npcpassengers.gesture_interval", "Gestenintervall")
language.Add("npcpassengers.crash_threshold_flinch", "Unfallempfindlichkeit")
language.Add("npcpassengers.body_sway_amount", "Schwankintensität")
language.Add("npcpassengers.threat_range", "Bedrohungserkennungsreichweite")
language.Add("npcpassengers.passenger_combat_range", "Passagierkampfreichweite")
language.Add("npcpassengers.passenger_combat_accuracy", "Passagiergenauigkeit")
language.Add("npcpassengers.passenger_combat_damage", "Passagierschadensmultiplikator")
language.Add("npcpassengers.fear_speed_threshold", "Angstgeschwindigkeitsschwellenwert")
language.Add("npcpassengers.drowsy_time", "Schläfrigkeitszeit")
language.Add("npcpassengers.detach_no_collide_duration", "Dauer ohne Kollision (Sekunden)")
language.Add("npcpassengers.tank_driver_range", "Erkennungsreichweite")
language.Add("npcpassengers.tank_driver_engage_distance", "Eingriffsdistanz")
language.Add("npcpassengers.tank_driver_speed", "Fahrgeschwindigkeit")
language.Add("npcpassengers.tank_driver_reverse_distance", "Rückwärtsdistanz")
language.Add("npcpassengers.turret_range", "Zielreichweite")
language.Add("npcpassengers.turret_accuracy", "Genauigkeit")
language.Add("npcpassengers.turret_reaction_time", "Reaktionszeit")
language.Add("npcpassengers.turret_fire_delay", "Feuerverzögerung")
language.Add("npcpassengers.turret_aim_speed", "Zielgeschwindigkeit")
language.Add("npcpassengers.hud_scale", "HUD-Skalierung")
language.Add("npcpassengers.hud_opacity", "HUD-Transparenz")
language.Add("npcpassengers.hud_alert_threshold", "Alarmschwelle")
language.Add("npcpassengers.hud_fear_threshold", "Angstschwelle")
language.Add("npcpassengers.hud_drowsy_threshold", "Schläfrigkeitsschwelle")
language.Add("npcpassengers.ui_sounds_volume", "UI-Geräuschlautstärke")
language.Add("npcpassengers.ui_panel_width", "Panelbreite")

-- Section headers
language.Add("npcpassengers.section.animation", "Animation und Verhalten")
language.Add("npcpassengers.section.realism", "Erweiterter Realismus")
language.Add("npcpassengers.section.hud_position", "HUD-Position und -stil")
language.Add("npcpassengers.section.emotion_thresholds", "Emotionsschwellenwerte")
language.Add("npcpassengers.section.emotion_actions", "Emotionsaktionen")
language.Add("npcpassengers.section.vehicle_control", "Fahrzeugsteuerung")
language.Add("npcpassengers.section.hud_controls", "HUD-Steuerelemente")
language.Add("npcpassengers.section.debug_controls", "Debug-Steuerelemente")
language.Add("npcpassengers.section.passenger_status", "Passagierstatusverwaltung")
language.Add("npcpassengers.section.quick_test", "Schnelltest-Buttons")
language.Add("npcpassengers.section.driver_system", "NPC-Fahrersystem")
language.Add("npcpassengers.section.ui_sounds", "UI-Geräuscheinstellungen")
language.Add("npcpassengers.section.appearance", "Erscheinungsbild")
language.Add("npcpassengers.section.context_menu", "Kontextmenüoptionen")
language.Add("npcpassengers.section.panel_preferences", "Panel-Einstellungsvorlieben")
language.Add("npcpassengers.section.performance", "Leistung und Technik")
language.Add("npcpassengers.section.simulation", "Simulationssystem")
language.Add("npcpassengers.section.modules", "Modulsystem")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Sitz zuweisen")
language.Add("npcpassengers.btn.detach", "Trennen")
language.Add("npcpassengers.btn.copy_summary", "Zusammenfassung kopieren")
language.Add("npcpassengers.btn.copy_debug", "Debug kopieren")
language.Add("npcpassengers.btn.enable_all_speech", "Alle Sprache aktivieren")
language.Add("npcpassengers.btn.disable_all_speech", "Alle Sprache deaktivieren")
language.Add("npcpassengers.btn.show_current_vehicle", "Nur aktuelles Fahrzeug anzeigen")
language.Add("npcpassengers.btn.auto_refresh", "Automatische Aktualisierung der sichtbaren Liste")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Aktuelles Fahrzeug nicht erkannt. Steigen Sie in ein Fahrzeug ein oder deaktivieren Sie den aktuellen Fahrzeugfilter.")
language.Add("npcpassengers.status.no_match_filter", "Passagiere entsprechen nicht Ihrem Filter. Versuchen Sie Name, Klasse, Sitznummer, Status oder Fahrzeugklasse.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Keine Passagiere in Ihrem aktuellen Fahrzeug gefunden.")
language.Add("npcpassengers.status.no_passengers", "Keine Passagiere gefunden. NPCs müssen in einem Fahrzeug sein, bevor sie hier verwaltet werden können.")
language.Add("npcpassengers.status.all_passengers", "Alle Passagiere")
language.Add("npcpassengers.status.current_vehicle_only", "Nur aktuelles Fahrzeug")
language.Add("npcpassengers.status.ctrl_f_search", "Strg+F für Suchfokus")
language.Add("npcpassengers.status.no_matches", "Keine übereinstimmenden Einstellungen")
language.Add("npcpassengers.status.showing_matches", "Zeige %d von %d Übereinstimmungen")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Einstellungen öffnen")
language.Add("npcpassengers.menu.reset_all", "Alle Einstellungen zurücksetzen")

-- Button states
language.Add("npcpassengers.state.on", "AN")
language.Add("npcpassengers.state.off", "AUS")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Auto-Beitreten")
language.Add("npcpassengers.chat.hud_status", "Passagier-HUD")
language.Add("npcpassengers.chat.hud_position", "HUD-Position")
language.Add("npcpassengers.chat.target_debug", "Ziel-Debug")
language.Add("npcpassengers.chat.turret_gunners", "Turmschützen")
language.Add("npcpassengers.chat.turret_holding", "FEUER HALTEN")
language.Add("npcpassengers.chat.turret_fire", "FEUER ÖFFNEN")
language.Add("npcpassengers.chat.unknown", "Unbekannt")
language.Add("npcpassengers.chat.nothing_copy", "Nichts zu kopieren.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Zugriff auf Zwischenablage in dieser Version nicht verfügbar.")
language.Add("npcpassengers.chat.copied_clipboard", "In Zwischenablage kopiert.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Setzen Sie sich in dasselbe Fahrzeug, um diesen Passagier neu zuzuweisen.")
language.Add("npcpassengers.chat.no_visible_passengers", "Keine sichtbaren Passagiere zum Kopieren.")
language.Add("npcpassengers.chat.need_vehicle", "Sie müssen in einem Fahrzeug sein, um dies zu verwenden.")
language.Add("npcpassengers.chat.keybinds_applied", "Empfohlene Tastenbelegungen angewendet.")
language.Add("npcpassengers.chat.keybinds_cleared", "Alle Tastenbelegungen gelöscht.")
language.Add("npcpassengers.chat.context_enabled", "Alle Kontextmenüoptionen aktiviert.")
language.Add("npcpassengers.chat.context_hidden", "Alle Kontextmenüoptionen ausgeblendet.")
language.Add("npcpassengers.chat.panel_compact", "Panelgröße auf kompakt gesetzt.")
language.Add("npcpassengers.chat.panel_default", "Panelgröße auf Standard gesetzt.")
language.Add("npcpassengers.chat.panel_large", "Panelgröße auf groß gesetzt.")
language.Add("npcpassengers.chat.panel_centered", "Panel zentriert.")
language.Add("npcpassengers.chat.settings_reset", "Alle UI-Einstellungen auf Standardwerte zurückgesetzt!")
language.Add("npcpassengers.chat.npc_selected", "NPC ausgewählt! Klicken Sie nun mit der rechten Maustaste auf das Fahrzeug und wählen Sie 'Ausgewählten NPC hinzufügen'")
language.Add("npcpassengers.chat.adding_npc", "Füge NPC zum Fahrzeug hinzu...")
language.Add("npcpassengers.chat.selection_cancelled", "NPC-Auswahl abgebrochen")
language.Add("npcpassengers.chat.summary_copied", "Passagierzusammenfassung kopiert.")
language.Add("npcpassengers.chat.debug_copied", "Passagier-Debug-Informationen kopiert.")
language.Add("npcpassengers.chat.no_passengers_found", "Keine Passagiere gefunden. NPCs müssen in einem Fahrzeug sein.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Statusintensität %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Passagiere filtern...")
language.Add("npcpassengers.ui.press_key", "Taste drücken...")
language.Add("npcpassengers.ui.work_in_progress", "In Entwicklung")
language.Add("npcpassengers.ui.under_development", "Diese Funktion ist in Entwicklung")
language.Add("npcpassengers.ui.check_back_later", "Überprüfen Sie in einem zukünftigen Update!")
language.Add("npcpassengers.ui.search_desc_passengers", "Aktive Passagiere nach Name, Klasse, Sitz, Status oder Fahrzeug filtern.")
language.Add("npcpassengers.ui.search_desc_sort", "Sichtbare Passagierliste nach Fahrzeug, Name, Sitz, Gesundheit oder Status sortieren.")
language.Add("npcpassengers.ui.search_label_filter", "Passagierfilter")
language.Add("npcpassengers.ui.search_label_sort", "Passagiersortierung")

-- Additional keybind names and descriptions
language.Add("npcpassengers.keybind.quick_attach", "Schnelles Einsteigen")
language.Add("npcpassengers.keybind.hold_fire", "NPCs halten Feuer")
language.Add("npcpassengers.keybind.open_fire", "NPCs öffnen Feuer")
language.Add("npcpassengers.keybind.cycle_view", "Passagierkamera-Zyklus")
language.Add("npcpassengers.keybind.cycle_hud_position", "HUD-Position-Zyklus")
language.Add("npcpassengers.keybind.toggle_debug", "Ziel-Debug umschalten")
language.Add("npcpassengers.keybind.test_gesture", "Zufällige Geste testen")
language.Add("npcpassengers.keybind.reset_all", "Alle NPCs zurücksetzen")
language.Add("npcpassengers.keybind.quick_attach.help", "Halten Sie gedrückt, um NPCs, die Sie ansehen, schnell einsteigen zu lassen")
language.Add("npcpassengers.keybind.hold_fire.help", "Sagen Sie den Turmschützen-NPCs, das Schießen zu stoppen")
language.Add("npcpassengers.keybind.open_fire.help", "Sagen Sie den Turmschützen-NPCs, Ziele anzugreifen")
language.Add("npcpassengers.keybind.cycle_view.help", "Kamera zyklisch zwischen Passagieren wechseln")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Passagier-HUD durch alle vier Ecken bewegen")
language.Add("npcpassengers.keybind.toggle_debug.help", "Kleine Ziel-Debug-Überlagerung umschalten")
language.Add("npcpassengers.keybind.test_gesture.help", "Zufällige Geste auf dem nächsten Passagier abspielen")
language.Add("npcpassengers.keybind.reset_all.help", "Animationszustände für alle Passagiere zurücksetzen")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Wie füge ich einen NPC zu meinem Fahrzeug hinzu?")
language.Add("npcpassengers.faq.add_npc.answer", "Verwenden Sie das Kontextmenü (Rechtsklick auf NPC) und wählen Sie 'Zum Passagier machen'. Oder verwenden Sie die Tastenbelegung 'Nächsten NPC einsteigen lassen'. NPCs müssen freundlich zu Ihnen sein.")
language.Add("npcpassengers.faq.remove_npc", "Wie entferne ich Passagiere aus meinem Fahrzeug?")
language.Add("npcpassengers.faq.remove_npc.answer", "Gehen Sie zur Registerkarte Passagiere in den Einstellungen, wählen Sie einen Passagier aus und klicken Sie auf Trennen. Oder verwenden Sie die Tastenbelegung 'Alle NPCs trennen'.")
language.Add("npcpassengers.faq.position", "NPCs schweben oder gehen durch Sitze!")
language.Add("npcpassengers.faq.position.answer", "Gehen Sie zur Registerkarte Position und passen Sie die Höhen-/Vorwärts-/Rechtsversätze an. Jedes Fahrzeugmodell ist unterschiedlich, daher müssen Sie die Werte möglicherweise präzise anpassen. Verwenden Sie das Debug-Panel, um Positionen in Echtzeit zu testen.")
language.Add("npcpassengers.faq.speech", "NPCs sprechen nicht!")
language.Add("npcpassengers.faq.speech.answer", "Überprüfen Sie die Registerkarte Verhalten und stellen Sie sicher, dass 'NPC-Sprache aktivieren' aktiviert ist. Stellen Sie auch sicher, dass die Sprachlautstärke über 0 liegt. Einige NPC-Modelle haben möglicherweise keine verfügbaren Sprachzeilen.")
language.Add("npcpassengers.faq.autojoin", "Wie funktioniert Auto-Beitreten?")
language.Add("npcpassengers.faq.autojoin.answer", "Wenn es auf der Registerkarte Auto-Beitreten aktiviert ist, treten freundliche NPCs in der Nähe automatisch Ihrem Fahrzeug bei, wenn Sie einsteigen – wie die Truppenmechanik in Half-Life 2. Sie können den Erkennungsbereich festlegen und begrenzen, wie viele NPCs automatisch beitreten können.")
language.Add("npcpassengers.faq.death", "Was passiert, wenn Passagiere sterben?")
language.Add("npcpassengers.faq.death.answer", "Tote Passagiere zeigen einen roten Leuchteffekt und einen Totenkopf auf dem HUD. Nähern Sie sich Ihrem Fahrzeug und halten Sie R, um ihre Körper zu entfernen. Die Körper werden mit Physik ausgestoßen.")
language.Add("npcpassengers.faq.status", "Was bedeuten die Passagierstatus?")
language.Add("npcpassengers.faq.status.answer", "RUHIG: Entspannt, keine Bedrohungen in der Nähe. ALARM: Feind erkannt. ANGST: Gefährliches Fahren. SCHLÄFRIG: Lange ruhige Fahrt. TOT: Gesundheit erreicht Null.")
language.Add("npcpassengers.faq.keybinds", "Meine Tastenbelegungen funktionieren nicht!")
language.Add("npcpassengers.faq.keybinds.answer", "Gehen Sie zur Registerkarte Tastenbelegung und stellen Sie sicher, dass Sie tatsächlich Tastenbelegungen festgelegt haben (standardmäßig sind sie nicht belegt). Klicken Sie auf die Taste neben jeder Aktion und drücken Sie die gewünschte Taste. Rechtsklick zum Aufheben.")
language.Add("npcpassengers.faq.errors", "Add-on funktioniert überhaupt nicht / Ich erhalte Fehler!")
language.Add("npcpassengers.faq.errors.answer", "Stellen Sie sicher, dass Sie die neueste Version von Garry's Mod verwenden. Überprüfen Sie die Konsole auf Fehler (Tildentaste ~). Versuchen Sie, konfliktierende Add-ons zu deaktivieren.")
language.Add("npcpassengers.faq.combat", "Können Passagiere aus dem Fahrzeug schießen?")
language.Add("npcpassengers.faq.combat.answer", "Derzeit nicht. NPCs werden Feinde verfolgen und auf Bedrohungen reagieren, aber nicht aus Waffen schießen, während sie sitzen. Diese Funktion könnte in zukünftigen Updates hinzugefügt werden.")
language.Add("npcpassengers.faq.stop_autojoin", "Wie verhindere ich, dass NPCs automatisch beitreten?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Deaktivieren Sie das Kontrollkästchen 'Auto-Beitreten aktivieren' auf der Registerkarte Auto-Beitreten oder verwenden Sie die Tastenbelegung 'Auto-Beitreten umschalten'.")
language.Add("npcpassengers.faq.settings", "Wo werden Einstellungen gespeichert?")
language.Add("npcpassengers.faq.settings.answer", "Alle Einstellungen werden als ConVars in Ihrer GMod-Konfiguration gespeichert. Sie bestehen zwischen Sitzungen und sind spezifisch für Ihren Client.")
language.Add("npcpassengers.faq.vehicles", "Funktioniert dies mit allen Fahrzeugen?")
language.Add("npcpassengers.faq.vehicles.answer", "Es funktioniert mit den meisten Fahrzeugen, die Physik haben. Panzer, APCs, Autos, Boote usw. Einige modded Fahrzeuge erfordern möglicherweise Positionsanpassungen.")
language.Add("npcpassengers.faq.multiple", "Kann ich mehrere NPCs in einem Fahrzeug haben?")
language.Add("npcpassengers.faq.multiple.answer", "Ja! Stellen Sie das 'Passagierlimit' in den allgemeinen Einstellungen ein. Das Add-on verteilt NPCs automatisch um das Fahrzeug. Für spezifische Sitzpositionen passen Sie die Versätze auf der Registerkarte Position an.")
language.Add("npcpassengers.faq.crashes", "NPCs verhalten sich seltsam nach Unfällen!")
language.Add("npcpassengers.faq.crashes.answer", "Dies ist normal – sie reagieren mit Angst auf gefährliches Fahren. Reduzieren Sie die Angstschwelle in den HUD-Einstellungen, wenn Sie möchten, dass sie weniger reaktiv sind.")
language.Add("npcpassengers.faq.reset_setting", "Wie setze ich nur eine Einstellung zurück?")
language.Add("npcpassengers.faq.reset_setting.answer", "Verwenden Sie den Konsolenbefehl für diese spezifische Einstellung. Alle Befehle beginnen mit 'nai_npc_'. Geben Sie 'find nai_npc' in der Konsole ein, um alle verfügbaren Befehle zu sehen.")
language.Add("npcpassengers.faq.multiplayer", "Funktioniert dies im Mehrspieler?")
language.Add("npcpassengers.faq.multiplayer.answer", "Ja! Das Add-on funktioniert sowohl auf Einzelspieler- als auch auf Mehrspielerservern. Jeder Spieler steuert seine eigenen Passagiere.")
language.Add("npcpassengers.faq.lvs", "Funktioniert dies mit LVS-Fahrzeugen?")
language.Add("npcpassengers.faq.lvs.answer", "Ja! Das Add-on hat vollständige Unterstützung für LVS-Fahrzeuge (Lua Vehicle System). NPCs können als Passagiere mitfahren und können sogar LVS-Fahrzeuge fahren, wenn der NPC-Fahrer-Modus aktiviert ist.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Diese Einstellungen steuern das Verhalten der Benutzeroberfläche des Add-ons")
language.Add("npcpassengers.panel.performance_note1", "Änderungen an der Panelgröße erfordern das Schließen und erneute Öffnen des Menüs")
language.Add("npcpassengers.panel.performance_note2", "Das Deaktivieren von Geräuschen oder Animationen kann die Leistung auf Low-End-Systemen verbessern")
language.Add("npcpassengers.panel.performance_title", "Informationen zu den Schnittstelleneinstellungen")
language.Add("npcpassengers.help.console_title", "Konsolenbefehle zum Debuggen:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Debug-Modus aktivieren, um detaillierte Informationen anzuzeigen")
language.Add("npcpassengers.about.title", "Über")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Sprache auf Englisch geändert. Panel wird automatisch aktualisiert.")
language.Add("npcpassengers.lang.changed_russian", "Sprache auf Russisch geändert. Panel wird automatisch aktualisiert.")
language.Add("npcpassengers.lang.changed_chinese", "Sprache auf Chinesisch geändert. Panel wird automatisch aktualisiert.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Hallo!")
language.Add("npcpassengers.welcome.msg1", "Bevor Sie sich über den Passagier beschweren, der auf dem Fahrzeug sitzt,\nbitte öffnen Sie die Einstellungen. Sie können es tun, ich glaube an Sie.")
language.Add("npcpassengers.welcome.msg2", "Dieses Add-on ist noch weit von PERFEKT entfernt, bitte zögern Sie nicht,\nBugs zu melden und neue Funktionen vorzuschlagen. Ich lese alle Ihre Kommentare!")
language.Add("npcpassengers.welcome.changelog", "Änderungsprotokoll")
language.Add("npcpassengers.welcome.got_it", "Verstanden!")
language.Add("npcpassengers.welcome.console_cmd", "Oder verwenden Sie den Konsolenbefehl: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "NPC-Klassen auf der Schwarzen Liste")
language.Add("npcpassengers.ui.blacklist_help", "Durch Kommas getrennte Liste von NPC-Klassennamen, die keine Türme verwenden können. Verwenden Sie den Konsolenbefehl 'getnpcblacklist', um die aktuelle Schwarze Liste anzuzeigen.")
language.Add("npcpassengers.ui.hud_position", "HUD-Position")
language.Add("npcpassengers.ui.not_bound", "Nicht belegt")
language.Add("npcpassengers.ui.keybind_tip", "Tipp: Rechtsklick auf eine Tastenbelegung zum Aufheben. Drücken Sie ESC während der Belegung zum Abbrechen.")
language.Add("npcpassengers.ui.dont_show_again", "Nicht mehr anzeigen")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Passagieroperationen")
language.Add("npcpassengers.hud.filter_prefix", "Filter: ")
language.Add("npcpassengers.hud.sort_prefix", "Sortierung: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Automatische Aktualisierung: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Fahrzeug: ")
language.Add("npcpassengers.hud.speed_prefix", "Geschwindigkeit: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "AN")
language.Add("npcpassengers.hud.off", "AUS")
language.Add("npcpassengers.hud.passengers", "Passagiere")
language.Add("npcpassengers.hud.npc_driver", "NPC-Fahrer")
language.Add("npcpassengers.hud.total_prefix", "Gesamt: ")
language.Add("npcpassengers.hud.showing_prefix", "Zeige: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Aktuelles Fahrzeug: ")
language.Add("npcpassengers.hud.hidden_prefix", "Ausgeblendet: ")
language.Add("npcpassengers.hud.dead_prefix", "Tot: ")
language.Add("npcpassengers.hud.scared_prefix", "Verängstigt: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Schläfrig: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Ruhig")
language.Add("npcpassengers.status.alert", "Alarm")
language.Add("npcpassengers.status.scared", "Verängstigt")
language.Add("npcpassengers.status.drowsy", "Schläfrig")
language.Add("npcpassengers.status.dead", "Tot")
language.Add("npcpassengers.status.unknown", "Unbekannt")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Bürger")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Pater Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dr. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Hund")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Fahrzeug")
language.Add("npcpassengers.sort.name", "Name")
language.Add("npcpassengers.sort.seat", "Sitz")
language.Add("npcpassengers.sort.health", "Gesundheit")
language.Add("npcpassengers.sort.status", "Status")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Fahrzeug zuerst")
language.Add("npcpassengers.sort.name_az", "Name A-Z")
language.Add("npcpassengers.sort.seat_number", "Sitznummer")
language.Add("npcpassengers.sort.highest_health", "Höchste Gesundheit")
language.Add("npcpassengers.sort.status_priority", "Statuspriorität")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Fahrzeug: Unbekannt")
language.Add("npcpassengers.ui.seat_prefix", "Sitz ")
language.Add("npcpassengers.ui.same_vehicle", "Gleiches Fahrzeug")
language.Add("npcpassengers.ui.other_vehicle", "Anderes Fahrzeug")
language.Add("npcpassengers.ui.hidden", "Ausgeblendet")
language.Add("npcpassengers.ui.visible", "Sichtbar")
language.Add("npcpassengers.ui.health_format", "Gesundheit %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Passagierliste aktualisieren")
language.Add("npcpassengers.ui.copy_list", "Sichtbare Passagierliste kopieren")
language.Add("npcpassengers.ui.make_exit", "Aktuelle Fahrzeugpassagiere aussteigen lassen")
language.Add("npcpassengers.ui.reset_pos", "Position und Winkel zurücksetzen")
language.Add("npcpassengers.ui.crash_reactions", "Unfallreaktionen")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Ein-/Ausstiegsgeräusche")
language.Add("npcpassengers.section.ambient_sounds", "Umgebungsgeräusche")
language.Add("npcpassengers.section.gesture_animations", "Gestenanimationen")
language.Add("npcpassengers.section.threat_awareness", "Bedrohungsbewusstsein")
language.Add("npcpassengers.section.emotional_states", "Emotionale Zustände")
language.Add("npcpassengers.section.turret_control", "Turmsteuerung (Experimentell)")
language.Add("npcpassengers.section.turret_blacklist", "NPC-Turm-Schwarze Liste")
language.Add("npcpassengers.section.idle_chatter", "Leerlauf-Plaudern")
language.Add("npcpassengers.section.body_physics", "Körperphysik")
language.Add("npcpassengers.section.npc_auto_driver", "NPC-Autofahrer")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Unten links")
language.Add("npcpassengers.hud.bottom_right", "Unten rechts")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Passagier-HUD aktivieren")
language.Add("npcpassengers.ui.cover_face", "Gesicht bedecken")
language.Add("npcpassengers.ui.apply_keybinds", "Empfohlene Tastenbelegungen anwenden")
language.Add("npcpassengers.ui.clear_keybinds", "Alle Tastenbelegungen löschen")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Zuck-Geste testen")
language.Add("npcpassengers.ui.test_random", "Zufällige Geste testen")
language.Add("npcpassengers.ui.reset_states", "Alle Zustände zurücksetzen")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Alle Kontextmenüoptionen aktivieren")
language.Add("npcpassengers.ui.hide_context", "Alle Kontextmenüoptionen ausblenden")
language.Add("npcpassengers.ui.set_compact", "Panelgröße auf kompakt setzen")
language.Add("npcpassengers.ui.set_default", "Panelgröße auf Standard setzen")
language.Add("npcpassengers.ui.set_large", "Panelgröße auf groß setzen")
language.Add("npcpassengers.ui.center_panel", "Panel jetzt zentrieren")
language.Add("npcpassengers.ui.reset_ui", "Alle UI-Einstellungen auf Standard zurücksetzen")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Bürger (W)")
language.Add("npcpassengers.role.citizen_male", "Bürger (M)")
language.Add("npcpassengers.role.medic", "Sanitäter")
language.Add("npcpassengers.role.rebel", "Rebell")
language.Add("npcpassengers.role.passenger", "Passagier")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Nur anzeigen, wenn im Fahrzeug")
language.Add("npcpassengers.hud.show_calm", "Ruhige Passagiere anzeigen")
language.Add("npcpassengers.hud.show_hints", "Kontexthinweise anzeigen")
language.Add("npcpassengers.hud.show_target_debug", "Ziel-Debug anzeigen")
language.Add("npcpassengers.hud.play_cues", "Erfolgs-/Fehlsignale abspielen")
language.Add("npcpassengers.debug.enable_mode", "Debug-Modus aktivieren")
language.Add("npcpassengers.ui.enable_sounds", "UI-Geräusche aktivieren")
language.Add("npcpassengers.ui.hover_sounds", "Button-Hover-Geräusche")
language.Add("npcpassengers.ui.click_sounds", "Button-Klick-Geräusche")
language.Add("npcpassengers.ui.enable_animations", "UI-Animationen aktivieren")
language.Add("npcpassengers.ui.show_tooltips", "Tooltips anzeigen")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Bildlaufleiste automatisch ausblenden")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Seitenleisten-Bildlaufglättung")
language.Add("npcpassengers.ui.color_theme", "Farbschema")
language.Add("npcpassengers.ui.font_scale", "Schriftskalierung")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "NPC-Auswahl abbrechen")
language.Add("npcpassengers.context.remove_passenger", "Passagier entfernen")
language.Add("npcpassengers.context.blacklist_passenger", "Zur Schwarzen Liste hinzufügen")
language.Add("npcpassengers.context.whitelist_passenger", "Zur Weißen Liste hinzufügen")
language.Add("npcpassengers.context.taxi_passenger", "Als Taxipassagier zuweisen")

-- Tool labels
language.Add("tool.npcpassengers_taxi_station.name", "Taxistation")
language.Add("tool.npcpassengers_taxi_station.desc", "Eine Taxistation für das NPC-Taxi-System erstellen")
language.Add("tool.npcpassengers_taxi_station.0", "Linksklick, um eine Taxistation zu platzieren. Rechtsklick zum Entfernen.")
language.Add("tool.npcpassengers_taxi_station.left", "Station platzieren")
language.Add("tool.npcpassengers_taxi_station.right", "Station entfernen")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Tastenbelegung")
language.Add("npcpassengers.keybinds.desc", "Konfigurieren Sie Tastaturkürzel für schnelle Aktionen.")
language.Add("npcpassengers.keybind.attach", "Nächsten NPC einsteigen lassen")
language.Add("npcpassengers.keybind.attach.help", "Den nächsten freundlichen NPC in Ihr Fahrzeug einsteigen lassen.")
language.Add("npcpassengers.keybind.detach_all", "Alle NPCs trennen")
language.Add("npcpassengers.keybind.detach_all.help", "Alle Passagiere aus Ihrem Fahrzeug entfernen.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Auto-Beitreten umschalten")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Auto-Beitreten schnell aktivieren/deaktivieren.")
language.Add("npcpassengers.keybind.menu", "Einstellungsmenü öffnen")
language.Add("npcpassengers.keybind.menu.help", "Einstellungspanel öffnen.")
language.Add("npcpassengers.keybind.exit_all", "Alle Passagiere aussteigen lassen")
language.Add("npcpassengers.keybind.exit_all.help", "Alle Passagiere das Fahrzeug verlassen lassen.")
language.Add("npcpassengers.keybind.toggle_hud", "HUD umschalten")
language.Add("npcpassengers.keybind.toggle_hud.help", "Passagier-HUD ein-/ausblenden.")
language.Add("npcpassengers.keybind.quick_attach", "Schnelles Einsteigen-Modus")
language.Add("npcpassengers.keybind.quick_attach.help", "Halten Sie gedrückt, um NPCs, die Sie ansehen, schnell einsteigen zu lassen")
language.Add("npcpassengers.keybind.hold_fire", "NPCs halten Feuer")
language.Add("npcpassengers.keybind.hold_fire.help", "Sagen Sie den Turmschützen-NPCs, das Schießen zu stoppen")
language.Add("npcpassengers.keybind.open_fire", "NPCs öffnen Feuer")
language.Add("npcpassengers.keybind.open_fire.help", "Sagen Sie den Turmschützen-NPCs, Ziele anzugreifen")
language.Add("npcpassengers.keybind.cycle_view", "Passagieransicht-Zyklus")
language.Add("npcpassengers.keybind.cycle_view.help", "Kamera zyklisch zwischen Passagieren wechseln")
language.Add("npcpassengers.keybind.cycle_hud_position", "HUD-Position-Zyklus")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Passagier-HUD durch alle vier Ecken bewegen")
language.Add("npcpassengers.keybind.toggle_debug", "Ziel-Debug umschalten")
language.Add("npcpassengers.keybind.toggle_debug.help", "Kleine Ziel-Debug-Überlagerung umschalten")
language.Add("npcpassengers.keybind.test_gesture", "Zufällige Geste testen")
language.Add("npcpassengers.keybind.test_gesture.help", "Zufällige Geste auf dem nächsten Passagier abspielen")
language.Add("npcpassengers.keybind.reset_all", "Alle NPCs zurücksetzen")
language.Add("npcpassengers.keybind.reset_all.help", "Animationszustände für alle Passagiere zurücksetzen")

-- HUD Settings
language.Add("npcpassengers.hud.header", "HUD-Einstellungen")
language.Add("npcpassengers.hud.enable", "HUD aktivieren")
language.Add("npcpassengers.hud.enable.help", "Zeigt die Passagierstatus-Überlagerung auf dem Bildschirm an.")
language.Add("npcpassengers.hud.position", "HUD-Position")
language.Add("npcpassengers.hud.position.help", "Wo das HUD auf dem Bildschirm erscheint.")
language.Add("npcpassengers.hud.position.topleft", "Oben links")
language.Add("npcpassengers.hud.position.topright", "Oben rechts")
language.Add("npcpassengers.hud.position.bottomleft", "Unten links")
language.Add("npcpassengers.hud.position.bottomright", "Unten rechts")
language.Add("npcpassengers.hud.scale", "HUD-Skalierung")
language.Add("npcpassengers.hud.scale.help", "Größenmultiplikator für das HUD.")
language.Add("npcpassengers.hud.opacity", "HUD-Transparenz")
language.Add("npcpassengers.hud.opacity.help", "Hintergrundtransparenz (0 = unsichtbar, 1 = fest).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC-Fahrer")
language.Add("npcpassengers.driver.desc", "Ermöglicht NPCs, Fahrzeuge für Sie zu fahren.")
language.Add("npcpassengers.driver.enable", "NPC-Fahrer aktivieren")
language.Add("npcpassengers.driver.enable.help", "Ermöglicht NPCs, die Kontrolle über das Fahrzeug zu übernehmen.")
language.Add("npcpassengers.driver.behavior", "Fahrverhalten")
language.Add("npcpassengers.driver.behavior.help", "Wie der NPC das Fahrzeug fährt.")
language.Add("npcpassengers.driver.behavior.cruise", "Zufällige Fahrt")
language.Add("npcpassengers.driver.behavior.follow", "Spieler folgen")
language.Add("npcpassengers.driver.behavior.patrol", "Patrouille")
language.Add("npcpassengers.driver.behavior.flee", "Fliehen")
language.Add("npcpassengers.driver.behavior.parked", "Geparkt bleiben")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Häufig gestellte Fragen")
language.Add("npcpassengers.help.desc", "Schnelle Antworten auf häufige Fragen und Fehlerbehebung.")
language.Add("npcpassengers.help.still_need", "Benötigen Sie noch Hilfe?")
language.Add("npcpassengers.help.community", "Treten Sie unserer Discord-Community bei, um Hilfe zu erhalten!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Panzer/LVS")
language.Add("npcpassengers.nav.debugging", "Debuggen")
language.Add("npcpassengers.nav.driver", "NPC-Fahrer")
language.Add("npcpassengers.nav.interface", "Schnittstelle")
language.Add("npcpassengers.nav.simulate", "Simulieren")
language.Add("npcpassengers.nav.modules", "Module")
language.Add("npcpassengers.nav.about", "Über")
language.Add("npcpassengers.search.placeholder", "Einstellungen suchen...")

-- About page
language.Add("npcpassengers.about.description", "Fortgeschrittenes Passagiersystem mit emotionaler KI und realistischer Physik")
language.Add("npcpassengers.about.feature_status", "Statussystem: RUHIG / ALARM / ANGST / SCHLÄFRIG / TOT")
language.Add("npcpassengers.about.feature_performance", "Leistung: Sitz-Caching, gedrosselte Timer, optimierte Client-Hooks")
language.Add("npcpassengers.about.feature_filtering", "Fahrzeugfilterung, Einsteig-Wiederholungs-Abklingzeit, Auto-Beitreten nur für Truppen")
language.Add("npcpassengers.about.actions", "Aktionen")
language.Add("npcpassengers.about.show_welcome", "Begrüßungsbildschirm anzeigen")
language.Add("npcpassengers.about.open_github", "GitHub-Seite öffnen")
language.Add("npcpassengers.about.reset_settings", "ALLE Einstellungen auf Standard zurücksetzen")

-- Status messages
language.Add("npcpassengers.status.calm", "RUHIG")
language.Add("npcpassengers.status.alert", "ALARM")
language.Add("npcpassengers.status.scared", "ANGST")
language.Add("npcpassengers.status.drowsy", "SCHLÄFRIG")
language.Add("npcpassengers.status.dead", "TOT")
language.Add("npcpassengers.status.calm.desc", "Entspannt, keine Bedrohungen in der Nähe")
language.Add("npcpassengers.status.alert.desc", "Feind erkannt, NPC verfolgt Bedrohungen")
language.Add("npcpassengers.status.scared.desc", "Gefährliches Fahren (hohe Geschwindigkeit, Unfälle)")
language.Add("npcpassengers.status.drowsy.desc", "Lange ruhige Fahrt, NPC wird schläfrig")
language.Add("npcpassengers.status.dead.desc", "Gesundheit erreicht Null")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Auto-Beitreten: AN")
language.Add("npcpassengers.chat.autojoin_off", "Auto-Beitreten: AUS")
language.Add("npcpassengers.chat.hud_on", "HUD: AN")
language.Add("npcpassengers.chat.hud_off", "HUD: AUS")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Kein Fahrzeug in der Nähe")
language.Add("npcpassengers.error.no_npc", "Kein NPC in der Nähe")
language.Add("npcpassengers.error.vehicle_full", "Fahrzeug voll")
language.Add("npcpassengers.error.too_far", "NPC zu weit vom Fahrzeug")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Sprache ändern")
language.Add("npcpassengers.tooltip.minimize", "Panel minimieren")
language.Add("npcpassengers.tooltip.expand", "Panel erweitern")
language.Add("npcpassengers.tooltip.welcome", "Begrüßungsbildschirm anzeigen")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Hauptschalter für die gesamte NPC-Sprache. Deaktivieren Sie dies, um Passagiere vollständig stumm zu schalten.")
language.Add("npcpassengers.speech_volume.help", "Wie laut NPCs sprechen (0 = stumm, 100 = volle Lautstärke).")
language.Add("npcpassengers.pitch_variation.help", "Zufällige Tonhöhenvariation für natürlichere Stimmen. 0 = monoton, höher = mehr Vielfalt.")
language.Add("npcpassengers.crash_enable.help", "NPCs stöhnen/schreien, wenn das Fahrzeug stark abgebremst wird (Unfälle, scharfes Bremsen).")
language.Add("npcpassengers.crash_threshold.help", "Verzögerung, die erforderlich ist, um Unfallgeräusche auszulösen. Niedriger = empfindlicher.")
language.Add("npcpassengers.crash_cooldown.help", "Minimale Sekunden zwischen Unfallgeräuschen pro NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPCs sprechen gelegentlich während der Fahrt: Kommentare, Fragen, Beobachtungen.")
language.Add("npcpassengers.speech_idle_chance.help", "Plauderwahrscheinlichkeit pro Überprüfung. 0 = nie, 1 = versucht immer zu sprechen.")
language.Add("npcpassengers.speech_idle_interval.help", "Minimale Sekunden zwischen Plauderversuchen.")
language.Add("npcpassengers.speech_board.help", "NPCs sprechen, wenn sie ein- und aussteigen.")
language.Add("npcpassengers.ambient_sounds.help", "Gelegentliches Husten, Seufzen, Summen – Hintergrundlebensgeräusche.")
language.Add("npcpassengers.ambient_interval.help", "Durchschnittliche Sekunden zwischen Umgebungsgeräuschen.")
language.Add("npcpassengers.animation.help", "Feinabstimmung von NPC-Animationen und Kopfbewegung.")
language.Add("npcpassengers.head_look.help", "NPCs schauen natürlich umher, zum Spieler, aus den Fenstern usw.")
language.Add("npcpassengers.head_smooth.help", "Wie glatt sich der Kopf bewegt. Niedriger = schneller, höher = schwebender.")
language.Add("npcpassengers.blink.help", "NPCs blinzeln realistisch, während sie sitzen.")
language.Add("npcpassengers.breathing.help", "Subtile Atmungsanimation auf NPC-Köpfen.")
language.Add("npcpassengers.walk_timeout.help", "Sekunden, bevor der NPC das Gehen zum Fahrzeug aufgibt.")
language.Add("npcpassengers.realism.help", "Physikbasierte Reaktionen und Wahrnehmungssysteme für maximale Immersion.")
language.Add("npcpassengers.talking_gestures.help", "NPCs spielen zufällig Handgesten und Körperanimationen während der Fahrt.")
language.Add("npcpassengers.gesture_chance.help", "Prozentuale Wahrscheinlichkeit, eine Geste pro Intervall abzuspielen.")
language.Add("npcpassengers.gesture_interval.help", "Sekunden zwischen Gestenmöglichkeiten-Überprüfungen.")
language.Add("npcpassengers.crash_flinch.help", "NPCs zucken und beugen sich nach vorne, wenn das Fahrzeug abstürzt oder scharf bremst.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Geschwindigkeitsänderung, die erforderlich ist, um Zucken auszulösen (niedriger = empfindlicher).")
language.Add("npcpassengers.body_sway.help", "NPCs lehnen sich in Kurven, stützen sich während Beschleunigung/Bremsen.")
language.Add("npcpassengers.body_sway_amount.help", "Wie stark NPCs mit der Fahrzeugbewegung schwanken.")
language.Add("npcpassengers.threat_awareness.help", "NPCs schauen automatisch auf nahegelegene Feinde.")
language.Add("npcpassengers.threat_range.help", "Wie weit NPCs Bedrohungen für die Kopfnachverfolgung erkennen können.")
language.Add("npcpassengers.combat_alert.help", "NPCs werden angespannt und reaktiv, wenn Feinde in der Nähe sind.")
language.Add("npcpassengers.passenger_combat.help", "Standardmäßig deaktiviert. Aktivieren Sie dies, um bewaffnete Passagiere aus dem Fahrzeug heraus schießen zu lassen.")
language.Add("npcpassengers.passenger_combat_range.help", "Wie weit bewaffnete Passagiere Ziele erfassen können.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Höhere Werte verringern die Streuung von Schüssen für bewaffnete Passagiere.")
language.Add("npcpassengers.passenger_combat_damage.help", "Skaliert den Schaden, der durch Passagierschüsse verursacht wird.")
language.Add("npcpassengers.passenger_interaction.help", "Mehrere Passagiere schauen sich an und plaudern gelegentlich miteinander.")
language.Add("npcpassengers.fear_reactions.help", "NPCs haben Angst vor gefährlichem Fahren – weit geöffnete Augen, Panikgeräusche.")
language.Add("npcpassengers.fear_speed_threshold.help", "Geschwindigkeit (Einheiten/Sek), bei der NPCs nervös werden.")
language.Add("npcpassengers.drowsiness.help", "NPCs werden auf langen ruhigen Fahrten schläfrig – langsames Blinzeln, Kopfnicken.")
language.Add("npcpassengers.drowsy_time.help", "Sekunden ruhiger Fahrt, bevor Schläfrigkeit einsetzt.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Einstellungen für Panzer, APCs und LVS-Fahrzeuge.")
language.Add("npcpassengers.hide_in_tanks.help", "Macht NPC-Passagiere unsichtbar, wenn sie sich in Panzern und APCs befinden.")
language.Add("npcpassengers.eject_stuck_check.help", "Stoßt NPCs automatisch aus dem Fahrzeug aus, wenn sie während des Ausstoßens feststecken. Verhindert, dass NPCs beim Aussteigen in das Fahrzeug geraten.")
language.Add("npcpassengers.detach_no_collide.help", "Nach dem Trennen gehen NPCs temporär durch das Fahrzeug, damit sie ohne Clipping oder Feststecken weggehen können.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Wie lange NPCs die Fahrzeugkollision nach dem Trennen ignorieren.")
language.Add("npcpassengers.die_with_vehicle.help", "NPC-Passagiere sterben, wenn ihr Fahrzeug durch Explosion oder Feuer zerstört wird (immersiver als wenn sie unverletzt aus den Trümmern gehen würden).")
language.Add("npcpassengers.tank_driver.help", "Ermöglicht NPCs auf dem Fahrersitz, automatisch zu Feinden zu fahren.")
language.Add("npcpassengers.tank_driver_range.help", "Maximale Reichweite für den Fahrer, um Feinde zu erkennen.")
language.Add("npcpassengers.tank_driver_distance.help", "Distanz, die von Feinden gehalten werden soll.")
language.Add("npcpassengers.tank_driver_throttle.help", "Gasmenge (0.1 = langsam, 1 = volle Geschwindigkeit).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distanz, bei der von Feinden zurückgefahren wird.")
language.Add("npcpassengers.tank_turret.help", "Ermöglicht NPCs, die Steuerung von Türmen auf LVS-Fahrzeugen zu übernehmen.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Zeigt den Passagierstatus (Emotionen, Alarm) auf dem Bildschirm während der Fahrt an.")
language.Add("npcpassengers.hud_show_calm.help", "Wenn deaktiviert, werden nur Passagiere mit nicht ruhigem Status angezeigt.")
language.Add("npcpassengers.hud_thresholds.desc", "Wenn Emotionsniveaus diese Schwellenwerte überschreiten, zeigen Passagiere diesen Status im HUD an.")
language.Add("npcpassengers.hud_alert_threshold.help", "Alarmpegel erforderlich, um 'ALARM'-Status anzuzeigen (Bedrohung erkannt).")
language.Add("npcpassengers.hud_fear_threshold.help", "Angstpegel erforderlich, um 'ANGST'-Status anzuzeigen (gefährliches Fahren).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Ruhig-Zeit-Verhältnis erforderlich, um 'SCHLÄFRIG'-Status anzuzeigen (lange ruhige Fahrt).")
language.Add("npcpassengers.hud_actions.desc", "Wählen Sie, welche Aktion Passagiere unternehmen, wenn sie jeden emotionalen Zustand erleben.")
language.Add("npcpassengers.hud_actions_note", "Hinweis: Einige Aktionen sind möglicherweise nicht sichtbar, je nach Unterstützung des NPC-Modells.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Legen Sie benutzerdefinierte Tastenbelegungen für NPC-Passagieraktionen fest. Klicken Sie auf einen Button und drücken Sie eine Taste zum Belegen.")
language.Add("npcpassengers.keybinds_hud.desc", "Schnelle HUD-Steuerelemente zum Anzeigen, Bewegen und Debuggen der Passagierüberlagerung.")
language.Add("npcpassengers.keybinds_debug_note", "Debug-Tastenbelegungen funktionieren nur, wenn der Debug-Modus aktiviert ist.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Erweiterte Debug-Tools zum Testen des NPC-Verhaltens. Aktivieren Sie zuerst den Debug-Modus in den Einstellungen.")
language.Add("npcpassengers.debug_mode.help", "Zeigt Debug-Test-Buttons an und aktiviert Debug-Befehle.")
language.Add("npcpassengers.debug_status.help", "Legen Sie den Passagierstatus manuell für Tests fest. Klicken Sie auf 'Liste aktualisieren', um aktuelle Passagiere anzuzeigen.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Konfigurieren Sie Soundeffekte für Buttons, Checkboxen und andere UI-Elemente")
language.Add("npcpassengers.ui_sounds_enabled.help", "Hauptschalter für alle UI-Soundeffekte")
language.Add("npcpassengers.ui_sounds_volume.help", "Lautstärkemultiplikator für UI-Sounds (1.0 = normal, 2.0 = doppelt)")
language.Add("npcpassengers.ui_hover_enabled.help", "Sound abspielen, wenn über Buttons gehovert wird")
language.Add("npcpassengers.ui_click_enabled.help", "Sound abspielen, wenn auf Buttons und Checkboxen geklickt wird")
language.Add("npcpassengers.context_menu.desc", "Wählen Sie, welche Optionen beim Rechtsklick auf NPCs erscheinen")
language.Add("npcpassengers.context_make_passenger.help", "NPC als Passagier zu Ihrem aktuellen Fahrzeug hinzufügen")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "NPC zu einem spezifischen Fahrzeug hinzufügen (Klicken Sie auf NPC, dann Fahrzeug)")
language.Add("npcpassengers.context_detach.help", "NPC aus dem Fahrzeug entfernen")
language.Add("npcpassengers.ui_show_welcome.help", "Begrüßungspanel anzeigen, wenn das Add-on auf eine neue Version aktualisiert wird")
language.Add("npcpassengers.ui_panel_width.help", "Breite des Einstellungspanels")
language.Add("npcpassengers.ui_panel_height.help", "Höhe des Einstellungspanels")
language.Add("npcpassengers.ui_animations.help", "Sanfte Übergänge und Hover-Effekte (kann die Leistung beeinträchtigen)")
language.Add("npcpassengers.ui_tooltips.help", "Nützliche Tooltips beim Hover über Einstellungen anzeigen")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Bildlaufleiste nur anzeigen, während Sie scrollen oder darüber hover.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Hinweis: Panel wird 70% transparent, wenn Sie einen Schieberegler ziehen, um den Inhalt im Hintergrund zu sehen.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Niedrigere Werte = glatter aber langsamer Bildlauf (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Wählen Sie ein Farbschema für das Einstellungspanel. Änderungen werden sofort angewendet.")
language.Add("npcpassengers.ui_font_scale.help", "Alle UI-Schriftgrößen skalieren. 1.0 = Standard, 0.5 = halbe Größe, 2.0 = doppelte Größe.")

print("[Better NPC Passengers] German localization loaded!")
