-- Better NPC Passengers - German Localization
-- Deutsche Lokalisierungsdatei

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Bessere NPC-Passagiere")
language.Add("npcpassengers.settings", "Einstellungen")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Allgemein")
language.Add("npcpassengers.nav.autojoin", "Automatisches Beitreten")
language.Add("npcpassengers.nav.passengers", "Passagiere")
language.Add("npcpassengers.nav.position", "Position")
language.Add("npcpassengers.nav.behaviour", "Verhalten")
language.Add("npcpassengers.nav.keybinds", "Tastenbelegungen")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Fahrer")
language.Add("npcpassengers.nav.help", "Hilfe")

-- General Settings
language.Add("npcassengers.general.header", "Allgemeine Einstellungen")
language.Add("npcpassengers.allow_multiple", "Mehrere Passagiere zulassen")
language.Add("npcpassengers.allow_multiple.help", "Ermöglicht, dass mehrere NPCs im selben Fahrzeug reisen.")
language.Add("npcpassengers.exit_behavior", "Ausstiegsverhalten")
language.Add("npcpassengers.exit_behavior.help", "Wann sollen NPC-Passagiere das Fahrzeug verlassen?")
language.Add("npcassengers.exit_mode.leave_player", "Verlassen, wenn Spieler aussteigt")
language.Add("npcpassengers.exit_mode.leave_attack", "Verlassen, wenn Fahrzeug angegriffen wird")
language.Add("npcpassengers.exit_mode.never", "Nie automatisch verlassen")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Zeitsteuerung")
language.Add("npcpassengers.max_attach_dist", "Maximale Anhängedistanz")
language.Add("npcpassengers.max_attach_dist.help", "Maximale Distanz (Einheiten) zum Anhängen eines NPCs an das Fahrzeug.")
language.Add("npcpassengers.detach_delay", "Ablösungsverzögerung")
language.Add("npcpassengers.detach_delay.help", "Sekunden zu warten, bevor nach dem Aussteigen des Spielers abgelöst wird.")
language.Add("npcpassengers.ai_delay", "KI-Wiederherstellungsverzögerung")
language.Add("npcpassengers.ai_delay.help", "Sekunden zu warten, bevor die KI des NPCs nach dem Ablösen wiederhergestellt wird.")
language.Add("npcpassengers.cooldown", "Abklingzeit")
language.Add("npcpassengers.cooldown.help", "Abklingzeit zwischen dem Anhängen von NPCs an dasselbe Fahrzeug.")
language.Add("npcpassengers.passenger_limit", "Passagierlimit")
language.Add("npcpassengers.passenger_limit.help", "Maximale Anzahl der im Fahrzeug zugelassenen NPCs.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Automatisches Beitreten (Truppenverhalten)")
language.Add("npcpassengers.autojoin.desc", "Freundliche NPCs treten automatisch Ihrem Fahrzeug bei, wenn Sie einsteigen - genau wie die Truppenmechanik in Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Automatisches Beitreten aktivieren")
language.Add("npcpassengers.autojoin.enable.help", "Nahegelegene freundliche NPCs treten automatisch bei, wenn Sie in ein Fahrzeug einsteigen.")
language.Add("npcpassengers.autojoin.range", "Reichweite für automatisches Beitreten")
language.Add("npcpassengers.autojoin.range.help", "Maximale Distanz zum Finden von NPCs für das automatische Beitreten.")
language.Add("npcpassengers.autojoin.max", "Maximale NPCs für automatisches Beitreten")
language.Add("npcpassengers.autojoin.max.help", "Maximale Anzahl von NPCs, die gleichzeitig automatisch beitreten können.")
language.Add("npcpassengers.autojoin.squad_only", "Nur Truppenmitglieder")
language.Add("npcpassengers.autojoin.squad_only.help", "Nur NPCs mit Truppennamen treten automatisch bei (für HL2-artige Truppen).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Freundliche NPCs treten automatisch Ihrem Fahrzeug bei, wenn Sie einsteigen - genau wie die Truppenmechanik in Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Passagiersteuerung")
language.Add("npcpassengers.panel.passengers.desc", "Verwalten Sie aktive Passagiere, filtern Sie nach Name/Klasse/Zustand, kopieren Sie Debug-Informationen, weisen Sie Sitze neu und lösen Sie Passagiere auf, ohne das Einstellungsfenster zu verlassen.")
language.Add("npcpassengers.panel.position.desc", "Justieren Sie die Position von NPCs in Fahrzeugen fein. Verwenden Sie dies, um Schwebeprobleme oder Überlappungen zu beheben.")
language.Add("npcpassengers.panel.angle.desc", "Justieren Sie die Drehung von NPCs in Fahrzeugen.")
language.Add("npcpassengers.panel.speech.desc", "Konfigurieren Sie, wie NPCs sprechen, während sie in Fahrzeugen reisen. Bürgerstimmen im HL2-Stil!")

-- Position Settings
language.Add("npcpassengers.position.header", "Positionsversätze")
language.Add("npcpassengers.position.desc", "Justieren Sie die Position von NPCs in Fahrzeugen fein. Verwenden Sie dies, um Schwebeprobleme oder Überlappungen zu beheben.")
language.Add("npcpassengers.height_offset", "Höhenversatz")
language.Add("npcpassengers.forward_offset", "Vorwärtsversatz")
language.Add("npcpassengers.right_offset", "Rechtsversatz")
language.Add("npcpassengers.angle.header", "Winkelversätze")
language.Add("npcpassengers.angle.desc", "Justieren Sie die Drehung von NPCs in Fahrzeugen.")
language.Add("npcpassengers.yaw_offset", "Gieren (Drehung)")
language.Add("npcpassengers.pitch_offset", "Nicken (Vorwärtsneigung)")
language.Add("npcpassengers.roll_offset", "Rollen (Seitwärtsneigung)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPC-Sprache (Erweitert)")
language.Add("npcpassengers.behaviour.desc", "Konfigurieren Sie, wie NPCs sprechen, während sie in Fahrzeugen reisen. Bürgerstimmen im HL2-Stil!")
language.Add("npcpassengers.speech_enable", "NPC-Sprache aktivieren")
language.Add("npcpassengers.speech_enable.help", "Hauptschalter für die gesamte NPC-Sprache. Deaktivieren Sie dies, um Passagiere vollständig stummzuschalten.")
language.Add("npcpassengers.speech_volume", "Sprachlautstärke")
language.Add("npcpassengers.speech_volume.help", "Wie laut die NPC-Stimmen sind (0 = stumm, 100 = volle Lautstärke).")
language.Add("npcpassengers.pitch_variation", "Tonhöhenvariation (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Zufällige Tonhöhenvariation für natürlichere Stimmen. 0 = monotone, höher = mehr Variation.")
language.Add("npcpassengers.crash.header", "Aufprallreaktionen")
language.Add("npcpassengers.crash_enable", "Aufprallgeräusche aktivieren")
language.Add("npcpassengers.crash_enable.help", "NPCs stöhnen/ächzen, wenn das Fahrzeug stark abgebremst wird (Aufprälle, scharfes Bremsen).")
language.Add("npcpassengers.crash_threshold", "Aufpallempfindlichkeit")
language.Add("npcpassengers.crash_threshold.help", "Abbremsung erforderlich, um Aufprallgeräusche auszulösen. Niedriger = empfindlicher.")
language.Add("npcpassengers.crash_cooldown", "Aufprallgeräusch-Abklingzeit")
language.Add("npcpassengers.crash_cooldown.help", "Minimale Sekunden zwischen Aufprallgeräuschen pro NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Leerlaufgespräch aktivieren")
language.Add("npcpassengers.speech_board", "Ein-/Ausstiegsgeräusche aktivieren")
language.Add("npcpassengers.ambient_sounds", "Umgebungsgeräusche aktivieren")
language.Add("npcpassengers.head_look", "Kopf-/Augenblick aktivieren")
language.Add("npcpassengers.blink", "Blinzeln aktivieren")
language.Add("npcpassengers.breathing", "Atmen aktivieren")
language.Add("npcpassengers.talking_gestures", "Sprechgesten aktivieren")
language.Add("npcpassengers.crash_flinch", "Aufprallzucken aktivieren")
language.Add("npcpassengers.body_sway", "Körperschwanken aktivieren")
language.Add("npcpassengers.threat_awareness", "Bedrohungsbewusstsein aktivieren")
language.Add("npcpassengers.combat_alert", "Kampfbereitschaft")
language.Add("npcpassengers.passenger_combat", "NPCs schießen aus Fahrzeugen (Experimentell)")
language.Add("npcpassengers.passenger_interaction", "Passagierinteraktion")
language.Add("npcpassengers.fear_reactions", "Angstreaktionen aktivieren")
language.Add("npcassengers.drowsiness", "Schläfrigkeit aktivieren")
language.Add("npcpassengers.hide_in_tanks", "NPCs in geschlossenen Fahrzeugen ausblenden")
language.Add("npcpassengers.eject_stuck_check", "Automatisches Auswerfen festsitzender NPCs")
language.Add("npcpassengers.detach_no_collide", "Keine Kollision mit Fahrzeug nach Ablösung")
language.Add("npcpassengers.die_with_vehicle", "Passagiere töten, wenn Fahrzeug explodiert")
language.Add("npcpassengers.driver_enabled", "Automatische Fahrt aktivieren")
language.Add("npcpassengers.turret_enabled", "Turmsteuerung aktivieren")
language.Add("npcpassengers.turret_lead_targets", "Ziele vorhersagen")
language.Add("npcpassengers.turret_friendly_fire", "Eigenbeschuss zulassen")
language.Add("npcpassengers.turret_hold_fire", "Feuer halten (Feuer deaktivieren)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Sprachlautstärke")
language.Add("npcpassengers.pitch_variation", "Tonhöhenvariation (+/-)")
language.Add("npcpassengers.crash_threshold", "Aufpallempfindlichkeit")
language.Add("npcpassengers.crash_cooldown", "Aufprallgeräusch-Abklingzeit")
language.Add("npcpassengers.speech_idle_chance", "Gesprächswahrscheinlichkeit")
language.Add("npcpassengers.speech_idle_interval", "Gesprächsintervall")
language.Add("npcpassengers.ambient_interval", "Umgebungsgeräusch-Intervall")
language.Add("npcpassengers.head_smooth", "Kopfweichheit")
language.Add("npcpassengers.walk_timeout", "Gehzeitüberschreitung")
language.Add("npcpassengers.gesture_chance", "Gestenwahrscheinlichkeit (%)")
language.Add("npcpassengers.gesture_interval", "Gestenintervall")
language.Add("npcpassengers.crash_threshold_flinch", "Aufpallempfindlichkeit")
language.Add("npcassengers.body_sway_amount", "Schwankungsintensität")
language.Add("npcpassengers.threat_range", "Bedrohungserkennungsreichweite")
language.Add("npcpassengers.passenger_combat_range", "Passagierkampfreichweite")
language.Add("npcpassengers.passenger_combat_accuracy", "Passagiergenauigkeit")
language.Add("npcpassengers.passenger_combat_damage", "Passagierschadensmultiplikator")
language.Add("npcpassengers.fear_speed_threshold", "Angstgeschwindigkeitsschwelle")
language.Add("npcpassengers.drowsy_time", "Schläfrigkeitszeit")
language.Add("npcpassengers.detach_no_collide_duration", "Kollisionsfreie Dauer (Sekunden)")
language.Add("npcpassengers.tank_driver_range", "Erkennungsreichweite")
language.Add("npcpassengers.tank_driver_engage_distance", "Eingriffsabstand")
language.Add("npcpassengers.tank_driver_speed", "Fahrgeschwindigkeit")
language.Add("npcpassengers.tank_driver_reverse_distance", "Rückwärtsabstand")
language.Add("npcpassengers.turret_range", "Zielreichweite")
language.Add("npcpassengers.turret_accuracy", "Genauigkeit")
language.Add("npcpassengers.turret_reaction_time", "Reaktionszeit")
language.Add("npcpassengers.turret_fire_delay", "Feuerverzögerung")
language.Add("npcpassengers.turret_aim_speed", "Zielgeschwindigkeit")
language.Add("npcpassengers.hud_scale", "HUD-Skalierung")
language.Add("npcpassengers.hud_opacity", "HUD-Transparenz")
language.Add("npcpassengers.hud_alert_threshold", "Alarmschwelle")
language.Add("npcpassengers.hud_fear_threshold", "Angstschwelle")
language.Add("npcpassengers.hud_drowsy_threshold", "Schläfrigkeitsschwelle")
language.Add("npcpassengers.ui_sounds_volume", "UI-Geräuschlautstärke")
language.Add("npcpassengers.ui_panel_width", "Panelbreite")

-- Section headers
language.Add("npcpassengers.section.animation", "Animation und Verhalten")
language.Add("npcpassengers.section.realism", "Erweiterter Realismus")
language.Add("npcpassengers.section.hud_position", "HUD-Position und -Stil")
language.Add("npcpassengers.section.emotion_thresholds", "Emotionsschwellen")
language.Add("npcpassengers.section.emotion_actions", "Emotionsaktionen")
language.Add("npcpassengers.section.vehicle_control", "Fahrzeugsteuerung")
language.Add("npcpassengers.section.hud_controls", "HUD-Steuerelemente")
language.Add("npcpassengers.section.debug_controls", "Debug-Steuerelemente")
language.Add("npcassengers.section.passenger_status", "Passagierzustandssteuerung")
language.Add("npcpassengers.section.quick_test", "Schnelltest-Schaltflächen")
language.Add("npcpassengers.section.driver_system", "NPC-Fahrersystem")
language.Add("npcpassengers.section.ui_sounds", "UI-Geräuscheinstellungen")
language.Add("npcpassengers.section.appearance", "Erscheinungsbild")
language.Add("npcpassengers.section.context_menu", "Kontextmenüoptionen")
language.Add("npcpassengers.section.panel_preferences", "Einstellungsfenster-Voreinstellungen")
language.Add("npcpassengers.section.performance", "Leistung und Technik")
language.Add("npcpassengers.section.simulation", "Simulationssystem")
language.Add("npcpassengers.section.modules", "Modulsystem")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Sitz zuweisen")
language.Add("npcpassengers.btn.detach", "Lösen")
language.Add("npcpassengers.btn.copy_summary", "Zusammenfassung kopieren")
language.Add("npcpassengers.btn.copy_debug", "Debug kopieren")
language.Add("npcpassengers.btn.enable_all_speech", "Alle Sprache aktivieren")
language.Add("npcpassengers.btn.disable_all_speech", "Alle Sprache deaktivieren")
language.Add("npcpassengers.btn.show_current_vehicle", "Nur aktuelles Fahrzeug anzeigen")
language.Add("npcpassengers.btn.auto_refresh", "Automatische Aktualisierung der sichtbaren Liste")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Kein aktuelles Fahrzeug erkannt. Setzen Sie sich in ein Fahrzeug oder deaktivieren Sie den aktuellen Fahrzeugfilter.")
language.Add("npcpassengers.status.no_match_filter", "Kein Passagier entspricht Ihrem Filter. Versuchen Sie einen Namen, eine Klasse, eine Sitznummer, einen Zustand oder eine Fahrzeugklasse.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Keine Passagiere in Ihrem aktuellen Fahrzeug gefunden.")
language.Add("npcpassengers.status.no_passengers", "Keine Passagiere gefunden. NPCs müssen in einem Fahrzeug reisen, bevor sie hier verwaltet werden können.")
language.Add("npcpassengers.status.all_passengers", "Alle Passagiere")
language.Add("npcpassengers.status.current_vehicle_only", "Nur aktuelles Fahrzeug")
language.Add("npcpassengers.status.ctrl_f_search", "Strg+F um Suche zu fokussieren")
language.Add("npcengers.status.no_matches", "Keine übereinstimmenden Einstellungen")
language.Add("npcpassengers.status.showing_matches", "Zeige %d Top von %d Übereinstimmungen")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Einstellungen öffnen")
language.Add("npcpassengers.menu.reset_all", "Alle Einstellungen zurücksetzen")

-- Button states
language.Add("npcpassengers.state.on", "EIN")
language.Add("npcpassengers.state.off", "AUS")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Automatisches Beitreten")
language.Add("npcpassengers.chat.hud_status", "Passagier-HUD")
language.Add("npcpassengers.chat.hud_position", "HUD-Position")
language.Add("npcpassengers.chat.target_debug", "Ziel-Debug")
language.Add("npcpassengers.chat.turret_gunners", "Turm-Schützen")
language.Add("npcpassengers.chat.turret_holding", "FEUER HALTEN")
language.Add("npcpassengers.chat.turret_fire", "FEUER ÖFFNEN")
language.Add("npcpassengers.chat.unknown", "Unbekannt")
language.Add("npcpassengers.chat.nothing_copy", "Nichts zu kopieren.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Zugriff auf Zwischenablage in dieser Version nicht verfügbar.")
language.Add("npcpassengers.chat.copied_clipboard", "In Zwischenablage kopiert.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Setzen Sie sich in dasselbe Fahrzeug, um diesen Passagier neu zuzuweisen.")
language.Add("npcpassengers.chat.no_visible_passengers", "Keine sichtbaren Passagiere zum Kopieren.")
language.Add("npcpassengers.chat.need_vehicle", "Sie müssen sich in einem Fahrzeug befinden, um dies zu verwenden.")
language.Add("npcpassengers.chat.keybinds_applied", "Empfohlene Tastenbelegungen angewendet.")
language.Add("npcpassengers.chat.keybinds_cleared", "Alle Tastenbelegungen gelöscht.")
language.Add("npcpassengers.chat.context_enabled", "Alle Kontextmenüoptionen aktiviert.")
language.Add("npcpassengers.chat.context_hidden", "Alle Kontextmenüoptionen ausgeblendet.")
language.Add("npcpassengers.chat.panel_compact", "Panelgröße auf kompakt eingestellt.")
language.Add("npcpassengers.chat.panel_default", "Panelgröße auf Standard eingestellt.")
language.Add("npcpassengers.chat.panel_large", "Panelgröße auf groß eingestellt.")
language.Add("npcpassengers.chat.panel_centered", "Panel zentriert.")
language.Add("npcpassengers.chat.settings_reset", "Alle UI-Einstellungen auf Standardwerte zurückgesetzt!")
language.Add("npcpassengers.chat.npc_selected", "NPC ausgewählt! Klicken Sie nun mit der rechten Maustaste auf ein Fahrzeug und wählen Sie 'Ausgewählten NPC hinzufügen'")
language.Add("npcpassengers.chat.adding_npc", "NPC wird zum Fahrzeug hinzugefügt...")
language.Add("npcpassengers.chat.selection_cancelled", "NPC-Auswahl abgebrochen")
language.Add("npcassengers.chat.summary_copied", "Passagierzusammenfassung kopiert.")
language.Add("npcpassengers.chat.debug_copied", "Passagier-Debug-Information kopiert.")
language.Add("npcpassengers.chat.no_passengers_found", "Keine Passagiere gefunden. NPCs müssen sich in einem Fahrzeug befinden.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Zustandsintensität %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Passagiere filtern...")
language.Add("npcpassengers.ui.press_key", "Drücken Sie eine Taste...")
language.Add("npcpassengers.ui.work_in_progress", "In Arbeit")
language.Add("npcpassengers.ui.under_development", "Diese Funktion ist derzeit in Entwicklung")
language.Add("npcpassengers.ui.check_back_later", "Überprüfen Sie es in einer zukünftigen Update!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtert aktive Passagiere nach Name, Klasse, Sitz, Zustand oder Fahrzeug.")
language.Add("npcpassengers.ui.search_desc_sort", "Sortiert die sichtbare Passagierliste nach Fahrzeug, Name, Sitz, Gesundheit oder Zustand.")
language.Add("npcpassengers.ui.search_label_filter", "Passagierfilter")
language.Add("npcpassengers.ui.search_label_sort", "Passagierreihenfolge")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Wie füge ich NPCs zu meinem Fahrzeug hinzu?")
language.Add("npcpassengers.faq.add_npc.answer", "Verwenden Sie das Kontextmenü (Rechtsklick auf einen NPC) und wählen Sie 'Zum Passagier machen'. Oder verwenden Sie die Tastenbelegung 'Nächsten NPC anhängen'. NPCs müssen freundlich zu Ihnen sein.")
language.Add("npcpassengers.faq.remove_npc", "Wie entferne ich Passagiere aus meinem Fahrzeug?")
language.Add("npcpassengers.faq.remove_npc.answer", "Gehen Sie zur Registerkarte Passagiere in den Einstellungen, wählen Sie den Passagier und klicken Sie auf Lösen. Oder verwenden Sie die Tastenbelegung 'Alle Passagiere lösen'.")
language.Add("npcpassengers.faq.position", "NPCs schweben/stecken in Sitzen fest!")
language.Add("npcpassengers.faq.position.answer", "Gehen Sie zur Registerkarte Position und passen Sie die Höhen-/Vorwärts-/Rechtsversätze an. Jedes Fahrzeugmodell ist unterschiedlich, daher müssen Sie möglicherweise diese Werte anpassen. Verwenden Sie das Debug-Fenster, um Positionen in Echtzeit zu testen.")
language.Add("npcpassengers.faq.speech", "NPCs sprechen nicht!")
language.Add("npcpassengers.faq.speech.answer", "Überprüfen Sie die Registerkarte Verhalten und stellen Sie sicher, dass 'NPC-Sprache aktivieren' aktiviert ist. Überprüfen Sie auch, ob die Sprachlautstärke über 0 liegt. Einige NPC-Modelle haben möglicherweise keine verfügbaren Sprachzeilen.")
language.Add("npcpassengers.faq.autojoin", "Wie funktioniert das automatische Beitreten?")
language.Add("npcpassengers.faq.autojoin.answer", "Wenn in der Registerkarte Automatisches Beitreten aktiviert, treten freundliche NPCs in der Nähe automatisch bei, wenn Sie einsteigen - genau wie die Truppenmechanik in Half-Life 2! Sie können den Erkennungsbereich festlegen und begrenzen, wie viele NPCs automatisch beitreten können.")
language.Add("npcassengers.faq.death", "Was passiert, wenn Passagiere sterben?")
language.Add("npcpassengers.faq.death.answer", "Tote Passagiere zeigen einen roten Glanzeffekt und zeigen einen Totenkopf im HUD. Nähern Sie sich Ihrem Fahrzeug und halten Sie R gedrückt, um ihre Körper zu entfernen. Die Körper werden mit Physik ausgeworfen.")
language.Add("npcpassengers.faq.status", "Was bedeuten die Passagierzustände?")
language.Add("npcpassengers.faq.status.answer", "RUHIG: Entspannt, keine Bedrohungen in der Nähe. ALARM: Feind erkannt. ANGST: Gefährliches Fahren. SCHLÄFRIG: Lange, ruhige Fahrt. TOT: Gesundheit erreicht Null.")
language.Add("npcpassengers.faq.keybinds", "Meine Tastenbelegungen funktionieren nicht!")
language.Add("npcpassengers.faq.keybinds.answer", "Gehen Sie zur Registerkarte Tastenbelegungen und stellen Sie sicher, dass Sie die Tastenbelegungen tatsächlich definiert haben (sie sind standardmäßig nicht zugewiesen). Klicken Sie auf die Schaltfläche neben jeder Aktion und drücken Sie die gewünschte Taste. Rechtsklick zum Aufheben.")
language.Add("npcpassengers.faq.errors", "Das Addon funktioniert überhaupt nicht / Ich erhalte Fehler!")
language.Add("npcpassengers.faq.errors.answer", "Stellen Sie sicher, dass Sie die neueste Version von Garry's Mod ausführen. Überprüfen Sie die Konsole auf Fehler (Taste Tilde ~). Versuchen Sie, konkurrierende Addons zu deaktivieren.")
language.Add("npcpassengers.faq.combat", "Können Passagiere aus Fahrzeugen schießen?")
language.Add("npcpassengers.faq.combat.answer", "Derzeit nicht. NPCs verfolgen Feinde und reagieren auf Bedrohungen, feuern aber keine Waffen, während sie sitzen. Diese Funktion könnte in zukünftigen Updates hinzugefügt werden.")
language.Add("npcpassengers.faq.stop_autojoin", "Wie stoppe ich NPCs am automatischen Beitreten?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Deaktivieren Sie das Kontrollkästchen 'Automatisches Beitreten aktivieren' in der Registerkarte Automatisches Beitreten oder verwenden Sie die Tastenbelegung 'Automatisches Beitreten umschalten'.")
language.Add("npcpassengers.faq.settings", "Wo werden die Einstellungen gespeichert?")
language.Add("npcpassengers.faq.settings.answer", "Alle Einstellungen werden als ConVars in Ihrer GMod-Konfiguration gespeichert. Sie bleiben zwischen Sitzungen bestehen und sind für Ihren Client spezifisch.")
language.Add("npcpassengers.faq.vehicles", "Funktioniert dies mit allen Fahrzeugen?")
language.Add("npcassengers.faq.vehicles.answer", "Es funktioniert mit den meisten Fahrzeugen, die Physik haben. Panzer, APCs, Autos, Boote usw. Einige moddierte Fahrzeuge erfordern möglicherweise Positionsanpassungen.")
language.Add("npcpassengers.faq.multiple", "Kann ich mehrere NPCs in einem Fahrzeug haben?")
language.Add("npcpassengers.faq.multiple.answer", "Ja! Stellen Sie das 'Passagierlimit' in den allgemeinen Einstellungen ein. Das Addon verteilt NPCs automatisch um das Fahrzeug. Für spezifische Sitzpositionen passen Sie die Versätze in der Registerkarte Position an.")
language.Add("npcpassengers.faq.crashes", "NPCs verhalten sich seltsam nach Aufprällen!")
language.Add("npcpassengers.faq.crashes.answer", "Dies ist normal - sie reagieren mit Angst auf gefährliches Fahren. Senken Sie die Angstschwelle in den HUD-Einstellungen, wenn Sie möchten, dass sie weniger reaktiv sind.")
language.Add("npcpassengers.faq.reset_setting", "Wie setze ich nur eine Einstellung zurück?")
language.Add("npcpassengers.faq.reset_setting.answer", "Verwenden Sie den Konsolenbefehl für diese spezifische Einstellung. Alle Befehle beginnen mit 'nai_npc_'. Geben Sie 'find nai_npc' in der Konsole ein, um alle verfügbaren Befehle anzuzeigen.")
language.Add("npcpassengers.faq.multiplayer", "Funktioniert dies im Multiplayer?")
language.Add("npcpassengers.faq.multiplayer.answer", "Ja! Das Addon funktioniert sowohl auf Einzelspieler- als auch auf Multiplayer-Servern. Jeder Spieler steuert seine eigenen Passagiere.")
language.Add("npcpassengers.faq.lvs", "Funktioniert dies mit LVS-Fahrzeugen?")
language.Add("npcpassengers.faq.lvs.answer", "Ja! Das Addon bietet volle Unterstützung für LVS (Lua Vehicle System) Fahrzeuge. NPCs können als Passagiere reisen und können sogar LVS-Fahrzeuge fahren, wenn der NPC-Fahrer-Modus aktiviert ist.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Diese Einstellungen steuern das Verhalten der Benutzeroberfläche des Addons")
language.Add("npcpassengers.panel.performance_note1", "Änderungen an der Panelgröße erfordern das Schließen und erneute Öffnen des Menüs")
language.Add("npcpassengers.panel.performance_note2", "Das Deaktivieren von Geräuschen oder Animationen kann die Leistung auf Low-End-Systemen verbessern")
language.Add("npcpassengers.panel.performance_title", "Informationen zur Benutzeroberflächenkonfiguration")
language.Add("npcpassengers.help.console_title", "Konsolenbefehle für Debugging:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Aktivieren Sie den Debug-Modus, um detaillierte Informationen anzuzeigen")
language.Add("npcpassengers.about.title", "Über")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")
language.Add("npcpassengers.lang.changed_portuguese", "Idioma alterado para português. O painel será atualizado automaticamente.")
language.Add("npcpassengers.lang.changed_german", "Sprache auf Deutsch geändert. Das Panel wird automatisch aktualisiert.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Hallo!")
language.Add("npcpassengers.welcome.msg1", "Bevor Sie sich beschweren, dass der Passagier auf dem Fahrzeug sitzt,\nbitte öffnen Sie die Einstellungen. Sie können es tun, ich glaube an Sie.")
language.Add("npcpassengers.welcome.msg2", "Dieses Add-on ist noch weit von PERFECT entfernt, zögern Sie nicht,\nBugs zu melden und neue Funktionen vorzuschlagen. Ich lese alle Ihre Kommentare!")
language.Add("npcpassengers.welcome.changelog", "Änderungsprotokoll")
language.Add("npcpassengers.welcome.got_it", "Verstanden!")
language.Add("npcpassengers.welcome.console_cmd", "Oder verwenden Sie den Konsolenbefehl: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "NPC-Klassen auf der Sperrliste")
language.Add("npcpassengers.ui.blacklist_help", "Durch Kommas getrennte Liste von NPC-Klassennamen, die keine Türme verwenden können. Verwenden Sie den Konsolenbefehl 'getnpcblacklist', um die aktuelle Sperrliste anzuzeigen.")
language.Add("npcpassengers.ui.hud_position", "HUD-Position")
language.Add("npcpassengers.ui.not_bound", "Nicht zugewiesen")
language.Add("npcpassengers.ui.keybind_tip", "Tipp: Rechtsklick auf eine Tastenbelegung zum Aufheben. Drücken Sie ESC während der Zuweisung zum Abbrechen.")
language.Add("npcpassengers.ui.dont_show_again", "Nicht erneut anzeigen")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Passagieroperationen")
language.Add("npcpassengers.hud.filter_prefix", "Filter: ")
language.Add("npcpassengers.hud.sort_prefix", "Sortieren: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Automatische Aktualisierung: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Fahrzeug: ")
language.Add("npcpassengers.hud.speed_prefix", "Geschwindigkeit: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "EIN")
language.Add("npcpassengers.hud.off", "AUS")
language.Add("npcpassengers.hud.passengers", "Passagiere")
language.Add("npcpassengers.hud.npc_driver", "NPC-Fahrer")
language.Add("npcpassengers.hud.total_prefix", "Gesamt: ")
language.Add("npcpassengers.hud.showing_prefix", "Zeige: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Aktuelles Fahrzeug: ")
language.Add("npcpassengers.hud.hidden_prefix", "Versteckt: ")
language.Add("npcpassengers.hud.dead_prefix", "Tot: ")
language.Add("npcpassengers.hud.scared_prefix", "Verängstigt: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Schläfrig: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Ruhig")
language.Add("npcpassengers.status.alert", "Alarm")
language.Add("npcpassengers.status.scared", "Verängstigt")
language.Add("npcpassengers.status.drowsy", "Schläfrig")
language.Add("npcpassengers.status.dead", "Tot")
language.Add("npcpassengers.status.unknown", "Unbekannt")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Bürger")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Pater Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dr. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Hund")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Fahrzeug")
language.Add("npcassengers.sort.name", "Name")
language.Add("npcpassengers.sort.seat", "Sitz")
language.Add("npcpassengers.sort.health", "Gesundheit")
language.Add("npcpassengers.sort.status", "Zustand")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Zuerst Fahrzeug")
language.Add("npcpassengers.sort.name_az", "Name A-Z")
language.Add("npcpassengers.sort.seat_number", "Sitznummer")
language.Add("npcpassengers.sort.highest_health", "Höchste Gesundheit")
language.Add("npcpassengers.sort.status_priority", "Zustandspriorität")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Fahrzeug: Unbekannt")
language.Add("npcpassengers.ui.seat_prefix", "Sitz ")
language.Add("npcpassengers.ui.same_vehicle", "Gleiches Fahrzeug")
language.Add("npcpassengers.ui.other_vehicle", "Anderes Fahrzeug")
language.Add("npcpassengers.ui.hidden", "Versteckt")
language.Add("npcpassengers.ui.visible", "Sichtbar")
language.Add("npcpassengers.ui.health_format", "Gesundheit %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Passagierliste aktualisieren")
language.Add("npcpassengers.ui.copy_list", "Sichtbare Passagierliste kopieren")
language.Add("npcpassengers.ui.make_exit", "Passagiere des aktuellen Fahrzeugs aussteigen lassen")
language.Add("npcpassengers.ui.reset_pos", "Position und Winkel zurücksetzen")
language.Add("npcpassengers.ui.crash_reactions", "Aufprallreaktionen")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Ein-/Ausstiegsgeräusche")
language.Add("npcpassengers.section.ambient_sounds", "Umgebungsgeräusche")
language.Add("npcpassengers.section.gesture_animations", "Gestenanimationen")
language.Add("npcpassengers.section.threat_awareness", "Bedrohungsbewusstsein")
language.Add("npcpassengers.section.emotional_states", "Emotionale Zustände")
language.Add("npcpassengers.section.turret_control", "Turmsteuerung (Experimentell)")
language.Add("npcpassengers.section.turret_blacklist", "NPC-Turm-Sperrliste")
language.Add("npcpassengers.section.idle_chatter", "Leerlaufgespräch")
language.Add("npcpassengers.section.body_physics", "Körperphysik")
language.Add("npcpassengers.section.npc_auto_driver", "NPC-Autofahrer")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Unten Links")
language.Add("npcpassengers.hud.bottom_right", "Unten Rechts")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Passagier-HUD aktivieren")
language.Add("npcpassengers.ui.cover_face", "Gesicht bedecken")
language.Add("npcpassengers.ui.apply_keybinds", "Empfohlene Tastenbelegungen anwenden")
language.Add("npcpassengers.ui.clear_keybinds", "Alle Tastenbelegungen löschen")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Zucken-Geste testen")
language.Add("npcpassengers.ui.test_random", "Zufällige Geste testen")
language.Add("npcpassengers.ui.reset_states", "Alle Zustände zurücksetzen")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Alle Kontextmenüoptionen aktivieren")
language.Add("npcpassengers.ui.hide_context", "Alle Kontextmenüoptionen ausblenden")
language.Add("npcpassengers.ui.set_compact", "Kompakte Panelgröße einstellen")
language.Add("npcpassengers.ui.set_default", "Standard-Panelgröße einstellen")
language.Add("npcpassengers.ui.set_large", "Große Panelgröße einstellen")
language.Add("npcpassengers.ui.center_panel", "Panel jetzt zentrieren")
language.Add("npcpassengers.ui.reset_ui", "Alle UI-Einstellungen auf Standard zurücksetzen")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Bürger (W)")
language.Add("npcpassengers.role.citizen_male", "Bürger (M)")
language.Add("npcpassengers.role.medic", "Sanitäter")
language.Add("npcpassengers.role.rebel", "Rebell")
language.Add("npcpassengers.role.passenger", "Passagier")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Nur anzeigen, wenn sich im Fahrzeug befindet")
language.Add("npcpassengers.hud.show_calm", "Ruhige Passagiere anzeigen")
language.Add("npcpassengers.hud.show_hints", "Kontexthinweise anzeigen")
language.Add("npcpassengers.hud.show_target_debug", "Ziel-Debug anzeigen")
language.Add("npcpassengers.hud.play_cues", "Erfolgs-/Fehler-Signale abspielen")
language.Add("npcpassengers.debug.enable_mode", "Debug-Modus aktivieren")
language.Add("npcpassengers.ui.enable_sounds", "UI-Geräusche aktivieren")
language.Add("npcpassengers.ui.hover_sounds", "Hover-Geräusche")
language.Add("npcpassengers.ui.click_sounds", "Klick-Geräusche")
language.Add("npcpassengers.ui.enable_animations", "UI-Animationen aktivieren")
language.Add("npcpassengers.ui.show_tooltips", "Tooltips anzeigen")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Scrollleiste automatisch ausblenden")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Seitenleisten-Scrollglätte")
language.Add("npcpassengers.ui.color_theme", "Farbschema")
language.Add("npcpassengers.ui.font_scale", "Schriftskalierung")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "NPC-Auswahl abbrechen")
language.Add("npcpassengers.context.remove_passenger", "Passagier entfernen")
language.Add("npcpassengers.context.blacklist_passenger", "Auf Sperrliste setzen")
language.Add("npcpassengers.context.whitelist_passenger", "Auf Erlaubnisliste setzen")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Tastenbelegungen")
language.Add("npcpassengers.keybinds.desc", "Konfigurieren Sie Tastaturkürzel für schnelle Aktionen.")
language.Add("npcpassengers.keybind.attach", "Nächsten NPC anhängen")
language.Add("npcpassengers.keybind.attach.help", "Hängt den nächsten freundlichen NPC an Ihr Fahrzeug.")
language.Add("npcpassengers.keybind.detach_all", "Alle NPCs lösen")
language.Add("npcpassengers.keybind.detach_all.help", "Entfernt alle Passagiere aus Ihrem Fahrzeug.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Automatisches Beitreten umschalten")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Aktiviert/deaktiviert schnell das automatische Beitreten.")
language.Add("npcpassengers.keybind.menu", "Einstellungsmenü öffnen")
language.Add("npcpassengers.keybind.menu.help", "Öffnet das Einstellungsfenster.")
language.Add("npcpassengers.keybind.exit_all", "Alle Passagiere aussteigen")
language.Add("npcpassengers.keybind.exit_all.help", "Lässt alle Passagiere das Fahrzeug verlassen.")
language.Add("npcpassengers.keybind.toggle_hud", "HUD umschalten")
language.Add("npcpassengers.keybind.toggle_hud.help", "Zeigt/versteckt das Passagier-HUD.")
language.Add("npcpassengers.keybind.quick_attach", "Schneller Anhängemodus")
language.Add("npcpassengers.keybind.quick_attach.help", "Gedrückt halten, um NPCs, auf die Sie schauen, schnell anzuhängen")
language.Add("npcpassengers.keybind.hold_fire", "NPCs halten Feuer")
language.Add("npcpassengers.keybind.hold_fire.help", "Sagen Sie Schützen-NPCs, sie sollen aufhören zu schießen")
language.Add("npcpassengers.keybind.open_fire", "NPCs öffnen Feuer")
language.Add("npcpassengers.keybind.open_fire.help", "Sagen Sie Schützen-NPCs, sie sollen Ziele angreifen")
language.Add("npcpassengers.keybind.cycle_view", "Passagiersicht durchlaufen")
language.Add("npcpassengers.keybind.cycle_view.help", "Durchläuft die Kamera durch Passagiere")
language.Add("npcpassengers.keybind.cycle_hud_position", "HUD-Position durchlaufen")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Bewegt das Passagier-HUD durch alle vier Ecken")
language.Add("npcpassengers.keybind.toggle_debug", "Ziel-Debug umschalten")
language.Add("npcpassengers.keybind.toggle_debug.help", "Schaltet die kleine Ziel-Debug-Überlagerung um")
language.Add("npcpassengers.keybind.test_gesture", "Zufällige Geste testen")
language.Add("npcpassengers.keybind.test_gesture.help", "Spielt eine zufällige Geste auf dem nächsten Passagier ab")
language.Add("npcpassengers.keybind.reset_all", "Alle NPCs zurücksetzen")
language.Add("npcpassengers.keybind.reset_all.help", "Setzt Animationszustände für alle Passagiere zurück")

-- HUD Settings
language.Add("npcassengers.hud.header", "HUD-Einstellungen")
language.Add("npcpassengers.hud.enable", "HUD aktivieren")
language.Add("npcpassengers.hud.enable.help", "Zeigt Passagierzustandsüberlagerung auf dem Bildschirm.")
language.Add("npcpassengers.hud.position", "HUD-Position")
language.Add("npcpassengers.hud.position.help", "Wo das HUD auf dem Bildschirm erscheint.")
language.Add("npcpassengers.hud.position.topleft", "Oben Links")
language.Add("npcpassengers.hud.position.topright", "Oben Rechts")
language.Add("npcpassengers.hud.position.bottomleft", "Unten Links")
language.Add("npcpassengers.hud.position.bottomright", "Unten Rechts")
language.Add("npcpassengers.hud.scale", "HUD-Skalierung")
language.Add("npcpassengers.hud.scale.help", "Größenmultiplikator für das HUD.")
language.Add("npcpassengers.hud.opacity", "HUD-Transparenz")
language.Add("npcpassengers.hud.opacity.help", "Hintergrundtransparenz (0 = unsichtbar, 1 = fest).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC-Fahrer")
language.Add("npcpassengers.driver.desc", "Ermöglicht NPCs, Fahrzeuge für Sie zu fahren.")
language.Add("npcpassengers.driver.enable", "NPC-Fahrer aktivieren")
language.Add("npcpassengers.driver.enable.help", "Ermöglicht NPCs, die Kontrolle über Fahrzeuge zu übernehmen.")
language.Add("npcpassengers.driver.behavior", "Fahrverhalten")
language.Add("npcpassengers.driver.behavior.help", "Wie der NPC das Fahrzeug fährt.")
language.Add("npcpassengers.driver.behavior.cruise", "Zufällige Fahrt")
language.Add("npcpassengers.driver.behavior.follow", "Spieler folgen")
language.Add("npcpassengers.driver.behavior.patrol", "Patrouille")
language.Add("npcpassengers.driver.behavior.flee", "Fliehen")
language.Add("npcpassengers.driver.behavior.parked", "Geparkt bleiben")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Häufig gestellte Fragen")
language.Add("npcpassengers.help.desc", "Schnelle Antworten auf häufige Fragen und Fehlerbehebung.")
language.Add("npcpassengers.help.still_need", "Benötigen Sie immer noch Hilfe?")
language.Add("npcpassengers.help.community", "Treten Sie unserer Discord-Community für Unterstützung bei!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Panzer/LVS")
language.Add("npcpassengers.nav.debugging", "Debugging")
language.Add("npcpassengers.nav.driver", "NPC-Fahrer")
language.Add("npcpassengers.nav.interface", "Benutzeroberfläche")
language.Add("npcassengers.nav.simulate", "Simulieren")
language.Add("npcpassengers.nav.modules", "Module")
language.Add("npcpassengers.nav.about", "Über")
language.Add("npcpassengers.search.placeholder", "Einstellungen suchen...")

-- About page
language.Add("npcpassengers.about.description", "Erweitertes Passagiersystem mit emotionaler KI und realistischer Physik")
language.Add("npcpassengers.about.feature_status", "Zustandssystem: RUHIG / ALARM / ANGST / SCHLÄFRIG / TOT")
language.Add("npcpassengers.about.feature_performance", "Leistung: Sitz-Caching, gedrosselte Timer, optimierte Client-Hooks")
language.Add("npcpassengers.about.feature_filtering", "Fahrzeugfilterung, Eintritt-Wiederholungs-Abklingzeit, nur Truppen-Automatisches Beitreten")
language.Add("npcpassengers.about.actions", "Aktionen")
language.Add("npcpassengers.about.show_welcome", "Willkommensbildschirm anzeigen")
language.Add("npcpassengers.about.open_github", "GitHub-Seite öffnen")
language.Add("npcpassengers.about.reset_settings", "ALLE Einstellungen auf Standard zurücksetzen")

-- Status messages
language.Add("npcpassengers.status.calm", "RUHIG")
language.Add("npcpassengers.status.alert", "ALARM")
language.Add("npcpassengers.status.scared", "ANGST")
language.Add("npcpassengers.status.drowsy", "SCHLÄFRIG")
language.Add("npcpassengers.status.dead", "TOT")
language.Add("npcpassengers.status.calm.desc", "Entspannt, keine Bedrohungen in der Nähe")
language.Add("npcpassengers.status.alert.desc", "Feind erkannt, NPC verfolgt Bedrohungen")
language.Add("npcpassengers.status.scared.desc", "Gefährliches Fahren (hohe Geschwindigkeit, Aufprälle)")
language.Add("npcpassengers.status.drowsy.desc", "Lange, ruhige Fahrt, NPC wird schläfrig")
language.Add("npcpassengers.status.dead.desc", "Gesundheit erreichte Null")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Automatisches Beitreten: EIN")
language.Add("npcpassengers.chat.autojoin_off", "Automatisches Beitreten: AUS")
language.Add("npcpassengers.chat.hud_on", "HUD: EIN")
language.Add("npcpassengers.chat.hud_off", "HUD: AUS")
language.Add("npcpassengers.chat.prefix", "[Bessere NPC-Passagiere]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Kein Fahrzeug in der Nähe")
language.Add("npcpassengers.error.no_npc", "Kein NPC in der Nähe")
language.Add("npcpassengers.error.vehicle_full", "Fahrzeug ist voll")
language.Add("npcpassengers.error.too_far", "NPC zu weit vom Fahrzeug")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Sprache ändern")
language.Add("npcpassengers.tooltip.minimize", "Panel minimieren")
language.Add("npcpassengers.tooltip.expand", "Panel maximieren")
language.Add("npcpassengers.tooltip.welcome", "Willkommensbildschirm anzeigen")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Hauptschalter für die gesamte NPC-Sprache. Deaktivieren Sie dies, um Passagiere vollständig stummzuschalten.")
language.Add("npcpassengers.speech_volume.help", "Wie laut die NPC-Stimmen sind (0 = stumm, 100 = volle Lautstärke).")
language.Add("npcpassengers.pitch_variation.help", "Zufällige Tonhöhenvariation für natürlichere Stimmen. 0 = monotone, höher = mehr Variation.")
language.Add("npcpassengers.crash_enable.help", "NPCs stöhnen/ächzen, wenn das Fahrzeug stark abgebremst wird (Aufprälle, scharfes Bremsen).")
language.Add("npcpassengers.crash_threshold.help", "Abbremsung erforderlich, um Aufprallgeräusche auszulösen. Niedriger = empfindlicher.")
language.Add("npcpassengers.crash_cooldown.help", "Minimale Sekunden zwischen Aufprallgeräuschen pro NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPCs sprechen gelegentlich, während sie reisen - Kommentare, Fragen, Beobachtungen.")
language.Add("npcpassengers.speech_idle_chance.help", "Wahrscheinlichkeit der Unterhaltung pro Prüfung. 0 = nie, 1 = versucht immer zu sprechen.")
language.Add("npcpassengers.speech_idle_interval.help", "Minimale Sekunden zwischen Leerlauf-Unterhaltungsversuchen.")
language.Add("npcpassengers.speech_board.help", "NPCs sprechen, wenn sie in Fahrzeuge ein- und aussteigen.")
language.Add("npcpassengers.ambient_sounds.help", "Gelegentliches Husten, Seufzen, Summen - Hintergrundlebensgeräusche.")
language.Add("npcpassengers.ambient_interval.help", "Durchschnittliche Sekunden zwischen Umgebungsgeräuschen.")
language.Add("npcpassengers.animation.help", "Justieren Sie NPC-Animationen und Kopfbewegungen fein.")
language.Add("npcpassengers.head_look.help", "NPCs schauen natürlich herum, zum Spieler, aus Fenstern usw.")
language.Add("npcpassengers.head_smooth.help", "Wie sanft der Kopf sich bewegt. Niedriger = schneller, höher = schwebender.")
language.Add("npcpassengers.blink.help", "NPCs blinzeln realistisch, während sie sitzen.")
language.Add("npcpassengers.breathing.help", "Subtile Atmungsanimation auf NPC-Köpfen.")
language.Add("npcpassengers.walk_timeout.help", "Sekunden, bevor der NPC das Gehen zum Fahrzeug aufgibt.")
language.Add("npcpassengers.realism.help", "Physikbasierte Reaktionen und Bewusstseinssysteme für maximale Immersion.")
language.Add("npcpassengers.talking_gestures.help", "NPCs spielen zufällige Handgesten und Körperanimationen ab, während sie reisen.")
language.Add("npcpassengers.gesture_chance.help", "Prozentuale Wahrscheinlichkeit, eine Geste pro Intervall abzuspielen.")
language.Add("npcpassengers.gesture_interval.help", "Sekunden zwischen Gestenmöglichkeitsprüfungen.")
language.Add("npcpassengers.crash_flinch.help", "NPCs zucken und stürzen nach vorne, wenn das Fahrzeug aufprallt oder scharf bremst.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Geschwindigkeitsänderung erforderlich, um Zucken auszulösen (niedriger = empfindlicher).")
language.Add("npcpassengers.body_sway.help", "NPCs lehnen sich in Kurven, stützen sich während Beschleunigung/Bremsen.")
language.Add("npcpassengers.body_sway_amount.help", "Wie stark NPCs mit der Fahrzeugbewegung schwanken.")
language.Add("npcpassengers.threat_awareness.help", "NPCs schauen automatisch auf nahegelegene Feinde.")
language.Add("npcpassengers.threat_range.help", "Wie weit NPCs Bedrohungen für Kopfverfolgung erkennen können.")
language.Add("npcpassengers.combat_alert.help", "NPCs werden angespannt und reaktiv, wenn Feinde in der Nähe sind.")
language.Add("npcpassengers.passenger_combat.help", "Standardmäßig deaktiviert. Aktivieren Sie dies, um bewaffnete Passagiere aus Fahrzeugen schießen zu lassen.")
language.Add("npcpassengers.passenger_combat_range.help", "Wie weit bewaffnete Passagiere Ziele erfassen können.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Höhere Werte verringern die Streuung für bewaffnete Passagiere.")
language.Add("npcpassengers.passenger_combat_damage.help", "Skaliert den Schaden, der von Passagierschüssen verursacht wird.")
language.Add("npcpassengers.passenger_interaction.help", "Mehrere Passagiere schauen sich an und unterhalten sich gelegentlich miteinander.")
language.Add("npcpassengers.fear_reactions.help", "NPCs werden durch gefährliches Fahren verängstigt - weit geöffnete Augen, Panikgeräusche.")
language.Add("npcpassengers.fear_speed_threshold.help", "Geschwindigkeit (Einheiten/Sek), bei der NPCs nervös werden.")
language.Add("npcpassengers.drowsiness.help", "NPCs werden auf langen, ruhigen Fahrten schläfrig - langsames Blinzeln, Kopfnicken.")
language.Add("npcpassengers.drowsy_time.help", "Sekunden ruhiger Fahrt, bevor Schläfrigkeit einsetzt.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Einstellungen für Panzer, APCs und LVS-Fahrzeuge.")
language.Add("npcpassengers.hide_in_tanks.help", "Macht NPC-Passagiere unsichtbar, wenn sie sich in Panzern und APCs befinden.")
language.Add("npcpassengers.eject_stuck_check.help", "Drückt NPCs automatisch aus Fahrzeugen, wenn sie beim Aussteigen feststecken. Verhindert, dass NPCs beim Aussteigen in Fahrzeuge eindringen.")
language.Add("npcpassengers.detach_no_collide.help", "Nach dem Ablösen gehen NPCs temporär durch das Fahrzeug, damit sie ohne Kollision oder Feststecken weggehen können.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Wie lange NPCs die Fahrzeugkollision nach dem Ablösen ignorieren.")
language.Add("npcpassengers.die_with_vehicle.help", "NPC-Passagiere sterben, wenn ihr Fahrzeug durch Explosion oder Feuer zerstört wird (immersiver als unversehrt aus den Trümmern herauszugehen).")
language.Add("npcpassengers.tank_driver.help", "Ermöglicht NPCs im Fahrersitz, automatisch in Richtung Feinde zu fahren.")
language.Add("npcpassengers.tank_driver_range.help", "Maximale Reichweite für den Fahrer, um Feinde zu erkennen.")
language.Add("npcpassengers.tank_driver_distance.help", "Abstand, der von Feinden gehalten werden soll.")
language.Add("npcpassengers.tank_driver_throttle.help", "Gasbetrag (0.1 = langsam, 1 = volle Geschwindigkeit).")
language.Add("npcpassengers.tank_driver_reverse.help", "Abstand, in dem rückwärts von Feinden gefahren wird.")
language.Add("npcpassengers.tank_turret.help", "Ermöglicht NPCs, Türme auf LVS-Fahrzeugen zu steuern.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Zeigt Passagierzustand (Emotionen, Alarm) auf dem Bildschirm während der Fahrt.")
language.Add("npcpassengers.hud_show_calm.help", "Wenn deaktiviert, werden nur Passagiere mit nicht ruhigem Zustand angezeigt.")
language.Add("npcpassengers.hud_thresholds.desc", "Wenn Emotionsniveaus diese Schwellen überschreiten, zeigen Passagiere diesen Zustand im HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Alarmniveau erforderlich, um 'ALARM'-Zustand anzuzeigen (Bedrohung erkannt).")
language.Add("npcpassengers.hud_fear_threshold.help", "Angstniveau erforderlich, um 'ANGST'-Zustand anzuzeigen (gefährliches Fahren).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Ruhigzeitverhältnis erforderlich, um 'SCHLÄFRIG'-Zustand anzuzeigen (lange, ruhige Fahrt).")
language.Add("npcpassengers.hud_actions.desc", "Wählen Sie, welche Aktion Passagiere bei jedem emotionalen Zustand ausführen.")
language.Add("npcpassengers.hud_actions_note", "Hinweis: Einige Aktionen sind möglicherweise nicht sichtbar, abhängig von der NPC-Modellunterstützung.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Legen Sie benutzerdefinierte Tastenbelegungen für Passagieraktionen fest. Klicken Sie auf eine Schaltfläche und drücken Sie eine Taste zum Zuweisen.")
language.Add("npcpassengers.keybinds_hud.desc", "Schnelle HUD-Steuerelemente zum Anzeigen, Bewegen und Debuggen der Passagierüberlagerung.")
language.Add("npcpassengers.keybinds_debug_note", "Debug-Tastenbelegungen funktionieren nur, wenn der Debug-Modus aktiviert ist.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Erweiterte Debugging-Tools zum Testen des NPC-Verhaltens. Aktivieren Sie zuerst den Debug-Modus in den Einstellungen.")
language.Add("npcpassengers.debug_mode.help", "Zeigt Debug-Test-Schaltflächen und aktiviert Debug-Befehle.")
language.Add("npcpassengers.debug_status.help", "Legen Sie manuell den Passagierzustand für Tests fest. Klicken Sie auf 'Liste aktualisieren', um aktuelle Passagiere anzuzeigen.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Konfigurieren Sie Soundeffekte für Schaltflächen, Kontrollkästchen und andere UI-Elemente")
language.Add("npcpassengers.ui_sounds_enabled.help", "Hauptschalter für alle UI-Soundeffekte")
language.Add("npcpassengers.ui_sounds_volume.help", "Lautstärkemultiplikator für UI-Sounds (1.0 = normal, 2.0 = doppelt)")
language.Add("npcpassengers.ui_hover_enabled.help", "Sound abspielen, wenn Maus über Schaltflächen bewegt")
language.Add("npcpassengers.ui_click_enabled.help", "Sound abspielen, wenn auf Schaltflächen und Kontrollkästchen geklickt wird")
language.Add("npcpassengers.context_menu.desc", "Wählen Sie, welche Optionen beim Rechtsklick auf NPCs erscheinen")
language.Add("npcpassengers.context_make_passenger.help", "Fügt NPC als Passagier zu Ihrem aktuellen Fahrzeug hinzu")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Fügt NPC zu einem bestimmten Fahrzeug hinzu (Klick auf NPC, dann auf Fahrzeug)")
language.Add("npcpassengers.context_detach.help", "Entfernt NPC aus dem Fahrzeug")
language.Add("npcpassengers.ui_show_welcome.help", "Zeigt Willkommensfenster, wenn das Addon auf eine neue Version aktualisiert wird")
language.Add("npcpassengers.ui_panel_width.help", "Breite des Einstellungsfensters")
language.Add("npcpassengers.ui_panel_height.help", "Höhe des Einstellungsfensters")
language.Add("npcpassengers.ui_animations.help", "Sanfte Übergänge und Hover-Effekte (kann Leistung beeinträchtigen)")
language.Add("npcpassengers.ui_tooltips.help", "Zeigt hilfreiche Tooltips an, wenn über Einstellungen gehovert wird")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Zeigt die Scrollleiste nur an, während Sie scrollen oder darüber hoveren.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Hinweis: Das Fenster wird 70% transparent, wenn ein Schieberegler gezogen wird, um Inhalt im Hintergrund zu sehen.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Niedrigere Werte = glatter aber langsamer (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Wählen Sie ein Farbschema für das Einstellungsfenster. Änderungen werden sofort angewendet.")
language.Add("npcpassengers.ui_font_scale.help", "Skaliert alle UI-Schriftgrößen. 1.0 = Standard, 0.5 = halbe Größe, 2.0 = doppelte Größe.")

print("[Better NPC Passengers] German localization loaded!")
