-- Better NPC Passengers - Italian Localization
-- Traduzione italiana

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Impostazioni")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Generale")
language.Add("npcpassengers.nav.autojoin", "Auto-Unisciti")
language.Add("npcpassengers.nav.passengers", "Passeggeri")
language.Add("npcpassengers.nav.position", "Posizione")
language.Add("npcpassengers.nav.behaviour", "Comportamento")
language.Add("npcpassengers.nav.keybinds", "Tasti")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Autista")
language.Add("npcpassengers.nav.help", "Aiuto")

-- General Settings
language.Add("npcpassengers.general.header", "Impostazioni Generali")
language.Add("npcpassengers.allow_multiple", "Permetti più passeggeri")
language.Add("npcpassengers.allow_multiple.help", "Permette a più NPC di viaggiare nello stesso veicolo.")
language.Add("npcpassengers.exit_behavior", "Comportamento di uscita")
language.Add("npcpassengers.exit_behavior.help", "Quando i passeggeri NPC dovrebbero lasciare il veicolo?")
language.Add("npcpassengers.exit_mode.leave_player", "Esci quando il giocatore esce")
language.Add("npcpassengers.exit_mode.leave_attack", "Esci quando il veicolo viene attaccato")
language.Add("npcpassengers.exit_mode.never", "Non uscire mai automaticamente")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Impostazioni temporali")
language.Add("npcpassengers.max_attach_dist", "Distanza massima di imbarco")
language.Add("npcpassengers.max_attach_dist.help", "Distanza massima (unità) per far salire un NPC nel veicolo.")
language.Add("npcpassengers.detach_delay", "Ritardo di uscita")
language.Add("npcpassengers.detach_delay.help", "Secondi di attesa prima che il NPC esca dopo che il giocatore ha lasciato il veicolo.")
language.Add("npcpassengers.ai_delay", "Ritardo di recupero IA")
language.Add("npcpassengers.ai_delay.help", "Secondi di attesa prima di ripristinare l'IA del NPC dopo l'uscita.")
language.Add("npcpassengers.cooldown", "Tempo di ricarica")
language.Add("npcpassengers.cooldown.help", "Tempo di ricarica tra gli imbarchi NPC nello stesso veicolo.")
language.Add("npcpassengers.passenger_limit", "Limite passeggeri")
language.Add("npcpassengers.passenger_limit.help", "Massimo di NPC nel veicolo.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Auto-Unisciti (Comportamento squadra)")
language.Add("npcpassengers.autojoin.desc", "Gli NPC amici si uniranno automaticamente al tuo veicolo quando sali, come la meccanica della squadra in Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Attiva auto-unisciti")
language.Add("npcpassengers.autojoin.enable.help", "Gli NPC amici vicini si uniranno automaticamente quando sali in un veicolo.")
language.Add("npcpassengers.autojoin.range", "Raggio auto-unisciti")
language.Add("npcpassengers.autojoin.range.help", "Distanza massima per cercare NPC per auto-unisciti.")
language.Add("npcpassengers.autojoin.max", "Massimo NPC per auto-unisciti")
language.Add("npcpassengers.autojoin.max.help", "Numero massimo di NPC che possono unirsi automaticamente alla volta.")
language.Add("npcpassengers.autojoin.squad_only", "Solo membri squadra")
language.Add("npcpassengers.autojoin.squad_only.help", "Solo gli NPC con nome squadra si uniranno automaticamente (per squadre stile HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Gli NPC amici si uniranno automaticamente al tuo veicolo quando sali, come la meccanica della squadra in Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Gestione passeggeri")
language.Add("npcpassengers.panel.passengers.desc", "Gestisci passeggeri attivi, filtra per nome/classe/stato, copia informazioni di debug, riassegna posti e fai uscire i passeggeri senza lasciare il pannello impostazioni.")
language.Add("npcpassengers.panel.position.desc", "Regolazione fine della posizione NPC nel veicolo. Usa questo per correggere problemi di galleggiamento o clipping.")
language.Add("npcpassengers.panel.angle.desc", "Regolazione della rotazione NPC nel veicolo.")
language.Add("npcpassengers.panel.speech.desc", "Configura come vocalizzano gli NPC mentre viaggiano nel veicolo. Voci dei cittadini stile HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Spostamenti posizione")
language.Add("npcpassengers.position.desc", "Regolazione fine della posizione NPC nel veicolo. Usa questo per correggere problemi di galleggiamento o clipping.")
language.Add("npcpassengers.height_offset", "Spostamento altezza")
language.Add("npcpassengers.forward_offset", "Spostamento avanti")
language.Add("npcpassengers.right_offset", "Spostamento destra")
language.Add("npcpassengers.angle.header", "Spostamenti angolo")
language.Add("npcpassengers.angle.desc", "Regolazione della rotazione NPC nel veicolo.")
language.Add("npcpassengers.yaw_offset", "Imbardata (Rotazione)")
language.Add("npcpassengers.pitch_offset", "Beccheggio (Inclinazione avanti)")
language.Add("npcpassengers.roll_offset", "Rollio (Inclinazione laterale)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Voce NPC (Avanzato)")
language.Add("npcpassengers.behaviour.desc", "Configura come vocalizzano gli NPC mentre viaggiano nel veicolo. Voci dei cittadini stile HL2!")
language.Add("npcpassengers.speech_enable", "Attiva voce NPC")
language.Add("npcpassengers.speech_enable.help", "Interruttore principale per tutta la voce NPC. Disabilita per rendere i passeggeri completamente silenziosi.")
language.Add("npcpassengers.speech_volume", "Volume voce")
language.Add("npcpassengers.speech_volume.help", "Quanto forte parlano gli NPC (0 = silenzioso, 100 = volume pieno).")
language.Add("npcpassengers.pitch_variation", "Variazione tono (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Variazione casuale del tono per voci più naturali. 0 = monotono, più alto = più varietà.")
language.Add("npcpassengers.crash.header", "Reazioni agli incidenti")
language.Add("npcpassengers.crash_enable", "Attiva suoni incidenti")
language.Add("npcpassengers.crash_enable.help", "Gli NPC gemono/urloano quando il veicolo decelera bruscamente (incidenti, frenata brusca).")
language.Add("npcpassengers.crash_threshold", "Sensibilità incidenti")
language.Add("npcpassengers.crash_threshold.help", "Decelerazione necessaria per attivare i suoni incidente. Più basso = più sensibile.")
language.Add("npcpassengers.crash_cooldown", "Ricarica suoni incidenti")
language.Add("npcpassengers.crash_cooldown.help", "Secondi minimi tra i suoni incidente per NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Attiva chiacchiere")
language.Add("npcpassengers.speech_board", "Attiva suoni imbarco/uscita")
language.Add("npcpassengers.ambient_sounds", "Attiva suoni ambientali")
language.Add("npcpassengers.head_look", "Attiva sguardo testa/occhi")
language.Add("npcpassengers.blink", "Attiva sbattito")
language.Add("npcpassengers.breathing", "Attiva respirazione")
language.Add("npcpassengers.talking_gestures", "Attiva gesti parlanti")
language.Add("npcpassengers.crash_flinch", "Attiva sobbalto incidente")
language.Add("npcpassengers.body_sway", "Attiva oscillazione corpo")
language.Add("npcpassengers.threat_awareness", "Attiva consapevolezza minacce")
language.Add("npcpassengers.combat_alert", "Allerta combattimento")
language.Add("npcpassengers.passenger_combat", "NPC sparano dal veicolo (Sperimentale)")
language.Add("npcpassengers.passenger_interaction", "Interazione passeggeri")
language.Add("npcpassengers.fear_reactions", "Attiva reazioni paura")
language.Add("npcpassengers.drowsiness", "Attiva sonnolenza")
language.Add("npcpassengers.hide_in_tanks", "Nascondi NPC in veicoli chiusi")
language.Add("npcpassengers.eject_stuck_check", "Espulsione automatica NPC bloccati")
language.Add("npcpassengers.detach_no_collide", "Nessuna collisione con veicolo dopo uscita")
language.Add("npcpassengers.die_with_vehicle", "Uccidi passeggeri all'esplosione veicolo")
language.Add("npcpassengers.driver_enabled", "Attiva guida automatica")
language.Add("npcpassengers.turret_enabled", "Attiva controllo torretta")
language.Add("npcpassengers.turret_lead_targets", "Anticipazione bersagli")
language.Add("npcpassengers.turret_friendly_fire", "Permetti fuoco amico")
language.Add("npcpassengers.turret_hold_fire", "Mantieni fuoco (Disabilita sparo)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Volume voce")
language.Add("npcpassengers.pitch_variation", "Variazione tono (+/-)")
language.Add("npcpassengers.crash_threshold", "Sensibilità incidenti")
language.Add("npcpassengers.crash_cooldown", "Ricarica suoni incidenti")
language.Add("npcpassengers.speech_idle_chance", "Probabilità chiacchiere")
language.Add("npcpassengers.speech_idle_interval", "Intervallo chiacchiere")
language.Add("npcpassengers.ambient_interval", "Intervallo suoni ambientali")
language.Add("npcpassengers.head_smooth", "Fluidità testa")
language.Add("npcpassengers.walk_timeout", "Timeout camminata")
language.Add("npcpassengers.gesture_chance", "Probabilità gesti (%)")
language.Add("npcpassengers.gesture_interval", "Intervallo gesti")
language.Add("npcpassengers.crash_threshold_flinch", "Sensibilità incidenti")
language.Add("npcpassengers.body_sway_amount", "Intensità oscillazione")
language.Add("npcpassengers.threat_range", "Raggio rilevamento minacce")
language.Add("npcpassengers.passenger_combat_range", "Raggio combattimento passeggeri")
language.Add("npcpassengers.passenger_combat_accuracy", "Precisione passeggeri")
language.Add("npcpassengers.passenger_combat_damage", "Moltiplicatore danno passeggeri")
language.Add("npcpassengers.fear_speed_threshold", "Soglia velocità paura")
language.Add("npcpassengers.drowsy_time", "Tempo sonnolenza")
language.Add("npcpassengers.detach_no_collide_duration", "Durata senza collisione (secondi)")
language.Add("npcpassengers.tank_driver_range", "Raggio rilevamento")
language.Add("npcpassengers.tank_driver_engage_distance", "Distanza impegno")
language.Add("npcpassengers.tank_driver_speed", "Velocità guida")
language.Add("npcpassengers.tank_driver_reverse_distance", "Distanza retromarcia")
language.Add("npcpassengers.turret_range", "Raggio bersaglio")
language.Add("npcpassengers.turret_accuracy", "Precisione")
language.Add("npcpassengers.turret_reaction_time", "Tempo reazione")
language.Add("npcpassengers.turret_fire_delay", "Ritardo sparo")
language.Add("npcpassengers.turret_aim_speed", "Velocità mira")
language.Add("npcpassengers.hud_scale", "Scala HUD")
language.Add("npcpassengers.hud_opacity", "Opacità HUD")
language.Add("npcpassengers.hud_alert_threshold", "Soglia allerta")
language.Add("npcpassengers.hud_fear_threshold", "Soglia paura")
language.Add("npcpassengers.hud_drowsy_threshold", "Soglia sonnolenza")
language.Add("npcpassengers.ui_sounds_volume", "Volume suoni UI")
language.Add("npcpassengers.ui_panel_width", "Larghezza pannello")

-- Section headers
language.Add("npcpassengers.section.animation", "Animazione e comportamento")
language.Add("npcpassengers.section.realism", "Realismo avanzato")
language.Add("npcpassengers.section.hud_position", "Posizione e stile HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Soglie emozioni")
language.Add("npcpassengers.section.emotion_actions", "Azioni emozioni")
language.Add("npcpassengers.section.vehicle_control", "Controllo veicolo")
language.Add("npcpassengers.section.hud_controls", "Controlli HUD")
language.Add("npcpassengers.section.debug_controls", "Controlli debug")
language.Add("npcpassengers.section.passenger_status", "Gestione stato passeggeri")
language.Add("npcpassengers.section.quick_test", "Pulsanti test rapido")
language.Add("npcpassengers.section.driver_system", "Sistema autista NPC")
language.Add("npcpassengers.section.ui_sounds", "Impostazioni suoni UI")
language.Add("npcpassengers.section.appearance", "Aspetto")
language.Add("npcpassengers.section.context_menu", "Opzioni menu contestuale")
language.Add("npcpassengers.section.panel_preferences", "Preferenze pannello impostazioni")
language.Add("npcpassengers.section.performance", "Prestazioni e tecnico")
language.Add("npcpassengers.section.simulation", "Sistema simulazione")
language.Add("npcpassengers.section.modules", "Sistema moduli")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Assegna posto")
language.Add("npcpassengers.btn.detach", "Scollega")
language.Add("npcpassengers.btn.copy_summary", "Copia riepilogo")
language.Add("npcpassengers.btn.copy_debug", "Copia debug")
language.Add("npcpassengers.btn.enable_all_speech", "Attiva tutta voce")
language.Add("npcpassengers.btn.disable_all_speech", "Disabilita tutta voce")
language.Add("npcpassengers.btn.show_current_vehicle", "Mostra solo veicolo attuale")
language.Add("npcpassengers.btn.auto_refresh", "Aggiornamento automatico lista visibile")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Veicolo attuale non rilevato. Salire in un veicolo o disabilita il filtro veicolo attuale.")
language.Add("npcpassengers.status.no_match_filter", "I passeggeri non corrispondono al tuo filtro. Prova nome, classe, numero posto, stato o classe veicolo.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Nessun passeggero trovato nel tuo veicolo attuale.")
language.Add("npcpassengers.status.no_passengers", "Nessun passeggero trovato. Gli NPC devono essere in un veicolo prima di poter essere gestiti qui.")
language.Add("npcpassengers.status.all_passengers", "Tutti i passeggeri")
language.Add("npcpassengers.status.current_vehicle_only", "Solo veicolo attuale")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F per focus ricerca")
language.Add("npcpassengers.status.no_matches", "Nessuna impostazione corrispondente")
language.Add("npcpassengers.status.showing_matches", "Mostrando %d di %d corrispondenze")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Apri impostazioni")
language.Add("npcpassengers.menu.reset_all", "Ripristina tutte impostazioni")

-- Button states
language.Add("npcpassengers.state.on", "ON")
language.Add("npcpassengers.state.off", "OFF")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Auto-Unisciti")
language.Add("npcpassengers.chat.hud_status", "HUD passeggeri")
language.Add("npcpassengers.chat.hud_position", "Posizione HUD")
language.Add("npcpassengers.chat.target_debug", "Debug bersaglio")
language.Add("npcpassengers.chat.turret_gunners", "Cecchini torretta")
language.Add("npcpassengers.chat.turret_holding", "MANTENGONO FUOCO")
language.Add("npcpassengers.chat.turret_fire", "FUOCO APERTO")
language.Add("npcpassengers.chat.unknown", "Sconosciuto")
language.Add("npcpassengers.chat.nothing_copy", "Niente da copiare.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Accesso agli appunti non disponibile in questa versione.")
language.Add("npcpassengers.chat.copied_clipboard", "Copiato negli appunti.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Siediti nello stesso veicolo per riassegnare questo passeggero.")
language.Add("npcpassengers.chat.no_visible_passengers", "Nessun passeggero visibile da copiare.")
language.Add("npcpassengers.chat.need_vehicle", "Devi essere in un veicolo per usare questo.")
language.Add("npcpassengers.chat.keybinds_applied", "Tasti consigliati applicati.")
language.Add("npcpassengers.chat.keybinds_cleared", "Tutti i tasti cancellati.")
language.Add("npcpassengers.chat.context_enabled", "Tutte le opzioni menu contestuale attivate.")
language.Add("npcpassengers.chat.context_hidden", "Tutte le opzioni menu contestuale nascoste.")
language.Add("npcpassengers.chat.panel_compact", "Dimensione pannello impostata su compatto.")
language.Add("npcpassengers.chat.panel_default", "Dimensione pannello impostata su predefinito.")
language.Add("npcpassengers.chat.panel_large", "Dimensione pannello impostata su grande.")
language.Add("npcpassengers.chat.panel_centered", "Pannello centrato.")
language.Add("npcpassengers.chat.settings_reset", "Tutte le impostazioni UI ripristinate ai valori predefiniti!")
language.Add("npcpassengers.chat.npc_selected", "NPC selezionato! Ora clic destro sul veicolo e seleziona 'Aggiungi NPC selezionato'")
language.Add("npcpassengers.chat.adding_npc", "Aggiunta NPC al veicolo...")
language.Add("npcpassengers.chat.selection_cancelled", "Selezione NPC annullata")
language.Add("npcpassengers.chat.summary_copied", "Riepilogo passeggeri copiato.")
language.Add("npcpassengers.chat.debug_copied", "Informazioni debug passeggero copiate.")
language.Add("npcpassengers.chat.no_passengers_found", "Nessun passeggero trovato. Gli NPC devono essere in un veicolo.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Intensità stato %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filtra passeggeri...")
language.Add("npcpassengers.ui.press_key", "Premi tasto...")
language.Add("npcpassengers.ui.work_in_progress", "In sviluppo")
language.Add("npcpassengers.ui.under_development", "Questa funzione è in sviluppo")
language.Add("npcpassengers.ui.check_back_later", "Controlla in un futuro aggiornamento!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtra passeggeri attivi per nome, classe, posto, stato o veicolo.")
language.Add("npcpassengers.ui.search_desc_sort", "Ordina la lista visibile dei passeggeri per veicolo, nome, posto, salute o stato.")
language.Add("npcpassengers.ui.search_label_filter", "Filtro passeggeri")
language.Add("npcpassengers.ui.search_label_sort", "Ordinamento passeggeri")

-- Additional keybind names and descriptions
language.Add("npcpassengers.keybind.quick_attach", "Imbarco rapido")
language.Add("npcpassengers.keybind.hold_fire", "NPC mantengono fuoco")
language.Add("npcpassengers.keybind.open_fire", "NPC aprono fuoco")
language.Add("npcpassengers.keybind.cycle_view", "Ciclo camera passeggeri")
language.Add("npcpassengers.keybind.cycle_hud_position", "Ciclo posizione HUD")
language.Add("npcpassengers.keybind.toggle_debug", "Alterna debug bersaglio")
language.Add("npcpassengers.keybind.test_gesture", "Test gesto casuale")
language.Add("npcpassengers.keybind.reset_all", "Ripristina tutti NPC")
language.Add("npcpassengers.keybind.quick_attach.help", "Tieni premuto per far salire rapidamente gli NPC che stai guardando")
language.Add("npcpassengers.keybind.hold_fire.help", "Di ai cecchini NPC di smettere di sparare")
language.Add("npcpassengers.keybind.open_fire.help", "Di ai cecchini NPC di attaccare bersagli")
language.Add("npcpassengers.keybind.cycle_view.help", "Cicla la camera tra i passeggeri")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Sposta l'HUD passeggeri nei quattro angoli")
language.Add("npcpassengers.keybind.toggle_debug.help", "Alterna la piccola sovrapposizione debug bersaglio")
language.Add("npcpassengers.keybind.test_gesture.help", "Riproduci un gesto casuale sul passeggero più vicino")
language.Add("npcpassengers.keybind.reset_all.help", "Ripristina gli stati animazione per tutti i passeggeri")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Come aggiungo un NPC al mio veicolo?")
language.Add("npcpassengers.faq.add_npc.answer", "Usa il menu contestuale (clic destro su NPC) e seleziona 'Rendi passeggero'. O usa il tasto 'Imbarca NPC più vicino'. Gli NPC devono essere amichevoli con te.")
language.Add("npcpassengers.faq.remove_npc", "Come rimuovo i passeggeri dal mio veicolo?")
language.Add("npcpassengers.faq.remove_npc.answer", "Vai alla scheda Passeggeri nelle impostazioni, seleziona un passeggero e clicca Scollega. O usa il tasto 'Scollega tutti NPC'.")
language.Add("npcpassengers.faq.position", "Gli NPC galleggiano o attraversano i sedili!")
language.Add("npcpassengers.faq.position.answer", "Vai alla scheda Posizione e regola gli spostamenti Altezza/Avanti/Destra. Ogni modello veicolo è diverso, quindi potresti dover regolare con precisione i valori. Usa il pannello debug per testare le posizioni in tempo reale.")
language.Add("npcpassengers.faq.speech", "Gli NPC non parlano!")
language.Add("npcpassengers.faq.speech.answer", "Controlla la scheda Comportamento e assicurati che 'Attiva voce NPC' sia attivo. Assicurati anche che il Volume voce sia superiore a 0. Alcuni modelli NPC potrebbero non avere linee vocali disponibili.")
language.Add("npcpassengers.faq.autojoin", "Come funziona l'auto-unisciti?")
language.Add("npcpassengers.faq.autojoin.answer", "Quando attivato nella scheda Auto-Unisciti, gli NPC amici vicini si uniranno automaticamente al tuo veicolo quando sali, come la meccanica della squadra in Half-Life 2. Puoi impostare il raggio di rilevamento e limitare quanti NPC possono unirsi automaticamente.")
language.Add("npcpassengers.faq.death", "Cosa succede quando i passeggeri muoiono?")
language.Add("npcpassengers.faq.death.answer", "I passeggeri morti mostreranno un effetto bagliore rosso e un'icona teschio sull'HUD. Avvicinati al tuo veicolo e tieni premuto R per rimuovere i loro corpi. I corpi verranno espulsi con fisica.")
language.Add("npcpassengers.faq.status", "Cosa significano gli stati dei passeggeri?")
language.Add("npcpassengers.faq.status.answer", "CALMO: Rilassato, nessuna minaccia vicina. ALLARMA: Nemico rilevato. PAURA: Guida pericolosa. SONNOLENZA: Lunga guida calma. MORTO: Salute raggiunta zero.")
language.Add("npcpassengers.faq.keybinds", "I miei tasti non funzionano!")
language.Add("npcpassengers.faq.keybinds.answer", "Vai alla scheda Tasti e assicurati di aver effettivamente impostato i tasti (non sono assegnati per impostazione predefinita). Clicca sul tasto accanto a ogni azione e premi il tasto desiderato. Clic destro per annullare.")
language.Add("npcpassengers.faq.errors", "L'add-on non funziona affatto / Ricevo errori!")
language.Add("npcpassengers.faq.errors.answer", "Assicurati di usare l'ultima versione di Garry's Mod. Controlla la console per errori (tilde ~). Prova a disabilitare add-on in conflitto.")
language.Add("npcpassengers.faq.combat", "I passeggeri possono sparare dal veicolo?")
language.Add("npcpassengers.faq.combat.answer", "Attualmente no. Gli NPC seguiranno i nemici e reagiranno alle minacce, ma non spareranno dalle armi mentre sono seduti. Questa funzione potrebbe essere aggiunta in futuri aggiornamenti.")
language.Add("npcpassengers.faq.stop_autojoin", "Come impedisco agli NPC di unirsi automaticamente?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Disabilita la casella 'Attiva auto-unisciti' nella scheda Auto-Unisciti, o usa il tasto 'Alterna auto-unisciti'.")
language.Add("npcpassengers.faq.settings", "Dove sono salvate le impostazioni?")
language.Add("npcpassengers.faq.settings.answer", "Tutte le impostazioni sono salvate come ConVars nella tua configurazione GMod. Persistono tra le sessioni e sono specifiche del tuo client.")
language.Add("npcpassengers.faq.vehicles", "Funziona con tutti i veicoli?")
language.Add("npcpassengers.faq.vehicles.answer", "Funziona con la maggior parte dei veicoli che hanno fisica. Carri armati, APC, auto, barche, ecc. Alcuni veicoli moddati potrebbero richiedere regolazioni posizione.")
language.Add("npcpassengers.faq.multiple", "Posso avere più NPC in un veicolo?")
language.Add("npcpassengers.faq.multiple.answer", "Sì! Imposta il 'Limite passeggeri' nelle impostazioni generali. L'add-on distribuirà automaticamente gli NPC attorno al veicolo. Per posizioni posto specifiche, regola gli spostamenti nella scheda Posizione.")
language.Add("npcpassengers.faq.crashes", "Gli NPC si comportano in modo strano dopo gli incidenti!")
language.Add("npcpassengers.faq.crashes.answer", "Questo è normale: reagiscono con paura alla guida pericolosa. Riduci la Soglia paura nelle impostazioni HUD se vuoi che siano meno reattivi.")
language.Add("npcpassengers.faq.reset_setting", "Come ripristino solo un'impostazione?")
language.Add("npcpassengers.faq.reset_setting.answer", "Usa il comando console per quella specifica impostazione. Tutti i comandi iniziano con 'nai_npc_'. Digita 'find nai_npc' nella console per vedere tutti i comandi disponibili.")
language.Add("npcpassengers.faq.multiplayer", "Funziona in multiplayer?")
language.Add("npcpassengers.faq.multiplayer.answer", "Sì! L'add-on funziona sia su server singleplayer che multiplayer. Ogni giocatore controlla i propri passeggeri.")
language.Add("npcpassengers.faq.lvs", "Funziona con i veicoli LVS?")
language.Add("npcpassengers.faq.lvs.answer", "Sì! L'add-on ha supporto completo per i veicoli LVS (Lua Vehicle System). Gli NPC possono viaggiare come passeggeri e possono persino guidare veicoli LVS se la modalità autista NPC è attivata.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Queste impostazioni controllano il comportamento dell'interfaccia utente dell'add-on")
language.Add("npcpassengers.panel.performance_note1", "Le modifiche alla dimensione pannello richiedono la chiusura e riapertura del menu")
language.Add("npcpassengers.panel.performance_note2", "Disabilitare suoni o animazioni può migliorare le prestazioni su sistemi basso profilo")
language.Add("npcpassengers.panel.performance_title", "Informazioni impostazioni interfaccia")
language.Add("npcpassengers.help.console_title", "Comandi console per debug:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Attiva modalità debug per vedere informazioni dettagliate")
language.Add("npcpassengers.about.title", "Informazioni")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Lingua cambiata in inglese. Il pannello si aggiornerà automaticamente.")
language.Add("npcpassengers.lang.changed_russian", "Lingua cambiata in russo. Il pannello si aggiornerà automaticamente.")
language.Add("npcpassengers.lang.changed_chinese", "Lingua cambiata in cinese. Il pannello si aggiornerà automaticamente.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Ciao!")
language.Add("npcpassengers.welcome.msg1", "Prima di lamentarti che il passeggero sia seduto sopra il veicolo,\nper favore apri le impostazioni. Puoi farlo, credo in te.")
language.Add("npcpassengers.welcome.msg2", "Questo add-on è ancora lontano dall'essere PERFETTO, per favore non esitare a\nsegnalare bug e suggerire nuove funzionalità. Leggo tutti i vostri commenti!")
language.Add("npcpassengers.welcome.changelog", "Registro modifiche")
language.Add("npcpassengers.welcome.got_it", "Capito!")
language.Add("npcpassengers.welcome.console_cmd", "O usa il comando console: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Classi NPC lista nera")
language.Add("npcpassengers.ui.blacklist_help", "Lista separata da virgole di nomi classi NPC che non possono usare torrette. Usa il comando console 'getnpcblacklist' per vedere la lista nera attuale.")
language.Add("npcpassengers.ui.hud_position", "Posizione HUD")
language.Add("npcpassengers.ui.not_bound", "Non assegnato")
language.Add("npcpassengers.ui.keybind_tip", "Suggerimento: Clic destro su un tasto per annullarlo. Premi ESC durante l'assegnazione per annullare.")
language.Add("npcpassengers.ui.dont_show_again", "Non mostrare più")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Operazioni passeggeri")
language.Add("npcpassengers.hud.filter_prefix", "Filtro: ")
language.Add("npcpassengers.hud.sort_prefix", "Ordina: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Aggiornamento automatico: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Veicolo: ")
language.Add("npcpassengers.hud.speed_prefix", "Velocità: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "ON")
language.Add("npcpassengers.hud.off", "OFF")
language.Add("npcpassengers.hud.passengers", "Passeggeri")
language.Add("npcpassengers.hud.npc_driver", "Autista NPC")
language.Add("npcpassengers.hud.total_prefix", "Totale: ")
language.Add("npcpassengers.hud.showing_prefix", "Mostrando: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Veicolo attuale: ")
language.Add("npcpassengers.hud.hidden_prefix", "Nascosto: ")
language.Add("npcpassengers.hud.dead_prefix", "Morti: ")
language.Add("npcpassengers.hud.scared_prefix", "Spaventati: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Sonnolenti: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Calmo")
language.Add("npcpassengers.status.alert", "Allerta")
language.Add("npcpassengers.status.scared", "Spaventato")
language.Add("npcpassengers.status.drowsy", "Sonnolento")
language.Add("npcpassengers.status.dead", "Morto")
language.Add("npcpassengers.status.unknown", "Sconosciuto")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Cittadino")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Padre Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dr. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Cane")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Veicolo")
language.Add("npcpassengers.sort.name", "Nome")
language.Add("npcpassengers.sort.seat", "Posto")
language.Add("npcpassengers.sort.health", "Salute")
language.Add("npcpassengers.sort.status", "Stato")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Veicolo prima")
language.Add("npcpassengers.sort.name_az", "Nome A-Z")
language.Add("npcpassengers.sort.seat_number", "Numero posto")
language.Add("npcpassengers.sort.highest_health", "Salute più alta")
language.Add("npcpassengers.sort.status_priority", "Priorità stato")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Veicolo: Sconosciuto")
language.Add("npcpassengers.ui.seat_prefix", "Posto ")
language.Add("npcpassengers.ui.same_vehicle", "Stesso veicolo")
language.Add("npcpassengers.ui.other_vehicle", "Altro veicolo")
language.Add("npcpassengers.ui.hidden", "Nascosto")
language.Add("npcpassengers.ui.visible", "Visibile")
language.Add("npcpassengers.ui.health_format", "Salute %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Aggiorna lista passeggeri")
language.Add("npcpassengers.ui.copy_list", "Copia lista visibile passeggeri")
language.Add("npcpassengers.ui.make_exit", "Fai uscire i passeggeri veicolo attuale")
language.Add("npcpassengers.ui.reset_pos", "Ripristina posizione e angoli")
language.Add("npcpassengers.ui.crash_reactions", "Reazioni incidenti")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Suoni imbarco/uscita")
language.Add("npcpassengers.section.ambient_sounds", "Suoni ambientali")
language.Add("npcpassengers.section.gesture_animations", "Animazioni gesti")
language.Add("npcpassengers.section.threat_awareness", "Consapevolezza minacce")
language.Add("npcpassengers.section.emotional_states", "Stati emotivi")
language.Add("npcpassengers.section.turret_control", "Controllo torretta (Sperimentale)")
language.Add("npcpassengers.section.turret_blacklist", "Lista nera torretta NPC")
language.Add("npcpassengers.section.idle_chatter", "Chiacchiere inattive")
language.Add("npcpassengers.section.body_physics", "Fisica corpo")
language.Add("npcpassengers.section.npc_auto_driver", "Autista automatico NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "In basso a sinistra")
language.Add("npcpassengers.hud.bottom_right", "In basso a destra")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Attiva HUD passeggeri")
language.Add("npcpassengers.ui.cover_face", "Coprifaccia")
language.Add("npcpassengers.ui.apply_keybinds", "Applica tasti consigliati")
language.Add("npcpassengers.ui.clear_keybinds", "Cancella tutti i tasti")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Test gesto sobbalto")
language.Add("npcpassengers.ui.test_random", "Test gesto casuale")
language.Add("npcpassengers.ui.reset_states", "Ripristina tutti gli stati")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Attiva tutte le opzioni menu contestuale")
language.Add("npcpassengers.ui.hide_context", "Nascondi tutte le opzioni menu contestuale")
language.Add("npcpassengers.ui.set_compact", "Imposta dimensione pannello compatta")
language.Add("npcpassengers.ui.set_default", "Imposta dimensione pannello predefinito")
language.Add("npcpassengers.ui.set_large", "Imposta dimensione pannello grande")
language.Add("npcpassengers.ui.center_panel", "Centra pannello ora")
language.Add("npcpassengers.ui.reset_ui", "Ripristina tutte le impostazioni UI ai predefiniti")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Cittadino (F)")
language.Add("npcpassengers.role.citizen_male", "Cittadino (M)")
language.Add("npcpassengers.role.medic", "Medico")
language.Add("npcpassengers.role.rebel", "Ribelle")
language.Add("npcpassengers.role.passenger", "Passeggero")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Mostra solo quando nel veicolo")
language.Add("npcpassengers.hud.show_calm", "Mostra passeggeri calmi")
language.Add("npcpassengers.hud.show_hints", "Mostra suggerimenti contestuali")
language.Add("npcpassengers.hud.show_target_debug", "Mostra debug bersaglio")
language.Add("npcpassengers.hud.play_cues", "Riproduci segnali successo/insuccesso")
language.Add("npcpassengers.debug.enable_mode", "Attiva modalità debug")
language.Add("npcpassengers.ui.enable_sounds", "Attiva suoni UI")
language.Add("npcpassengers.ui.hover_sounds", "Suoni hover pulsante")
language.Add("npcpassengers.ui.click_sounds", "Suoni clic pulsante")
language.Add("npcpassengers.ui.enable_animations", "Attiva animazioni UI")
language.Add("npcpassengers.ui.show_tooltips", "Mostra suggerimenti")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Nascondi automaticamente barra scorrimento")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Fluidità scorrimento barra laterale")
language.Add("npcpassengers.ui.color_theme", "Tema colore")
language.Add("npcpassengers.ui.font_scale", "Scala carattere")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Annulla selezione NPC")
language.Add("npcpassengers.context.remove_passenger", "Rimuovi passeggero")
language.Add("npcpassengers.context.blacklist_passenger", "Aggiungi alla lista nera")
language.Add("npcpassengers.context.whitelist_passenger", "Aggiungi alla lista bianca")
language.Add("npcpassengers.context.taxi_passenger", "Assegna come passeggero taxi")

-- Tool labels
language.Add("tool.npcpassengers_taxi_station.name", "Stazione taxi")
language.Add("tool.npcpassengers_taxi_station.desc", "Crea una stazione taxi per il sistema taxi NPC")
language.Add("tool.npcpassengers_taxi_station.0", "Clic sinistro per posizionare una stazione taxi. Clic destro per rimuovere.")
language.Add("tool.npcpassengers_taxi_station.left", "Posiziona stazione")
language.Add("tool.npcpassengers_taxi_station.right", "Rimuovi stazione")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Tasti")
language.Add("npcpassengers.keybinds.desc", "Configura scorciatoie da tastiera per azioni rapide.")
language.Add("npcpassengers.keybind.attach", "Imbarca NPC più vicino")
language.Add("npcpassengers.keybind.attach.help", "Imbarca il NPC amico più vicino nel tuo veicolo.")
language.Add("npcpassengers.keybind.detach_all", "Scollega tutti NPC")
language.Add("npcpassengers.keybind.detach_all.help", "Rimuovi tutti i passeggeri dal tuo veicolo.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Alterna auto-unisciti")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Attiva/disattiva rapidamente l'auto-unisciti.")
language.Add("npcpassengers.keybind.menu", "Apri menu impostazioni")
language.Add("npcpassengers.keybind.menu.help", "Apri il pannello impostazioni.")
language.Add("npcpassengers.keybind.exit_all", "Uscita tutti passeggeri")
language.Add("npcpassengers.keybind.exit_all.help", "Fai uscire tutti i passeggeri dal veicolo.")
language.Add("npcpassengers.keybind.toggle_hud", "Alterna HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Mostra/nascondi l'HUD passeggeri.")
language.Add("npcpassengers.keybind.quick_attach", "Modalità imbarco rapido")
language.Add("npcpassengers.keybind.quick_attach.help", "Tieni premuto per far salire rapidamente gli NPC che stai guardando")
language.Add("npcpassengers.keybind.hold_fire", "NPC mantengono fuoco")
language.Add("npcpassengers.keybind.hold_fire.help", "Di ai cecchini NPC di smettere di sparare")
language.Add("npcpassengers.keybind.open_fire", "NPC aprono fuoco")
language.Add("npcpassengers.keybind.open_fire.help", "Di ai cecchini NPC di attaccare bersagli")
language.Add("npcpassengers.keybind.cycle_view", "Ciclo vista passeggeri")
language.Add("npcpassengers.keybind.cycle_view.help", "Cicla la camera tra i passeggeri")
language.Add("npcpassengers.keybind.cycle_hud_position", "Ciclo posizione HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Sposta l'HUD passeggeri nei quattro angoli")
language.Add("npcpassengers.keybind.toggle_debug", "Alterna debug bersaglio")
language.Add("npcpassengers.keybind.toggle_debug.help", "Alterna la piccola sovrapposizione debug bersaglio")
language.Add("npcpassengers.keybind.test_gesture", "Test gesto casuale")
language.Add("npcpassengers.keybind.test_gesture.help", "Riproduci un gesto casuale sul passeggero più vicino")
language.Add("npcpassengers.keybind.reset_all", "Ripristina tutti NPC")
language.Add("npcpassengers.keybind.reset_all.help", "Ripristina gli stati animazione per tutti i passeggeri")

-- HUD Settings
language.Add("npcpassengers.hud.header", "Impostazioni HUD")
language.Add("npcpassengers.hud.enable", "Attiva HUD")
language.Add("npcpassengers.hud.enable.help", "Mostra la sovrapposizione stato passeggeri sullo schermo.")
language.Add("npcpassengers.hud.position", "Posizione HUD")
language.Add("npcpassengers.hud.position.help", "Dove appare l'HUD sullo schermo.")
language.Add("npcpassengers.hud.position.topleft", "In alto a sinistra")
language.Add("npcpassengers.hud.position.topright", "In alto a destra")
language.Add("npcpassengers.hud.position.bottomleft", "In basso a sinistra")
language.Add("npcpassengers.hud.position.bottomright", "In basso a destra")
language.Add("npcpassengers.hud.scale", "Scala HUD")
language.Add("npcpassengers.hud.scale.help", "Moltiplicatore dimensione per l'HUD.")
language.Add("npcpassengers.hud.opacity", "Opacità HUD")
language.Add("npcpassengers.hud.opacity.help", "Trasparenza sfondo (0 = invisibile, 1 = solido).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Autista NPC")
language.Add("npcpassengers.driver.desc", "Permette agli NPC di guidare veicoli per te.")
language.Add("npcpassengers.driver.enable", "Attiva autisti NPC")
language.Add("npcpassengers.driver.enable.help", "Permette agli NPC di prendere il controllo del veicolo.")
language.Add("npcpassengers.driver.behavior", "Comportamento guida")
language.Add("npcpassengers.driver.behavior.help", "Come l'NPC guida il veicolo.")
language.Add("npcpassengers.driver.behavior.cruise", "Crociera casuale")
language.Add("npcpassengers.driver.behavior.follow", "Segui giocatore")
language.Add("npcpassengers.driver.behavior.patrol", "Pattugliamento")
language.Add("npcpassengers.driver.behavior.flee", "Fuggi")
language.Add("npcpassengers.driver.behavior.parked", "Rimani parcheggiato")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Domande frequenti")
language.Add("npcpassengers.help.desc", "Risposte rapide a domande comuni e risoluzione problemi.")
language.Add("npcpassengers.help.still_need", "Hai ancora bisogno di aiuto?")
language.Add("npcpassengers.help.community", "Unisciti alla nostra community Discord per supporto!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Carro/LVS")
language.Add("npcpassengers.nav.debugging", "Debug")
language.Add("npcpassengers.nav.driver", "Autista NPC")
language.Add("npcpassengers.nav.interface", "Interfaccia")
language.Add("npcpassengers.nav.simulate", "Simula")
language.Add("npcpassengers.nav.modules", "Moduli")
language.Add("npcpassengers.nav.about", "Informazioni")
language.Add("npcpassengers.search.placeholder", "Cerca impostazioni...")

-- About page
language.Add("npcpassengers.about.description", "Sistema passeggeri avanzato con IA emotiva e fisica realistica")
language.Add("npcpassengers.about.feature_status", "Sistema stato: CALMO / ALLARMA / PAURA / SONNOLENZA / MORTO")
language.Add("npcpassengers.about.feature_performance", "Prestazioni: cache posti, timer limitati, hook client ottimizzati")
language.Add("npcpassengers.about.feature_filtering", "Filtraggio veicoli, ricarica tentativi imbarco, auto-unisciti solo squadra")
language.Add("npcpassengers.about.actions", "Azioni")
language.Add("npcpassengers.about.show_welcome", "Mostra schermo benvenuto")
language.Add("npcpassengers.about.open_github", "Apri pagina GitHub")
language.Add("npcpassengers.about.reset_settings", "Ripristina TUTTE le impostazioni ai predefiniti")

-- Status messages
language.Add("npcpassengers.status.calm", "CALMO")
language.Add("npcpassengers.status.alert", "ALLARMA")
language.Add("npcpassengers.status.scared", "PAURA")
language.Add("npcpassengers.status.drowsy", "SONNOLENZA")
language.Add("npcpassengers.status.dead", "MORTO")
language.Add("npcpassengers.status.calm.desc", "Rilassato, nessuna minaccia vicina")
language.Add("npcpassengers.status.alert.desc", "Nemico rilevato, NPC seguendo minacce")
language.Add("npcpassengers.status.scared.desc", "Guida pericolosa (alta velocità, incidenti)")
language.Add("npcpassengers.status.drowsy.desc", "Lunga guida calma, NPC diventa sonnolento")
language.Add("npcpassengers.status.dead.desc", "Salute raggiunta zero")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Auto-Unisciti: ON")
language.Add("npcpassengers.chat.autojoin_off", "Auto-Unisciti: OFF")
language.Add("npcpassengers.chat.hud_on", "HUD: ON")
language.Add("npcpassengers.chat.hud_off", "HUD: OFF")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Nessun veicolo vicino")
language.Add("npcpassengers.error.no_npc", "Nessun NPC vicino")
language.Add("npcpassengers.error.vehicle_full", "Veicolo pieno")
language.Add("npcpassengers.error.too_far", "NPC troppo lontano dal veicolo")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Cambia lingua")
language.Add("npcpassengers.tooltip.minimize", "Minimizza pannello")
language.Add("npcpassengers.tooltip.expand", "Espandi pannello")
language.Add("npcpassengers.tooltip.welcome", "Mostra schermo benvenuto")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Interruttore principale per tutta la voce NPC. Disabilita per rendere i passeggeri completamente silenziosi.")
language.Add("npcpassengers.speech_volume.help", "Quanto forte parlano gli NPC (0 = silenzioso, 100 = volume pieno).")
language.Add("npcpassengers.pitch_variation.help", "Variazione casuale del tono per voci più naturali. 0 = monotono, più alto = più varietà.")
language.Add("npcpassengers.crash_enable.help", "Gli NPC gemono/urloano quando il veicolo decelera bruscamente (incidenti, frenata brusca).")
language.Add("npcpassengers.crash_threshold.help", "Decelerazione necessaria per attivare i suoni incidente. Più basso = più sensibile.")
language.Add("npcpassengers.crash_cooldown.help", "Secondi minimi tra i suoni incidente per NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "Gli NPC parlano occasionalmente durante il viaggio: commenti, domande, osservazioni.")
language.Add("npcpassengers.speech_idle_chance.help", "Probabilità chiacchiere per controllo. 0 = mai, 1 = cerca sempre di parlare.")
language.Add("npcpassengers.speech_idle_interval.help", "Secondi minimi tra tentativi chiacchiere.")
language.Add("npcpassengers.speech_board.help", "Gli NPC parlano quando entrano ed escono dal veicolo.")
language.Add("npcpassengers.ambient_sounds.help", "Tosse occasionale, sospiri, canticchi – suoni vita di sfondo.")
language.Add("npcpassengers.ambient_interval.help", "Secondi medi tra suoni ambientali.")
language.Add("npcpassengers.animation.help", "Regolazione fine animazioni NPC e movimento testa.")
language.Add("npcpassengers.head_look.help", "Gli NPC guardano naturalmente intorno, al giocatore, fuori dalle finestre, ecc.")
language.Add("npcpassengers.head_smooth.help", "Quanto fluidamente si muove la testa. Più basso = più veloce, più alto = più fluttuante.")
language.Add("npcpassengers.blink.help", "Gli NPC sbattono realisticamente mentre sono seduti.")
language.Add("npcpassengers.breathing.help", "Animazione respirazione sottile sulle teste NPC.")
language.Add("npcpassengers.walk_timeout.help", "Secondi prima che l'NPC rinunci a camminare verso il veicolo.")
language.Add("npcpassengers.realism.help", "Reazioni basate sulla fisica e sistemi consapevolezza per massima immersione.")
language.Add("npcpassengers.talking_gestures.help", "Gli NPC riproducono casualmente gesti con le mani e animazioni corpo durante il viaggio.")
language.Add("npcpassengers.gesture_chance.help", "Percentuale probabilità di riprodurre un gesto ogni intervallo.")
language.Add("npcpassengers.gesture_interval.help", "Secondi tra controlli opportunità gesti.")
language.Add("npcpassengers.crash_flinch.help", "Gli NPC sobbalzano e si piegano in avanti quando il veicolo si schianta o frena bruscamente.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Cambio velocità necessario per attivare sobbalto (più basso = più sensibile).")
language.Add("npcpassengers.body_sway.help", "Gli NPC si piegano nelle curve, si appoggiano durante accelerazione/frenata.")
language.Add("npcpassengers.body_sway_amount.help", "Quanto gli NPC oscillano con il movimento veicolo.")
language.Add("npcpassengers.threat_awareness.help", "Gli NPC guardano automaticamente verso i nemici vicini.")
language.Add("npcpassengers.threat_range.help", "Quanto lontano gli NPC possono rilevare minacce per il tracciamento testa.")
language.Add("npcpassengers.combat_alert.help", "Gli NPC diventano tesi e reattivi quando i nemici sono vicini.")
language.Add("npcpassengers.passenger_combat.help", "Disabilitato per impostazione predefinita. Attiva questo per permettere ai passeggeri armati di sparare dall'interno del veicolo.")
language.Add("npcpassengers.passenger_combat_range.help", "Quanto lontano i passeggeri armati possono acquisire bersagli.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Valori più alti riducono la diffusione sparo per passeggeri armati.")
language.Add("npcpassengers.passenger_combat_damage.help", "Scala il danno inflitto da spari passeggero.")
language.Add("npcpassengers.passenger_interaction.help", "Più passeggeri si guardano e occasionalmente chiacchierano tra loro.")
language.Add("npcpassengers.fear_reactions.help", "Gli NPC hanno paura della guida pericolosa – occhi spalancati, suoni panico.")
language.Add("npcpassengers.fear_speed_threshold.help", "Velocità (unità/sec) alla quale gli NPC iniziano a diventare nervosi.")
language.Add("npcpassengers.drowsiness.help", "Gli NPC diventano sonnolenti su lunghi viaggi calmi – sbattiti lenti, annuire con la testa.")
language.Add("npcpassengers.drowsy_time.help", "Secondi guida calma prima che la sonnolenza inizi.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Impostazioni per carri armati, APC e veicoli LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Rende i passeggeri NPC invisibili quando sono dentro carri armati e APC.")
language.Add("npcpassengers.eject_stuck_check.help", "Espelle automaticamente gli NPC dal veicolo quando rimangono bloccati durante l'espulsione. Previene gli NPC dal finire nel veicolo all'uscita.")
language.Add("npcpassengers.detach_no_collide.help", "Dopo lo scollegamento, gli NPC attraversano temporaneamente il veicolo per poter allontanarsi senza clipping o blocco.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Quanto a lungo gli NPC ignorano la collisione veicolo dopo lo scollegamento.")
language.Add("npcpassengers.die_with_vehicle.help", "I passeggeri NPC muoiono quando il loro veicolo viene distrutto da esplosione o fuoco (più immersivo di se escono illesi dai rottami).")
language.Add("npcpassengers.tank_driver.help", "Permette agli NPC sul posto autista di guidare automaticamente verso i nemici.")
language.Add("npcpassengers.tank_driver_range.help", "Raggio massimo per l'autista rilevare nemici.")
language.Add("npcpassengers.tank_driver_distance.help", "Distanza da mantenere dai nemici.")
language.Add("npcpassengers.tank_driver_throttle.help", "Quantità acceleratore (0.1 = lento, 1 = velocità piena).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distanza alla quale retromarcare dai nemici.")
language.Add("npcpassengers.tank_turret.help", "Permette agli NPC di controllare le torrette sui veicoli LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Mostra lo stato passeggeri (emozioni, allerta) sullo schermo durante la guida.")
language.Add("npcpassengers.hud_show_calm.help", "Quando disabilitato, mostra solo passeggeri con stato non calmo.")
language.Add("npcpassengers.hud_thresholds.desc", "Quando i livelli emozione superano queste soglie, i passeggeri mostrano questo stato nell'HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Livello allerta necessario per mostrare stato 'ALLARMA' (minaccia rilevata).")
language.Add("npcpassengers.hud_fear_threshold.help", "Livello paura necessario per mostrare stato 'PAURA' (guida pericolosa).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Rapporto tempo calmo necessario per mostrare stato 'SONNOLENZA' (lunga guida calma).")
language.Add("npcpassengers.hud_actions.desc", "Scegli quale azione intraprendono i passeggeri quando sperimentano ogni stato emotivo.")
language.Add("npcpassengers.hud_actions_note", "Nota: Alcune azioni potrebbero non essere visibili a seconda del supporto modello NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Imposta tasti personalizzati per azioni passeggero NPC. Clicca un pulsante e premi un tasto per assegnare.")
language.Add("npcpassengers.keybinds_hud.desc", "Controlli rapidi HUD per mostrare, spostare e debuggare la sovrapposizione passeggeri.")
language.Add("npcpassengers.keybinds_debug_note", "I tasti debug funzionano solo quando la modalità debug è attivata.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Strumenti debug avanzati per testare il comportamento NPC. Attiva prima la modalità debug nelle impostazioni.")
language.Add("npcpassengers.debug_mode.help", "Mostra pulsanti test debug e attiva comandi debug.")
language.Add("npcpassengers.debug_status.help", "Imposta manualmente lo stato passeggero per test. Clicca 'Aggiorna lista' per vedere i passeggeri attuali.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configura effetti sonori per pulsanti, checkbox e altri elementi UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Interruttore principale per tutti gli effetti sonori UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Moltiplicatore volume per suoni UI (1.0 = normale, 2.0 = doppio)")
language.Add("npcpassengers.ui_hover_enabled.help", "Riproduci suono quando hover sopra pulsanti")
language.Add("npcpassengers.ui_click_enabled.help", "Riproduci suono quando clic su pulsanti e checkbox")
language.Add("npcpassengers.context_menu.desc", "Scegli quali opzioni appaiono quando clic destro su NPC")
language.Add("npcpassengers.context_make_passenger.help", "Aggiungi NPC come passeggero al tuo veicolo attuale")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Aggiungi NPC a un veicolo specifico (clic NPC, poi veicolo)")
language.Add("npcpassengers.context_detach.help", "Rimuovi NPC dal veicolo")
language.Add("npcpassengers.ui_show_welcome.help", "Mostra pannello benvenuto quando l'add-on viene aggiornato a una nuova versione")
language.Add("npcpassengers.ui_panel_width.help", "Larghezza pannello impostazioni")
language.Add("npcpassengers.ui_panel_height.help", "Altezza pannello impostazioni")
language.Add("npcpassengers.ui_animations.help", "Transizioni fluide ed effetti hover (possono influire sulle prestazioni)")
language.Add("npcpassengers.ui_tooltips.help", "Mostra suggerimenti utili quando hover sopra le impostazioni")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Mostra la barra scorrimento solo mentre scorri o ci passi sopra.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Nota: Il pannello diventa 70% trasparente quando trascini qualsiasi cursore per vedere il contenuto in background.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Valori più bassi = più fluido ma più lento scorrimento (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Scegli un tema colore per il pannello impostazioni. I cambiamenti si applicano immediatamente.")
language.Add("npcpassengers.ui_font_scale.help", "Scala tutte le dimensioni carattere UI. 1.0 = predefinito, 0.5 = metà dimensione, 2.0 = doppia dimensione.")

print("[Better NPC Passengers] Italian localization loaded!")
