-- Better NPC Passengers - Japanese Localization
-- 日本語ローカライゼーションファイル

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "最高級NPC乗客")
language.Add("npcpassengers.settings", "設定")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "一般")
language.Add("npcpassengers.nav.autojoin", "自動参加")
language.Add("npcpassengers.nav.passengers", "乗客")
language.Add("npcpassengers.nav.position", "位置")
language.Add("npcpassengers.nav.behaviour", "挙動")
language.Add("npcpassengers.nav.keybinds", "キーバインド")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "運転手")
language.Add("npcpassengers.nav.help", "ヘルプ")

-- General Settings
language.Add("npcassengers.general.header", "一般設定")
language.Add("npcpassengers.allow_multiple", "複数の乗客を許可")
language.Add("npcpassengers.allow_multiple.help", "同じ車両に複数のNPCが搭乗できるようにします。")
language.Add("npcpassengers.exit_behavior", "降車挙動")
language.Add("npcpassengers.exit_behavior.help", "NPC乗客はいつ車両を降りるべきですか？")
language.Add("npcassengers.exit_mode.leave_player", "プレイヤーが降りる時に降りる")
language.Add("npcpassengers.exit_mode.leave_attack", "車両が攻撃された時に降りる")
language.Add("npcpassengers.exit_mode.never", "自動的に降りない")

-- Timing Settings
language.Add("npcpassengers.timing.header", "タイミング")
language.Add("npcpassengers.max_attach_dist", "最大アタッチ距離")
language.Add("npcpassengers.max_attach_dist.help", "NPCを車両にアタッチする最大距離（単位）。")
language.Add("npcpassengers.detach_delay", "デタッチ遅延")
language.Add("npcpassengers.detach_delay.help", "プレイヤーが降りた後にデタッチするまで待機する秒数。")
language.Add("npcpassengers.ai_delay", "AI復元遅延")
language.Add("npcpassengers.ai_delay.help", "デタッチ後にNPCのAIを復元するまで待機する秒数。")
language.Add("npcpassengers.cooldown", "クールダウン")
language.Add("npcpassengers.cooldown.help", "同じ車両にNPCをアタッチする間のクールダウン。")
language.Add("npcpassengers.passenger_limit", "乗客制限")
language.Add("npcpassengers.passenger_limit.help", "車両で許可されるNPCの最大数。")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "自動参加（分隊挙動）")
language.Add("npcpassengers.autojoin.desc", "フレンドリーなNPCがあなたが乗り込むと自動的に乗り込みます - Half-Life 2の分隊メカニクと同じ！")
language.Add("npcpassengers.autojoin.enable", "自動参加を有効にする")
language.Add("npcpassengers.autojoin.enable.help", "近くのフレンドリーなNPCがあなたが車両に乗り込むと自動的に乗り込みます。")
language.Add("npcpassengers.autojoin.range", "自動参加範囲")
language.Add("npcpassengers.autojoin.range.help", "自動参加のNPCを見つける最大距離。")
language.Add("npcpassengers.autojoin.max", "自動参加最大NPC数")
language.Add("npcpassengers.autojoin.max.help", "一度に自動参加できるNPCの最大数。")
language.Add("npcpassengers.autojoin.squad_only", "分隊メンバーのみ")
language.Add("npcpassengers.autojoin.squad_only.help", "分隊名を持つNPCのみが自動参加します（HL2スタイルの分隊用）。")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "フレンドリーなNPCがあなたが乗り込むと自動的に乗り込みます - Half-Life 2の分隊メカニクと同じ！")
language.Add("npcpassengers.panel.passengers.header", "乗客制御")
language.Add("npcpassengers.panel.passengers.desc", "アクティブな乗客を管理し、名前/クラス/状態でフィルタリングし、デバッグ情報をコピーし、シートを再割り当てし、設定パネルを離れずに乗客をデタッチします。")
language.Add("npcpassengers.panel.position.desc", "車両内のNPCの位置を微調整します。浮遊や重なり問題を修正するのに使用します。")
language.Add("npcpassengers.panel.angle.desc", "車両内のNPCの回転を調整します。")
language.Add("npcpassengers.panel.speech.desc", "車両に乗っている間のNPCのボイスを設定します。HL2スタイルの市民ボイス！")

-- Position Settings
language.Add("npcpassengers.position.header", "位置オフセット")
language.Add("npcpassengers.position.desc", "車両内のNPCの位置を微調整します。浮遊や重なり問題を修正するのに使用します。")
language.Add("npcpassengers.height_offset", "高さオフセット")
language.Add("npcpassengers.forward_offset", "前方オフセット")
language.Add("npcpassengers.right_offset", "右オフセット")
language.Add("npcpassengers.angle.header", "角度オフセット")
language.Add("npcpassengers.angle.desc", "車両内のNPCの回転を調整します。")
language.Add("npcpassengers.yaw_offset", "ヨー（回転）")
language.Add("npcpassengers.pitch_offset", "ピッチ（前方傾斜）")
language.Add("npcpassengers.roll_offset", "ロール（側方傾斜）")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPCボイス（高度）")
language.Add("npcpassengers.behaviour.desc", "車両に乗っている間のNPCのボイスを設定します。HL2スタイルの市民ボイス！")
language.Add("npcpassengers.speech_enable", "NPCボイスを有効にする")
language.Add("npcpassengers.speech_enable.help", "全NPCボイスのマスター切り替え。乗客を完全にミュートにするには無効にします。")
language.Add("npcpassengers.speech_volume", "ボイス音量")
language.Add("npcpassengers.speech_volume.help", "NPCボイスの音量（0 = ミュート、100 = フルボリューム）。")
language.Add("npcpassengers.pitch_variation", "ピッチ変動（+/-）")
language.Add("npcpassengers.pitch_variation.help", "より自然なボイスのためのランダムピッチ変動。0 = 単調、高い = 多様性が増加。")
language.Add("npcpassengers.crash.header", "衝突反応")
language.Add("npcpassengers.crash_enable", "衝突音を有効にする")
language.Add("npcpassengers.crash_enable.help", "車両が急減速するとNPCがうめく/悲鳴を上げます（衝突、急ブレーキ）。")
language.Add("npcpassengers.crash_threshold", "衝突感度")
language.Add("npcpassengers.crash_threshold.help", "衝突音をトリガーするために必要な減速。低い = より敏感。")
language.Add("npcpassengers.crash_cooldown", "衝突音クールダウン")
language.Add("npcpassengers.crash_cooldown.help", "NPCごとの衝突音間の最小秒数。")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "アイドルチャットを有効にする")
language.Add("npcpassengers.speech_board", "乗降音を有効にする")
language.Add("npcpassengers.ambient_sounds", "アンビエント音を有効にする")
language.Add("npcpassengers.head_look", "ヘッド/アイルックを有効にする")
language.Add("npcpassengers.blink", "瞬きを有効にする")
language.Add("npcpassengers.breathing", "呼吸を有効にする")
language.Add("npcpassengers.talking_gestures", "話し中のジェスチャーを有効にする")
language.Add("npcpassengers.crash_flinch", "衝突フリンチを有効にする")
language.Add("npcpassengers.body_sway", "ボディスウェイを有効にする")
language.Add("npcpassengers.threat_awareness", "脅威認識を有効にする")
language.Add("npcpassengers.combat_alert", "戦闘アラート")
language.Add("npcpassengers.passenger_combat", "NPCが車両から発砲（実験的）")
language.Add("npcpassengers.passenger_interaction", "乗客インタラクション")
language.Add("npcpassengers.fear_reactions", "恐怖反応を有効にする")
language.Add("npcassengers.drowsiness", "眠気を有効にする")
language.Add("npcpassengers.hide_in_tanks", "密閉車両内のNPCを非表示")
language.Add("npcpassengers.eject_stuck_check", "スタックしたNPCの自動排出")
language.Add("npcpassengers.detach_no_collide", "デタッチ後車両との衝突なし")
language.Add("npcpassengers.die_with_vehicle", "車両爆発時に乗客を殺す")
language.Add("npcpassengers.driver_enabled", "自動運転を有効にする")
language.Add("npcpassengers.turret_enabled", "タレット制御を有効にする")
language.Add("npcpassengers.turret_lead_targets", "ターゲットを予測")
language.Add("npcpassengers.turret_friendly_fire", "フレンドリーファイアを許可")
language.Add("npcpassengers.turret_hold_fire", "発砲ホールド（発砲無効）")

-- Slider labels
language.Add("npcpassengers.speech_volume", "ボイス音量")
language.Add("npcpassengers.pitch_variation", "ピッチ変動（+/-）")
language.Add("npcpassengers.crash_threshold", "衝突感度")
language.Add("npcpassengers.crash_cooldown", "衝突音クールダウン")
language.Add("npcpassengers.speech_idle_chance", "チャット確率")
language.Add("npcpassengers.speech_idle_interval", "チャット間隔")
language.Add("npcpassengers.ambient_interval", "アンビエント音間隔")
language.Add("npcpassengers.head_smooth", "ヘッド滑らかさ")
language.Add("npcpassengers.walk_timeout", "歩行タイムアウト")
language.Add("npcpassengers.gesture_chance", "ジェスチャー確率（%）")
language.Add("npcpassengers.gesture_interval", "ジェスチャー間隔")
language.Add("npcpassengers.crash_threshold_flinch", "衝突感度")
language.Add("npcassengers.body_sway_amount", "スウェイ強度")
language.Add("npcpassengers.threat_range", "脅威検知範囲")
language.Add("npcpassengers.passenger_combat_range", "乗客戦闘範囲")
language.Add("npcpassengers.passenger_combat_accuracy", "乗客精度")
language.Add("npcpassengers.passenger_combat_damage", "乗客ダメージ倍率")
language.Add("npcpassengers.fear_speed_threshold", "恐怖速度閾値")
language.Add("npcpassengers.drowsy_time", "眠気時間")
language.Add("npcpassengers.detach_no_collide_duration", "衝突なし持続時間（秒）")
language.Add("npcpassengers.tank_driver_range", "検知範囲")
language.Add("npcpassengers.tank_driver_engage_distance", "交戦距離")
language.Add("npcpassengers.tank_driver_speed", "運転速度")
language.Add("npcpassengers.tank_driver_reverse_distance", "後退距離")
language.Add("npcpassengers.turret_range", "ターゲット範囲")
language.Add("npcpassengers.turret_accuracy", "精度")
language.Add("npcpassengers.turret_reaction_time", "反応時間")
language.Add("npcpassengers.turret_fire_delay", "発砲遅延")
language.Add("npcpassengers.turret_aim_speed", "照準速度")
language.Add("npcpassengers.hud_scale", "HUDスケール")
language.Add("npcpassengers.hud_opacity", "HUD不透明度")
language.Add("npcpassengers.hud_alert_threshold", "アラート閾値")
language.Add("npcpassengers.hud_fear_threshold", "恐怖閾値")
language.Add("npcpassengers.hud_drowsy_threshold", "眠気閾値")
language.Add("npcpassengers.ui_sounds_volume", "UIサウンド音量")
language.Add("npcpassengers.ui_panel_width", "パネル幅")

-- Section headers
language.Add("npcpassengers.section.animation", "アニメーションと挙動")
language.Add("npcpassengers.section.realism", "高度なリアリズム")
language.Add("npcpassengers.section.hud_position", "HUD位置とスタイル")
language.Add("npcpassengers.section.emotion_thresholds", "感情閾値")
language.Add("npcpassengers.section.emotion_actions", "感情アクション")
language.Add("npcpassengers.section.vehicle_control", "車両制御")
language.Add("npcpassengers.section.hud_controls", "HUDコントロール")
language.Add("npcpassengers.section.debug_controls", "デバッグコントロール")
language.Add("npcassengers.section.passenger_status", "乗客状態制御")
language.Add("npcpassengers.section.quick_test", "クイックテストボタン")
language.Add("npcpassengers.section.driver_system", "NPC運転手システム")
language.Add("npcpassengers.section.ui_sounds", "UIサウンド設定")
language.Add("npcpassengers.section.appearance", "外観")
language.Add("npcpassengers.section.context_menu", "コンテキストメニューオプション")
language.Add("npcpassengers.section.panel_preferences", "設定パネル設定")
language.Add("npcpassengers.section.performance", "パフォーマンスと技術")
language.Add("npcpassengers.section.simulation", "シミュレーションシステム")
language.Add("npcpassengers.section.modules", "モジュールシステム")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "シート割り当て")
language.Add("npcpassengers.btn.detach", "デタッチ")
language.Add("npcpassengers.btn.copy_summary", "サマリーをコピー")
language.Add("npcpassengers.btn.copy_debug", "デバッグをコピー")
language.Add("npcpassengers.btn.enable_all_speech", "全ボイスを有効にする")
language.Add("npcpassengers.btn.disable_all_speech", "全ボイスを無効にする")
language.Add("npcpassengers.btn.show_current_vehicle", "現在の車両のみ表示")
language.Add("npcpassengers.btn.auto_refresh", "表示リストの自動更新")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "現在の車両が検出されません。車両に乗るか、現在の車両フィルターを無効にしてください。")
language.Add("npcpassengers.status.no_match_filter", "フィルターに一致する乗客がいません。名前、クラス、シート番号、状態、または車両クラスを試してください。")
language.Add("npcpassengers.status.no_passengers_vehicle", "現在の車両に乗客が見つかりません。")
language.Add("npcpassengers.status.no_passengers", "乗客が見つかりません。NPCはここで管理される前に車両に乗っている必要があります。")
language.Add("npcpassengers.status.all_passengers", "全乗客")
language.Add("npcpassengers.status.current_vehicle_only", "現在の車両のみ")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+Fで検索にフォーカス")
language.Add("npcengers.status.no_matches", "一致する設定なし")
language.Add("npcpassengers.status.showing_matches", "%d件の一致のうち上位%d件を表示")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "設定を開く")
language.Add("npcpassengers.menu.reset_all", "全設定をリセット")

-- Button states
language.Add("npcpassengers.state.on", "オン")
language.Add("npcpassengers.state.off", "オフ")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "自動参加")
language.Add("npcpassengers.chat.hud_status", "乗客HUD")
language.Add("npcpassengers.chat.hud_position", "HUD位置")
language.Add("npcpassengers.chat.target_debug", "ターゲットデバッグ")
language.Add("npcpassengers.chat.turret_gunners", "タレットガンナー")
language.Add("npcpassengers.chat.turret_holding", "発砲ホールド")
language.Add("npcpassengers.chat.turret_fire", "発砲オープン")
language.Add("npcpassengers.chat.unknown", "不明")
language.Add("npcpassengers.chat.nothing_copy", "コピーするものがありません。")
language.Add("npcpassengers.chat.clipboard_unavailable", "このバージョンではクリップボードへのアクセスが利用できません。")
language.Add("npcpassengers.chat.copied_clipboard", "クリップボードにコピーしました。")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "この乗客を再割り当てするには同じ車両に乗ってください。")
language.Add("npcpassengers.chat.no_visible_passengers", "コピーする表示中の乗客がいません。")
language.Add("npcpassengers.chat.need_vehicle", "これを使用するには車両に乗る必要があります。")
language.Add("npcpassengers.chat.keybinds_applied", "推奨キーバインドを適用しました。")
language.Add("npcpassengers.chat.keybinds_cleared", "全キーバインドをクリアしました。")
language.Add("npcpassengers.chat.context_enabled", "全コンテキストメニューオプションを有効にしました。")
language.Add("npcpassengers.chat.context_hidden", "全コンテキストメニューオプションを非表示にしました。")
language.Add("npcpassengers.chat.panel_compact", "パネルサイズをコンパクトに設定しました。")
language.Add("npcpassengers.chat.panel_default", "パネルサイズをデフォルトに設定しました。")
language.Add("npcpassengers.chat.panel_large", "パネルサイズをラージに設定しました。")
language.Add("npcpassengers.chat.panel_centered", "パネルを中央に配置しました。")
language.Add("npcpassengers.chat.settings_reset", "全UI設定がデフォルト値にリセットされました！")
language.Add("npcpassengers.chat.npc_selected", "NPCが選択されました！次に車両を右クリックして「選択したNPCを追加」を選択してください")
language.Add("npcpassengers.chat.adding_npc", "NPCを車両に追加中...")
language.Add("npcpassengers.chat.selection_cancelled", "NPC選択がキャンセルされました")
language.Add("npcassengers.chat.summary_copied", "乗客サマリーをコピーしました。")
language.Add("npcpassengers.chat.debug_copied", "乗客デバッグ情報をコピーしました。")
language.Add("npcpassengers.chat.no_passengers_found", "乗客が見つかりません。NPCは車両に乗っている必要があります。")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "状態強度 %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "乗客をフィルタリング...")
language.Add("npcpassengers.ui.press_key", "キーを押してください...")
language.Add("npcpassengers.ui.work_in_progress", "作業中")
language.Add("npcpassengers.ui.under_development", "この機能は現在開発中です")
language.Add("npcpassengers.ui.check_back_later", "将来の更新で確認してください！")
language.Add("npcpassengers.ui.search_desc_passengers", "名前、クラス、シート、状態、または車両でアクティブな乗客をフィルタリングします。")
language.Add("npcpassengers.ui.search_desc_sort", "表示中の乗客リストを車両、名前、シート、ヘルス、または状態で並べ替えます。")
language.Add("npcpassengers.ui.search_label_filter", "乗客フィルター")
language.Add("npcpassengers.ui.search_label_sort", "乗客順序")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "車両にNPCを追加するには？")
language.Add("npcpassengers.faq.add_npc.answer", "コンテキストメニュー（NPCを右クリック）を使用し、「乗客にする」を選択します。または「最も近いNPCをアタッチ」キーバインドを使用します。NPCはあなたにフレンドリーである必要があります。")
language.Add("npcpassengers.faq.remove_npc", "車両から乗客を削除するには？")
language.Add("npcpassengers.faq.remove_npc.answer", "設定の乗客タブに移動し、乗客を選択してデタッチをクリックします。または「全乗客をデタッチ」キーバインドを使用します。")
language.Add("npcpassengers.faq.position", "NPCが浮遊/シートを通り抜けています！")
language.Add("npcpassengers.faq.position.answer", "位置タブに移動し、高さ/前方/右オフセットを調整します。各車両モデルは異なるため、これらの値を調整する必要がある場合があります。リアルタイムで位置をテストするにはデバッグパネルを使用します。")
language.Add("npcpassengers.faq.speech", "NPCが話しません！")
language.Add("npcpassengers.faq.speech.answer", "挙動タブを確認し、「NPCボイスを有効にする」が有効になっていることを確認してください。ボイス音量が0以上であることも確認してください。一部のNPCモデルは利用可能なボイス行がない場合があります。")
language.Add("npcpassengers.faq.autojoin", "自動参加はどのように機能しますか？")
language.Add("npcpassengers.faq.autojoin.answer", "自動参加タブで有効になると、フレンドリーなNPCがあなたが乗り込むと自動的に乗り込みます - Half-Life 2の分隊メカニクと同じ！検知範囲を設定し、自動参加できるNPCの数を制限できます。")
language.Add("npcassengers.faq.death", "乗客が死んだときどうなりますか？")
language.Add("npcpassengers.faq.death.answer", "死亡した乗客は赤い輝きエフェクトを表示し、HUDに頭蓋骨アイコンを表示します。車両に近づき、Rを押し続けて彼らの体を削除します。体は物理で排出されます。")
language.Add("npcpassengers.faq.status", "乗客の状態はどういう意味ですか？")
language.Add("npcpassengers.faq.status.answer", "穏やか: リラックス、近くに脅威なし。警告: 敵検出、NPCは脅威を追跡。恐怖: 危険な運転（高速、衝突）。眠気: 長く穏やかな乗車。死亡: ヘルスがゼロに到達。")
language.Add("npcpassengers.faq.keybinds", "キーバインドが機能しません！")
language.Add("npcpassengers.faq.keybinds.answer", "キーバインドタブに移動し、実際にキーバインドを定義したことを確認してください（デフォルトでは割り当てられていません）。各アクションの横のボタンをクリックし、希望するキーを押します。右クリックで割り当て解除。")
language.Add("npcpassengers.faq.errors", "アドオンがまったく機能しない / エラーが発生しています！")
language.Add("npcpassengers.faq.errors.answer", "Garry's Modの最新バージョンを実行していることを確認してください。エラーについてはコンソールを確認してください（チルダキー ~ キー）。競合するアドオンを無効にしてみてください。")
language.Add("npcpassengers.faq.combat", "乗客は車両から発砲できますか？")
language.Add("npcpassengers.faq.combat.answer", "現在はいいえ。NPCは敵を追跡し脅威に反応しますが、座っている間は武器を発砲しません。この機能は将来の更新で追加される可能性があります。")
language.Add("npcpassengers.faq.stop_autojoin", "NPCの自動参加を止めるには？")
language.Add("npcpassengers.faq.stop_autojoin.answer", "自動参加タブの「自動参加を有効にする」チェックボックスを無効にするか、「自動参加を切り替え」キーバインドを使用します。")
language.Add("npcpassengers.faq.settings", "設定はどこに保存されますか？")
language.Add("npcpassengers.faq.settings.answer", "すべての設定はGMod設定のConVarsとして保存されます。セッション間で維持され、クライアント固有です。")
language.Add("npcpassengers.faq.vehicles", "これはすべての車両で機能しますか？")
language.Add("npcassengers.faq.vehicles.answer", "物理を持つほとんどの車両で機能します。戦車、APC、車、ボートなど。一部のmod車両は位置調整が必要な場合があります。")
language.Add("npcpassengers.faq.multiple", "1台の車両に複数のNPCを乗せられますか？")
language.Add("npcpassengers.faq.multiple.answer", "はい！一般設定で「乗客制限」を設定します。アドオンは自動的にNPCを車両の周囲に分散します。特定のシート位置については、位置タブでオフセットを調整します。")
language.Add("npcpassengers.faq.crashes", "衝突後、NPCが奇妙に振る舞っています！")
language.Add("npcpassengers.faq.crashes.answer", "これは正常です - 彼らは危険な運転に恐怖で反応します。あまり反応させたくない場合は、HUD設定で恐怖閾値を下げてください。")
language.Add("npcpassengers.faq.reset_setting", "1つの設定のみをリセットするには？")
language.Add("npcpassengers.faq.reset_setting.answer", "その特定の設定のコンソールコマンドを使用します。すべてのコマンドは「nai_npc_」で始まります。コンソールで「find nai_npc」と入力して利用可能な全コマンドを表示します。")
language.Add("npcpassengers.faq.multiplayer", "これはマルチプレイヤーで機能しますか？")
language.Add("npcpassengers.faq.multiplayer.answer", "はい！アドオンはシングルプレイヤーとマルチプレイヤーサーバーの両方で機能します。各プレイヤーは独自の乗客を制御します。")
language.Add("npcpassengers.faq.lvs", "これはLVS車両で機能しますか？")
language.Add("npcpassengers.faq.lvs.answer", "はい！アドオンはLVS（Lua Vehicle System）車両の完全なサポートを提供しています。NPCは乗客として乗ることができ、NPC運転手モードが有効な場合はLVS車両を運転することさえできます。")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "これらの設定はアドオンのユーザーインターフェイスの動作を制御します")
language.Add("npcpassengers.panel.performance_note1", "パネルサイズの変更にはメニューを閉じて再度開く必要があります")
language.Add("npcpassengers.panel.performance_note2", "サウンドやアニメーションを無効にすると、ローエンドシステムでパフォーマンスが向上する場合があります")
language.Add("npcpassengers.panel.performance_title", "インターフェース設定情報")
language.Add("npcpassengers.help.console_title", "デバッグ用コンソールコマンド:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- デバッグモードを有効にして詳細情報を表示")
language.Add("npcpassengers.about.title", "について")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")
language.Add("npcpassengers.lang.changed_portuguese", "Idioma alterado para português. O painel será atualizado automaticamente.")
language.Add("npcpassengers.lang.changed_german", "Sprache auf Deutsch geändert. Das Panel wird automatisch aktualisiert.")
language.Add("npcpassengers.lang.changed_french", "Langue changée en français. Le panneau s'actualisera automatiquement.")
language.Add("npcpassengers.lang.changed_japanese", "言語が日本語に変更されました。パネルは自動的に更新されます。")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "こんにちは！")
language.Add("npcpassengers.welcome.msg1", "乗客が車両の上に座っていることを文句を言う前に、\n設定を開いてください。あなたならできます、私はあなたを信じています。")
language.Add("npcpassengers.welcome.msg2", "このアドオンはまだPERFECTからはほど遠いので、遠慮なく\nバグを報告し、新機能を提案してください。すべてのコメントを読んでいます！")
language.Add("npcpassengers.welcome.changelog", "更新ログ")
language.Add("npcpassengers.welcome.got_it", "了解！")
language.Add("npcpassengers.welcome.console_cmd", "またはコンソールコマンドを使用: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "ブラックリストNPCクラス")
language.Add("npcpassengers.ui.blacklist_help", "タレットを使用できないNPCクラス名のカンマ区切りリスト。現在のブラックリストを表示するには「getnpcblacklist」コンソールコマンドを使用します。")
language.Add("npcpassengers.ui.hud_position", "HUD位置")
language.Add("npcpassengers.ui.not_bound", "未割り当て")
language.Add("npcpassengers.ui.keybind_tip", "ヒント: キーバインドを右クリックして割り当て解除。割り当て中にESCを押してキャンセル。")
language.Add("npcpassengers.ui.dont_show_again", "今後表示しない")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "乗客操作")
language.Add("npcpassengers.hud.filter_prefix", "フィルター: ")
language.Add("npcpassengers.hud.sort_prefix", "並べ替え: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  自動更新: ")
language.Add("npcpassengers.hud.vehicle_prefix", "車両: ")
language.Add("npcpassengers.hud.speed_prefix", "速度: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "オン")
language.Add("npcpassengers.hud.off", "オフ")
language.Add("npcpassengers.hud.passengers", "乗客")
language.Add("npcpassengers.hud.npc_driver", "NPC運転手")
language.Add("npcpassengers.hud.total_prefix", "合計: ")
language.Add("npcpassengers.hud.showing_prefix", "表示中: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "現在の車両: ")
language.Add("npcpassengers.hud.hidden_prefix", "非表示: ")
language.Add("npcpassengers.hud.dead_prefix", "死亡: ")
language.Add("npcpassengers.hud.scared_prefix", "恐怖: ")
language.Add("npcpassengers.hud.drowsy_prefix", "眠気: ")

-- Status labels
language.Add("npcpassengers.status.calm", "穏やか")
language.Add("npcpassengers.status.alert", "警告")
language.Add("npcpassengers.status.scared", "恐怖")
language.Add("npcpassengers.status.drowsy", "眠気")
language.Add("npcpassengers.status.dead", "死亡")
language.Add("npcpassengers.status.unknown", "不明")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "市民")
language.Add("npcpassengers.npc.alyx", "アリックス")
language.Add("npcpassengers.npc.barney", "バーニー")
language.Add("npcpassengers.npc.monk", "グリゴリー神父")
language.Add("npcpassengers.npc.vortigaunt", "ヴォーティガント")
language.Add("npcpassengers.npc.eli", "イーライ")
language.Add("npcpassengers.npc.kleiner", "クライナー博士")
language.Add("npcpassengers.npc.mossman", "モスマン博士")
language.Add("npcpassengers.npc.breen", "ブリーン博士")
language.Add("npcpassengers.npc.dog", "ドッグ")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "車両")
language.Add("npcassengers.sort.name", "名前")
language.Add("npcpassengers.sort.seat", "シート")
language.Add("npcpassengers.sort.health", "ヘルス")
language.Add("npcpassengers.sort.status", "状態")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "車両優先")
language.Add("npcpassengers.sort.name_az", "名前A-Z")
language.Add("npcpassengers.sort.seat_number", "シート番号")
language.Add("npcpassengers.sort.highest_health", "最高ヘルス")
language.Add("npcpassengers.sort.status_priority", "状態優先")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "車両: 不明")
language.Add("npcpassengers.ui.seat_prefix", "シート ")
language.Add("npcpassengers.ui.same_vehicle", "同一車両")
language.Add("npcpassengers.ui.other_vehicle", "他の車両")
language.Add("npcpassengers.ui.hidden", "非表示")
language.Add("npcpassengers.ui.visible", "表示")
language.Add("npcpassengers.ui.health_format", "ヘルス %d / %d")
language.Add("npcpassengers.ui.refresh_list", "乗客リストを更新")
language.Add("npcpassengers.ui.copy_list", "表示中の乗客リストをコピー")
language.Add("npcpassengers.ui.make_exit", "現在の車両の乗客を降車させる")
language.Add("npcpassengers.ui.reset_pos", "位置と角度をリセット")
language.Add("npcpassengers.ui.crash_reactions", "衝突反応")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "乗降音")
language.Add("npcpassengers.section.ambient_sounds", "アンビエント音")
language.Add("npcpassengers.section.gesture_animations", "ジェスチャーアニメーション")
language.Add("npcpassengers.section.threat_awareness", "脅威認識")
language.Add("npcpassengers.section.emotional_states", "感情的状態")
language.Add("npcpassengers.section.turret_control", "タレット制御（実験的）")
language.Add("npcpassengers.section.turret_blacklist", "タレットNPCブラックリスト")
language.Add("npcpassengers.section.idle_chatter", "アイドルチャット")
language.Add("npcpassengers.section.body_physics", "ボディフィジックス")
language.Add("npcpassengers.section.npc_auto_driver", "NPC自動運転手")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "左下")
language.Add("npcpassengers.hud.bottom_right", "右下")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "乗客HUDを有効にする")
language.Add("npcpassengers.ui.cover_face", "顔を覆う")
language.Add("npcpassengers.ui.apply_keybinds", "推奨キーバインドを適用")
language.Add("npcpassengers.ui.clear_keybinds", "全キーバインドをクリア")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "フリンチジェスチャーをテスト")
language.Add("npcpassengers.ui.test_random", "ランダムジェスチャーをテスト")
language.Add("npcpassengers.ui.reset_states", "全状態をリセット")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "全コンテキストメニューオプションを有効にする")
language.Add("npcpassengers.ui.hide_context", "全コンテキストメニューオプションを非表示にする")
language.Add("npcpassengers.ui.set_compact", "コンパクトパネルサイズを設定")
language.Add("npcpassengers.ui.set_default", "デフォルトパネルサイズを設定")
language.Add("npcpassengers.ui.set_large", "ラージパネルサイズを設定")
language.Add("npcpassengers.ui.center_panel", "パネルを中央に配置")
language.Add("npcpassengers.ui.reset_ui", "全UI設定をデフォルトにリセット")

-- Role names
language.Add("npcpassengers.role.citizen_female", "市民（女性）")
language.Add("npcpassengers.role.citizen_male", "市民（男性）")
language.Add("npcpassengers.role.medic", "衛生兵")
language.Add("npcpassengers.role.rebel", "反乱軍")
language.Add("npcpassengers.role.passenger", "乗客")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "車両にいる時のみ表示")
language.Add("npcpassengers.hud.show_calm", "穏やかな乗客を表示")
language.Add("npcpassengers.hud.show_hints", "コンテキストヒントを表示")
language.Add("npcpassengers.hud.show_target_debug", "ターゲットデバッグを表示")
language.Add("npcpassengers.hud.play_cues", "成功/失敗キューを再生")
language.Add("npcpassengers.debug.enable_mode", "デバッグモードを有効にする")
language.Add("npcpassengers.ui.enable_sounds", "UIサウンドを有効にする")
language.Add("npcpassengers.ui.hover_sounds", "ホバーサウンド")
language.Add("npcpassengers.ui.click_sounds", "クリックサウンド")
language.Add("npcpassengers.ui.enable_animations", "UIアニメーションを有効にする")
language.Add("npcpassengers.ui.show_tooltips", "ツールチップを表示")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "スクロールバーを自動的に非表示")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "サイドバースクロール滑らかさ")
language.Add("npcpassengers.ui.color_theme", "カラーテーマ")
language.Add("npcpassengers.ui.font_scale", "フォントスケール")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "NPC選択をキャンセル")
language.Add("npcpassengers.context.remove_passenger", "乗客を削除")
language.Add("npcpassengers.context.blacklist_passenger", "ブラックリストに追加")
language.Add("npcpassengers.context.whitelist_passenger", "ホワイトリストに追加")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "キーバインド")
language.Add("npcpassengers.keybinds.desc", "クイックアクション用のキーボードショートを設定します。")
language.Add("npcpassengers.keybind.attach", "最も近いNPCをアタッチ")
language.Add("npcpassengers.keybind.attach.help", "最も近いフレンドリーなNPCを車両にアタッチします。")
language.Add("npcpassengers.keybind.detach_all", "全NPCをデタッチ")
language.Add("npcpassengers.keybind.detach_all.help", "車両から全乗客を削除します。")
language.Add("npcpassengers.keybind.toggle_autojoin", "自動参加を切り替え")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "自動参加を素早く有効/無効にします。")
language.Add("npcpassengers.keybind.menu", "設定メニューを開く")
language.Add("npcpassengers.keybind.menu.help", "設定パネルを開きます。")
language.Add("npcpassengers.keybind.exit_all", "全乗客降車")
language.Add("npcpassengers.keybind.exit_all.help", "全乗客を車両から降車させます。")
language.Add("npcpassengers.keybind.toggle_hud", "HUDを切り替え")
language.Add("npcpassengers.keybind.toggle_hud.help", "乗客HUDを表示/非表示にします。")
language.Add("npcpassengers.keybind.quick_attach", "クイックアタッチモード")
language.Add("npcpassengers.keybind.quick_attach.help", "見ているNPCを素早くアタッチするために押し続けます")
language.Add("npcpassengers.keybind.hold_fire", "NPC発砲ホールド")
language.Add("npcpassengers.keybind.hold_fire.help", "ガンナーNPCに発砲をやめるよう伝えます")
language.Add("npcpassengers.keybind.open_fire", "NPC発砲オープン")
language.Add("npcpassengers.keybind.open_fire.help", "ガンナーNPCにターゲットを攻撃するよう伝えます")
language.Add("npcpassengers.keybind.cycle_view", "乗客ビューを循環")
language.Add("npcpassengers.keybind.cycle_view.help", "カメラを乗客間で循環します")
language.Add("npcpassengers.keybind.cycle_hud_position", "HUD位置を循環")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "乗客HUDを4つのコーナーに移動します")
language.Add("npcpassengers.keybind.toggle_debug", "ターゲットデバッグを切り替え")
language.Add("npcpassengers.keybind.toggle_debug.help", "小さなターゲットデバッグオーバーレイを切り替えます")
language.Add("npcpassengers.keybind.test_gesture", "ランダムジェスチャーをテスト")
language.Add("npcpassengers.keybind.test_gesture.help", "最も近い乗客でランダムなジェスチャーを再生します")
language.Add("npcpassengers.keybind.reset_all", "全NPCをリセット")
language.Add("npcpassengers.keybind.reset_all.help", "全乗客のアニメーション状態をリセットします")

-- HUD Settings
language.Add("npcassengers.hud.header", "HUD設定")
language.Add("npcpassengers.hud.enable", "HUDを有効にする")
language.Add("npcpassengers.hud.enable.help", "画面に乗客状態オーバーレイを表示します。")
language.Add("npcpassengers.hud.position", "HUD位置")
language.Add("npcpassengers.hud.position.help", "HUDが画面に表示される場所。")
language.Add("npcpassengers.hud.position.topleft", "左上")
language.Add("npcpassengers.hud.position.topright", "右上")
language.Add("npcpassengers.hud.position.bottomleft", "左下")
language.Add("npcpassengers.hud.position.bottomright", "右下")
language.Add("npcpassengers.hud.scale", "HUDスケール")
language.Add("npcpassengers.hud.scale.help", "HUDのサイズ倍率。")
language.Add("npcpassengers.hud.opacity", "HUD不透明度")
language.Add("npcpassengers.hud.opacity.help", "背景透明度（0 = 不可視、1 = 固体）。")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC運転手")
language.Add("npcpassengers.driver.desc", "NPCに車両を運転させることができます。")
language.Add("npcpassengers.driver.enable", "NPC運転手を有効にする")
language.Add("npcpassengers.driver.enable.help", "NPCが車両の制御を取ることを許可します。")
language.Add("npcpassengers.driver.behavior", "運転挙動")
language.Add("npcpassengers.driver.behavior.help", "NPCが車両をどのように運転するか。")
language.Add("npcpassengers.driver.behavior.cruise", "ランダムクルーズ")
language.Add("npcpassengers.driver.behavior.follow", "プレイヤー追従")
language.Add("npcpassengers.driver.behavior.patrol", "パトロール")
language.Add("npcpassengers.driver.behavior.flee", "逃走")
language.Add("npcpassengers.driver.behavior.parked", "駐車のまま")

-- Help / FAQ
language.Add("npcpassengers.help.header", "よくある質問")
language.Add("npcpassengers.help.desc", "一般的な質問への迅速な回答とトラブルシューティング。")
language.Add("npcpassengers.help.still_need", "まだサポートが必要ですか？")
language.Add("npcpassengers.help.community", "Discordコミュニティに参加してサポートを受けましょう！")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "戦車/LVS")
language.Add("npcpassengers.nav.debugging", "デバッグ")
language.Add("npcpassengers.nav.driver", "NPC運転手")
language.Add("npcpassengers.nav.interface", "インターフェース")
language.Add("npcassengers.nav.simulate", "シミュレート")
language.Add("npcpassengers.nav.modules", "モジュール")
language.Add("npcpassengers.nav.about", "について")
language.Add("npcpassengers.search.placeholder", "設定を検索...")

-- About page
language.Add("npcpassengers.about.description", "感情的AIとリアルな物理を持つ高度な乗客システム")
language.Add("npcpassengers.about.feature_status", "状態システム: 穏やか / 警告 / 恐怖 / 眠気 / 死亡")
language.Add("npcpassengers.about.feature_performance", "パフォーマンス: シートキャッシュ、制限されたタイマー、最適化されたクライアントフック")
language.Add("npcpassengers.about.feature_filtering", "車両フィルタリング、搭乗再試行クールダウン、分隊のみ自動参加")
language.Add("npcpassengers.about.actions", "アクション")
language.Add("npcpassengers.about.show_welcome", "ウェルカム画面を表示")
language.Add("npcpassengers.about.open_github", "GitHubページを開く")
language.Add("npcpassengers.about.reset_settings", "全設定をデフォルトにリセット")

-- Status messages
language.Add("npcpassengers.status.calm", "穏やか")
language.Add("npcpassengers.status.alert", "警告")
language.Add("npcpassengers.status.scared", "恐怖")
language.Add("npcpassengers.status.drowsy", "眠気")
language.Add("npcpassengers.status.dead", "死亡")
language.Add("npcpassengers.status.calm.desc", "リラックス、近くに脅威なし")
language.Add("npcpassengers.status.alert.desc", "敵検出、NPCは脅威を追跡")
language.Add("npcpassengers.status.scared.desc", "危険な運転（高速、衝突）")
language.Add("npcpassengers.status.drowsy.desc", "長く穏やかな乗車、NPCが眠くなる")
language.Add("npcpassengers.status.dead.desc", "ヘルスがゼロに到達")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "自動参加: オン")
language.Add("npcpassengers.chat.autojoin_off", "自動参加: オフ")
language.Add("npcpassengers.chat.hud_on", "HUD: オン")
language.Add("npcpassengers.chat.hud_off", "HUD: オフ")
language.Add("npcpassengers.chat.prefix", "[最高級NPC乗客]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "近くに車両なし")
language.Add("npcpassengers.error.no_npc", "近くにNPCなし")
language.Add("npcpassengers.error.vehicle_full", "車両が満員")
language.Add("npcpassengers.error.too_far", "NPCが車両から遠すぎる")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "言語を変更")
language.Add("npcpassengers.tooltip.minimize", "パネルを最小化")
language.Add("npcpassengers.tooltip.expand", "パネルを展開")
language.Add("npcpassengers.tooltip.welcome", "ウェルカム画面を表示")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "全NPCボイスのマスター切り替え。乗客を完全にミュートにするには無効にします。")
language.Add("npcpassengers.speech_volume.help", "NPCボイスの音量（0 = ミュート、100 = フルボリューム）。")
language.Add("npcpassengers.pitch_variation.help", "より自然なボイスのためのランダムピッチ変動。0 = 単調、高い = 多様性が増加。")
language.Add("npcpassengers.crash_enable.help", "車両が急減速するとNPCがうめく/悲鳴を上げます（衝突、急ブレーキ）。")
language.Add("npcpassengers.crash_threshold.help", "衝突音をトリガーするために必要な減速。低い = より敏感。")
language.Add("npcpassengers.crash_cooldown.help", "NPCごとの衝突音間の最小秒数。")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPCは乗車中に時々話します - コメント、質問、観察。")
language.Add("npcpassengers.speech_idle_chance.help", "チェックごとのチャット確率。0 = 決して話さない、1 = 常に話そうとする。")
language.Add("npcpassengers.speech_idle_interval.help", "アイドルチャット試行間の最小秒数。")
language.Add("npcpassengers.speech_board.help", "NPCは車両に乗り降りする時に話します。")
language.Add("npcpassengers.ambient_sounds.help", "時折の咳、ため息、ハミング - 背景の生活音。")
language.Add("npcpassengers.ambient_interval.help", "アンビエント音間の平均秒数。")
language.Add("npcpassengers.animation.help", "NPCアニメーションとヘッドムーブメントを微調整します。")
language.Add("npcpassengers.head_look.help", "NPCは自然に周囲を見回し、プレイヤー、窓などを見ます。")
language.Add("npcpassengers.head_smooth.help", "ヘッドがどれだけ滑らかに動くか。低い = より速い、高い = より浮遊。")
language.Add("npcpassengers.blink.help", "NPCは座っている間リアルに瞬きます。")
language.Add("npcpassengers.breathing.help", "NPCヘッドの微妙な呼吸アニメーション。")
language.Add("npcpassengers.walk_timeout.help", "NPCが車両への歩行を諦めるまでの秒数。")
language.Add("npcpassengers.realism.help", "最大没入感のための物理ベースの反応と認識システム。")
language.Add("npcpassengers.talking_gestures.help", "NPCは乗車中にランダムなハンドジェスチャーとボディアニメーションを再生します。")
language.Add("npcpassengers.gesture_chance.help", "各インターバルでジェスチャーを再生する確率。")
language.Add("npcpassengers.gesture_interval.help", "ジェスチャー機会チェック間の秒数。")
language.Add("npcpassengers.crash_flinch.help", "車両が衝突または急ブレーキすると、NPCはフリンチして前に飛び出します。")
language.Add("npcpassengers.crash_threshold_flinch.help", "フリンチをトリガーするために必要な速度変化（低い = より敏感）。")
language.Add("npcpassengers.body_sway.help", "NPCはターンで傾き、加速/ブレーキ中に支えます。")
language.Add("npcpassengers.body_sway_amount.help", "NPCが車両の動きでどれだけスウェイするか。")
language.Add("npcpassengers.threat_awareness.help", "NPCは自動的に近くの敵を見ます。")
language.Add("npcpassengers.threat_range.help", "NPCがヘッドトラッキングのために脅威を検知できる距離。")
language.Add("npcpassengers.combat_alert.help", "敵が近くにいるとNPCは緊張し反応的になります。")
language.Add("npcpassengers.passenger_combat.help", "デフォルトで無効。これを有効にすると、武装した乗客が車両内から発砲できます。")
language.Add("npcpassengers.passenger_combat_range.help", "武装した乗客がターゲットを取得できる距離。")
language.Add("npcpassengers.passenger_combat_accuracy.help", "高い値は武装した乗客の発砲拡散を狭めます。")
language.Add("npcpassengers.passenger_combat_damage.help", "乗客の発砲によって与えられるダメージをスケーリングします。")
language.Add("npcpassengers.passenger_interaction.help", "複数の乗客が互いを見て時折会話します。")
language.Add("npcpassengers.fear_reactions.help", "NPCは危険な運転に恐怖します - 目を大きく見開き、パニック音。")
language.Add("npcpassengers.fear_speed_threshold.help", "NPCが神経質になり始める速度（単位/秒）。")
language.Add("npcpassengers.drowsiness.help", "NPCは長く穏やかな乗車で眠くなります - ゆっくり瞬き、うなだき。")
language.Add("npcpassengers.drowsy_time.help", "眠気が始まるまでの穏やかな運転の秒数。")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "戦車、APC、LVS車両の設定。")
language.Add("npcpassengers.hide_in_tanks.help", "戦車やAPCの中にいるとき、NPC乗客を不可視にします。")
language.Add("npcpassengers.eject_stuck_check.help", "NPCが排出中にスタックしたとき、自動的に車両から押し出します。NPCが排出時に車両を通り抜けるのを防ぎます。")
language.Add("npcpassengers.detach_no_collide.help", "デタッチ後、NPCは一時的に車両を通過できるため、衝突やスタックなしで歩き去ることができます。")
language.Add("npcpassengers.detach_no_collide_duration.help", "デタッチ後にNPCが車両衝突を無視する時間。")
language.Add("npcpassengers.die_with_vehicle.help", "NPC乗客は車両が爆発または火で破壊されたときに死亡します（無傷で残骸から歩き出すよりも没入感があります）。")
language.Add("npcpassengers.tank_driver.help", "運転席のNPCが敵に向かって自動的に運転することを許可します。")
language.Add("npcpassengers.tank_driver_range.help", "運転手が敵を検知できる最大範囲。")
language.Add("npcpassengers.tank_driver_distance.help", "敵から維持する距離。")
language.Add("npcpassengers.tank_driver_throttle.help", "スロットル量（0.1 = 遅い、1 = フルスピード）。")
language.Add("npcpassengers.tank_driver_reverse.help", "敵から後退する距離。")
language.Add("npcpassengers.tank_turret.help", "NPCがLVS車両でタレットを制御することを許可します。")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "運転中に画面に乗客状態（感情、アラート）を表示します。")
language.Add("npcpassengers.hud_show_calm.help", "無効な場合、穏やかでない状態の乗客のみを表示します。")
language.Add("npcpassengers.hud_thresholds.desc", "感情レベルがこれらの閾値を超えると、乗客はHUDでその状態を表示します。")
language.Add("npcpassengers.hud_alert_threshold.help", "'警告'状態を表示するために必要なアラートレベル（脅威検出）。")
language.Add("npcpassengers.hud_fear_threshold.help", "'恐怖'状態を表示するために必要な恐怖レベル（危険な運転）。")
language.Add("npcpassengers.hud_drowsy_threshold.help", "'眠気'状態を表示するために必要な穏やか時間比率（長く穏やかな乗車）。")
language.Add("npcpassengers.hud_actions.desc", "各感情的状態を経験するときに乗客が取るアクションを選択します。")
language.Add("npcpassengers.hud_actions_note", "注: 一部のアクションはNPCモデルサポートに応じて表示されない場合があります。")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "乗客アクション用のカスタムキーバインドを設定します。ボタンをクリックし、キーを押して割り当てます。")
language.Add("npcpassengers.keybinds_hud.desc", "乗客オーバーレイを表示、移動、デバッグするためのクイックHUDコントロール。")
language.Add("npcpassengers.keybinds_debug_note", "デバッグキーバインドはデバッグモードが有効な場合のみ機能します。")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "NPC挙動をテストするための高度なデバッグツール。最初に設定でデバッグモードを有効にします。")
language.Add("npcpassengers.debug_mode.help", "デバッグテストボタンを表示し、デバッグコマンドを有効にします。")
language.Add("npcpassengers.debug_status.help", "テスト用に乗客状態を手動で設定します。現在の乗客を表示するには「リストを更新」をクリックします。")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "ボタン、チェックボックス、その他UI要素のサウンドエフェクトを設定します")
language.Add("npcpassengers.ui_sounds_enabled.help", "全UIサウンドエフェクトのマスター切り替え")
language.Add("npcpassengers.ui_sounds_volume.help", "UIサウンドの音量倍率（1.0 = 通常、2.0 = 倍）")
language.Add("npcpassengers.ui_hover_enabled.help", "ボタンをホバーしたときにサウンドを再生")
language.Add("npcpassengers.ui_click_enabled.help", "ボタンとチェックボックスをクリックしたときにサウンドを再生")
language.Add("npcpassengers.context_menu.desc", "NPCを右クリックしたときに表示されるオプションを選択します")
language.Add("npcpassengers.context_make_passenger.help", "NPCを現在の車両の乗客として追加")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "NPCを特定の車両に追加（NPCをクリック、次に車両）")
language.Add("npcpassengers.context_detach.help", "車両からNPCを削除")
language.Add("npcpassengers.ui_show_welcome.help", "アドオンが新しいバージョンに更新されたときにウェルカムパネルを表示")
language.Add("npcpassengers.ui_panel_width.help", "設定パネルの幅")
language.Add("npcpassengers.ui_panel_height.help", "設定パネルの高さ")
language.Add("npcpassengers.ui_animations.help", "スムーズな遷移とホバーエフェクト（パフォーマンスに影響する場合があります）")
language.Add("npcpassengers.ui_tooltips.help", "設定にホバーするときに役立つツールチップを表示")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "スクロール中またはホバーしているときのみスクロールバーを表示します。")
language.Add("npcpassengers.ui_scroll_smoothness_note", "注: スライダーをドラッグするとパネルは70%透明になり、背景のコンテンツを見ることができます。")
language.Add("npcpassengers.ui_scroll_smoothness.help", "より低い値 = より滑らかだが遅い（0.01-1）")
language.Add("npcpassengers.ui_color_theme.help", "設定パネルのカラーテーマを選択します。変更はすぐに適用されます。")
language.Add("npcpassengers.ui_font_scale.help", "全UIフォントサイズをスケーリングします。1.0 = デフォルト、0.5 = 半分のサイズ、2.0 = 倍のサイズ。")

print("[Better NPC Passengers] Japanese localization loaded!")
