-- Better NPC Passengers - Portuguese Localization
-- Arquivo de localização em português

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Melhores Passageiros NPC")
language.Add("npcpassengers.settings", "Configurações")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Geral")
language.Add("npcpassengers.nav.autojoin", "Entrada Automática")
language.Add("npcpassengers.nav.passengers", "Passageiros")
language.Add("npcpassengers.nav.position", "Posição")
language.Add("npcpassengers.nav.behaviour", "Comportamento")
language.Add("npcpassengers.nav.keybinds", "Atalhos de Teclado")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Motorista")
language.Add("npcpassengers.nav.help", "Ajuda")

-- General Settings
language.Add("npcassengers.general.header", "Configurações Gerais")
language.Add("npcpassengers.allow_multiple", "Permitir Múltiplos Passageiros")
language.Add("npcpassengers.allow_multiple.help", "Permite que vários NPCs viajem no mesmo veículo.")
language.Add("npcpassengers.exit_behavior", "Comportamento de Saída")
language.Add("npcpassengers.exit_behavior.help", "Quando os passageiros NPC devem sair do veículo?")
language.Add("npcassengers.exit_mode.leave_player", "Sair quando o jogador sai")
language.Add("npcpassengers.exit_mode.leave_attack", "Sair quando o veículo é atacado")
language.Add("npcpassengers.exit_mode.never", "Nunca sair automaticamente")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Tempo")
language.Add("npcpassengers.max_attach_dist", "Distância Máxima de Anexo")
language.Add("npcpassengers.max_attach_dist.help", "Distância máxima (unidades) para anexar NPC ao veículo.")
language.Add("npcpassengers.detach_delay", "Atraso de Desanexo")
language.Add("npcpassengers.detach_delay.help", "Segundos a esperar antes de desanexar após o jogador sair.")
language.Add("npcpassengers.ai_delay", "Atraso de Restauração de IA")
language.Add("npcpassengers.ai_delay.help", "Segundos a esperar antes de restaurar a IA do NPC após desanexar.")
language.Add("npcpassengers.cooldown", "Tempo de Recarga")
language.Add("npcpassengers.cooldown.help", "Tempo de recarga entre anexar NPC ao mesmo veículo.")
language.Add("npcpassengers.passenger_limit", "Limite de Passageiros")
language.Add("npcpassengers.passenger_limit.help", "Máximo de NPCs permitidos no veículo.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Entrada Automática (Comportamento de Esquadrão)")
language.Add("npcpassengers.autojoin.desc", "NPCs amigáveis entrarão automaticamente no seu veículo quando você entrar, igual à mecânica de esquadrão em Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Ativar Entrada Automática")
language.Add("npcpassengers.autojoin.enable.help", "NPCs amigáveis próximos entrarão automaticamente quando você entrar em um veículo.")
language.Add("npcpassengers.autojoin.range", "Alcance de Entrada Automática")
language.Add("npcpassengers.autojoin.range.help", "Distância máxima para encontrar NPCs para entrada automática.")
language.Add("npcpassengers.autojoin.max", "Máximo de NPCs de Entrada Automática")
language.Add("npcpassengers.autojoin.max.help", "Número máximo de NPCs que podem entrar automaticamente de uma vez.")
language.Add("npcpassengers.autojoin.squad_only", "Apenas Membros do Esquadrão")
language.Add("npcpassengers.autojoin.squad_only.help", "Apenas NPCs com nome de esquadrão entrarão automaticamente (para esquadrões estilo HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "NPCs amigáveis entrarão automaticamente no seu veículo quando você entrar, igual à mecânica de esquadrão em Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Controle de Passageiros")
language.Add("npcpassengers.panel.passengers.desc", "Gerencie passageiros ativos, filtre por nome/classe/estado, copie informações de depuração, reatribua assentos e separe passageiros sem sair do painel de configurações.")
language.Add("npcpassengers.panel.position.desc", "Ajuste finamente a posição dos NPCs nos veículos. Use isso para corrigir problemas de flutuação ou intersecção.")
language.Add("npcpassengers.panel.angle.desc", "Ajuste a rotação dos NPCs nos veículos.")
language.Add("npcpassengers.panel.speech.desc", "Configure como os NPCs vocalizam enquanto viajam em veículos. Vozes de cidadãos estilo HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Deslocamentos de Posição")
language.Add("npcpassengers.position.desc", "Ajuste finamente a posição dos NPCs nos veículos. Use isso para corrigir problemas de flutuação ou intersecção.")
language.Add("npcpassengers.height_offset", "Deslocamento de Altura")
language.Add("npcpassengers.forward_offset", "Deslocamento Frontal")
language.Add("npcpassengers.right_offset", "Deslocamento Direito")
language.Add("npcpassengers.angle.header", "Deslocamentos de Ângulo")
language.Add("npcpassengers.angle.desc", "Ajuste a rotação dos NPCs nos veículos.")
language.Add("npcpassengers.yaw_offset", "Guinada (Rotação)")
language.Add("npcpassengers.pitch_offset", "Arfagem (Inclinação Frontal)")
language.Add("npcpassengers.roll_offset", "Rolamento (Inclinação Lateral)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Voz de NPC (Avançado)")
language.Add("npcpassengers.behaviour.desc", "Configure como os NPCs vocalizam enquanto viajam em veículos. Vozes de cidadãos estilo HL2!")
language.Add("npcpassengers.speech_enable", "Ativar Voz de NPC")
language.Add("npcpassengers.speech_enable.help", "Interruptor mestre para toda a voz de NPC. Desative para silenciar passageiros completamente.")
language.Add("npcpassengers.speech_volume", "Volume de Voz")
language.Add("npcpassengers.speech_volume.help", "Quão altas são as vozes dos NPCs (0 = silencioso, 100 = volume completo).")
language.Add("npcpassengers.pitch_variation", "Variação de Tom (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Variação aleatória de tom para vozes mais naturais. 0 = monótono, mais alto = mais variedade.")
language.Add("npcpassengers.crash.header", "Reações a Colisões")
language.Add("npcpassengers.crash_enable", "Ativar Sons de Colisão")
language.Add("npcpassengers.crash_enable.help", "Os NPCs grunhem/gemem quando o veículo desacelera bruscamente (colisões, freada brusca).")
language.Add("npcpassengers.crash_threshold", "Sensibilidade a Colisões")
language.Add("npcpassengers.crash_threshold.help", "Desaceleração necessária para ativar sons de colisão. Menor = mais sensível.")
language.Add("npcpassengers.crash_cooldown", "Recarga de Som de Colisão")
language.Add("npcpassengers.crash_cooldown.help", "Segundos mínimos entre sons de colisão por NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Ativar Conversa Ociosa")
language.Add("npcpassengers.speech_board", "Ativar Sons de Embarque/Desembarque")
language.Add("npcpassengers.ambient_sounds", "Ativar Sons Ambientais")
language.Add("npcpassengers.head_look", "Ativar Olhar de Cabeça/Olhos")
language.Add("npcpassengers.blink", "Ativar Piscar")
language.Add("npcpassengers.breathing", "Ativar Respiração")
language.Add("npcpassengers.talking_gestures", "Ativar Gestos ao Falar")
language.Add("npcpassengers.crash_flinch", "Ativar Encolhimento por Colisão")
language.Add("npcpassengers.body_sway", "Ativar Balanço do Corpo")
language.Add("npcpassengers.threat_awareness", "Ativar Consciência de Ameaças")
language.Add("npcpassengers.combat_alert", "Alerta de Combate")
language.Add("npcpassengers.passenger_combat", "NPCs atiram de veículos (Experimental)")
language.Add("npcpassengers.passenger_interaction", "Interação de Passageiros")
language.Add("npcpassengers.fear_reactions", "Ativar Reações de Medo")
language.Add("npcassengers.drowsiness", "Ativar Sonolência")
language.Add("npcpassengers.hide_in_tanks", "Ocultar NPCs em Veículos Fechados")
language.Add("npcpassengers.eject_stuck_check", "Ejeção Automática de NPCs Presos")
language.Add("npcpassengers.detach_no_collide", "Sem Colisão com Veículo Após Desanexar")
language.Add("npcpassengers.die_with_vehicle", "Matar Passageiros Quando Veículo Explode")
language.Add("npcpassengers.driver_enabled", "Ativar Condução Automática")
language.Add("npcpassengers.turret_enabled", "Ativar Controle de Torre")
language.Add("npcpassengers.turret_lead_targets", "Prever Alvos")
language.Add("npcpassengers.turret_friendly_fire", "Permitir Fogo Amigo")
language.Add("npcpassengers.turret_hold_fire", "Segurar Fogo (Desativar Tiro)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Volume de Voz")
language.Add("npcpassengers.pitch_variation", "Variação de Tom (+/-)")
language.Add("npcpassengers.crash_threshold", "Sensibilidade a Colisões")
language.Add("npcpassengers.crash_cooldown", "Recarga de Som de Colisão")
language.Add("npcpassengers.speech_idle_chance", "Probabilidade de Conversa")
language.Add("npcpassengers.speech_idle_interval", "Intervalo de Conversa")
language.Add("npcpassengers.ambient_interval", "Intervalo de Som Ambiental")
language.Add("npcpassengers.head_smooth", "Suavidade de Cabeça")
language.Add("npcpassengers.walk_timeout", "Tempo de Espera de Caminhada")
language.Add("npcpassengers.gesture_chance", "Probabilidade de Gesto (%)")
language.Add("npcpassengers.gesture_interval", "Intervalo de Gesto")
language.Add("npcpassengers.crash_threshold_flinch", "Sensibilidade a Colisões")
language.Add("npcassengers.body_sway_amount", "Intensidade de Balanço")
language.Add("npcpassengers.threat_range", "Alcance de Detecção de Ameaças")
language.Add("npcpassengers.passenger_combat_range", "Alcance de Combate de Passageiros")
language.Add("npcpassengers.passenger_combat_accuracy", "Precisão de Passageiros")
language.Add("npcpassengers.passenger_combat_damage", "Multiplicador de Dano de Passageiros")
language.Add("npcpassengers.fear_speed_threshold", "Limiar de Velocidade de Medo")
language.Add("npcpassengers.drowsy_time", "Tempo de Sonolência")
language.Add("npcpassengers.detach_no_collide_duration", "Duração Sem Colisão (segundos)")
language.Add("npcpassengers.tank_driver_range", "Alcance de Detecção")
language.Add("npcpassengers.tank_driver_engage_distance", "Distância de Engajamento")
language.Add("npcpassengers.tank_driver_speed", "Velocidade de Condução")
language.Add("npcpassengers.tank_driver_reverse_distance", "Distância de Ré")
language.Add("npcpassengers.turret_range", "Alcance de Alvo")
language.Add("npcpassengers.turret_accuracy", "Precisão")
language.Add("npcpassengers.turret_reaction_time", "Tempo de Reação")
language.Add("npcpassengers.turret_fire_delay", "Atraso de Tiro")
language.Add("npcpassengers.turret_aim_speed", "Velocidade de Mira")
language.Add("npcpassengers.hud_scale", "Escala de HUD")
language.Add("npcpassengers.hud_opacity", "Opacidade de HUD")
language.Add("npcpassengers.hud_alert_threshold", "Limiar de Alerta")
language.Add("npcpassengers.hud_fear_threshold", "Limiar de Medo")
language.Add("npcpassengers.hud_drowsy_threshold", "Limiar de Sonolência")
language.Add("npcpassengers.ui_sounds_volume", "Volume de Sons UI")
language.Add("npcpassengers.ui_panel_width", "Largura do Painel")

-- Section headers
language.Add("npcpassengers.section.animation", "Animação e Comportamento")
language.Add("npcpassengers.section.realism", "Realismo Avançado")
language.Add("npcpassengers.section.hud_position", "Posição e Estilo de HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Limitares de Emoção")
language.Add("npcpassengers.section.emotion_actions", "Ações de Emoção")
language.Add("npcpassengers.section.vehicle_control", "Controle de Veículo")
language.Add("npcpassengers.section.hud_controls", "Controles de HUD")
language.Add("npcpassengers.section.debug_controls", "Controles de Depuração")
language.Add("npcassengers.section.passenger_status", "Controle de Estado de Passageiros")
language.Add("npcpassengers.section.quick_test", "Botões de Teste Rápido")
language.Add("npcpassengers.section.driver_system", "Sistema de Motorista NPC")
language.Add("npcpassengers.section.ui_sounds", "Configuração de Sons UI")
language.Add("npcpassengers.section.appearance", "Aparência")
language.Add("npcpassengers.section.context_menu", "Opções do Menu de Contexto")
language.Add("npcpassengers.section.panel_preferences", "Preferências do Painel de Configurações")
language.Add("npcpassengers.section.performance", "Performance e Técnico")
language.Add("npcpassengers.section.simulation", "Sistema de Simulação")
language.Add("npcpassengers.section.modules", "Sistema de Módulos")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Atribuir Assento")
language.Add("npcpassengers.btn.detach", "Separar")
language.Add("npcpassengers.btn.copy_summary", "Copiar Resumo")
language.Add("npcpassengers.btn.copy_debug", "Copiar Depuração")
language.Add("npcpassengers.btn.enable_all_speech", "Ativar Toda a Voz")
language.Add("npcpassengers.btn.disable_all_speech", "Desativar Toda a Voz")
language.Add("npcpassengers.btn.show_current_vehicle", "Mostrar Apenas Veículo Atual")
language.Add("npcpassengers.btn.auto_refresh", "Atualização Automática de Lista Visível")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Nenhum veículo atual detectado. Sente-se em um veículo ou desative o filtro de veículo atual.")
language.Add("npcpassengers.status.no_match_filter", "Nenhum passageiro corresponde ao seu filtro. Tente um nome, classe, número de assento, estado ou classe de veículo.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Nenhum passageiro encontrado no seu veículo atual.")
language.Add("npcpassengers.status.no_passengers", "Nenhum passageiro encontrado. Os NPCs devem estar viajando em um veículo antes de poderem ser gerenciados aqui.")
language.Add("npcpassengers.status.all_passengers", "Todos os passageiros")
language.Add("npcpassengers.status.current_vehicle_only", "Apenas veículo atual")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F para focar na pesquisa")
language.Add("npcengers.status.no_matches", "Sem configurações correspondentes")
language.Add("npcpassengers.status.showing_matches", "Mostrando %d principais de %d correspondências")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Abrir Configurações")
language.Add("npcpassengers.menu.reset_all", "Redefinir Todas as Configurações")

-- Button states
language.Add("npcpassengers.state.on", "LIGADO")
language.Add("npcpassengers.state.off", "DESLIGADO")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Entrada Automática")
language.Add("npcpassengers.chat.hud_status", "HUD de Passageiros")
language.Add("npcpassengers.chat.hud_position", "Posição de HUD")
language.Add("npcpassengers.chat.target_debug", "Depuração de Alvo")
language.Add("npcpassengers.chat.turret_gunners", "Artilheiros de Torre")
language.Add("npcpassengers.chat.turret_holding", "SEGURANDO FOGO")
language.Add("npcpassengers.chat.turret_fire", "ABRINDO FOGO")
language.Add("npcpassengers.chat.unknown", "Desconhecido")
language.Add("npcpassengers.chat.nothing_copy", "Nada para copiar.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Acesso à área de transferência não está disponível nesta versão.")
language.Add("npcpassengers.chat.copied_clipboard", "Copiado para a área de transferência.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Sente-se no mesmo veículo para reatribuir este passageiro.")
language.Add("npcpassengers.chat.no_visible_passengers", "Nenhum passageiro visível para copiar.")
language.Add("npcpassengers.chat.need_vehicle", "Você precisa estar em um veículo para usar isso.")
language.Add("npcpassengers.chat.keybinds_applied", "Atalhos recomendados aplicados.")
language.Add("npcpassengers.chat.keybinds_cleared", "Todos os atalhos limpos.")
language.Add("npcpassengers.chat.context_enabled", "Todas as opções do menu de contexto ativadas.")
language.Add("npcpassengers.chat.context_hidden", "Todas as opções do menu de contexto ocultas.")
language.Add("npcpassengers.chat.panel_compact", "Tamanho do painel definido como compacto.")
language.Add("npcpassengers.chat.panel_default", "Tamanho do painel definido como padrão.")
language.Add("npcpassengers.chat.panel_large", "Tamanho do painel definido como grande.")
language.Add("npcpassengers.chat.panel_centered", "Painel centralizado.")
language.Add("npcpassengers.chat.settings_reset", "Todas as configurações de UI redefinidas para valores padrão!")
language.Add("npcpassengers.chat.npc_selected", "NPC selecionado! Agora clique com o botão direito em um veículo e selecione 'Adicionar NPC Selecionado'")
language.Add("npcpassengers.chat.adding_npc", "Adicionando NPC ao veículo...")
language.Add("npcpassengers.chat.selection_cancelled", "Seleção de NPC cancelada")
language.Add("npcassengers.chat.summary_copied", "Resumo de passageiros copiado.")
language.Add("npcpassengers.chat.debug_copied", "Informação de depuração de passageiro copiada.")
language.Add("npcpassengers.chat.no_passengers_found", "Nenhum passageiro encontrado. Os NPCs devem estar em um veículo.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Intensidade de estado %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filtrar passageiros...")
language.Add("npcpassengers.ui.press_key", "Pressione uma tecla...")
language.Add("npcpassengers.ui.work_in_progress", "Em Progresso")
language.Add("npcpassengers.ui.under_development", "Este recurso está atualmente em desenvolvimento")
language.Add("npcpassengers.ui.check_back_later", "Volte a verificar em uma atualização futura!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtra passageiros ativos por nome, classe, assento, estado ou veículo.")
language.Add("npcpassengers.ui.search_desc_sort", "Ordena a lista visível de passageiros por veículo, nome, assento, saúde ou estado.")
language.Add("npcpassengers.ui.search_label_filter", "Filtro de Passageiros")
language.Add("npcpassengers.ui.search_label_sort", "Ordem de Passageiros")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Como adiciono NPCs ao meu veículo?")
language.Add("npcpassengers.faq.add_npc.answer", "Use o menu de contexto (clique com o botão direito em um NPC) e selecione 'Tornar Passageiro'. Ou use o atalho 'Anexar NPC Mais Próximo'. Os NPCs devem ser amigáveis com você.")
language.Add("npcpassengers.faq.remove_npc", "Como removo passageiros do meu veículo?")
language.Add("npcpassengers.faq.remove_npc.answer", "Vá para a aba Passageiros nas configurações, selecione o passageiro e clique em Separar. Ou use o atalho 'Separar Todos os Passageiros'.")
language.Add("npcpassengers.faq.position", "Os NPCs estão flutuando/atravessando assentos!")
language.Add("npcpassengers.faq.position.answer", "Vá para a aba Posição e ajuste os deslocamentos de Altura/Frontal/Direito. Cada modelo de veículo é diferente, então você pode precisar ajustar esses valores. Use o painel de depuração para testar posições em tempo real.")
language.Add("npcpassengers.faq.speech", "Os NPCs não estão falando!")
language.Add("npcpassengers.faq.speech.answer", "Verifique a aba Comportamento e certifique-se de que 'Ativar Voz de NPC' esteja ativado. Também verifique se o Volume de Voz está acima de 0. Alguns modelos de NPC podem não ter linhas de voz disponíveis.")
language.Add("npcpassengers.faq.autojoin", "Como funciona a Entrada Automática?")
language.Add("npcpassengers.faq.autojoin.answer", "Quando ativado na aba Entrada Automática, NPCs amigáveis próximos entrarão automaticamente no seu veículo quando você entrar, igual à mecânica de esquadrão em Half-Life 2! Você pode definir o alcance de detecção e limitar quantos NPCs podem entrar automaticamente.")
language.Add("npcassengers.faq.death", "O que acontece quando os passageiros morrem?")
language.Add("npcpassengers.faq.death.answer", "Passageiros mortos mostrarão um efeito de brilho vermelho e mostrarão um ícone de caveira no HUD. Aproxime-se do seu veículo e mantenha R pressionado para remover seus corpos. Os corpos serão ejetados com física.")
language.Add("npcpassengers.faq.status", "O que significam os estados dos passageiros?")
language.Add("npcpassengers.faq.status.answer", "CALMO: Relaxado, sem ameaças próximas. ALERTA: Inimigo detectado. MEDO: Condução perigosa. SONOLENTO: Viagem longa e calma. MORTO: Saúde atingiu zero.")
language.Add("npcpassengers.faq.keybinds", "Meus atalhos não estão funcionando!")
language.Add("npcpassengers.faq.keybinds.answer", "Vá para a aba Atalhos e certifique-se de que você realmente definiu os atalhos (eles não são atribuídos por padrão). Clique no botão ao lado de cada ação e pressione a tecla desejada. Clique com o botão direito para desvincular.")
language.Add("npcpassengers.faq.errors", "O addon não está funcionando de jeito nenhum / Estou recebendo erros!")
language.Add("npcpassengers.faq.errors.answer", "Certifique-se de estar executando a versão mais recente do Garry's Mod. Verifique o console em busca de erros (tecla til ~). Tente desativar addons conflitantes.")
language.Add("npcpassengers.faq.combat", "Os passageiros podem atirar de veículos?")
language.Add("npcpassengers.faq.combat.answer", "Atualmente não. Os NPCs rastrearão inimigos e reagirão a ameaças, mas não atirarão armas enquanto estiverem sentados. Este recurso pode ser adicionado em atualizações futuras.")
language.Add("npcpassengers.faq.stop_autojoin", "Como paro os NPCs de entrarem automaticamente?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Desative a caixa 'Ativar Entrada Automática' na aba Entrada Automática, ou use o atalho 'Alternar Entrada Automática'.")
language.Add("npcpassengers.faq.settings", "Onde as configurações são salvas?")
language.Add("npcpassengers.faq.settings.answer", "Todas as configurações são salvas como ConVars na sua configuração do GMod. Elas persistem entre sessões e são específicas do seu cliente.")
language.Add("npcpassengers.faq.vehicles", "Isso funciona com todos os veículos?")
language.Add("npcassengers.faq.vehicles.answer", "Funciona com a maioria dos veículos que têm física. Tanques, APCs, carros, barcos, etc. Alguns veículos modificados podem exigir ajustes de posição.")
language.Add("npcpassengers.faq.multiple", "Posso ter múltiplos NPCs em um veículo?")
language.Add("npcpassengers.faq.multiple.answer", "Sim! Defina o 'Limite de Passageiros' nas configurações gerais. O addon distribuirá automaticamente os NPCs ao redor do veículo. Para posições de assento específicas, ajuste os deslocamentos na aba Posição.")
language.Add("npcpassengers.faq.crashes", "Os NPCs estão agindo de forma estranha após colisões!")
language.Add("npcpassengers.faq.crashes.answer", "Isso é normal - eles reagem com medo à condução perigosa. Abaixe o Limiar de Medo nas configurações de HUD se quiser que eles sejam menos reativos.")
language.Add("npcpassengers.faq.reset_setting", "Como redefino apenas uma configuração?")
language.Add("npcpassengers.faq.reset_setting.answer", "Use o comando de console para essa configuração específica. Todos os comandos começam com 'nai_npc_'. Digite 'find nai_npc' no console para ver todos os comandos disponíveis.")
language.Add("npcpassengers.faq.multiplayer", "Isso funciona em multijogador?")
language.Add("npcpassengers.faq.multiplayer.answer", "Sim! O addon funciona tanto em servidores de um jogador quanto multijogador. Cada jogador controla seus próprios passageiros.")
language.Add("npcpassengers.faq.lvs", "Isso funciona com veículos LVS?")
language.Add("npcpassengers.faq.lvs.answer", "Sim! O addon tem suporte completo para veículos LVS (Lua Vehicle System). Os NPCs podem viajar como passageiros e até mesmo podem dirigir veículos LVS se o modo de Motorista NPC estiver ativado.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Essas configurações controlam o comportamento da interface do usuário do addon")
language.Add("npcpassengers.panel.performance_note1", "Mudanças no tamanho do painel exigem fechar e reabrir o menu")
language.Add("npcpassengers.panel.performance_note2", "Desativar sons ou animações pode melhorar a performance em sistemas de baixo desempenho")
language.Add("npcpassengers.panel.performance_title", "Informações de Configuração de Interface")
language.Add("npcpassengers.help.console_title", "Comandos de Console para Depuração:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Ative o modo de depuração para ver informações detalhadas")
language.Add("npcpassengers.about.title", "Sobre")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")
language.Add("npcpassengers.lang.changed_portuguese", "Idioma alterado para português. O painel será atualizado automaticamente.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Olá!")
language.Add("npcpassengers.welcome.msg1", "Antes de reclamar que o passageiro está sentado em cima do veículo,\npor favor abra as configurações. Você pode fazer isso, acredito em você.")
language.Add("npcpassengers.welcome.msg2", "Este addon ainda está longe de ser PERFEITO, por favor não hesite em\nrelatar bugs e sugerir novos recursos. Leio todos os seus comentários!")
language.Add("npcpassengers.welcome.changelog", "Registro de Alterações")
language.Add("npcpassengers.welcome.got_it", "Entendi!")
language.Add("npcpassengers.welcome.console_cmd", "Ou use o comando de console: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Classes de NPC na Lista Negra")
language.Add("npcpassengers.ui.blacklist_help", "Lista separada por vírgulas de nomes de classes de NPC que não podem usar torres. Use o comando de console 'getnpcblacklist' para ver a lista negra atual.")
language.Add("npcpassengers.ui.hud_position", "Posição de HUD")
language.Add("npcpassengers.ui.not_bound", "Não Atribuído")
language.Add("npcpassengers.ui.keybind_tip", "Dica: Clique com o botão direito em um atalho para desvinculá-lo. Pressione ESC ao atribuir para cancelar.")
language.Add("npcpassengers.ui.dont_show_again", "Não mostrar isso novamente")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Operações de Passageiros")
language.Add("npcpassengers.hud.filter_prefix", "Filtro: ")
language.Add("npcpassengers.hud.sort_prefix", "Ordenar: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Atualização Automática: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Veículo: ")
language.Add("npcpassengers.hud.speed_prefix", "Velocidade: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "LIGADO")
language.Add("npcpassengers.hud.off", "DESLIGADO")
language.Add("npcpassengers.hud.passengers", "Passageiros")
language.Add("npcpassengers.hud.npc_driver", "Motorista NPC")
language.Add("npcpassengers.hud.total_prefix", "Total: ")
language.Add("npcpassengers.hud.showing_prefix", "Mostrando: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Veículo Atual: ")
language.Add("npcpassengers.hud.hidden_prefix", "Oculto: ")
language.Add("npcpassengers.hud.dead_prefix", "Mortos: ")
language.Add("npcpassengers.hud.scared_prefix", "Com Medo: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Sonolentos: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Calmo")
language.Add("npcpassengers.status.alert", "Alerta")
language.Add("npcpassengers.status.scared", "Com Medo")
language.Add("npcpassengers.status.drowsy", "Sonolento")
language.Add("npcpassengers.status.dead", "Morto")
language.Add("npcpassengers.status.unknown", "Desconhecido")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Cidadão")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Padre Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dra. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Cachorro")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Veículo")
language.Add("npcassengers.sort.name", "Nome")
language.Add("npcpassengers.sort.seat", "Assento")
language.Add("npcpassengers.sort.health", "Saúde")
language.Add("npcpassengers.sort.status", "Estado")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Primeiro Veículo")
language.Add("npcpassengers.sort.name_az", "Nome A-Z")
language.Add("npcpassengers.sort.seat_number", "Número do Assento")
language.Add("npcpassengers.sort.highest_health", "Saúde Mais Alta")
language.Add("npcpassengers.sort.status_priority", "Prioridade de Estado")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Veículo: Desconhecido")
language.Add("npcpassengers.ui.seat_prefix", "Assento ")
language.Add("npcpassengers.ui.same_vehicle", "Mesmo Veículo")
language.Add("npcpassengers.ui.other_vehicle", "Outro Veículo")
language.Add("npcpassengers.ui.hidden", "Oculto")
language.Add("npcpassengers.ui.visible", "Visível")
language.Add("npcpassengers.ui.health_format", "Saúde %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Atualizar Lista de Passageiros")
language.Add("npcpassengers.ui.copy_list", "Copiar Lista Visível de Passageiros")
language.Add("npcpassengers.ui.make_exit", "Fazer Passageiros do Veículo Atual Saírem")
language.Add("npcpassengers.ui.reset_pos", "Redefinir Posição e Ângulos")
language.Add("npcpassengers.ui.crash_reactions", "Reações a Colisões")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Sons de Embarque/Desembarque")
language.Add("npcpassengers.section.ambient_sounds", "Sons Ambientais")
language.Add("npcpassengers.section.gesture_animations", "Animações de Gestos")
language.Add("npcpassengers.section.threat_awareness", "Consciência de Ameaças")
language.Add("npcpassengers.section.emotional_states", "Estados Emocionais")
language.Add("npcpassengers.section.turret_control", "Controle de Torre (Experimental)")
language.Add("npcpassengers.section.turret_blacklist", "Lista Negra de NPC de Torre")
language.Add("npcpassengers.section.idle_chatter", "Conversa Ociosa")
language.Add("npcpassengers.section.body_physics", "Física do Corpo")
language.Add("npcpassengers.section.npc_auto_driver", "Motorista Automático de NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Inferior Esquerda")
language.Add("npcpassengers.hud.bottom_right", "Inferior Direita")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Ativar HUD de Passageiros")
language.Add("npcpassengers.ui.cover_face", "Cobrir Rosto")
language.Add("npcpassengers.ui.apply_keybinds", "Aplicar Atalhos Recomendados")
language.Add("npcpassengers.ui.clear_keybinds", "Limpar Todos os Atalhos")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Testar Gesto de Encolhimento")
language.Add("npcpassengers.ui.test_random", "Testar Gesto Aleatório")
language.Add("npcpassengers.ui.reset_states", "Redefinir Todos os Estados")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Ativar Todas as Opções do Menu de Contexto")
language.Add("npcpassengers.ui.hide_context", "Ocultar Todas as Opções do Menu de Contexto")
language.Add("npcpassengers.ui.set_compact", "Definir Tamanho Compacto de Painel")
language.Add("npcpassengers.ui.set_default", "Definir Tamanho Padrão de Painel")
language.Add("npcpassengers.ui.set_large", "Definir Tamanho Grande de Painel")
language.Add("npcpassengers.ui.center_panel", "Centralizar Painel Agora")
language.Add("npcpassengers.ui.reset_ui", "Redefinir Todas as Configurações de UI para Padrão")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Cidadão (F)")
language.Add("npcpassengers.role.citizen_male", "Cidadão (M)")
language.Add("npcpassengers.role.medic", "Médico")
language.Add("npcpassengers.role.rebel", "Rebelde")
language.Add("npcpassengers.role.passenger", "Passageiro")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Mostrar Apenas Quando Estiver em Veículo")
language.Add("npcpassengers.hud.show_calm", "Mostrar Passageiros Calmos")
language.Add("npcpassengers.hud.show_hints", "Mostrar Dicas de Contexto")
language.Add("npcpassengers.hud.show_target_debug", "Mostrar Depuração de Alvo")
language.Add("npcpassengers.hud.play_cues", "Reproduzir Sinais de Sucesso/Falha")
language.Add("npcpassengers.debug.enable_mode", "Ativar Modo de Depuração")
language.Add("npcpassengers.ui.enable_sounds", "Ativar Sons UI")
language.Add("npcpassengers.ui.hover_sounds", "Sons ao Passar o Cursor")
language.Add("npcpassengers.ui.click_sounds", "Sons ao Clique")
language.Add("npcpassengers.ui.enable_animations", "Ativar Animações UI")
language.Add("npcpassengers.ui.show_tooltips", "Mostrar Dicas")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Ocultar Barra de Rolagem Automaticamente")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Suavidade de Rolagem da Barra Lateral")
language.Add("npcpassengers.ui.color_theme", "Tema de Cor")
language.Add("npcpassengers.ui.font_scale", "Escala de Fonte")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Cancelar Seleção de NPC")
language.Add("npcpassengers.context.remove_passenger", "Remover Passageiro")
language.Add("npcpassengers.context.blacklist_passenger", "Adicionar à Lista Negra")
language.Add("npcpassengers.context.whitelist_passenger", "Adicionar à Lista Branca")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Atalhos de Teclado")
language.Add("npcpassengers.keybinds.desc", "Configure atalhos de teclado para ações rápidas.")
language.Add("npcpassengers.keybind.attach", "Anexar NPC Mais Próximo")
language.Add("npcpassengers.keybind.attach.help", "Anexa o NPC amigável mais próximo ao seu veículo.")
language.Add("npcpassengers.keybind.detach_all", "Separar Todos os NPCs")
language.Add("npcpassengers.keybind.detach_all.help", "Remove todos os passageiros do seu veículo.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Alternar Entrada Automática")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Ativa/desativa rapidamente a entrada automática.")
language.Add("npcpassengers.keybind.menu", "Abrir Menu de Configurações")
language.Add("npcpassengers.keybind.menu.help", "Abre o painel de configurações.")
language.Add("npcpassengers.keybind.exit_all", "Todos os Passageiros Saem")
language.Add("npcpassengers.keybind.exit_all.help", "Faz todos os passageiros saírem do veículo.")
language.Add("npcpassengers.keybind.toggle_hud", "Alternar HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Mostra/oculta o HUD de passageiros.")
language.Add("npcpassengers.keybind.quick_attach", "Modo de Anexo Rápido")
language.Add("npcpassengers.keybind.quick_attach.help", "Mantenha pressionado para anexar rapidamente os NPCs que você está olhando")
language.Add("npcpassengers.keybind.hold_fire", "NPCs Seguram Fogo")
language.Add("npcpassengers.keybind.hold_fire.help", "Diga aos artilheiros NPC para pararem de atirar")
language.Add("npcpassengers.keybind.open_fire", "NPCs Abrem Fogo")
language.Add("npcpassengers.keybind.open_fire.help", "Diga aos artilheiros NPC para engajarem alvos")
language.Add("npcpassengers.keybind.cycle_view", "Ciclar Vista de Passageiro")
language.Add("npcpassengers.keybind.cycle_view.help", "Cicla a câmera através dos passageiros")
language.Add("npcpassengers.keybind.cycle_hud_position", "Ciclar Posição de HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Move o HUD de passageiros através das quatro cantos")
language.Add("npcpassengers.keybind.toggle_debug", "Alternar Depuração de Alvo")
language.Add("npcpassengers.keybind.toggle_debug.help", "Alterna a sobreposição pequena de depuração de alvo")
language.Add("npcpassengers.keybind.test_gesture", "Testar Gesto Aleatório")
language.Add("npcpassengers.keybind.test_gesture.help", "Reproduz um gesto aleatório no passageiro mais próximo")
language.Add("npcpassengers.keybind.reset_all", "Redefinir Todos os NPCs")
language.Add("npcpassengers.keybind.reset_all.help", "Redefine estados de animação para todos os passageiros")

-- HUD Settings
language.Add("npcassengers.hud.header", "Configurações de HUD")
language.Add("npcpassengers.hud.enable", "Ativar HUD")
language.Add("npcpassengers.hud.enable.help", "Mostra sobreposição de estado de passageiros na tela.")
language.Add("npcpassengers.hud.position", "Posição de HUD")
language.Add("npcpassengers.hud.position.help", "Onde o HUD aparece na tela.")
language.Add("npcpassengers.hud.position.topleft", "Superior Esquerda")
language.Add("npcpassengers.hud.position.topright", "Superior Direita")
language.Add("npcpassengers.hud.position.bottomleft", "Inferior Esquerda")
language.Add("npcpassengers.hud.position.bottomright", "Inferior Direita")
language.Add("npcpassengers.hud.scale", "Escala de HUD")
language.Add("npcpassengers.hud.scale.help", "Multiplicador de tamanho para o HUD.")
language.Add("npcpassengers.hud.opacity", "Opacidade de HUD")
language.Add("npcpassengers.hud.opacity.help", "Transparência de fundo (0 = invisível, 1 = sólido).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Motorista NPC")
language.Add("npcpassengers.driver.desc", "Permite que NPCs dirijam veículos para você.")
language.Add("npcpassengers.driver.enable", "Ativar Motoristas NPC")
language.Add("npcpassengers.driver.enable.help", "Permite que NPCs tomem o controle de veículos.")
language.Add("npcpassengers.driver.behavior", "Comportamento de Condução")
language.Add("npcpassengers.driver.behavior.help", "Como o NPC dirige o veículo.")
language.Add("npcpassengers.driver.behavior.cruise", "Cruzeiro Aleatório")
language.Add("npcpassengers.driver.behavior.follow", "Seguir Jogador")
language.Add("npcpassengers.driver.behavior.patrol", "Patrulha")
language.Add("npcpassengers.driver.behavior.flee", "Fugir")
language.Add("npcpassengers.driver.behavior.parked", "Permanecer Estacionado")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Perguntas Frequentes")
language.Add("npcpassengers.help.desc", "Respostas rápidas para perguntas comuns e solução de problemas.")
language.Add("npcpassengers.help.still_need", "Ainda Precisa de Ajuda?")
language.Add("npcpassengers.help.community", "Junte-se à nossa comunidade Discord para suporte!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Tanque/LVS")
language.Add("npcpassengers.nav.debugging", "Depuração")
language.Add("npcpassengers.nav.driver", "Motorista NPC")
language.Add("npcpassengers.nav.interface", "Interface")
language.Add("npcassengers.nav.simulate", "Simular")
language.Add("npcpassengers.nav.modules", "Módulos")
language.Add("npcpassengers.nav.about", "Sobre")
language.Add("npcpassengers.search.placeholder", "Pesquisar configurações...")

-- About page
language.Add("npcpassengers.about.description", "Sistema de passageiros avançado com IA emocional e física realista")
language.Add("npcpassengers.about.feature_status", "Sistema de Estado: CALMO / ALERTA / MEDO / SONOLENTO / MORTO")
language.Add("npcpassengers.about.feature_performance", "Performance: cache de assentos, temporizadores limitados, ganchos de cliente otimizados")
language.Add("npcpassengers.about.feature_filtering", "Filtragem de veículos, recarga de nova tentativa de embarque, entrada automática apenas para esquadrões")
language.Add("npcpassengers.about.actions", "Ações")
language.Add("npcpassengers.about.show_welcome", "Mostrar Tela de Boas-Vindas")
language.Add("npcpassengers.about.open_github", "Abrir Página do GitHub")
language.Add("npcpassengers.about.reset_settings", "Redefinir TODAS as Configurações para Padrão")

-- Status messages
language.Add("npcpassengers.status.calm", "CALMO")
language.Add("npcpassengers.status.alert", "ALERTA")
language.Add("npcpassengers.status.scared", "MEDO")
language.Add("npcpassengers.status.drowsy", "SONOLENTO")
language.Add("npcpassengers.status.dead", "MORTO")
language.Add("npcpassengers.status.calm.desc", "Relaxado, sem ameaças próximas")
language.Add("npcpassengers.status.alert.desc", "Inimigo detectado, NPC está rastreando ameaças")
language.Add("npcpassengers.status.scared.desc", "Condução perigosa (alta velocidade, colisões)")
language.Add("npcpassengers.status.drowsy.desc", "Viagem longa e calma, NPC está ficando sonolento")
language.Add("npcpassengers.status.dead.desc", "Saúde atingiu zero")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Entrada Automática: LIGADO")
language.Add("npcpassengers.chat.autojoin_off", "Entrada Automática: DESLIGADO")
language.Add("npcpassengers.chat.hud_on", "HUD: LIGADO")
language.Add("npcpassengers.chat.hud_off", "HUD: DESLIGADO")
language.Add("npcpassengers.chat.prefix", "[Melhores Passageiros NPC]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Nenhum veículo próximo")
language.Add("npcpassengers.error.no_npc", "Nenhum NPC próximo")
language.Add("npcpassengers.error.vehicle_full", "Veículo está cheio")
language.Add("npcpassengers.error.too_far", "NPC muito longe do veículo")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Alterar idioma")
language.Add("npcpassengers.tooltip.minimize", "Minimizar painel")
language.Add("npcpassengers.tooltip.expand", "Expandir painel")
language.Add("npcpassengers.tooltip.welcome", "Mostrar tela de boas-vindas")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Interruptor mestre para toda a voz de NPC. Desative para silenciar passageiros completamente.")
language.Add("npcpassengers.speech_volume.help", "Quão altas são as vozes dos NPCs (0 = silencioso, 100 = volume completo).")
language.Add("npcpassengers.pitch_variation.help", "Variação aleatória de tom para vozes mais naturais. 0 = monótono, mais alto = mais variedade.")
language.Add("npcpassengers.crash_enable.help", "Os NPCs grunhem/gemem quando o veículo desacelera bruscamente (colisões, freada brusca).")
language.Add("npcpassengers.crash_threshold.help", "Desaceleração necessária para ativar sons de colisão. Menor = mais sensível.")
language.Add("npcpassengers.crash_cooldown.help", "Segundos mínimos entre sons de colisão por NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "Os NPCs ocasionalmente falam enquanto viajam - comentários, perguntas, observações.")
language.Add("npcpassengers.speech_idle_chance.help", "Probabilidade de conversa por verificação. 0 = nunca, 1 = sempre tenta falar.")
language.Add("npcpassengers.speech_idle_interval.help", "Segundos mínimos entre tentativas de conversa ociosa.")
language.Add("npcpassengers.speech_board.help", "Os NPCs falam quando entram e saem do veículo.")
language.Add("npcpassengers.ambient_sounds.help", "Tosses ocasionais, suspiros, murmúrios - sons de vida de fundo.")
language.Add("npcpassengers.ambient_interval.help", "Segundos médios entre sons ambientais.")
language.Add("npcpassengers.animation.help", "Ajuste finamente as animações de NPC e o movimento de cabeça.")
language.Add("npcpassengers.head_look.help", "Os NPCs olham naturalmente ao redor, para o jogador, pelas janelas, etc.")
language.Add("npcpassengers.head_smooth.help", "Quão suavemente a cabeça se move. Menor = mais rápido, maior = mais flutuante.")
language.Add("npcpassengers.blink.help", "Os NPCs piscam de forma realista enquanto estão sentados.")
language.Add("npcpassengers.breathing.help", "Animação de respiração sutil nas cabeças dos NPCs.")
language.Add("npcpassengers.walk_timeout.help", "Segundos antes do NPC desistir de caminhar para o veículo.")
language.Add("npcpassengers.realism.help", "Reações baseadas em física e sistemas de consciência para imersão máxima.")
language.Add("npcpassengers.talking_gestures.help", "Os NPCs reproduzem aleatoriamente gestos de mãos e animações corporais enquanto viajam.")
language.Add("npcpassengers.gesture_chance.help", "Porcentagem de probabilidade de reproduzir um gesto a cada intervalo.")
language.Add("npcpassengers.gesture_interval.help", "Segundos entre verificações de oportunidade de gesto.")
language.Add("npcpassengers.crash_flinch.help", "Os NPCs se encolhem e se lançam para frente quando o veículo colide ou freia bruscamente.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Mudança de velocidade necessária para ativar encolhimento (menor = mais sensível).")
language.Add("npcpassengers.body_sway.help", "Os NPCs se inclinam em curvas, se apoiam durante aceleração/freada.")
language.Add("npcpassengers.body_sway_amount.help", "Quanto os NPCs balançam com o movimento do veículo.")
language.Add("npcpassengers.threat_awareness.help", "Os NPCs olham automaticamente para inimigos próximos.")
language.Add("npcpassengers.threat_range.help", "A que distância os NPCs podem detectar ameaças para rastreamento de cabeça.")
language.Add("npcpassengers.combat_alert.help", "Os NPCs ficam tensos e reativos quando inimigos estão próximos.")
language.Add("npcpassengers.passenger_combat.help", "Desativado por padrão. Ative isso para permitir que passageiros armados atirem de dentro de veículos.")
language.Add("npcpassengers.passenger_combat_range.help", "A que distância passageiros armados podem adquirir alvos.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Valores mais altos apertam a dispersão de tiros para passageiros armados.")
language.Add("npcpassengers.passenger_combat_damage.help", "Escala o dano causado por tiros de passageiros.")
language.Add("npcpassengers.passenger_interaction.help", "Múltiplos passageiros olham e ocasionalmente conversam entre si.")
language.Add("npcpassengers.fear_reactions.help", "Os NPCs ficam com medo da condução perigosa - olhos abertos, sons de pânico.")
language.Add("npcpassengers.fear_speed_threshold.help", "Velocidade (unidades/seg) na qual os NPCs começam a ficar nervosos.")
language.Add("npcpassengers.drowsiness.help", "Os NPCs ficam sonolentos em viagens longas e calmas - piscadas lentas, cabeceios.")
language.Add("npcpassengers.drowsy_time.help", "Segundos de condução calma antes que a sonolência comece.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Configurações para tanques, APCs e veículos LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Torna passageiros NPC invisíveis quando estão dentro de tanques e APCs.")
language.Add("npcpassengers.eject_stuck_check.help", "Empurra automaticamente os NPCs para fora dos veículos quando eles ficam presos durante a ejeção. Impede que os NPCs atravessem veículos ao sair.")
language.Add("npcpassengers.detach_no_collide.help", "Após desanexar, os NPCs passam temporariamente através do veículo para que possam caminhar sem intersecção ou ficarem presos.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Quanto tempo os NPCs ignoram a colisão do veículo após desanexar.")
language.Add("npcpassengers.die_with_vehicle.help", "Passageiros NPC morrem quando seu veículo é destruído por explosão ou fogo (mais imersivo do que saírem dos destroços ilesos).")
language.Add("npcpassengers.tank_driver.help", "Permite que NPCs no assento do motorista dirijam automaticamente em direção aos inimigos.")
language.Add("npcpassengers.tank_driver_range.help", "Alcance máximo para o motorista detectar inimigos.")
language.Add("npcpassengers.tank_driver_distance.help", "Distância a manter dos inimigos.")
language.Add("npcpassengers.tank_driver_throttle.help", "Quantidade de acelerador (0.1 = lento, 1 = velocidade completa).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distância na qual para dar ré para longe dos inimigos.")
language.Add("npcpassengers.tank_turret.help", "Permite que NPCs controlem torres em veículos LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Mostra estado de passageiros (emoções, alerta) na tela enquanto dirige.")
language.Add("npcpassengers.hud_show_calm.help", "Quando desativado, mostra apenas passageiros com estado não calmo.")
language.Add("npcpassengers.hud_thresholds.desc", "Quando os níveis de emoção excedem esses limitares, os passageiros mostram esse estado no HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Nível de alerta necessário para mostrar estado 'ALERTA' (ameaça detectada).")
language.Add("npcpassengers.hud_fear_threshold.help", "Nível de medo necessário para mostrar estado 'MEDO' (condução perigosa).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Razão de tempo calmo necessário para mostrar estado 'SONOLENTO' (viagem longa e calma).")
language.Add("npcpassengers.hud_actions.desc", "Escolha qual ação os passageiros tomam quando experimentam cada estado emocional.")
language.Add("npcpassengers.hud_actions_note", "Nota: Algumas ações podem não ser visíveis dependendo do suporte do modelo de NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Defina atalhos personalizados para ações de passageiro. Clique em um botão e pressione uma tecla para atribuir.")
language.Add("npcpassengers.keybinds_hud.desc", "Controles rápidos de HUD para mostrar, mover e depurar a sobreposição de passageiros.")
language.Add("npcpassengers.keybinds_debug_note", "Atalhos de depuração funcionam apenas quando o Modo de Depuração está ativado.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Ferramentas avançadas de depuração para testar o comportamento de NPC. Ative o Modo de Depuração nas configurações primeiro.")
language.Add("npcpassengers.debug_mode.help", "Mostra botões de teste de depuração e habilita comandos de depuração.")
language.Add("npcpassengers.debug_status.help", "Define manualmente o estado do passageiro para testes. Clique em 'Atualizar Lista' para ver os passageiros atuais.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configure efeitos de som para botões, caixas de seleção e outros elementos UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Interruptor mestre para todos os efeitos de som UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Multiplicador de volume para sons UI (1.0 = normal, 2.0 = dobro)")
language.Add("npcpassengers.ui_hover_enabled.help", "Reproduz som ao passar o cursor sobre botões")
language.Add("npcpassengers.ui_click_enabled.help", "Reproduz som ao clicar em botões e caixas de seleção")
language.Add("npcpassengers.context_menu.desc", "Escolha quais opções aparecem ao clicar com o botão direito em NPCs")
language.Add("npcpassengers.context_make_passenger.help", "Adiciona NPC como passageiro ao seu veículo atual")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Adiciona NPC a um veículo específico (clique no NPC, depois no veículo)")
language.Add("npcpassengers.context_detach.help", "Remove NPC do veículo")
language.Add("npcpassengers.ui_show_welcome.help", "Exibe painel de boas-vindas quando o addon é atualizado para uma nova versão")
language.Add("npcpassengers.ui_panel_width.help", "Largura do painel de configurações")
language.Add("npcpassengers.ui_panel_height.help", "Altura do painel de configurações")
language.Add("npcpassengers.ui_animations.help", "Transições suaves e efeitos de hover (pode afetar performance)")
language.Add("npcpassengers.ui_tooltips.help", "Exibe dicas úteis ao passar o cursor sobre configurações")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Mostra a barra de rolagem apenas enquanto você está rolando ou passando o cursor sobre ela.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Nota: O painel fica 70% transparente ao arrastar qualquer controle deslizante para ver conteúdo em segundo plano.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Valores mais baixos = mais suave mas mais lento (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Escolha um tema de cor para o painel de configurações. As alterações são aplicadas imediatamente.")
language.Add("npcpassengers.ui_font_scale.help", "Escala todos os tamanhos de fonte UI. 1.0 = padrão, 0.5 = meio tamanho, 2.0 = tamanho dobrado.")

print("[Better NPC Passengers] Portuguese localization loaded!")
