-- Better NPC Passengers - Russian Localization
-- TRANSLATORS: Replace the English text after each language.Add() with Russian translations
-- This is a template - fill in the Russian translations

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Настройки")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Общие")
language.Add("npcpassengers.nav.autojoin", "Авто-посадка")
language.Add("npcpassengers.nav.passengers", "Пассажиры")
language.Add("npcpassengers.nav.position", "Позиция")
language.Add("npcpassengers.nav.behaviour", "Поведение")
language.Add("npcpassengers.nav.keybinds", "Клавиши")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Водитель")
language.Add("npcpassengers.nav.help", "Помощь")

-- General Settings
language.Add("npcpassengers.general.header", "Общие настройки")
language.Add("npcpassengers.allow_multiple", "Разрешить несколько пассажиров")
language.Add("npcpassengers.allow_multiple.help", "Позволяет нескольким NPC ехать в одном транспорте.")
language.Add("npcpassengers.exit_behavior", "Поведение при выходе")
language.Add("npcpassengers.exit_behavior.help", "Когда NPC пассажиры должны покинуть транспорт?")
language.Add("npcpassengers.exit_mode.leave_player", "Покинуть когда игрок выходит")
language.Add("npcpassengers.exit_mode.leave_attack", "Покинуть когда транспорт атакуют")
language.Add("npcpassengers.exit_mode.never", "Никогда не выходить автоматически")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Тайминги")
language.Add("npcpassengers.max_attach_dist", "Макс. дистанция посадки")
language.Add("npcpassengers.max_attach_dist.help", "Максимальное расстояние (единицы) для посадки NPC в транспорт.")
language.Add("npcpassengers.detach_delay", "Задержка выхода")
language.Add("npcpassengers.detach_delay.help", "Секунды ожидания перед выходом после того как игрок покидает транспорт.")
language.Add("npcpassengers.ai_delay", "Задержка восстановления ИИ")
language.Add("npcpassengers.ai_delay.help", "Секунды ожидания перед восстановлением ИИ NPC после выхода.")
language.Add("npcpassengers.cooldown", "Время перезарядки")
language.Add("npcpassengers.cooldown.help", "Перезарядка между посадками NPC в тот же транспорт.")
language.Add("npcpassengers.passenger_limit", "Лимит пассажиров")
language.Add("npcpassengers.passenger_limit.help", "Максимум NPC в транспорте.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Авто-посадка (Поведение отряда)")
language.Add("npcpassengers.autojoin.desc", "Дружественные NPC будут автоматически садиться в ваш транспорт когда вы в него входите - как механика отрядов в Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Включить авто-посадку")
language.Add("npcpassengers.autojoin.enable.help", "Поблизости дружественные NPC будут автоматически присоединяться когда вы садитесь в транспорт.")
language.Add("npcpassengers.autojoin.range", "Дальность авто-посадки")
language.Add("npcpassengers.autojoin.range.help", "Максимальное расстояние для поиска NPC для авто-посадки.")
language.Add("npcpassengers.autojoin.max", "Макс. NPC для авто-посадки")
language.Add("npcpassengers.autojoin.max.help", "Максимальное количество NPC которые могут автоматически сесть за раз.")
language.Add("npcpassengers.autojoin.squad_only", "Только члены отряда")
language.Add("npcpassengers.autojoin.squad_only.help", "Только NPC с именем отряда будут автоматически садиться (для отрядов в стиле HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Дружественные NPC будут автоматически садиться в ваш транспорт когда вы в него входите - как механика отрядов в Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Управление пассажирами")
language.Add("npcpassengers.panel.passengers.desc", "Управляйте активными пассажирами, фильтруйте по имени/классу/статусу, копируйте отладочную информацию, переназначайте места и высаживайте пассажиров не выходя из панели настроек.")
language.Add("npcpassengers.panel.position.desc", "Точная настройка позиции NPC в транспорте. Используйте это чтобы исправить проблемы с парением или клиппингом.")
language.Add("npcpassengers.panel.angle.desc", "Настройка вращения NPC в транспорте.")
language.Add("npcpassengers.panel.speech.desc", "Настройка того как NPC vocalize во время езды в транспорте. Голоса граждан в стиле HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Смещения позиции")
language.Add("npcpassengers.position.desc", "Точная настройка позиции NPC в транспорте. Используйте это чтобы исправить проблемы с парением или клиппингом.")
language.Add("npcpassengers.height_offset", "Смещение по высоте")
language.Add("npcpassengers.forward_offset", "Смещение вперед")
language.Add("npcpassengers.right_offset", "Смещение вправо")
language.Add("npcpassengers.angle.header", "Смещения углов")
language.Add("npcpassengers.angle.desc", "Настройка вращения NPC в транспорте.")
language.Add("npcpassengers.yaw_offset", "Рыскание (Вращение)")
language.Add("npcpassengers.pitch_offset", "Тангаж (Наклон вперед)")
language.Add("npcpassengers.roll_offset", "Крен (Наклон вбок)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Речь NPC (Расширенное)")
language.Add("npcpassengers.behaviour.desc", "Настройка того как NPC vocalize во время езды в транспорте. Голоса граждан в стиле HL2!")
language.Add("npcpassengers.speech_enable", "Включить речь NPC")
language.Add("npcpassengers.speech_enable.help", "Главный переключатель для всей речи NPC. Отключите чтобы полностью замолчить пассажиров.")
language.Add("npcpassengers.speech_volume", "Громкость речи")
language.Add("npcpassengers.speech_volume.help", "Насколько громко говорят NPC (0 = тихо, 100 = полная громкость).")
language.Add("npcpassengers.pitch_variation", "Вариация тона (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Случайная вариация тона для более естественных голосов. 0 = монотонно, выше = больше разнообразия.")
language.Add("npcpassengers.crash.header", "Реакции на аварии")
language.Add("npcpassengers.crash_enable", "Включить звуки аварий")
language.Add("npcpassengers.crash_enable.help", "NPC стонут/вскрикивают когда транспорт резко замедляется (аварии, резкое торможение).")
language.Add("npcpassengers.crash_threshold", "Чувствительность к авариям")
language.Add("npcpassengers.crash_threshold.help", "Замедление необходимое для triggering звуков аварий. Ниже = более чувствительно.")
language.Add("npcpassengers.crash_cooldown", "Перезарядка звуков аварий")
language.Add("npcpassengers.crash_cooldown.help", "Минимальные секунды между звуками аварий на NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Включить болтовню")
language.Add("npcpassengers.speech_board", "Включить звуки посадки/выхода")
language.Add("npcpassengers.ambient_sounds", "Включить фоновые звуки")
language.Add("npcpassengers.head_look", "Включить взгляд головы/глаз")
language.Add("npcpassengers.blink", "Включить моргание")
language.Add("npcpassengers.breathing", "Включить дыхание")
language.Add("npcpassengers.talking_gestures", "Включить жесты разговора")
language.Add("npcpassengers.crash_flinch", "Включить вздрагивание при аварии")
language.Add("npcpassengers.body_sway", "Включить покачивание тела")
language.Add("npcpassengers.threat_awareness", "Включить осознанность угроз")
language.Add("npcpassengers.combat_alert", "Боевая готовность")
language.Add("npcpassengers.passenger_combat", "NPC стреляют из транспорта (Экспериментально)")
language.Add("npcpassengers.passenger_interaction", "Взаимодействие пассажиров")
language.Add("npcpassengers.fear_reactions", "Включить реакции страха")
language.Add("npcpassengers.drowsiness", "Включить сонливость")
language.Add("npcpassengers.hide_in_tanks", "Скрыть NPC в закрытых транспортных средствах")
language.Add("npcpassengers.eject_stuck_check", "Авто-выталкивание застрявших NPC")
language.Add("npcpassengers.detach_no_collide", "Без коллизии с транспортом после выхода")
language.Add("npcpassengers.die_with_vehicle", "Убивать пассажиров при взрыве транспорта")
language.Add("npcpassengers.driver_enabled", "Включить авто-езду")
language.Add("npcpassengers.turret_enabled", "Включить управление турелью")
language.Add("npcpassengers.turret_lead_targets", "Предварение целей")
language.Add("npcpassengers.turret_friendly_fire", "Разрешить дружественный огонь")
language.Add("npcpassengers.turret_hold_fire", "Удерживать огонь (Отключить стрельбу)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Громкость речи")
language.Add("npcpassengers.pitch_variation", "Вариация тона (+/-)")
language.Add("npcpassengers.crash_threshold", "Чувствительность к авариям")
language.Add("npcpassengers.crash_cooldown", "Перезарядка звуков аварий")
language.Add("npcpassengers.speech_idle_chance", "Шанс болтовни")
language.Add("npcpassengers.speech_idle_interval", "Интервал болтовни")
language.Add("npcpassengers.ambient_interval", "Интервал фоновых звуков")
language.Add("npcpassengers.head_smooth", "Плавность головы")
language.Add("npcpassengers.walk_timeout", "Таймаут ходьбы")
language.Add("npcpassengers.gesture_chance", "Шанс жестов (%)")
language.Add("npcpassengers.gesture_interval", "Интервал жестов")
language.Add("npcpassengers.crash_threshold_flinch", "Чувствительность к авариям")
language.Add("npcpassengers.body_sway_amount", "Интенсивность покачивания")
language.Add("npcpassengers.threat_range", "Дальность обнаружения угроз")
language.Add("npcpassengers.passenger_combat_range", "Дальность боя пассажиров")
language.Add("npcpassengers.passenger_combat_accuracy", "Точность пассажиров")
language.Add("npcpassengers.passenger_combat_damage", "Множитель урона пассажиров")
language.Add("npcpassengers.fear_speed_threshold", "Порог скорости страха")
language.Add("npcpassengers.drowsy_time", "Время сонливости")
language.Add("npcpassengers.detach_no_collide_duration", "Длительность без коллизии (секунды)")
language.Add("npcpassengers.tank_driver_range", "Дальность обнаружения")
language.Add("npcpassengers.tank_driver_engage_distance", "Дистанция вступления")
language.Add("npcpassengers.tank_driver_speed", "Скорость езды")
language.Add("npcpassengers.tank_driver_reverse_distance", "Дистанция разворота")
language.Add("npcpassengers.turret_range", "Дальность цели")
language.Add("npcpassengers.turret_accuracy", "Точность")
language.Add("npcpassengers.turret_reaction_time", "Время реакции")
language.Add("npcpassengers.turret_fire_delay", "Задержка огня")
language.Add("npcpassengers.turret_aim_speed", "Скорость прицеливания")
language.Add("npcpassengers.hud_scale", "Масштаб HUD")
language.Add("npcpassengers.hud_opacity", "Прозрачность HUD")
language.Add("npcpassengers.hud_alert_threshold", "Порог тревоги")
language.Add("npcpassengers.hud_fear_threshold", "Порог страха")
language.Add("npcpassengers.hud_drowsy_threshold", "Порог сонливости")
language.Add("npcpassengers.ui_sounds_volume", "Громкость звуков UI")
language.Add("npcpassengers.ui_panel_width", "Ширина панели")

-- Section headers
language.Add("npcpassengers.section.animation", "Анимация и поведение")
language.Add("npcpassengers.section.realism", "Расширенный реализм")
language.Add("npcpassengers.section.hud_position", "Позиция и стиль HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Пороги эмоций")
language.Add("npcpassengers.section.emotion_actions", "Действия эмоций")
language.Add("npcpassengers.section.vehicle_control", "Управление транспортом")
language.Add("npcpassengers.section.hud_controls", "Управление HUD")
language.Add("npcpassengers.section.debug_controls", "Управление отладкой")
language.Add("npcpassengers.section.passenger_status", "Управление статусом пассажиров")
language.Add("npcpassengers.section.quick_test", "Кнопки быстрого теста")
language.Add("npcpassengers.section.driver_system", "Система NPC водителя")
language.Add("npcpassengers.section.ui_sounds", "Настройки звуков UI")
language.Add("npcpassengers.section.context_menu", "Опции контекстного меню")
language.Add("npcpassengers.section.panel_preferences", "Предпочтения панели настроек")
language.Add("npcpassengers.section.performance", "Производительность и техническое")
language.Add("npcpassengers.section.simulation", "Система симуляции")
language.Add("npcpassengers.section.modules", "Система модулей")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Назначить место")
language.Add("npcpassengers.btn.detach", "Отсоединить")
language.Add("npcpassengers.btn.copy_summary", "Копировать сводку")
language.Add("npcpassengers.btn.copy_debug", "Копировать отладку")
language.Add("npcpassengers.btn.enable_all_speech", "Включить всю речь")
language.Add("npcpassengers.btn.disable_all_speech", "Отключить всю речь")
language.Add("npcpassengers.btn.show_current_vehicle", "Показывать только текущий транспорт")
language.Add("npcpassengers.btn.auto_refresh", "Автообновление видимого списка")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Текущий транспорт не обнаружен. Сядьте в транспорт или отключите фильтр текущего транспорта.")
language.Add("npcpassengers.status.no_match_filter", "Пассажиры не соответствуют вашему фильтру. Попробуйте имя, класс, номер места, статус или класс транспорта.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Пассажиры не найдены в вашем текущем транспорте.")
language.Add("npcpassengers.status.no_passengers", "Пассажиры не найдены. NPC должны ехать в транспорте прежде чем их можно будет управлять здесь.")
language.Add("npcpassengers.status.all_passengers", "Все пассажиры")
language.Add("npcpassengers.status.current_vehicle_only", "Только текущий транспорт")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F для фокуса поиска")
language.Add("npcpassengers.status.no_matches", "Нет соответствующих настроек")
language.Add("npcpassengers.status.showing_matches", "Показано %d из %d совпадений")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Открыть настройки")
language.Add("npcpassengers.menu.reset_all", "Сбросить все настройки")

-- Button states
language.Add("npcpassengers.state.on", "ВКЛ")
language.Add("npcpassengers.state.off", "ВЫКЛ")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Авто-посадка")
language.Add("npcpassengers.chat.hud_status", "HUD пассажиров")
language.Add("npcpassengers.chat.hud_position", "Позиция HUD")
language.Add("npcpassengers.chat.target_debug", "Отладка цели")
language.Add("npcpassengers.chat.turret_gunners", "Стрелки турели")
language.Add("npcpassengers.chat.turret_holding", "УДЕРЖИВАЮТ ОГОНЬ")
language.Add("npcpassengers.chat.turret_fire", "ОТКРЫТ ОГОНЬ")
language.Add("npcpassengers.chat.unknown", "Неизвестно")
language.Add("npcpassengers.chat.nothing_copy", "Нечего копировать.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Доступ к буферу обмена недоступен в этой сборке.")
language.Add("npcpassengers.chat.copied_clipboard", "Скопировано в буфер обмена.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Сядьте в тот же транспорт чтобы переназначить этого пассажира.")
language.Add("npcpassengers.chat.no_visible_passengers", "Нет видимых пассажиров для копирования.")
language.Add("npcpassengers.chat.need_vehicle", "Вам нужно быть в транспорте чтобы использовать это.")
language.Add("npcpassengers.chat.keybinds_applied", "Рекомендованные привязки применены.")
language.Add("npcpassengers.chat.keybinds_cleared", "Все привязки очищены.")
language.Add("npcpassengers.chat.context_enabled", "Все опции контекстного меню включены.")
language.Add("npcpassengers.chat.context_hidden", "Все опции контекстного меню скрыты.")
language.Add("npcpassengers.chat.panel_compact", "Размер панели установлен на компактный.")
language.Add("npcpassengers.chat.panel_default", "Размер панели установлен на стандартный.")
language.Add("npcpassengers.chat.panel_large", "Размер панели установлен на большой.")
language.Add("npcpassengers.chat.panel_centered", "Панель центрирована.")
language.Add("npcpassengers.chat.settings_reset", "Все настройки UI сброшены на значения по умолчанию!")
language.Add("npcpassengers.chat.npc_selected", "NPC выбран! Теперь нажмите правой кнопкой на транспорт и выберите 'Добавить выбранного NPC'")
language.Add("npcpassengers.chat.adding_npc", "Добавление NPC в транспорт...")
language.Add("npcpassengers.chat.summary_copied", "Сводка пассажиров скопирована.")
language.Add("npcpassengers.chat.debug_copied", "Отладочная информация пассажира скопирована.")
language.Add("npcpassengers.chat.no_passengers_found", "Пассажиры не найдены. NPC должны быть в транспорте.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Интенсивность статуса %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Фильтровать пассажиров...")
language.Add("npcpassengers.ui.press_key", "Нажмите клавишу...")
language.Add("npcpassengers.ui.work_in_progress", "В разработке")
language.Add("npcpassengers.ui.under_development", "Эта функция находится в разработке")
language.Add("npcpassengers.ui.check_back_later", "Проверьте в будущем обновлении!")
language.Add("npcpassengers.ui.search_desc_passengers", "Фильтровать активных пассажиров по имени, классу, месту, статусу или транспорту.")
language.Add("npcpassengers.ui.search_desc_sort", "Сортировать видимый список пассажиров по транспорту, имени, месту, здоровью или статусу.")
language.Add("npcpassengers.ui.search_label_filter", "Фильтр пассажиров")
language.Add("npcpassengers.ui.search_label_sort", "Сортировка пассажиров")

-- Additional keybind names and descriptions
language.Add("npcpassengers.keybind.quick_attach", "Быстрая посадка")
language.Add("npcpassengers.keybind.hold_fire", "NPC удерживают огонь")
language.Add("npcpassengers.keybind.open_fire", "NPC открывают огонь")
language.Add("npcpassengers.keybind.cycle_view", "Цикл камеры пассажиров")
language.Add("npcpassengers.keybind.cycle_hud_position", "Цикл позиции HUD")
language.Add("npcpassengers.keybind.toggle_debug", "Переключить отладку цели")
language.Add("npcpassengers.keybind.test_gesture", "Тест случайного жеста")
language.Add("npcpassengers.keybind.reset_all", "Сбросить всех NPC")
language.Add("npcpassengers.keybind.quick_attach.help", "Удерживайте чтобы быстро посадить NPC на которые вы смотрите")
language.Add("npcpassengers.keybind.hold_fire.help", "Сказать стрелкам NPC прекратить стрельбу")
language.Add("npcpassengers.keybind.open_fire.help", "Сказать стрелкам NPC атаковать цели")
language.Add("npcpassengers.keybind.cycle_view.help", "Циклически переключать камеру между пассажирами")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Переместить HUD пассажиров через все четыре угла")
language.Add("npcpassengers.keybind.toggle_debug.help", "Переключить маленькое оверлей отладки цели")
language.Add("npcpassengers.keybind.test_gesture.help", "Сыграть случайный жест на ближайшем пассажире")
language.Add("npcpassengers.keybind.reset_all.help", "Сбросить состояния анимации для всех пассажиров")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Клавиши")
language.Add("npcpassengers.keybinds.desc", "Настройка горячих клавиш для быстрых действий.")
language.Add("npcpassengers.keybind.attach", "Посадить ближайшего NPC")
language.Add("npcpassengers.keybind.attach.help", "Посадить ближайшего дружественного NPC в ваш транспорт.")
language.Add("npcpassengers.keybind.detach_all", "Высадить всех NPC")
language.Add("npcpassengers.keybind.detach_all.help", "Удалить всех пассажиров из вашего транспорта.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Переключить авто-посадку")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Быстро включить/выключить авто-посадку.")
language.Add("npcpassengers.keybind.menu", "Открыть меню настроек")
language.Add("npcpassengers.keybind.menu.help", "Открыть панель настроек.")
language.Add("npcpassengers.keybind.exit_all", "Выход всех пассажиров")
language.Add("npcpassengers.keybind.exit_all.help", "Заставить всех пассажиров покинуть транспорт.")
language.Add("npcpassengers.keybind.toggle_hud", "Переключить HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Показать/скрыть HUD пассажиров.")

-- HUD Settings
language.Add("npcpassengers.hud.header", "Настройки HUD")
language.Add("npcpassengers.hud.enable", "Включить HUD")
language.Add("npcpassengers.hud.enable.help", "Показать оверлей статуса пассажиров на экране.")
language.Add("npcpassengers.hud.position", "Позиция HUD")
language.Add("npcpassengers.hud.position.help", "Где HUD появляется на экране.")
language.Add("npcpassengers.hud.position.topleft", "Слева вверху")
language.Add("npcpassengers.hud.position.topright", "Справа вверху")
language.Add("npcpassengers.hud.position.bottomleft", "Слева внизу")
language.Add("npcpassengers.hud.position.bottomright", "Справа внизу")
language.Add("npcpassengers.hud.scale", "Масштаб HUD")
language.Add("npcpassengers.hud.scale.help", "Множитель размера для HUD.")
language.Add("npcpassengers.hud.opacity", "Прозрачность HUD")
language.Add("npcpassengers.hud.opacity.help", "Прозрачность фона (0 = невидимый, 1 = сплошной).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC Водитель")
language.Add("npcpassengers.driver.desc", "Разрешить NPC водить транспорт за вас.")
language.Add("npcpassengers.driver.enable", "Включить NPC водителей")
language.Add("npcpassengers.driver.enable.help", "Разрешить NPC взять контроль над транспортом.")
language.Add("npcpassengers.driver.behavior", "Поведение водителя")
language.Add("npcpassengers.driver.behavior.help", "Как NPC водит транспорт.")
language.Add("npcpassengers.driver.behavior.cruise", "Случайная поездка")
language.Add("npcpassengers.driver.behavior.follow", "Следовать за игроком")
language.Add("npcpassengers.driver.behavior.patrol", "Патруль")
language.Add("npcpassengers.driver.behavior.flee", "Бежать")
language.Add("npcpassengers.driver.behavior.parked", "Оставаться припаркованным")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Часто задаваемые вопросы")
language.Add("npcpassengers.help.desc", "Быстрые ответы на общие вопросы и устранение проблем.")
language.Add("npcpassengers.help.still_need", "Все еще нужна помощь?")
language.Add("npcpassengers.help.community", "Присоединяйтесь к нашему Discord сообществу для поддержки!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Танк/LVS")
language.Add("npcpassengers.nav.debugging", "Отладка")
language.Add("npcpassengers.nav.driver", "NPC Водитель")
language.Add("npcpassengers.nav.interface", "Интерфейс")
language.Add("npcpassengers.nav.simulate", "Симуляция")
language.Add("npcpassengers.nav.modules", "Модули")
language.Add("npcpassengers.nav.about", "О программе")
language.Add("npcpassengers.search.placeholder", "Поиск настроек...")

-- About page
language.Add("npcpassengers.about.description", "Продвинутая система пассажиров с эмоциональным ИИ и реалистичной физикой")
language.Add("npcpassengers.about.feature_status", "Система статусов: СПОКОЕН / ТРЕВОГА / ИСПУГАН / СОННЫЙ / МЕРТВ")
language.Add("npcpassengers.about.feature_performance", "Производительность: кэширование мест, ограниченные таймеры, оптимизированные клиентские хуки")
language.Add("npcpassengers.about.feature_filtering", "Фильтрация транспорта, перезарядка повторных попыток посадки, авто-посадка только для отрядов")
language.Add("npcpassengers.about.actions", "Действия")
language.Add("npcpassengers.about.show_welcome", "Показать приветственный экран")
language.Add("npcpassengers.about.open_github", "Открыть страницу GitHub")
language.Add("npcpassengers.about.reset_settings", "Сбросить ВСЕ настройки по умолчанию")

-- Status messages
language.Add("npcpassengers.status.calm", "СПОКОЕН")
language.Add("npcpassengers.status.alert", "ТРЕВОГА")
language.Add("npcpassengers.status.scared", "ИСПУГАН")
language.Add("npcpassengers.status.drowsy", "СОННЫЙ")
language.Add("npcpassengers.status.dead", "МЕРТВ")
language.Add("npcpassengers.status.calm.desc", "Расслаблен, угроз поблизости нет")
language.Add("npcpassengers.status.alert.desc", "Враг обнаружен, NPC следит за угрозами")
language.Add("npcpassengers.status.scared.desc", "Опасная езда (высокая скорость, аварии)")
language.Add("npcpassengers.status.drowsy.desc", "Долгая спокойная езда, NPC становится сонным")
language.Add("npcpassengers.status.dead.desc", "Здоровье достигло нуля")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Авто-посадка: ВКЛ")
language.Add("npcpassengers.chat.autojoin_off", "Авто-посадка: ВЫКЛ")
language.Add("npcpassengers.chat.hud_on", "HUD: ВКЛ")
language.Add("npcpassengers.chat.hud_off", "HUD: ВЫКЛ")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Транспорта поблизости нет")
language.Add("npcpassengers.error.no_npc", "NPC поблизости нет")
language.Add("npcpassengers.error.vehicle_full", "Транспорт полон")
language.Add("npcpassengers.error.too_far", "NPC слишком далеко от транспорта")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Изменить язык")
language.Add("npcpassengers.tooltip.minimize", "Свернуть панель")
language.Add("npcpassengers.tooltip.expand", "Развернуть панель")
language.Add("npcpassengers.tooltip.welcome", "Показать приветственный экран")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Главный переключатель для всей речи NPC. Отключите чтобы полностью замолчить пассажиров.")
language.Add("npcpassengers.speech_volume.help", "Насколько громко говорят NPC (0 = тихо, 100 = полная громкость).")
language.Add("npcpassengers.pitch_variation.help", "Случайная вариация тона для более естественных голосов. 0 = монотонно, выше = больше разнообразия.")
language.Add("npcpassengers.crash_enable.help", "NPC стонут/вскрикивают когда транспорт резко замедляется (аварии, резкое торможение).")
language.Add("npcpassengers.crash_threshold.help", "Замедление необходимое для triggering звуков аварий. Ниже = более чувствительно.")
language.Add("npcpassengers.crash_cooldown.help", "Минимальные секунды между звуками аварий на NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPC иногда говорят во время езды - комментарии, вопросы, наблюдения.")
language.Add("npcpassengers.speech_idle_chance.help", "Вероятность болтовни за проверку. 0 = никогда, 1 = всегда пытается говорить.")
language.Add("npcpassengers.speech_idle_interval.help", "Минимальные секунды между попытками болтовни.")
language.Add("npcpassengers.speech_board.help", "NPC говорят когда входят и выходят из транспорта.")
language.Add("npcpassengers.ambient_sounds.help", "Редкие кашли, вздохи, гудения - фоновые звуки жизни.")
language.Add("npcpassengers.ambient_interval.help", "Средние секунды между фоновыми звуками.")
language.Add("npcpassengers.animation.help", "Точная настройка анимаций NPC и движения головы.")
language.Add("npcpassengers.head_look.help", "NPC естественно смотрят вокруг, на игрока, в окна и т.д.")
language.Add("npcpassengers.head_smooth.help", "Насколько плавно движется голова. Ниже = резче, выше = более плавно.")
language.Add("npcpassengers.blink.help", "NPC моргают реалистично пока сидят.")
language.Add("npcpassengers.breathing.help", "Тонкая анимация дыхания на головах NPC.")
language.Add("npcpassengers.walk_timeout.help", "Секунды перед тем как NPC сдастся идти к транспорту.")
language.Add("npcpassengers.realism.help", "Реакции на основе физики и системы осознанности для максимального погружения.")
language.Add("npcpassengers.talking_gestures.help", "NPC случайно играют жесты руками и анимации тела во время езды.")
language.Add("npcpassengers.gesture_chance.help", "Процент шанс сыграть жест каждый интервал.")
language.Add("npcpassengers.gesture_interval.help", "Секунды между проверками возможности жеста.")
language.Add("npcpassengers.crash_flinch.help", "NPC вздрагивают и подаются вперед когда транспорт разбивается или резко тормозит.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Изменение скорости необходимое для triggering вздрагивания (ниже = более чувствительно).")
language.Add("npcpassengers.body_sway.help", "NPC наклоняются в повороты, упираются при ускорении/торможении.")
language.Add("npcpassengers.body_sway_amount.help", "Насколько NPC качаются с движением транспорта.")
language.Add("npcpassengers.threat_awareness.help", "NPC автоматически смотрят на ближайших врагов.")
language.Add("npcpassengers.threat_range.help", "Как далеко NPC могут обнаруживать угрозы для отслеживания головой.")
language.Add("npcpassengers.combat_alert.help", "NPC становятся напряженными и реактивными когда враги рядом.")
language.Add("npcpassengers.passenger_combat.help", "По умолчанию отключено. Включите это чтобы позволить вооруженным пассажирам стрелять изнутри транспорта.")
language.Add("npcpassengers.passenger_combat_range.help", "Как далеко вооруженные пассажиры могут приобретать цели.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Более высокие значения уменьшают разброс выстрелов для вооруженных пассажиров.")
language.Add("npcpassengers.passenger_combat_damage.help", "Масштабирует урон наносимый выстрелами пассажиров.")
language.Add("npcpassengers.passenger_interaction.help", "Несколько пассажиров смотрят друг на друга и иногда болтают друг с другом.")
language.Add("npcpassengers.fear_reactions.help", "NPC пугаются опасной езды - широкие глаза, панические звуки.")
language.Add("npcpassengers.fear_speed_threshold.help", "Скорость (единицы/сек) при которой NPC начинают нервничать.")
language.Add("npcpassengers.drowsiness.help", "NPC становятся сонными на долгих спокойных поездках - медленные моргания, кивание головой.")
language.Add("npcpassengers.drowsy_time.help", "Секунды спокойной езды перед появлением сонливости.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Настройки для танков, БТР и LVS транспорта.")
language.Add("npcpassengers.hide_in_tanks.help", "Сделать пассажиров NPC невидимыми когда они внутри танков и БТР.")
language.Add("npcpassengers.eject_stuck_check.help", "Автоматически выталкивать NPC из транспорта когда они застревают при выходе. Предотвращает клиппинг NPC в транспорт при выходе.")
language.Add("npcpassengers.detach_no_collide.help", "После выхода NPC временно проходят сквозь транспорт чтобы они могли уйти без клиппинга или застревания.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Как долго NPC игнорируют коллизию транспорта после выхода.")
language.Add("npcpassengers.die_with_vehicle.help", "Пассажиры NPC умирают когда их транспорт уничтожается взрывом или огнем (более погружающе чем если бы они вышли из обломков невредимыми).")
language.Add("npcpassengers.tank_driver.help", "Разрешить NPC на водительском месте автоматически ехать к врагам.")
language.Add("npcpassengers.tank_driver_range.help", "Максимальная дальность для водителя чтобы обнаруживать врагов.")
language.Add("npcpassengers.tank_driver_distance.help", "Дистанция для поддержания от врагов.")
language.Add("npcpassengers.tank_driver_throttle.help", "Количество газа (0.1 = медленно, 1 = полная скорость).")
language.Add("npcpassengers.tank_driver_reverse.help", "Дистанция при которой разворачиваться от врагов.")
language.Add("npcpassengers.tank_turret.help", "Разрешить NPC управлять турелями на LVS транспорте.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Показывает статус пассажиров (эмоции, бдительность) на экране во время езды.")
language.Add("npcpassengers.hud_show_calm.help", "Когда отключено, показывает только пассажиров с неспокойным статусом.")
language.Add("npcpassengers.hud_thresholds.desc", "Когда уровни эмоций превышают эти пороги, пассажиры показывают этот статус в HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Уровень тревоги необходимый для показа статуса 'ТРЕВОГА' (угроза обнаружена).")
language.Add("npcpassengers.hud_fear_threshold.help", "Уровень страха необходимый для показа статуса 'ИСПУГАН' (опасная езда).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Коэффициент спокойного времени необходимый для показа статуса 'СОННЫЙ' (долгая спокойная поездка).")
language.Add("npcpassengers.hud_actions.desc", "Выберите какое действие предпринимают пассажиры когда испытывают каждое эмоциональное состояние.")
language.Add("npcpassengers.hud_actions_note", "Примечание: Некоторые действия могут быть не видны в зависимости от поддержки модели NPC.")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Как добавить NPC в мой транспорт?")
language.Add("npcpassengers.faq.add_npc.answer", "Используйте контекстное меню (правый клик на NPC) и выберите 'Сделать пассажиром'. Или используйте привязку 'Посадить ближайшего NPC'. NPC должны быть дружественными к вам.")
language.Add("npcpassengers.faq.remove_npc", "Как удалить пассажиров из моего транспорта?")
language.Add("npcpassengers.faq.remove_npc.answer", "Перейдите на вкладку Пассажиры в настройках, выберите пассажира и нажмите Отсоединить. Или используйте привязку 'Высадить всех NPC'.")
language.Add("npcpassengers.faq.position", "NPC парят или клиппают через сиденья!")
language.Add("npcpassengers.faq.position.answer", "Перейдите на вкладку Позиция и настройте смещения Высота/Вперед/Вправо. Каждая модель транспорта разная, поэтому вам может потребоваться точная настройка значений. Используйте панель отладки чтобы тестировать позиции в реальном времени.")
language.Add("npcpassengers.faq.speech", "NPC не разговаривают!")
language.Add("npcpassengers.faq.speech.answer", "Проверьте вкладку Поведение и убедитесь что 'Включить речь NPC' включено. Также убедитесь что Громкость речи выше 0. Некоторые модели NPC могут не иметь доступных голосовых линий.")
language.Add("npcpassengers.faq.autojoin", "Как работает авто-посадка?")
language.Add("npcpassengers.faq.autojoin.answer", "Когда включено на вкладке Авто-посадка, поблизости дружественные NPC будут автоматически садиться в ваш транспорт когда вы в него входите - как механика отрядов в Half-Life 2. Вы можете установить дальность обнаружения и ограничить сколько NPC могут автоматически сесть.")
language.Add("npcpassengers.faq.death", "Что происходит когда пассажиры умирают?")
language.Add("npcpassengers.faq.death.answer", "Мертвые пассажиры будут показывать красный эффект свечения и отображать икон черепа на HUD. Подойдите к вашему транспорту и удерживайте R чтобы удалить их тела. Тела будут выброшены с физикой.")
language.Add("npcpassengers.faq.status", "Что означают статусы пассажиров?")
language.Add("npcpassengers.faq.status.answer", "СПОКОЕН: Расслаблен, угроз нет. ТРЕВОГА: Враг обнаружен. ИСПУГАН: Опасная езда. СОННЫЙ: Долгая спокойная езда. МЕРТВ: Здоровье достигло нуля.")
language.Add("npcpassengers.faq.keybinds", "Мои привязки не работают!")
language.Add("npcpassengers.faq.keybinds.answer", "Перейдите на вкладку Клавиши и убедитесь что вы фактически установили привязки (они не привязаны по умолчанию). Нажмите кнопку рядом с каждым действием и нажмите желаемую клавишу. Правый клик чтобы отвязать.")
language.Add("npcpassengers.faq.errors", "Аддон вообще не работает / Я получаю ошибки!")
language.Add("npcpassengers.faq.errors.answer", "Убедитесь что вы используете последнюю версию Garry's Mod. Проверьте консоль на ошибки (клавиша тильда ~). Попробуйте отключить конфликтующие аддоны.")
language.Add("npcpassengers.faq.combat", "Могут ли пассажи стрелять из транспорта?")
language.Add("npcpassengers.faq.combat.answer", "В настоящее время нет. NPC будут отслеживать врагов и реагировать на угрозы, но не будут стрелять из оружия пока сидят. Эта функция может быть добавлена в будущих обновлениях.")
language.Add("npcpassengers.faq.stop_autojoin", "Как остановить NPC от авто-посадки?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Отключите чекбокс 'Включить авто-посадку' на вкладке Авто-посадка, или используйте привязку 'Переключить авто-посадку'.")
language.Add("npcpassengers.faq.settings", "Где сохраняются настройки?")
language.Add("npcpassengers.faq.settings.answer", "Все настройки сохраняются как ConVars в вашей конфигурации GMod. Они сохраняются между сессиями и специфичны для вашего клиента.")
language.Add("npcpassengers.faq.vehicles", "Это работает со всеми транспортами?")
language.Add("npcpassengers.faq.vehicles.answer", "Это работает с большинством транспортов которые имеют физику. Танки, БТР, машины, лодки и т.д. Некоторые модовые транспорты могут потребовать корректировки позиции.")
language.Add("npcpassengers.faq.multiple", "Можно ли иметь несколько NPC в одном транспорте?")
language.Add("npcpassengers.faq.multiple.answer", "Да! Установите 'Лимит пассажиров' в общих настройках. Аддон автоматически распределит NPC вокруг транспорта. Для конкретных позиций сидений настройте смещения на вкладке Позиция.")
language.Add("npcpassengers.faq.crashes", "NPC ведут себя странно после аварий!")
language.Add("npcpassengers.faq.crashes.answer", "Это нормально - они реагируют со страхом на опасную езду. Снизьте Порог страха в настройках HUD если хотите чтобы они были менее реактивными.")
language.Add("npcpassengers.faq.reset_setting", "Как сбросить только одну настройку?")
language.Add("npcpassengers.faq.reset_setting.answer", "Используйте консольную команду для этой конкретной настройки. Все команды начинаются с 'nai_npc_'. Введите 'find nai_npc' в консоли чтобы увидеть все доступные команды.")
language.Add("npcpassengers.faq.multiplayer", "Это работает в мультиплеере?")
language.Add("npcpassengers.faq.multiplayer.answer", "Да! Аддон работает как в одиночном так и в мультиплеере серверах. Каждый игрок управляет своими пассажирами.")
language.Add("npcpassengers.faq.lvs", "Это работает с транспортами LVS?")
language.Add("npcpassengers.faq.lvs.answer", "Да! Аддон имеет полную поддержку транспортов LVS (Lua Vehicle System). NPC могут ехать как пассажиры и даже могут водить транспорты LVS если режим NPC водителя включен.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Эти настройки управляют поведением пользовательского интерфейса аддона")
language.Add("npcpassengers.panel.performance_note1", "Изменения размера панели требуют закрытия и повторного открытия меню")
language.Add("npcpassengers.panel.performance_note2", "Отключение звуков или анимаций может улучшить производительность на слабых системах")
language.Add("npcpassengers.panel.performance_title", "Информация о настройках интерфейса")
language.Add("npcpassengers.help.console_title", "Консольные команды для отладки:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Включить режим отладки для просмотра подробной информации")
language.Add("npcpassengers.about.title", "О")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Язык изменен на Английский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "Язык изменен на Китайский. Панель обновится автоматически.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Привет!")
language.Add("npcpassengers.welcome.msg1", "Прежде чем жаловаться на пассажира сидящего поверх транспорта,\nпожалуйста откройте настройки. Вы можете это сделать, я верю в вас.")
language.Add("npcpassengers.welcome.msg2", "Этот аддон все еще далек от СОВЕРШЕНСТВА, пожалуйста не стесняйтесь\nсообщать об ошибках и предлагать новые функции. Я читаю все ваши комментарии!")
language.Add("npcpassengers.welcome.changelog", "Список изменений")
language.Add("npcpassengers.welcome.got_it", "Понял!")
language.Add("npcpassengers.welcome.console_cmd", "Или используйте консольную команду: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Черный список классов NPC")
language.Add("npcpassengers.ui.blacklist_help", "Разделенный запятыми список имен классов NPC которые не могут использовать турели. Используйте консольную команду 'getnpcblacklist' чтобы увидеть текущий черный список.")
language.Add("npcpassengers.ui.hud_position", "Позиция HUD")
language.Add("npcpassengers.ui.not_bound", "Не привязано")
language.Add("npcpassengers.ui.keybind_tip", "Совет: Нажмите правой кнопкой на привязку чтобы отвязать. Нажмите ESC во время привязки чтобы отменить.")
language.Add("npcpassengers.ui.custom_font", "Пользовательский шрифт")
language.Add("npcpassengers.ui.custom_font_hint", "Или введите имя пользовательского шрифта")
language.Add("npcpassengers.ui.dont_show_again", "Больше не показывать")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Операции с пассажирами")
language.Add("npcpassengers.hud.filter_prefix", "Фильтр: ")
language.Add("npcpassengers.hud.sort_prefix", "Сортировка: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Автообновление: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Транспорт: ")
language.Add("npcpassengers.hud.speed_prefix", "Скорость: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "ВКЛ")
language.Add("npcpassengers.hud.off", "ВЫКЛ")
language.Add("npcpassengers.hud.passengers", "Пассажиры")
language.Add("npcpassengers.hud.npc_driver", "NPC водитель")
language.Add("npcpassengers.hud.total_prefix", "Всего: ")
language.Add("npcpassengers.hud.showing_prefix", "Показано: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Текущий транспорт: ")
language.Add("npcpassengers.hud.hidden_prefix", "Скрыто: ")
language.Add("npcpassengers.hud.dead_prefix", "Мертвых: ")
language.Add("npcpassengers.hud.scared_prefix", "Испуганных: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Сонных: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Спокоен")
language.Add("npcpassengers.status.alert", "Тревога")
language.Add("npcpassengers.status.scared", "Испуган")
language.Add("npcpassengers.status.drowsy", "Сонный")
language.Add("npcpassengers.status.dead", "Мертв")
language.Add("npcpassengers.status.unknown", "Неизвестно")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Гражданский")
language.Add("npcpassengers.npc.alyx", "Аликс")
language.Add("npcpassengers.npc.barney", "Барни")
language.Add("npcpassengers.npc.monk", "Отец Григорий")
language.Add("npcpassengers.npc.vortigaunt", "Вортигонт")
language.Add("npcpassengers.npc.eli", "Эли")
language.Add("npcpassengers.npc.kleiner", "Доктор Кляйнер")
language.Add("npcpassengers.npc.mossman", "Доктор Моссман")
language.Add("npcpassengers.npc.breen", "Доктор Брин")
language.Add("npcpassengers.npc.dog", "Пёс")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Транспорт")
language.Add("npcpassengers.sort.name", "Имя")
language.Add("npcpassengers.sort.seat", "Место")
language.Add("npcpassengers.sort.health", "Здоровье")
language.Add("npcpassengers.sort.status", "Статус")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Сначала транспорт")
language.Add("npcpassengers.sort.name_az", "Имя А-Я")
language.Add("npcpassengers.sort.seat_number", "Номер места")
language.Add("npcpassengers.sort.highest_health", "Наибольшее здоровье")
language.Add("npcpassengers.sort.status_priority", "Приоритет статуса")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Транспорт: Неизвестно")
language.Add("npcpassengers.ui.seat_prefix", "Место ")
language.Add("npcpassengers.ui.same_vehicle", "Тот же транспорт")
language.Add("npcpassengers.ui.other_vehicle", "Другой транспорт")
language.Add("npcpassengers.ui.hidden", "Скрыт")
language.Add("npcpassengers.ui.visible", "Видимый")
language.Add("npcpassengers.ui.health_format", "Здоровье %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Обновить список пассажиров")
language.Add("npcpassengers.ui.copy_list", "Копировать видимый список пассажиров")
language.Add("npcpassengers.ui.make_exit", "Заставить пассажиров текущего транспорта выйти")
language.Add("npcpassengers.ui.reset_pos", "Сбросить позицию и углы")
language.Add("npcpassengers.ui.crash_reactions", "Реакции на аварии")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Звуки посадки/выхода")
language.Add("npcpassengers.section.ambient_sounds", "Фоновые звуки")
language.Add("npcpassengers.section.gesture_animations", "Анимации жестов")
language.Add("npcpassengers.section.threat_awareness", "Осознание угроз")
language.Add("npcpassengers.section.emotional_states", "Эмоциональные состояния")
language.Add("npcpassengers.section.turret_control", "Управление турелью (Экспериментально)")
language.Add("npcpassengers.section.turret_blacklist", "Черный список турелей NPC")
language.Add("npcpassengers.section.idle_chatter", "Болтовня в покое")
language.Add("npcpassengers.section.body_physics", "Физика тела")
language.Add("npcpassengers.section.npc_auto_driver", "NPC автопилот")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Слева снизу")
language.Add("npcpassengers.hud.bottom_right", "Справа снизу")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Включить HUD пассажиров")
language.Add("npcpassengers.ui.cover_face", "Закрыть лицо")
language.Add("npcpassengers.ui.apply_keybinds", "Применить рекомендуемые привязки")
language.Add("npcpassengers.ui.clear_keybinds", "Очистить все привязки")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Тест жеста вздрагивания")
language.Add("npcpassengers.ui.test_random", "Тест случайного жеста")
language.Add("npcpassengers.ui.reset_states", "Сбросить все состояния")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Включить все опции контекстного меню")
language.Add("npcpassengers.ui.hide_context", "Скрыть все опции контекстного меню")
language.Add("npcpassengers.ui.set_compact", "Установить компактный размер панели")
language.Add("npcpassengers.ui.set_default", "Установить размер панели по умолчанию")
language.Add("npcpassengers.ui.set_large", "Установить большой размер панели")
language.Add("npcpassengers.ui.center_panel", "Центрировать панель сейчас")
language.Add("npcpassengers.ui.reset_ui", "Сбросить все настройки UI по умолчанию")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Гражданский (Ж)")
language.Add("npcpassengers.role.citizen_male", "Гражданский (М)")
language.Add("npcpassengers.role.medic", "Медик")
language.Add("npcpassengers.role.rebel", "Бунтарь")
language.Add("npcpassengers.role.passenger", "Пассажир")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Показывать только когда в транспорте")
language.Add("npcpassengers.hud.show_calm", "Показывать спокойных пассажиров")
language.Add("npcpassengers.hud.show_hints", "Показывать контекстные подсказки")
language.Add("npcpassengers.hud.show_target_debug", "Показывать отладку цели")
language.Add("npcpassengers.hud.play_cues", "Воспроизводить звуковые сигналы успеха/неудачи")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Настройте горячие клавиши для действий пассажиров NPC. Нажмите кнопку и нажмите клавишу для привязки.")
language.Add("npcpassengers.keybinds_hud.desc", "Быстрые элементы управления HUD для показа, перемещения и отладки оверлея пассажиров.")
language.Add("npcpassengers.keybinds_debug_note", "Клавиши отладки работают только когда Режим Отладки включен.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Расширенные инструменты отладки для тестирования поведения NPC. Сначала включите Режим Отладки в настройках.")
language.Add("npcpassengers.debug_mode.help", "Показывает кнопки теста отладки и включает команды отладки.")
language.Add("npcpassengers.debug_status.help", "Вручную установите статус пассажира для тестирования. Нажмите 'Обновить список' чтобы увидеть текущих пассажиров.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Настройте звуковые эффекты для кнопок, чекбоксов и других элементов UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Главный переключатель для всех звуковых эффектов UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Множитель громкости звуков UI (1.0 = нормально, 2.0 = двойной)")
language.Add("npcpassengers.ui_hover_enabled.help", "Играть звук при наведении на кнопки")
language.Add("npcpassengers.ui_click_enabled.help", "Играть звук при нажатии на кнопки и чекбоксы")
language.Add("npcpassengers.context_menu.desc", "Выберите какие опции появляются при правом клике на NPC")
language.Add("npcpassengers.context_make_passenger.help", "Добавить NPC как пассажира в ваш текущий транспорт")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Добавить NPC в конкретный транспорт (нажмите NPC, затем транспорт)")
language.Add("npcpassengers.context_detach.help", "Удалить NPC из транспорта")
language.Add("npcpassengers.ui_show_welcome.help", "Показать приветственную панель когда аддон обновляется до новой версии")
language.Add("npcpassengers.ui_default_font.help", "Переключить UI на шрифты Garry's Mod по умолчанию если вы предпочитаете более чистое резервное отображение.")
language.Add("npcpassengers.ui_custom_font.help", "Выберите пользовательский шрифт. Добавьте файлы .ttf в resource/fonts/ и используйте фактическое имя шрифта (например, 'Roboto', 'Arial'). Изменения применяются немедленно.")
language.Add("npcpassengers.ui_panel_width.help", "Ширина панели настроек")
language.Add("npcpassengers.ui_panel_height.help", "Высота панели настроек")
language.Add("npcpassengers.ui_animations.help", "Плавные переходы и эффекты наведения (может повлиять на производительность)")
language.Add("npcpassengers.ui_tooltips.help", "Показывать полезные подсказки при наведении на настройки")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Показывать полосу прокрутки только пока вы прокручиваете или наводите на нее.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Примечание: Панель становится 70% прозрачной при перетаскивании любого слайдера чтобы видеть содержимое на фоне.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Более низкие значения = более плавно но медленнее прокручивание (0.01-1)")

print("[Better NPC Passengers] Russian localization loaded!")
