-- Better NPC Passengers - Spanish Localization
-- Archivo de localización en español

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Mejores Pasajeros NPC")
language.Add("npcpassengers.settings", "Configuración")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "General")
language.Add("npcpassengers.nav.autojoin", "Unión Automática")
language.Add("npcpassengers.nav.passengers", "Pasajeros")
language.Add("npcpassengers.nav.position", "Posición")
language.Add("npcpassengers.nav.behaviour", "Comportamiento")
language.Add("npcpassengers.nav.keybinds", "Atajos de Teclado")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Conductor")
language.Add("npcpassengers.nav.help", "Ayuda")

-- General Settings
language.Add("npcassengers.general.header", "Configuración General")
language.Add("npcpassengers.allow_multiple", "Permitir Múltiples Pasajeros")
language.Add("npcpassengers.allow_multiple.help", "Permite que varios NPC viajen en el mismo vehículo.")
language.Add("npcpassengers.exit_behavior", "Comportamiento de Salida")
language.Add("npcpassengers.exit_behavior.help", "¿Cuándo deben salir los pasajeros NPC del vehículo?")
language.Add("npcassengers.exit_mode.leave_player", "Salir cuando el jugador sale")
language.Add("npcpassengers.exit_mode.leave_attack", "Salir cuando el vehículo es atacado")
language.Add("npcpassengers.exit_mode.never", "Nunca salir automáticamente")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Tiempo")
language.Add("npcpassengers.max_attach_dist", "Distancia Máxima de Adjunto")
language.Add("npcpassengers.max_attach_dist.help", "Distancia máxima (unidades) para adjuntar NPC al vehículo.")
language.Add("npcpassengers.detach_delay", "Retraso de Desconexión")
language.Add("npcpassengers.detach_delay.help", "Segundos a esperar antes de desconectar después de que el jugador sale.")
language.Add("npcpassengers.ai_delay", "Retraso de Restauración de IA")
language.Add("npcpassengers.ai_delay.help", "Segundos a esperar antes de restaurar la IA del NPC después de desconectar.")
language.Add("npcpassengers.cooldown", "Tiempo de Enfriamiento")
language.Add("npcpassengers.cooldown.help", "Enfriamiento entre adjuntar NPC al mismo vehículo.")
language.Add("npcpassengers.passenger_limit", "Límite de Pasajeros")
language.Add("npcpassengers.passenger_limit.help", "Máximo de NPC permitidos en el vehículo.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Unión Automática (Comportamiento de Escuadrón)")
language.Add("npcpassengers.autojoin.desc", "Los NPC amistosos abordarán automáticamente tu vehículo cuando entres en él, ¡igual que la mecánica de escuadrones en Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Activar Unión Automática")
language.Add("npcpassengers.autojoin.enable.help", "Los NPC amistados cercanos se unirán automáticamente cuando entres en un vehículo.")
language.Add("npcpassengers.autojoin.range", "Rango de Unión Automática")
language.Add("npcpassengers.autojoin.range.help", "Distancia máxima para encontrar NPC para unión automática.")
language.Add("npcpassengers.autojoin.max", "Máximo de NPC de Unión Automática")
language.Add("npcpassengers.autojoin.max.help", "Número máximo de NPC que pueden unirse automáticamente a la vez.")
language.Add("npcpassengers.autojoin.squad_only", "Solo Miembros del Escuadrón")
language.Add("npcpassengers.autojoin.squad_only.help", "Solo los NPC con nombre de escuadrón se unirán automáticamente (para escuadrones estilo HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Los NPC amistosos abordarán automáticamente tu vehículo cuando entres en él, ¡igual que la mecánica de escuadrones en Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Control de Pasajeros")
language.Add("npcpassengers.panel.passengers.desc", "Gestiona pasajeros activos, filtra por nombre/clase/estado, copia información de depuración, reasigna asientos y separa pasajeros sin salir del panel de configuración.")
language.Add("npcpassengers.panel.position.desc", "Ajusta finamente la posición de los NPC en los vehículos. Usa esto para arreglar problemas de flotación o intersección.")
language.Add("npcpassengers.panel.angle.desc", "Ajusta la rotación de NPC en los vehículos.")
language.Add("npcpassengers.panel.speech.desc", "Configura cómo vocalizan los NPC mientras viajan en vehículos. ¡Voces de ciudadanos estilo HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Desplazamientos de Posición")
language.Add("npcpassengers.position.desc", "Ajusta finamente la posición de los NPC en los vehículos. Usa esto para arreglar problemas de flotación o intersección.")
language.Add("npcpassengers.height_offset", "Desplazamiento de Altura")
language.Add("npcpassengers.forward_offset", "Desplazamiento Frontal")
language.Add("npcpassengers.right_offset", "Desplazamiento Derecho")
language.Add("npcpassengers.angle.header", "Desplazamientos de Ángulo")
language.Add("npcpassengers.angle.desc", "Ajusta la rotación de NPC en los vehículos.")
language.Add("npcpassengers.yaw_offset", "Guiñada (Rotación)")
language.Add("npcpassengers.pitch_offset", "Cabeceo (Inclinación Frontal)")
language.Add("npcpassengers.roll_offset", "Balanceo (Inclinación Lateral)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Voz de NPC (Avanzado)")
language.Add("npcpassengers.behaviour.desc", "Configura cómo vocalizan los NPC mientras viajan en vehículos. ¡Voces de ciudadanos estilo HL2!")
language.Add("npcpassengers.speech_enable", "Activar Voz de NPC")
language.Add("npcpassengers.speech_enable.help", "Interruptor maestro para toda la voz de NPC. Desactiva para silenciar pasajeros completamente.")
language.Add("npcpassengers.speech_volume", "Volumen de Voz")
language.Add("npcpassengers.speech_volume.help", "Qué tan fuerte son las voces de NPC (0 = silencio, 100 = volumen completo).")
language.Add("npcpassengers.pitch_variation", "Variación de Tono (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Variación aleatoria de tono para voces más naturales. 0 = monótono, más alto = más variedad.")
language.Add("npcpassengers.crash.header", "Reacciones a Choques")
language.Add("npcpassengers.crash_enable", "Activar Sonidos de Choque")
language.Add("npcpassengers.crash_enable.help", "Los NPC gruñen/gimen cuando el vehículo desacelera bruscamente (choques, frenado brusco).")
language.Add("npcpassengers.crash_threshold", "Sensibilidad a Choques")
language.Add("npcpassengers.crash_threshold.help", "Desaceleración necesaria para activar sonidos de choque. Menor = más sensible.")
language.Add("npcpassengers.crash_cooldown", "Enfriamiento de Sonido de Choque")
language.Add("npcpassengers.crash_cooldown.help", "Segundos mínimos entre sonidos de choque por NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Activar Charla Inactiva")
language.Add("npcpassengers.speech_board", "Activar Sonidos de Embarque/Desembarque")
language.Add("npcpassengers.ambient_sounds", "Activar Sonidos Ambientales")
language.Add("npcpassengers.head_look", "Activar Mirada de Cabeza/Ojos")
language.Add("npcpassengers.blink", "Activar Parpadeo")
language.Add("npcpassengers.breathing", "Activar Respiración")
language.Add("npcpassengers.talking_gestures", "Activar Gestos al Hablar")
language.Add("npcpassengers.crash_flinch", "Activar Encogimiento por Choque")
language.Add("npcpassengers.body_sway", "Activar Balanceo del Cuerpo")
language.Add("npcpassengers.threat_awareness", "Activar Conciencia de Amenazas")
language.Add("npcpassengers.combat_alert", "Alerta de Combate")
language.Add("npcpassengers.passenger_combat", "NPC disparan desde vehículos (Experimental)")
language.Add("npcpassengers.passenger_interaction", "Interacción de Pasajeros")
language.Add("npcpassengers.fear_reactions", "Activar Reacciones de Miedo")
language.Add("npcassengers.drowsiness", "Activar Somnolencia")
language.Add("npcpassengers.hide_in_tanks", "Ocultar NPC en Vehículos Cerrados")
language.Add("npcpassengers.eject_stuck_check", "Expulsión Automática de NPC Atascados")
language.Add("npcpassengers.detach_no_collide", "Sin Colisión con Vehículo Después de Desconectar")
language.Add("npcpassengers.die_with_vehicle", "Matar Pasajeros Cuando Explota el Vehículo")
language.Add("npcpassengers.driver_enabled", "Activar Conducción Automática")
language.Add("npcpassengers.turret_enabled", "Activar Control de Torreta")
language.Add("npcpassengers.turret_lead_targets", "Predecir Objetivos")
language.Add("npcpassengers.turret_friendly_fire", "Permitir Fuego Amigo")
language.Add("npcpassengers.turret_hold_fire", "Mantener Fuego (Desactivar Disparo)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Volumen de Voz")
language.Add("npcpassengers.pitch_variation", "Variación de Tono (+/-)")
language.Add("npcpassengers.crash_threshold", "Sensibilidad a Choques")
language.Add("npcpassengers.crash_cooldown", "Enfriamiento de Sonido de Choque")
language.Add("npcpassengers.speech_idle_chance", "Probabilidad de Charla")
language.Add("npcpassengers.speech_idle_interval", "Intervalo de Charla")
language.Add("npcpassengers.ambient_interval", "Intervalo de Sonido Ambiental")
language.Add("npcpassengers.head_smooth", "Suavidad de Cabeza")
language.Add("npcpassengers.walk_timeout", "Tiempo de Espera de Caminata")
language.Add("npcpassengers.gesture_chance", "Probabilidad de Gesto (%)")
language.Add("npcpassengers.gesture_interval", "Intervalo de Gesto")
language.Add("npcpassengers.crash_threshold_flinch", "Sensibilidad a Choques")
language.Add("npcassengers.body_sway_amount", "Intensidad de Balanceo")
language.Add("npcpassengers.threat_range", "Rango de Detección de Amenazas")
language.Add("npcpassengers.passenger_combat_range", "Rango de Combate de Pasajeros")
language.Add("npcpassengers.passenger_combat_accuracy", "Precisión de Pasajeros")
language.Add("npcpassengers.passenger_combat_damage", "Multiplicador de Daño de Pasajeros")
language.Add("npcpassengers.fear_speed_threshold", "Umbral de Velocidad de Miedo")
language.Add("npcpassengers.drowsy_time", "Tiempo de Somnolencia")
language.Add("npcpassengers.detach_no_collide_duration", "Duración Sin Colisión (segundos)")
language.Add("npcpassengers.tank_driver_range", "Rango de Detección")
language.Add("npcpassengers.tank_driver_engage_distance", "Distancia de Enfrentamiento")
language.Add("npcpassengers.tank_driver_speed", "Velocidad de Conducción")
language.Add("npcpassengers.tank_driver_reverse_distance", "Distancia de Reversa")
language.Add("npcpassengers.turret_range", "Rango de Objetivo")
language.Add("npcpassengers.turret_accuracy", "Precisión")
language.Add("npcpassengers.turret_reaction_time", "Tiempo de Reacción")
language.Add("npcpassengers.turret_fire_delay", "Retraso de Disparo")
language.Add("npcpassengers.turret_aim_speed", "Velocidad de Apuntado")
language.Add("npcpassengers.hud_scale", "Escala de HUD")
language.Add("npcpassengers.hud_opacity", "Opacidad de HUD")
language.Add("npcpassengers.hud_alert_threshold", "Umbral de Alerta")
language.Add("npcpassengers.hud_fear_threshold", "Umbral de Miedo")
language.Add("npcpassengers.hud_drowsy_threshold", "Umbral de Somnolencia")
language.Add("npcpassengers.ui_sounds_volume", "Volumen de Sonidos UI")
language.Add("npcpassengers.ui_panel_width", "Ancho del Panel")

-- Section headers
language.Add("npcpassengers.section.animation", "Animación y Comportamiento")
language.Add("npcpassengers.section.realism", "Realismo Avanzado")
language.Add("npcpassengers.section.hud_position", "Posición y Estilo de HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Umbrales de Emoción")
language.Add("npcpassengers.section.emotion_actions", "Acciones de Emoción")
language.Add("npcpassengers.section.vehicle_control", "Control de Vehículo")
language.Add("npcpassengers.section.hud_controls", "Controles de HUD")
language.Add("npcpassengers.section.debug_controls", "Controles de Depuración")
language.Add("npcassengers.section.passenger_status", "Control de Estado de Pasajeros")
language.Add("npcpassengers.section.quick_test", "Botones de Prueba Rápida")
language.Add("npcpassengers.section.driver_system", "Sistema de Conductor NPC")
language.Add("npcpassengers.section.ui_sounds", "Configuración de Sonidos UI")
language.Add("npcpassengers.section.appearance", "Apariencia")
language.Add("npcpassengers.section.context_menu", "Opciones del Menú Contextual")
language.Add("npcpassengers.section.panel_preferences", "Preferencias del Panel de Configuración")
language.Add("npcpassengers.section.performance", "Rendimiento y Técnico")
language.Add("npcpassengers.section.simulation", "Sistema de Simulación")
language.Add("npcpassengers.section.modules", "Sistema de Módulos")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Asignar Asiento")
language.Add("npcpassengers.btn.detach", "Separar")
language.Add("npcpassengers.btn.copy_summary", "Copiar Resumen")
language.Add("npcpassengers.btn.copy_debug", "Copiar Depuración")
language.Add("npcpassengers.btn.enable_all_speech", "Activar Toda la Voz")
language.Add("npcpassengers.btn.disable_all_speech", "Desactivar Toda la Voz")
language.Add("npcpassengers.btn.show_current_vehicle", "Mostrar Solo Vehículo Actual")
language.Add("npcpassengers.btn.auto_refresh", "Actualización Automática de Lista Visible")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "No se detectó vehículo actual. Siéntate en un vehículo o desactiva el filtro de vehículo actual.")
language.Add("npcpassengers.status.no_match_filter", "Ningún pasajero coincide con tu filtro. Intenta un nombre, clase, número de asiento, estado o clase de vehículo.")
language.Add("npcpassengers.status.no_passengers_vehicle", "No se encontraron pasajeros en tu vehículo actual.")
language.Add("npcpassengers.status.no_passengers", "No se encontraron pasajeros. Los NPC deben estar viajando en un vehículo antes de poder ser gestionados aquí.")
language.Add("npcpassengers.status.all_passengers", "Todos los pasajeros")
language.Add("npcpassengers.status.current_vehicle_only", "Solo vehículo actual")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F para enfocar búsqueda")
language.Add("npcengers.status.no_matches", "Sin configuraciones coincidentes")
language.Add("npcpassengers.status.showing_matches", "Mostrando %d principales de %d coincidencias")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Abrir Configuración")
language.Add("npcpassengers.menu.reset_all", "Restablecer Toda la Configuración")

-- Button states
language.Add("npcpassengers.state.on", "ENCENDIDO")
language.Add("npcpassengers.state.off", "APAGADO")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Unión Automática")
language.Add("npcpassengers.chat.hud_status", "HUD de Pasajeros")
language.Add("npcpassengers.chat.hud_position", "Posición de HUD")
language.Add("npcpassengers.chat.target_debug", "Depuración de Objetivo")
language.Add("npcpassengers.chat.turret_gunners", "Artilleros de Torreta")
language.Add("npcpassengers.chat.turret_holding", "MANTENIENDO FUEGO")
language.Add("npcpassengers.chat.turret_fire", "ABRIENDO FUEGO")
language.Add("npcpassengers.chat.unknown", "Desconocido")
language.Add("npcpassengers.chat.nothing_copy", "Nada que copiar.")
language.Add("npcpassengers.chat.clipboard_unavailable", "El acceso al portapapeles no está disponible en esta versión.")
language.Add("npcpassengers.chat.copied_clipboard", "Copiado al portapapeles.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Siéntate en el mismo vehículo para reasignar este pasajero.")
language.Add("npcpassengers.chat.no_visible_passengers", "No hay pasajeros visibles para copiar.")
language.Add("npcpassengers.chat.need_vehicle", "Necesitas estar en un vehículo para usar esto.")
language.Add("npcpassengers.chat.keybinds_applied", "Atajos recomendados aplicados.")
language.Add("npcpassengers.chat.keybinds_cleared", "Todos los atajos borrados.")
language.Add("npcpassengers.chat.context_enabled", "Todas las opciones del menú contextual activadas.")
language.Add("npcpassengers.chat.context_hidden", "Todas las opciones del menú contextual ocultas.")
language.Add("npcpassengers.chat.panel_compact", "Tamaño del panel establecido en compacto.")
language.Add("npcpassengers.chat.panel_default", "Tamaño del panel establecido en predeterminado.")
language.Add("npcpassengers.chat.panel_large", "Tamaño del panel establecido en grande.")
language.Add("npcpassengers.chat.panel_centered", "Panel centrado.")
language.Add("npcpassengers.chat.settings_reset", "¡Toda la configuración de UI restablecida a valores predeterminados!")
language.Add("npcpassengers.chat.npc_selected", "¡NPC seleccionado! Ahora haz clic derecho en un vehículo y selecciona 'Añadir NPC Seleccionado'")
language.Add("npcpassengers.chat.adding_npc", "Añadiendo NPC al vehículo...")
language.Add("npcpassengers.chat.selection_cancelled", "Selección de NPC cancelada")
language.Add("npcassengers.chat.summary_copied", "Resumen de pasajeros copiado.")
language.Add("npcpassengers.chat.debug_copied", "Información de depuración de pasajero copiada.")
language.Add("npcpassengers.chat.no_passengers_found", "No se encontraron pasajeros. Los NPC deben estar en un vehículo.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Intensidad de estado %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filtrar pasajeros...")
language.Add("npcpassengers.ui.press_key", "Presiona una tecla...")
language.Add("npcpassengers.ui.work_in_progress", "En Progreso")
language.Add("npcpassengers.ui.under_development", "Esta característica está actualmente en desarrollo")
language.Add("npcpassengers.ui.check_back_later", "¡Vuelve a revisar en una actualización futura!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtra pasajeros activos por nombre, clase, asiento, estado o vehículo.")
language.Add("npcpassengers.ui.search_desc_sort", "Ordena la lista visible de pasajeros por vehículo, nombre, asiento, salud o estado.")
language.Add("npcpassengers.ui.search_label_filter", "Filtro de Pasajeros")
language.Add("npcpassengers.ui.search_label_sort", "Orden de Pasajeros")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "¿Cómo añado NPC a mi vehículo?")
language.Add("npcpassengers.faq.add_npc.answer", "Usa el menú contextual (clic derecho en un NPC) y selecciona 'Hacer Pasajero'. O usa el atajo 'Adjuntar NPC Más Cercano'. Los NPC deben ser amistosos contigo.")
language.Add("npcpassengers.faq.remove_npc", "¿Cómo elimino pasajeros de mi vehículo?")
language.Add("npcpassengers.faq.remove_npc.answer", "Ve a la pestaña Pasajeros en configuración, selecciona el pasajero y haz clic en Separar. O usa el atajo 'Separar Todos los Pasajeros'.")
language.Add("npcpassengers.faq.position", "¡Los NPC están flotando/atravesando asientos!")
language.Add("npcpassengers.faq.position.answer", "Ve a la pestaña Posición y ajusta los desplazamientos de Altura/Frontal/Derecho. Cada modelo de vehículo es diferente, por lo que es posible que necesites ajustar estos valores. Usa el panel de depuración para probar posiciones en tiempo real.")
language.Add("npcpassengers.faq.speech", "¡Los NPC no hablan!")
language.Add("npcpassengers.faq.speech.answer", "Verifica la pestaña Comportamiento y asegúrate de que 'Activar Voz de NPC' esté activado. También verifica que el Volumen de Voz esté por encima de 0. Algunos modelos de NPC pueden no tener líneas de voz disponibles.")
language.Add("npcpassengers.faq.autojoin", "¿Cómo funciona la Unión Automática?")
language.Add("npcpassengers.faq.autojoin.answer", "Cuando se activa en la pestaña Unión Automática, los NPC amistados cercanos abordarán automáticamente tu vehículo cuando entres en él, ¡igual que la mecánica de escuadrones en Half-Life 2! Puedes establecer el rango de detección y limitar cuántos NPC pueden unirse automáticamente.")
language.Add("npcassengers.faq.death", "¿Qué sucede cuando mueren los pasajeros?")
language.Add("npcpassengers.faq.death.answer", "Los pasajeros muertos mostrarán un efecto de brillo rojo y mostrarán un icono de calavera en el HUD. Acerca tu vehículo y mantén presionada R para eliminar sus cuerpos. Los cuerpos serán expulsados con física.")
language.Add("npcpassengers.faq.status", "¿Qué significan los estados de los pasajeros?")
language.Add("npcpassengers.faq.status.answer", "TRANQUILO: Relajado, sin amenazas. ALERTA: Enemigo detectado. ASUSTADO: Conducción peligrosa. SOMNOLIENTO: Viaje largo y tranquilo. MUERTO: Salud alcanzó cero.")
language.Add("npcpassengers.faq.keybinds", "¡Mis atajos no funcionan!")
language.Add("npcpassengers.faq.keybinds.answer", "Ve a la pestaña Atajos y asegúrate de que realmente hayas establecido los atajos (están sin asignar por defecto). Haz clic en el botón junto a cada acción y presiona la tecla deseada. Clic derecho para desvincular.")
language.Add("npcpassengers.faq.errors", "¡El complemento no funciona en absoluto / ¡Estoy recibiendo errores!")
language.Add("npcpassengers.faq.errors.answer", "Asegúrate de estar ejecutando la última versión de Garry's Mod. Revisa la consola en busca de errores (tecla tilde ~). Intenta desactivar complementos conflictivos.")
language.Add("npcpassengers.faq.combat", "¿Pueden los pasajeros disparar desde vehículos?")
language.Add("npcpassengers.faq.combat.answer", "Actualmente no. Los NPC rastrearán enemigos y reaccionarán a amenazas, pero no dispararán armas mientras estén sentados. Esta característica puede agregarse en actualizaciones futuras.")
language.Add("npcpassengers.faq.stop_autojoin", "¿Cómo detengo que los NPC se unan automáticamente?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Desactiva la casilla 'Activar Unión Automática' en la pestaña Unión Automática, o usa el atajo 'Alternar Unión Automática'.")
language.Add("npcpassengers.faq.settings", "¿Dónde se guardan la configuración?")
language.Add("npcpassengers.faq.settings.answer", "Toda la configuración se guarda como ConVars en tu configuración de GMod. Persisten entre sesiones y son específicas de tu cliente.")
language.Add("npcpassengers.faq.vehicles", "¿Esto funciona con todos los vehículos?")
language.Add("npcassengers.faq.vehicles.answer", "Funciona con la mayoría de vehículos que tienen física. Tanques, APC, autos, botes, etc. Algunos vehículos modificados pueden requerir ajustes de posición.")
language.Add("npcpassengers.faq.multiple", "¿Puedo tener múltiples NPC en un vehículo?")
language.Add("npcpassengers.faq.multiple.answer", "¡Sí! Establece el 'Límite de Pasajeros' en configuración general. El complemento distribuirá automáticamente los NPC alrededor del vehículo. Para posiciones de asiento específicas, ajusta los desplazamientos en la pestaña Posición.")
language.Add("npcpassengers.faq.crashes", "¡Los NPC actúan de manera extraña después de los choques!")
language.Add("npcpassengers.faq.crashes.answer", "Esto es normal - reaccionan con miedo a la conducción peligrosa. Baja el Umbral de Miedo en configuración de HUD si quieres que sean menos reactivos.")
language.Add("npcpassengers.faq.reset_setting", "¿Cómo restablezco solo una configuración?")
language.Add("npcpassengers.faq.reset_setting.answer", "Usa el comando de consola para esa configuración específica. Todos los comandos comienzan con 'nai_npc_'. Escribe 'find nai_npc' en consola para ver todos los comandos disponibles.")
language.Add("npcpassengers.faq.multiplayer", "¿Esto funciona en multijugador?")
language.Add("npcpassengers.faq.multiplayer.answer", "¡Sí! El complemento funciona tanto en servidores de un jugador como multijugador. Cada jugador controla sus propios pasajeros.")
language.Add("npcpassengers.faq.lvs", "¿Esto funciona con vehículos LVS?")
language.Add("npcpassengers.faq.lvs.answer", "¡Sí! El complemento tiene soporte completo para vehículos LVS (Lua Vehicle System). Los NPC pueden viajar como pasajeros e incluso pueden conducir vehículos LVS si el modo de Conductor NPC está activado.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Estas configuraciones controlan el comportamiento de la interfaz de usuario del complemento")
language.Add("npcpassengers.panel.performance_note1", "Los cambios de tamaño del panel requieren cerrar y volver a abrir el menú")
language.Add("npcpassengers.panel.performance_note2", "Desactivar sonidos o animaciones puede mejorar el rendimiento en sistemas de gama baja")
language.Add("npcpassengers.panel.performance_title", "Información de Configuración de Interfaz")
language.Add("npcpassengers.help.console_title", "Comandos de Consola para Depuración:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Activa modo depuración para ver información detallada")
language.Add("npcpassengers.about.title", "Acerca de")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Idioma cambiado a inglés. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "¡Hola!")
language.Add("npcpassengers.welcome.msg1", "Antes de quejarte de que el pasajero está sentado encima del vehículo,\npor favor abre la configuración. Puedes hacerlo, creo en ti.")
language.Add("npcpassengers.welcome.msg2", "Este complemento todavía está lejos de ser PERFECTO, por favor no dudes en\nreportar errores y sugerir nuevas características. ¡Leo todos tus comentarios!")
language.Add("npcpassengers.welcome.changelog", "Registro de Cambios")
language.Add("npcpassengers.welcome.got_it", "¡Entendido!")
language.Add("npcpassengers.welcome.console_cmd", "O usa el comando de consola: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Clases de NPC en Lista Negra")
language.Add("npcpassengers.ui.blacklist_help", "Lista separada por comas de nombres de clases de NPC que no pueden usar torretas. Usa el comando de consola 'getnpcblacklist' para ver la lista negra actual.")
language.Add("npcpassengers.ui.hud_position", "Posición de HUD")
language.Add("npcpassengers.ui.not_bound", "Sin Asignar")
language.Add("npcpassengers.ui.keybind_tip", "Consejo: Clic derecho en un atajo para desvincularlo. Presiona ESC mientras asignas para cancelar.")
language.Add("npcpassengers.ui.dont_show_again", "No mostrar esto de nuevo")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Operaciones de Pasajeros")
language.Add("npcpassengers.hud.filter_prefix", "Filtro: ")
language.Add("npcpassengers.hud.sort_prefix", "Ordenar: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Actualización Automática: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Vehículo: ")
language.Add("npcpassengers.hud.speed_prefix", "Velocidad: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "ENCENDIDO")
language.Add("npcpassengers.hud.off", "APAGADO")
language.Add("npcpassengers.hud.passengers", "Pasajeros")
language.Add("npcpassengers.hud.npc_driver", "Conductor NPC")
language.Add("npcpassengers.hud.total_prefix", "Total: ")
language.Add("npcpassengers.hud.showing_prefix", "Mostrando: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Vehículo Actual: ")
language.Add("npcpassengers.hud.hidden_prefix", "Oculto: ")
language.Add("npcpassengers.hud.dead_prefix", "Muertos: ")
language.Add("npcpassengers.hud.scared_prefix", "Asustados: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Somnolientos: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Tranquilo")
language.Add("npcpassengers.status.alert", "Alerta")
language.Add("npcpassengers.status.scared", "Asustado")
language.Add("npcpassengers.status.drowsy", "Somnoliento")
language.Add("npcpassengers.status.dead", "Muerto")
language.Add("npcpassengers.status.unknown", "Desconocido")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Ciudadano")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Padre Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dra. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Perro")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Vehículo")
language.Add("npcassengers.sort.name", "Nombre")
language.Add("npcpassengers.sort.seat", "Asiento")
language.Add("npcpassengers.sort.health", "Salud")
language.Add("npcpassengers.sort.status", "Estado")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Vehículo Primero")
language.Add("npcpassengers.sort.name_az", "Nombre A-Z")
language.Add("npcpassengers.sort.seat_number", "Número de Asiento")
language.Add("npcpassengers.sort.highest_health", "Salud Más Alta")
language.Add("npcpassengers.sort.status_priority", "Prioridad de Estado")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Vehículo: Desconocido")
language.Add("npcpassengers.ui.seat_prefix", "Asiento ")
language.Add("npcpassengers.ui.same_vehicle", "Mismo Vehículo")
language.Add("npcpassengers.ui.other_vehicle", "Otro Vehículo")
language.Add("npcpassengers.ui.hidden", "Oculto")
language.Add("npcpassengers.ui.visible", "Visible")
language.Add("npcpassengers.ui.health_format", "Salud %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Actualizar Lista de Pasajeros")
language.Add("npcpassengers.ui.copy_list", "Copiar Lista Visible de Pasajeros")
language.Add("npcpassengers.ui.make_exit", "Hacer que Pasajeros del Vehículo Actual Salgan")
language.Add("npcpassengers.ui.reset_pos", "Restablecer Posición y Ángulos")
language.Add("npcpassengers.ui.crash_reactions", "Reacciones a Choques")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Sonidos de Embarque/Desembarque")
language.Add("npcpassengers.section.ambient_sounds", "Sonidos Ambientales")
language.Add("npcpassengers.section.gesture_animations", "Animaciones de Gestos")
language.Add("npcpassengers.section.threat_awareness", "Conciencia de Amenazas")
language.Add("npcpassengers.section.emotional_states", "Estados Emocionales")
language.Add("npcpassengers.section.turret_control", "Control de Torreta (Experimental)")
language.Add("npcpassengers.section.turret_blacklist", "Lista Negra de NPC de Torreta")
language.Add("npcpassengers.section.idle_chatter", "Charla Inactiva")
language.Add("npcpassengers.section.body_physics", "Física del Cuerpo")
language.Add("npcpassengers.section.npc_auto_driver", "Conductor Automático de NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Inferior Izquierda")
language.Add("npcpassengers.hud.bottom_right", "Inferior Derecha")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Activar HUD de Pasajeros")
language.Add("npcpassengers.ui.cover_face", "Cubrir Cara")
language.Add("npcpassengers.ui.apply_keybinds", "Aplicar Atajos Recomendados")
language.Add("npcpassengers.ui.clear_keybinds", "Borrar Todos los Atajos")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Probar Gesto de Encogimiento")
language.Add("npcpassengers.ui.test_random", "Probar Gesto Aleatorio")
language.Add("npcpassengers.ui.reset_states", "Restablecer Todos los Estados")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Activar Todas las Opciones del Menú Contextual")
language.Add("npcpassengers.ui.hide_context", "Ocultar Todas las Opciones del Menú Contextual")
language.Add("npcpassengers.ui.set_compact", "Establecer Tamaño Compacto de Panel")
language.Add("npcpassengers.ui.set_default", "Establecer Tamaño Predeterminado de Panel")
language.Add("npcpassengers.ui.set_large", "Establecer Tamaño Grande de Panel")
language.Add("npcpassengers.ui.center_panel", "Centrar Panel Ahora")
language.Add("npcpassengers.ui.reset_ui", "Restablecer Toda la Configuración de UI a Predeterminado")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Ciudadano (F)")
language.Add("npcpassengers.role.citizen_male", "Ciudadano (M)")
language.Add("npcpassengers.role.medic", "Médico")
language.Add("npcpassengers.role.rebel", "Rebelde")
language.Add("npcpassengers.role.passenger", "Pasajero")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Mostrar Solo Cuando Está en Vehículo")
language.Add("npcpassengers.hud.show_calm", "Mostrar Pasajeros Tranquilos")
language.Add("npcpassengers.hud.show_hints", "Mostrar Sugerencias Contextuales")
language.Add("npcpassengers.hud.show_target_debug", "Mostrar Depuración de Objetivo")
language.Add("npcpassengers.hud.play_cues", "Reproducir Pistas de Éxito/Fracaso")
language.Add("npcpassengers.debug.enable_mode", "Activar Modo Depuración")
language.Add("npcpassengers.ui.enable_sounds", "Activar Sonidos UI")
language.Add("npcpassengers.ui.hover_sounds", "Sonidos al Pasar el Cursor")
language.Add("npcpassengers.ui.click_sounds", "Sonidos al Clic")
language.Add("npcpassengers.ui.enable_animations", "Activar Animaciones UI")
language.Add("npcpassengers.ui.show_tooltips", "Mostrar Sugerencias")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Ocultar Barra de Desplazamiento Automáticamente")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Suavidad de Desplazamiento de Barra Lateral")
language.Add("npcpassengers.ui.color_theme", "Tema de Color")
language.Add("npcpassengers.ui.font_scale", "Escala de Fuente")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Cancelar Selección de NPC")
language.Add("npcpassengers.context.remove_passenger", "Eliminar Pasajero")
language.Add("npcpassengers.context.blacklist_passenger", "Agregar a Lista Negra")
language.Add("npcpassengers.context.whitelist_passenger", "Agregar a Lista Blanca")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Atajos de Teclado")
language.Add("npcpassengers.keybinds.desc", "Configura atajos de teclado para acciones rápidas.")
language.Add("npcpassengers.keybind.attach", "Adjuntar NPC Más Cercano")
language.Add("npcpassengers.keybind.attach.help", "Adjunta el NPC amistoso más cercano a tu vehículo.")
language.Add("npcpassengers.keybind.detach_all", "Separar Todos los NPC")
language.Add("npcpassengers.keybind.detach_all.help", "Elimina todos los pasajeros de tu vehículo.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Alternar Unión Automática")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Activa/desactiva rápidamente la unión automática.")
language.Add("npcpassengers.keybind.menu", "Abrir Menú de Configuración")
language.Add("npcpassengers.keybind.menu.help", "Abre el panel de configuración.")
language.Add("npcpassengers.keybind.exit_all", "Todos los Pasajeros Salen")
language.Add("npcpassengers.keybind.exit_all.help", "Hace que todos los pasajeros salgan del vehículo.")
language.Add("npcpassengers.keybind.toggle_hud", "Alternar HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Muestra/oculta el HUD de pasajeros.")
language.Add("npcpassengers.keybind.quick_attach", "Modo de Adjunto Rápido")
language.Add("npcpassengers.keybind.quick_attach.help", "Mantén presionado para adjuntar rápidamente los NPC que estás mirando")
language.Add("npcpassengers.keybind.hold_fire", "NPC Mantienen Fuego")
language.Add("npcpassengers.keybind.hold_fire.help", "Dile a los artilleros NPC que dejen de disparar")
language.Add("npcpassengers.keybind.open_fire", "NPC Abren Fuego")
language.Add("npcpassengers.keybind.open_fire.help", "Dile a los artilleros NPC que ataquen objetivos")
language.Add("npcpassengers.keybind.cycle_view", "Ciclar Vista de Pasajero")
language.Add("npcpassengers.keybind.cycle_view.help", "Cicla la cámara a través de pasajeros")
language.Add("npcpassengers.keybind.cycle_hud_position", "Ciclar Posición de HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Mueve el HUD de pasajeros a través de las cuatro esquinas")
language.Add("npcpassengers.keybind.toggle_debug", "Alternar Depuración de Objetivo")
language.Add("npcpassengers.keybind.toggle_debug.help", "Alterna la superposición pequeña de depuración de objetivo")
language.Add("npcpassengers.keybind.test_gesture", "Probar Gesto Aleatorio")
language.Add("npcpassengers.keybind.test_gesture.help", "Reproduce un gesto aleatorio en el pasajero más cercano")
language.Add("npcpassengers.keybind.reset_all", "Restablecer Todos los NPC")
language.Add("npcpassengers.keybind.reset_all.help", "Restablece estados de animación para todos los pasajeros")

-- HUD Settings
language.Add("npcassengers.hud.header", "Configuración de HUD")
language.Add("npcpassengers.hud.enable", "Activar HUD")
language.Add("npcpassengers.hud.enable.help", "Muestra superposición de estado de pasajeros en pantalla.")
language.Add("npcpassengers.hud.position", "Posición de HUD")
language.Add("npcpassengers.hud.position.help", "Dónde aparece el HUD en pantalla.")
language.Add("npcpassengers.hud.position.topleft", "Superior Izquierda")
language.Add("npcpassengers.hud.position.topright", "Superior Derecha")
language.Add("npcpassengers.hud.position.bottomleft", "Inferior Izquierda")
language.Add("npcpassengers.hud.position.bottomright", "Inferior Derecha")
language.Add("npcpassengers.hud.scale", "Escala de HUD")
language.Add("npcpassengers.hud.scale.help", "Multiplicador de tamaño para el HUD.")
language.Add("npcpassengers.hud.opacity", "Opacidad de HUD")
language.Add("npcpassengers.hud.opacity.help", "Transparencia de fondo (0 = invisible, 1 = sólido).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Conductor NPC")
language.Add("npcpassengers.driver.desc", "Permite que los NPC conduzcan vehículos por ti.")
language.Add("npcpassengers.driver.enable", "Activar Conductores NPC")
language.Add("npcpassengers.driver.enable.help", "Permite que los NPC tomen el control de vehículos.")
language.Add("npcpassengers.driver.behavior", "Comportamiento de Conducción")
language.Add("npcpassengers.driver.behavior.help", "Cómo conduce el NPC el vehículo.")
language.Add("npcpassengers.driver.behavior.cruise", "Crucero Aleatorio")
language.Add("npcpassengers.driver.behavior.follow", "Seguir Jugador")
language.Add("npcpassengers.driver.behavior.patrol", "Patrulla")
language.Add("npcpassengers.driver.behavior.flee", "Huir")
language.Add("npcpassengers.driver.behavior.parked", "Permanecer Estacionado")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Preguntas Frecuentes")
language.Add("npcpassengers.help.desc", "Respuestas rápidas a preguntas comunes y solución de problemas.")
language.Add("npcpassengers.help.still_need", "¿Aún Necesitas Ayuda?")
language.Add("npcpassengers.help.community", "¡Únete a nuestra comunidad de Discord para soporte!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Tanque/LVS")
language.Add("npcpassengers.nav.debugging", "Depuración")
language.Add("npcpassengers.nav.driver", "Conductor NPC")
language.Add("npcpassengers.nav.interface", "Interfaz")
language.Add("npcassengers.nav.simulate", "Simular")
language.Add("npcpassengers.nav.modules", "Módulos")
language.Add("npcpassengers.nav.about", "Acerca de")
language.Add("npcpassengers.search.placeholder", "Buscar configuración...")

-- About page
language.Add("npcpassengers.about.description", "Sistema de pasajeros avanzado con IA emocional y física realista")
language.Add("npcpassengers.about.feature_status", "Sistema de Estado: TRANQUILO / ALERTA / ASUSTADO / SOMNOLIENTO / MUERTO")
language.Add("npcpassengers.about.feature_performance", "Rendimiento: caché de asientos, temporizadores limitados, ganchos de cliente optimizados")
language.Add("npcpassengers.about.feature_filtering", "Filtrado de vehículos, enfriamiento de reintento de abordaje, unión automática solo para escuadrones")
language.Add("npcpassengers.about.actions", "Acciones")
language.Add("npcpassengers.about.show_welcome", "Mostrar Pantalla de Bienvenida")
language.Add("npcpassengers.about.open_github", "Abrir Página de GitHub")
language.Add("npcpassengers.about.reset_settings", "Restablecer TODA la Configuración a Valores Predeterminados")

-- Status messages
language.Add("npcpassengers.status.calm", "TRANQUILO")
language.Add("npcpassengers.status.alert", "ALERTA")
language.Add("npcpassengers.status.scared", "ASUSTADO")
language.Add("npcpassengers.status.drowsy", "SOMNOLIENTO")
language.Add("npcpassengers.status.dead", "MUERTO")
language.Add("npcpassengers.status.calm.desc", "Relajado, sin amenazas cercanas")
language.Add("npcpassengers.status.alert.desc", "Enemigo detectado, NPC está rastreando amenazas")
language.Add("npcpassengers.status.scared.desc", "Conducción peligrosa (alta velocidad, choques)")
language.Add("npcpassengers.status.drowsy.desc", "Viaje largo y tranquilo, NPC está quedando soñoliento")
language.Add("npcpassengers.status.dead.desc", "Salud alcanzó cero")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Unión Automática: ENCENDIDO")
language.Add("npcpassengers.chat.autojoin_off", "Unión Automática: APAGADO")
language.Add("npcpassengers.chat.hud_on", "HUD: ENCENDIDO")
language.Add("npcpassengers.chat.hud_off", "HUD: APAGADO")
language.Add("npcpassengers.chat.prefix", "[Mejores Pasajeros NPC]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "No hay vehículo cerca")
language.Add("npcpassengers.error.no_npc", "No hay NPC cerca")
language.Add("npcpassengers.error.vehicle_full", "El vehículo está lleno")
language.Add("npcpassengers.error.too_far", "NPC demasiado lejos del vehículo")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Cambiar idioma")
language.Add("npcpassengers.tooltip.minimize", "Minimizar panel")
language.Add("npcpassengers.tooltip.expand", "Expandir panel")
language.Add("npcpassengers.tooltip.welcome", "Mostrar pantalla de bienvenida")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Interruptor maestro para toda la voz de NPC. Desactiva para silenciar pasajeros completamente.")
language.Add("npcpassengers.speech_volume.help", "Qué tan fuerte son las voces de NPC (0 = silencio, 100 = volumen completo).")
language.Add("npcpassengers.pitch_variation.help", "Variación aleatoria de tono para voces más naturales. 0 = monótono, más alto = más variedad.")
language.Add("npcpassengers.crash_enable.help", "Los NPC gruñen/gimen cuando el vehículo desacelera bruscamente (choques, frenado brusco).")
language.Add("npcpassengers.crash_threshold.help", "Desaceleración necesaria para activar sonidos de choque. Menor = más sensible.")
language.Add("npcpassengers.crash_cooldown.help", "Segundos mínimos entre sonidos de choque por NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "Los NPC ocasionalmente hablan mientras viajan - comentarios, preguntas, observaciones.")
language.Add("npcpassengers.speech_idle_chance.help", "Probabilidad de charla por verificación. 0 = nunca, 1 = siempre intenta hablar.")
language.Add("npcpassengers.speech_idle_interval.help", "Segundos mínimos entre intentos de charla inactiva.")
language.Add("npcpassengers.speech_board.help", "Los NPC hablan cuando entran y salen del vehículo.")
language.Add("npcpassengers.ambient_sounds.help", "Toses ocasionales, suspiros, murmullos - sonidos de vida de fondo.")
language.Add("npcpassengers.ambient_interval.help", "Segundos promedio entre sonidos ambientales.")
language.Add("npcpassengers.animation.help", "Ajusta finamente las animaciones de NPC y el movimiento de cabeza.")
language.Add("npcpassengers.head_look.help", "Los NPC miran naturalmente alrededor, al jugador, por las ventanas, etc.")
language.Add("npcpassengers.head_smooth.help", "Qué suavemente se mueve la cabeza. Menor = más rápido, mayor = más flotante.")
language.Add("npcpassengers.blink.help", "Los NPC parpadean de manera realista mientras están sentados.")
language.Add("npcpassengers.breathing.help", "Animación de respiración sutil en las cabezas de NPC.")
language.Add("npcpassengers.walk_timeout.help", "Segundos antes de que el NPC abandone caminar hacia el vehículo.")
language.Add("npcpassengers.realism.help", "Reacciones basadas en física y sistemas de conciencia para máxima inmersión.")
language.Add("npcpassengers.talking_gestures.help", "Los NPC reproducen aleatoriamente gestos de manos y animaciones corporales mientras viajan.")
language.Add("npcpassengers.gesture_chance.help", "Porcentaje de probabilidad de reproducir un gesto cada intervalo.")
language.Add("npcpassengers.gesture_interval.help", "Segundos entre verificaciones de oportunidad de gesto.")
language.Add("npcpassengers.crash_flinch.help", "Los NPC se encogen y se lanzan hacia adelante cuando el vehículo choca o frena bruscamente.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Cambio de velocidad necesario para activar encogimiento (menor = más sensible).")
language.Add("npcpassengers.body_sway.help", "Los NPC se inclinan en giros, se apoyan durante aceleración/frenado.")
language.Add("npcpassengers.body_sway_amount.help", "Cuánto se balancean los NPC con el movimiento del vehículo.")
language.Add("npcpassengers.threat_awareness.help", "Los NPC miran automáticamente hacia enemigos cercanos.")
language.Add("npcpassengers.threat_range.help", "A qué distancia pueden detectar amenazas los NPC para rastreo de cabeza.")
language.Add("npcpassengers.combat_alert.help", "Los NPC se tensan y reaccionan cuando los enemigos están cerca.")
language.Add("npcpassengers.passenger_combat.help", "Desactivado por defecto. Activa esto para permitir que pasajeros armados disparen desde dentro de vehículos.")
language.Add("npcpassengers.passenger_combat_range.help", "A qué distancia pueden adquirir objetivos los pasajeros armados.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Valores más altos reducen la dispersión de disparos para pasajeros armados.")
language.Add("npcpassengers.passenger_combat_damage.help", "Escala el daño infligido por disparos de pasajeros.")
language.Add("npcpassengers.passenger_interaction.help", "Múltiples pasajeros se miran y ocasionalmente conversan entre sí.")
language.Add("npcpassengers.fear_reactions.help", "Los NPC se asustan por la conducción peligrosa - ojos abiertos, sonidos de pánico.")
language.Add("npcpassengers.fear_speed_threshold.help", "Velocidad (unidades/seg) a la que los NPC empiezan a ponerse nerviosos.")
language.Add("npcpassengers.drowsiness.help", "Los NPC se duermen en viajes largos y tranquilos - parpadeos lentos, cabeceos.")
language.Add("npcpassengers.drowsy_time.help", "Segundos de conducción tranquila antes de que aparezca la somnolencia.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Configuración para tanques, APC y vehículos LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Hace invisibles a los pasajeros NPC cuando están dentro de tanques y APC.")
language.Add("npcpassengers.eject_stuck_check.help", "Empuja automáticamente a los NPC fuera de vehículos cuando se atascan durante la expulsión. Evita que los NPC atraviesen vehículos al salir.")
language.Add("npcpassengers.detach_no_collide.help", "Después de desconectar, los NPC pasan temporalmente a través del vehículo para que puedan alejarse sin interseción o atascarse.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Cuánto tiempo ignoran los NPC la colisión del vehículo después de desconectar.")
language.Add("npcpassengers.die_with_vehicle.help", "Los pasajeros NPC mueren cuando su vehículo es destruido por explosión o fuego (más inmersivo que si salieran de los restos ilesos).")
language.Add("npcpassengers.tank_driver.help", "Permite a los NPC en el asiento del conductor conducir automáticamente hacia los enemigos.")
language.Add("npcpassengers.tank_driver_range.help", "Rango máximo para que el conductor detecte enemigos.")
language.Add("npcpassengers.tank_driver_distance.help", "Distancia a mantener de los enemigos.")
language.Add("npcpassengers.tank_driver_throttle.help", "Cantidad de acelerador (0.1 = lento, 1 = velocidad completa).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distancia a la que retroceder lejos de los enemigos.")
language.Add("npcpassengers.tank_turret.help", "Permite a los NPC controlar torretas en vehículos LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Muestra estado de pasajeros (emociones, alerta) en pantalla mientras conduces.")
language.Add("npcpassengers.hud_show_calm.help", "Cuando está desactivado, solo muestra pasajeros con estado no tranquilo.")
language.Add("npcpassengers.hud_thresholds.desc", "Cuando los niveles de emoción exceden estos umbrales, los pasajeros muestran ese estado en el HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Nivel de alerta necesario para mostrar estado 'ALERTA' (amenaza detectada).")
language.Add("npcpassengers.hud_fear_threshold.help", "Nivel de miedo necesario para mostrar estado 'ASUSTADO' (conducción peligrosa).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Relación de tiempo tranquilo necesario para mostrar estado 'SOMNOLIENTO' (viaje largo y tranquilo).")
language.Add("npcpassengers.hud_actions.desc", "Elige qué acción toman los pasajeros cuando experimentan cada estado emocional.")
language.Add("npcpassengers.hud_actions_note", "Nota: Algunas acciones pueden no ser visibles dependiendo del soporte del modelo de NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Establece atajos personalizados para acciones de pasajero. Haz clic en un botón y presiona una tecla para asignar.")
language.Add("npcpassengers.keybinds_hud.desc", "Controles rápidos de HUD para mostrar, mover y depurar la superposición de pasajeros.")
language.Add("npcpassengers.keybinds_debug_note", "Los atajos de depuración solo funcionan cuando el Modo Depuración está activado.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Herramientas avanzadas de depuración para probar el comportamiento de NPC. Activa el Modo Depuración en configuración primero.")
language.Add("npcpassengers.debug_mode.help", "Muestra botones de prueba de depuración y habilita comandos de depuración.")
language.Add("npcpassengers.debug_status.help", "Establece manualmente el estado del pasajero para pruebas. Haz clic en 'Actualizar Lista' para ver los pasajeros actuales.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configura efectos de sonido para botones, casillas y otros elementos UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Interruptor maestro para todos los efectos de sonido UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Multiplicador de volumen para sonidos UI (1.0 = normal, 2.0 = doble)")
language.Add("npcpassengers.ui_hover_enabled.help", "Reproduce sonido al pasar el cursor sobre botones")
language.Add("npcpassengers.ui_click_enabled.help", "Reproduce sonido al hacer clic en botones y casillas")
language.Add("npcpassengers.context_menu.desc", "Elige qué opciones aparecen al hacer clic derecho en NPC")
language.Add("npcpassengers.context_make_passenger.help", "Agrega NPC como pasajero a tu vehículo actual")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Agrega NPC a un vehículo específico (haz clic en NPC, luego vehículo)")
language.Add("npcpassengers.context_detach.help", "Elimina NPC del vehículo")
language.Add("npcpassengers.ui_show_welcome.help", "Muestra panel de bienvenida cuando el complemento se actualiza a una nueva versión")
language.Add("npcpassengers.ui_panel_width.help", "Ancho del panel de configuración")
language.Add("npcpassengers.ui_panel_height.help", "Alto del panel de configuración")
language.Add("npcpassengers.ui_animations.help", "Transiciones suaves y efectos de paso (puede afectar rendimiento)")
language.Add("npcpassengers.ui_tooltips.help", "Muestra sugerencias útiles al pasar el cursor sobre configuración")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Muestra la barra de desplazamiento solo mientras estás desplazando o pasando el cursor sobre ella.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Nota: El panel se vuelve 70% transparente al arrastrar cualquier control deslizador para ver contenido en el fondo.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Valores más bajos = más suave pero más lento (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Elige un tema de color para el panel de configuración. Los cambios se aplican inmediatamente.")
language.Add("npcpassengers.ui_font_scale.help", "Escala todos los tamaños de fuente UI. 1.0 = predeterminado, 0.5 = medio tamaño, 2.0 = tamaño doble.")

print("[Better NPC Passengers] Spanish localization loaded!")
