-- Better NPC Passengers - Spanish Localization
-- Traducción al español

-- Addon name
language.Add("npcpassengers.name", "Better NPC Passengers")
language.Add("npcpassengers.settings", "Configuración")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "General")
language.Add("npcpassengers.nav.autojoin", "Unión Automática")
language.Add("npcpassengers.nav.passengers", "Pasajeros")
language.Add("npcpassengers.nav.position", "Posición")
language.Add("npcpassengers.nav.behaviour", "Comportamiento")
language.Add("npcpassengers.nav.keybinds", "Atajos")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Conductor")
language.Add("npcpassengers.nav.help", "Ayuda")

-- General Settings
language.Add("npcpassengers.general.header", "Configuración General")
language.Add("npcpassengers.allow_multiple", "Permitir múltiples pasajeros")
language.Add("npcpassengers.allow_multiple.help", "Permite que varios NPC viajen en el mismo vehículo.")
language.Add("npcpassengers.exit_behavior", "Comportamiento de salida")
language.Add("npcpassengers.exit_behavior.help", "¿Cuándo deben salir los pasajeros NPC del vehículo?")
language.Add("npcpassengers.exit_mode.leave_player", "Salir cuando el jugador sale")
language.Add("npcpassengers.exit_mode.leave_attack", "Salir cuando el vehículo es atacado")
language.Add("npcpassengers.exit_mode.never", "Nunca salir automáticamente")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Configuración de tiempo")
language.Add("npcpassengers.max_attach_dist", "Distancia máxima de abordaje")
language.Add("npcpassengers.max_attach_dist.help", "Distancia máxima (unidades) para que un NPC suba al vehículo.")
language.Add("npcpassengers.detach_delay", "Retraso de salida")
language.Add("npcpassengers.detach_delay.help", "Segundos de espera antes de que el NPC salga después de que el jugador abandone el vehículo.")
language.Add("npcpassengers.ai_delay", "Retraso de recuperación de IA")
language.Add("npcpassengers.ai_delay.help", "Segundos de espera antes de restaurar la IA del NPC después de salir.")
language.Add("npcpassengers.cooldown", "Tiempo de reutilización")
language.Add("npcpassengers.cooldown.help", "Tiempo de reutilización entre abordajes de NPC al mismo vehículo.")
language.Add("npcpassengers.passenger_limit", "Límite de pasajeros")
language.Add("npcpassengers.passenger_limit.help", "Máximo de NPC en el vehículo.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Unión Automática (Comportamiento de escuadrón)")
language.Add("npcpassengers.autojoin.desc", "Los NPC amigos se unirán automáticamente a tu vehículo cuando entres en él, ¡como la mecánica de escuadrones en Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Activar unión automática")
language.Add("npcpassengers.autojoin.enable.help", "Los NPC amigables cercanos se unirán automáticamente cuando entres en un vehículo.")
language.Add("npcpassengers.autojoin.range", "Rango de unión automática")
language.Add("npcpassengers.autojoin.range.help", "Distancia máxima para buscar NPC para unión automática.")
language.Add("npcpassengers.autojoin.max", "Máximo de NPC para unión automática")
language.Add("npcpassengers.autojoin.max.help", "Cantidad máxima de NPC que pueden unirse automáticamente a la vez.")
language.Add("npcpassengers.autojoin.squad_only", "Solo miembros de escuadrón")
language.Add("npcpassengers.autojoin.squad_only.help", "Solo los NPC con nombre de escuadrón se unirán automáticamente (para escuadrones estilo HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Los NPC amigos se unirán automáticamente a tu vehículo cuando entres en él, ¡como la mecánica de escuadrones en Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Gestión de pasajeros")
language.Add("npcpassengers.panel.passengers.desc", "Gestiona pasajeros activos, filtra por nombre/clase/estado, copia información de depuración, reasigna asientos y haz que los pasajeros salgan sin salir del panel de configuración.")
language.Add("npcpassengers.panel.position.desc", "Ajuste fino de la posición de los NPC en el vehículo. Úsalo para corregir problemas de flotación o clipping.")
language.Add("npcpassengers.panel.angle.desc", "Ajuste de la rotación de los NPC en el vehículo.")
language.Add("npcpassengers.panel.speech.desc", "Configura cómo vocalizan los NPC mientras viajan en el vehículo. ¡Voces de ciudadanos estilo HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Desplazamientos de posición")
language.Add("npcpassengers.position.desc", "Ajuste fino de la posición de los NPC en el vehículo. Úsalo para corregir problemas de flotación o clipping.")
language.Add("npcpassengers.height_offset", "Desplazamiento de altura")
language.Add("npcpassengers.forward_offset", "Desplazamiento frontal")
language.Add("npcpassengers.right_offset", "Desplazamiento derecho")
language.Add("npcpassengers.angle.header", "Desplazamientos de ángulo")
language.Add("npcpassengers.angle.desc", "Ajuste de la rotación de los NPC en el vehículo.")
language.Add("npcpassengers.yaw_offset", "Guiñada (Rotación)")
language.Add("npcpassengers.pitch_offset", "Cabeceo (Inclinación frontal)")
language.Add("npcpassengers.roll_offset", "Alabeo (Inclinación lateral)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Voz de NPC (Avanzado)")
language.Add("npcpassengers.behaviour.desc", "Configura cómo vocalizan los NPC mientras viajan en el vehículo. ¡Voces de ciudadanos estilo HL2!")
language.Add("npcpassengers.speech_enable", "Activar voz de NPC")
language.Add("npcpassengers.speech_enable.help", "Interruptor maestro para toda la voz de NPC. Desactívalo para silenciar completamente a los pasajeros.")
language.Add("npcpassengers.speech_volume", "Volumen de voz")
language.Add("npcpassengers.speech_volume.help", "Qué tan fuerte hablan los NPC (0 = silencio, 100 = volumen completo).")
language.Add("npcpassengers.pitch_variation", "Variación de tono (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Variación aleatoria de tono para voces más naturales. 0 = monótono, más alto = más variedad.")
language.Add("npcpassengers.crash.header", "Reacciones a accidentes")
language.Add("npcpassengers.crash_enable", "Activar sonidos de accidentes")
language.Add("npcpassengers.crash_enable.help", "Los NPC gimotean/gritan cuando el vehículo desacelera bruscamente (accidentes, frenado brusco).")
language.Add("npcpassengers.crash_threshold", "Sensibilidad a accidentes")
language.Add("npcpassengers.crash_threshold.help", "Desaceleración necesaria para activar sonidos de accidentes. Más bajo = más sensible.")
language.Add("npcpassengers.crash_cooldown", "Enfriamiento de sonidos de accidentes")
language.Add("npcpassengers.crash_cooldown.help", "Segundos mínimos entre sonidos de accidentes por NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Activar charla")
language.Add("npcpassengers.speech_board", "Activar sonidos de abordaje/salida")
language.Add("npcpassengers.ambient_sounds", "Activar sonidos ambientales")
language.Add("npcpassengers.head_look", "Activar mirada de cabeza/ojos")
language.Add("npcpassengers.blink", "Activar parpadeo")
language.Add("npcpassengers.breathing", "Activar respiración")
language.Add("npcpassengers.talking_gestures", "Activar gestos de habla")
language.Add("npcpassengers.crash_flinch", "Activar encogimiento por accidente")
language.Add("npcpassengers.body_sway", "Activar balanceo del cuerpo")
language.Add("npcpassengers.threat_awareness", "Activar conciencia de amenazas")
language.Add("npcpassengers.combat_alert", "Alerta de combate")
language.Add("npcpassengers.passenger_combat", "NPC disparan desde el vehículo (Experimental)")
language.Add("npcpassengers.passenger_interaction", "Interacción de pasajeros")
language.Add("npcpassengers.fear_reactions", "Activar reacciones de miedo")
language.Add("npcpassengers.drowsiness", "Activar somnolencia")
language.Add("npcpassengers.hide_in_tanks", "Ocultar NPC en vehículos cerrados")
language.Add("npcpassengers.eject_stuck_check", "Expulsión automática de NPC atascados")
language.Add("npcpassengers.detach_no_collide", "Sin colisión con vehículo después de salir")
language.Add("npcpassengers.die_with_vehicle", "Matar pasajeros al explotar el vehículo")
language.Add("npcpassengers.driver_enabled", "Activar conducción automática")
language.Add("npcpassengers.turret_enabled", "Activar control de torreta")
language.Add("npcpassengers.turret_lead_targets", "Anticipación de objetivos")
language.Add("npcpassengers.turret_friendly_fire", "Permitir fuego amigo")
language.Add("npcpassengers.turret_hold_fire", "Mantener fuego (Desactivar disparo)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Volumen de voz")
language.Add("npcpassengers.pitch_variation", "Variación de tono (+/-)")
language.Add("npcpassengers.crash_threshold", "Sensibilidad a accidentes")
language.Add("npcpassengers.crash_cooldown", "Enfriamiento de sonidos de accidentes")
language.Add("npcpassengers.speech_idle_chance", "Probabilidad de charla")
language.Add("npcpassengers.speech_idle_interval", "Intervalo de charla")
language.Add("npcpassengers.ambient_interval", "Intervalo de sonidos ambientales")
language.Add("npcpassengers.head_smooth", "Suavidad de cabeza")
language.Add("npcpassengers.walk_timeout", "Tiempo de espera de caminata")
language.Add("npcpassengers.gesture_chance", "Probabilidad de gestos (%)")
language.Add("npcpassengers.gesture_interval", "Intervalo de gestos")
language.Add("npcpassengers.crash_threshold_flinch", "Sensibilidad a accidentes")
language.Add("npcpassengers.body_sway_amount", "Intensidad de balanceo")
language.Add("npcpassengers.threat_range", "Rango de detección de amenazas")
language.Add("npcpassengers.passenger_combat_range", "Rango de combate de pasajeros")
language.Add("npcpassengers.passenger_combat_accuracy", "Precisión de pasajeros")
language.Add("npcpassengers.passenger_combat_damage", "Multiplicador de daño de pasajeros")
language.Add("npcpassengers.fear_speed_threshold", "Umbral de velocidad de miedo")
language.Add("npcpassengers.drowsy_time", "Tiempo de somnolencia")
language.Add("npcpassengers.detach_no_collide_duration", "Duración sin colisión (segundos)")
language.Add("npcpassengers.tank_driver_range", "Rango de detección")
language.Add("npcpassengers.tank_driver_engage_distance", "Distancia de compromiso")
language.Add("npcpassengers.tank_driver_speed", "Velocidad de conducción")
language.Add("npcpassengers.tank_driver_reverse_distance", "Distancia de reversa")
language.Add("npcpassengers.turret_range", "Rango de objetivo")
language.Add("npcpassengers.turret_accuracy", "Precisión")
language.Add("npcpassengers.turret_reaction_time", "Tiempo de reacción")
language.Add("npcpassengers.turret_fire_delay", "Retraso de disparo")
language.Add("npcpassengers.turret_aim_speed", "Velocidad de apuntado")
language.Add("npcpassengers.hud_scale", "Escala de HUD")
language.Add("npcpassengers.hud_opacity", "Opacidad de HUD")
language.Add("npcpassengers.hud_alert_threshold", "Umbral de alerta")
language.Add("npcpassengers.hud_fear_threshold", "Umbral de miedo")
language.Add("npcpassengers.hud_drowsy_threshold", "Umbral de somnolencia")
language.Add("npcpassengers.ui_sounds_volume", "Volumen de sonidos de UI")
language.Add("npcpassengers.ui_panel_width", "Ancho del panel")

-- Section headers
language.Add("npcpassengers.section.animation", "Animación y comportamiento")
language.Add("npcpassengers.section.realism", "Realismo avanzado")
language.Add("npcpassengers.section.hud_position", "Posición y estilo de HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Umbrales de emoción")
language.Add("npcpassengers.section.emotion_actions", "Acciones de emoción")
language.Add("npcpassengers.section.vehicle_control", "Control de vehículo")
language.Add("npcpassengers.section.hud_controls", "Controles de HUD")
language.Add("npcpassengers.section.debug_controls", "Controles de depuración")
language.Add("npcpassengers.section.passenger_status", "Gestión de estado de pasajeros")
language.Add("npcpassengers.section.quick_test", "Botones de prueba rápida")
language.Add("npcpassengers.section.driver_system", "Sistema de conductor NPC")
language.Add("npcpassengers.section.ui_sounds", "Configuración de sonidos de UI")
language.Add("npcpassengers.section.appearance", "Apariencia")
language.Add("npcpassengers.section.context_menu", "Opciones de menú contextual")
language.Add("npcpassengers.section.panel_preferences", "Preferencias del panel de configuración")
language.Add("npcpassengers.section.performance", "Rendimiento y técnico")
language.Add("npcpassengers.section.simulation", "Sistema de simulación")
language.Add("npcpassengers.section.modules", "Sistema de módulos")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Asignar asiento")
language.Add("npcpassengers.btn.detach", "Desconectar")
language.Add("npcpassengers.btn.copy_summary", "Copiar resumen")
language.Add("npcpassengers.btn.copy_debug", "Copiar depuración")
language.Add("npcpassengers.btn.enable_all_speech", "Activar toda la voz")
language.Add("npcpassengers.btn.disable_all_speech", "Desactivar toda la voz")
language.Add("npcpassengers.btn.show_current_vehicle", "Mostrar solo vehículo actual")
language.Add("npcpassengers.btn.auto_refresh", "Actualización automática de lista visible")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Vehículo actual no detectado. Entra en un vehículo o desactiva el filtro de vehículo actual.")
language.Add("npcpassengers.status.no_match_filter", "Los pasajeros no coinciden con tu filtro. Intenta con nombre, clase, número de asiento, estado o clase de vehículo.")
language.Add("npcpassengers.status.no_passengers_vehicle", "No se encontraron pasajeros en tu vehículo actual.")
language.Add("npcpassengers.status.no_passengers", "No se encontraron pasajeros. Los NPC deben estar en un vehículo antes de poder gestionarlos aquí.")
language.Add("npcpassengers.status.all_passengers", "Todos los pasajeros")
language.Add("npcpassengers.status.current_vehicle_only", "Solo vehículo actual")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F para enfocar búsqueda")
language.Add("npcpassengers.status.no_matches", "Sin configuraciones coincidentes")
language.Add("npcpassengers.status.showing_matches", "Mostrando %d de %d coincidencias")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Abrir configuración")
language.Add("npcpassengers.menu.reset_all", "Restablecer toda la configuración")

-- Button states
language.Add("npcpassengers.state.on", "ON")
language.Add("npcpassengers.state.off", "OFF")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Unión automática")
language.Add("npcpassengers.chat.hud_status", "HUD de pasajeros")
language.Add("npcpassengers.chat.hud_position", "Posición de HUD")
language.Add("npcpassengers.chat.target_debug", "Depuración de objetivo")
language.Add("npcpassengers.chat.turret_gunners", "Artilleros de torreta")
language.Add("npcpassengers.chat.turret_holding", "MANTENIENDO FUEGO")
language.Add("npcpassengers.chat.turret_fire", "FUEGO ABIERTO")
language.Add("npcpassengers.chat.unknown", "Desconocido")
language.Add("npcpassengers.chat.nothing_copy", "Nada que copiar.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Acceso al portapapeles no disponible en esta compilación.")
language.Add("npcpassengers.chat.copied_clipboard", "Copiado al portapapeles.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Entra en el mismo vehículo para reasignar este pasajero.")
language.Add("npcpassengers.chat.no_visible_passengers", "Sin pasajeros visibles para copiar.")
language.Add("npcpassengers.chat.need_vehicle", "Necesitas estar en un vehículo para usar esto.")
language.Add("npcpassengers.chat.keybinds_applied", "Atajos recomendados aplicados.")
language.Add("npcpassengers.chat.keybinds_cleared", "Todos los atajos borrados.")
language.Add("npcpassengers.chat.context_enabled", "Todas las opciones del menú contextual activadas.")
language.Add("npcpassengers.chat.context_hidden", "Todas las opciones del menú contextual ocultas.")
language.Add("npcpassengers.chat.panel_compact", "Tamaño del panel establecido en compacto.")
language.Add("npcpassengers.chat.panel_default", "Tamaño del panel establecido en predeterminado.")
language.Add("npcpassengers.chat.panel_large", "Tamaño del panel establecido en grande.")
language.Add("npcpassengers.chat.panel_centered", "Panel centrado.")
language.Add("npcpassengers.chat.settings_reset", "¡Toda la configuración de UI restablecida a valores predeterminados!")
language.Add("npcpassengers.chat.npc_selected", "¡NPC seleccionado! Ahora haz clic derecho en el vehículo y selecciona 'Añadir NPC seleccionado'")
language.Add("npcpassengers.chat.adding_npc", "Añadiendo NPC al vehículo...")
language.Add("npcpassengers.chat.selection_cancelled", "Selección de NPC cancelada")
language.Add("npcpassengers.chat.summary_copied", "Resumen de pasajeros copiado.")
language.Add("npcpassengers.chat.debug_copied", "Información de depuración de pasajero copiada.")
language.Add("npcpassengers.chat.no_passengers_found", "No se encontraron pasajeros. Los NPC deben estar en un vehículo.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Intensidad de estado %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Filtrar pasajeros...")
language.Add("npcpassengers.ui.press_key", "Presiona tecla...")
language.Add("npcpassengers.ui.work_in_progress", "En desarrollo")
language.Add("npcpassengers.ui.under_development", "Esta función está en desarrollo")
language.Add("npcpassengers.ui.check_back_later", "¡Revisa en una futura actualización!")
language.Add("npcpassengers.ui.search_desc_passengers", "Filtrar pasajeros activos por nombre, clase, asiento, estado o vehículo.")
language.Add("npcpassengers.ui.search_desc_sort", "Ordenar la lista visible de pasajeros por vehículo, nombre, asiento, salud o estado.")
language.Add("npcpassengers.ui.search_label_filter", "Filtro de pasajeros")
language.Add("npcpassengers.ui.search_label_sort", "Orden de pasajeros")

-- Additional keybind names and descriptions
language.Add("npcpassengers.keybind.quick_attach", "Abordaje rápido")
language.Add("npcpassengers.keybind.hold_fire", "NPC mantienen fuego")
language.Add("npcpassengers.keybind.open_fire", "NPC abren fuego")
language.Add("npcpassengers.keybind.cycle_view", "Ciclo de cámara de pasajeros")
language.Add("npcpassengers.keybind.cycle_hud_position", "Ciclo de posición de HUD")
language.Add("npcpassengers.keybind.toggle_debug", "Alternar depuración de objetivo")
language.Add("npcpassengers.keybind.test_gesture", "Probar gesto aleatorio")
language.Add("npcpassengers.keybind.reset_all", "Restablecer todos los NPC")
language.Add("npcpassengers.keybind.quick_attach.help", "Mantén presionado para abordar rápidamente los NPC que estás mirando")
language.Add("npcpassengers.keybind.hold_fire.help", "Decir a los artilleros NPC que dejen de disparar")
language.Add("npcpassengers.keybind.open_fire.help", "Decir a los artilleros NPC que ataquen objetivos")
language.Add("npcpassengers.keybind.cycle_view.help", "Cambiar cíclicamente la cámara entre pasajeros")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Mover el HUD de pasajeros a las cuatro esquinas")
language.Add("npcpassengers.keybind.toggle_debug.help", "Alternar la superposición de depuración de objetivo pequeña")
language.Add("npcpassengers.keybind.test_gesture.help", "Reproducir un gesto aleatorio en el pasajero más cercano")
language.Add("npcpassengers.keybind.reset_all.help", "Restablecer estados de animación para todos los pasajeros")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "¿Cómo añado un NPC a mi vehículo?")
language.Add("npcpassengers.faq.add_npc.answer", "Usa el menú contextual (clic derecho en NPC) y selecciona 'Hacer pasajero'. O usa el atajo 'Abordar NPC más cercano'. Los NPC deben ser amigables contigo.")
language.Add("npcpassengers.faq.remove_npc", "¿Cómo elimino pasajeros de mi vehículo?")
language.Add("npcpassengers.faq.remove_npc.answer", "Ve a la pestaña Pasajeros en la configuración, selecciona un pasajero y haz clic en Desconectar. O usa el atajo 'Desconectar todos los NPC'.")
language.Add("npcpassengers.faq.position", "¡Los NPC flotan o atraviesan los asientos!")
language.Add("npcpassengers.faq.position.answer", "Ve a la pestaña Posición y ajusta los desplazamientos de Altura/Frente/Derecha. Cada modelo de vehículo es diferente, por lo que es posible que necesites ajustar los valores con precisión. Usa el panel de depuración para probar posiciones en tiempo real.")
language.Add("npcpassengers.faq.speech", "¡Los NPC no hablan!")
language.Add("npcpassengers.faq.speech.answer", "Verifica la pestaña Comportamiento y asegúrate de que 'Activar voz de NPC' esté activado. También asegúrate de que el Volumen de voz sea superior a 0. Algunos modelos de NPC pueden no tener líneas de voz disponibles.")
language.Add("npcpassengers.faq.autojoin", "¿Cómo funciona la unión automática?")
language.Add("npcpassengers.faq.autojoin.answer", "Cuando está activado en la pestaña Unión automática, los NPC amigables cercanos se unirán automáticamente a tu vehículo cuando entres en él, ¡como la mecánica de escuadrones en Half-Life 2. Puedes establecer el rango de detección y limitar cuántos NPC pueden unirse automáticamente.")
language.Add("npcpassengers.faq.death", "¿Qué sucede cuando los pasajeros mueren?")
language.Add("npcpassengers.faq.death.answer", "Los pasajeros muertos mostrarán un efecto de resplandor rojo y un icono de calavera en el HUD. Acércate a tu vehículo y mantén presionada R para eliminar sus cuerpos. Los cuerpos serán expulsados con física.")
language.Add("npcpassengers.faq.status", "¿Qué significan los estados de los pasajeros?")
language.Add("npcpassengers.faq.status.answer", "CALMA: Relajado, sin amenazas cercanas. ALERTA: Enemigo detectado. MIEDO: Conducción peligrosa. SOMNOLENCIA: Viaje tranquilo largo. MUERTE: Salud alcanzó cero.")
language.Add("npcpassengers.faq.keybinds", "¡Mis atajos no funcionan!")
language.Add("npcpassengers.faq.keybinds.answer", "Ve a la pestaña Atajos y asegúrate de que realmente hayas establecido los atajos (no están vinculados de forma predeterminada). Haz clic en el botón junto a cada acción y presiona la tecla deseada. Clic derecho para desvincular.")
language.Add("npcpassengers.faq.errors", "¡El complemento no funciona en absoluto / Recibo errores!")
language.Add("npcpassengers.faq.errors.answer", "Asegúrate de que estás usando la última versión de Garry's Mod. Verifica la consola en busca de errores (tecla tilde ~). Intenta desactivar complementos conflictivos.")
language.Add("npcpassengers.faq.combat", "¿Pueden los pasajeros disparar desde el vehículo?")
language.Add("npcpassengers.faq.combat.answer", "Actualmente no. Los NPC rastrearán enemigos y reaccionarán a amenazas, pero no dispararán desde armas mientras estén sentados. Esta función puede añadirse en futuras actualizaciones.")
language.Add("npcpassengers.faq.stop_autojoin", "¿Cómo detengo que los NPC se unan automáticamente?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Desactiva la casilla 'Activar unión automática' en la pestaña Unión automática, o usa el atajo 'Alternar unión automática'.")
language.Add("npcpassengers.faq.settings", "¿Dónde se guarda la configuración?")
language.Add("npcpassengers.faq.settings.answer", "Toda la configuración se guarda como ConVars en tu configuración de GMod. Persiste entre sesiones y es específica de tu cliente.")
language.Add("npcpassengers.faq.vehicles", "¿Esto funciona con todos los vehículos?")
language.Add("npcpassengers.faq.vehicles.answer", "Funciona con la mayoría de los vehículos que tienen física. Tanques, APC, automóviles, botes, etc. Algunos vehículos modificados pueden requerir ajustes de posición.")
language.Add("npcpassengers.faq.multiple", "¿Puedo tener múltiples NPC en un vehículo?")
language.Add("npcpassengers.faq.multiple.answer", "¡Sí! Establece el 'Límite de pasajeros' en la configuración general. El complemento distribuirá automáticamente los NPC alrededor del vehículo. Para posiciones de asiento específicas, ajusta los desplazamientos en la pestaña Posición.")
language.Add("npcpassengers.faq.crashes", "¡Los NPC se comportan de manera extraña después de accidentes!")
language.Add("npcpassengers.faq.crashes.answer", "Esto es normal: reaccionan con miedo a la conducción peligrosa. Reduce el Umbral de miedo en la configuración de HUD si quieres que sean menos reactivos.")
language.Add("npcpassengers.faq.reset_setting", "¿Cómo restablezco solo una configuración?")
language.Add("npcpassengers.faq.reset_setting.answer", "Usa el comando de consola para esa configuración específica. Todos los comandos comienzan con 'nai_npc_'. Escribe 'find nai_npc' en la consola para ver todos los comandos disponibles.")
language.Add("npcpassengers.faq.multiplayer", "¿Esto funciona en multijugador?")
language.Add("npcpassengers.faq.multiplayer.answer", "¡Sí! El complemento funciona en servidores tanto de un jugador como de multijugador. Cada jugador controla sus propios pasajeros.")
language.Add("npcpassengers.faq.lvs", "¿Esto funciona con vehículos LVS?")
language.Add("npcpassengers.faq.lvs.answer", "¡Sí! El complemento tiene soporte completo para vehículos LVS (Lua Vehicle System). Los NPC pueden viajar como pasajeros e incluso pueden conducir vehículos LVS si el modo de conductor NPC está activado.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Esta configuración controla el comportamiento de la interfaz de usuario del complemento")
language.Add("npcpassengers.panel.performance_note1", "Los cambios en el tamaño del panel requieren cerrar y volver a abrir el menú")
language.Add("npcpassengers.panel.performance_note2", "Desactivar sonidos o animaciones puede mejorar el rendimiento en sistemas de gama baja")
language.Add("npcpassengers.panel.performance_title", "Información de configuración de interfaz")
language.Add("npcpassengers.help.console_title", "Comandos de consola para depuración:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Activa el modo de depuración para ver información detallada")
language.Add("npcpassengers.about.title", "Acerca de")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Idioma cambiado a inglés. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_russian", "Idioma cambiado a ruso. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_chinese", "Idioma cambiado a chino. El panel se actualizará automáticamente.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "¡Hola!")
language.Add("npcpassengers.welcome.msg1", "Antes de quejarte de que el pasajero esté sentado encima del vehículo,\npor favor abre la configuración. Puedes hacerlo, creo en ti.")
language.Add("npcpassengers.welcome.msg2", "Este complemento aún está lejos de ser PERFECTO, por favor no dudes en\nreportar errores y sugerir nuevas funciones. ¡Leo todos tus comentarios!")
language.Add("npcpassengers.welcome.changelog", "Registro de cambios")
language.Add("npcpassengers.welcome.got_it", "¡Entendido!")
language.Add("npcpassengers.welcome.console_cmd", "O usa el comando de consola: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Clases de NPC en lista negra")
language.Add("npcpassengers.ui.blacklist_help", "Lista separada por comas de nombres de clases de NPC que no pueden usar torretas. Usa el comando de consola 'getnpcblacklist' para ver la lista negra actual.")
language.Add("npcpassengers.ui.hud_position", "Posición de HUD")
language.Add("npcpassengers.ui.not_bound", "No vinculado")
language.Add("npcpassengers.ui.keybind_tip", "Consejo: Haz clic derecho en un atajo para desvincularlo. Presiona ESC mientras vinculas para cancelar.")
language.Add("npcpassengers.ui.dont_show_again", "No mostrar de nuevo")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Operaciones de pasajeros")
language.Add("npcpassengers.hud.filter_prefix", "Filtro: ")
language.Add("npcpassengers.hud.sort_prefix", "Ordenar: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Actualización automática: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Vehículo: ")
language.Add("npcpassengers.hud.speed_prefix", "Velocidad: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "ON")
language.Add("npcpassengers.hud.off", "OFF")
language.Add("npcpassengers.hud.passengers", "Pasajeros")
language.Add("npcpassengers.hud.npc_driver", "Conductor NPC")
language.Add("npcpassengers.hud.total_prefix", "Total: ")
language.Add("npcpassengers.hud.showing_prefix", "Mostrando: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Vehículo actual: ")
language.Add("npcpassengers.hud.hidden_prefix", "Oculto: ")
language.Add("npcpassengers.hud.dead_prefix", "Muertos: ")
language.Add("npcpassengers.hud.scared_prefix", "Asustados: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Somnolientos: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Calma")
language.Add("npcpassengers.status.alert", "Alerta")
language.Add("npcpassengers.status.scared", "Asustado")
language.Add("npcpassengers.status.drowsy", "Somnoliento")
language.Add("npcpassengers.status.dead", "Muerto")
language.Add("npcpassengers.status.unknown", "Desconocido")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Ciudadano")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Padre Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dra. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Perro")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Vehículo")
language.Add("npcpassengers.sort.name", "Nombre")
language.Add("npcpassengers.sort.seat", "Asiento")
language.Add("npcpassengers.sort.health", "Salud")
language.Add("npcpassengers.sort.status", "Estado")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Vehículo primero")
language.Add("npcpassengers.sort.name_az", "Nombre A-Z")
language.Add("npcpassengers.sort.seat_number", "Número de asiento")
language.Add("npcpassengers.sort.highest_health", "Salud más alta")
language.Add("npcpassengers.sort.status_priority", "Prioridad de estado")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Vehículo: Desconocido")
language.Add("npcpassengers.ui.seat_prefix", "Asiento ")
language.Add("npcpassengers.ui.same_vehicle", "Mismo vehículo")
language.Add("npcpassengers.ui.other_vehicle", "Otro vehículo")
language.Add("npcpassengers.ui.hidden", "Oculto")
language.Add("npcpassengers.ui.visible", "Visible")
language.Add("npcpassengers.ui.health_format", "Salud %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Actualizar lista de pasajeros")
language.Add("npcpassengers.ui.copy_list", "Copiar lista visible de pasajeros")
language.Add("npcpassengers.ui.make_exit", "Hacer que los pasajeros del vehículo actual salgan")
language.Add("npcpassengers.ui.reset_pos", "Restablecer posición y ángulos")
language.Add("npcpassengers.ui.crash_reactions", "Reacciones a accidentes")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Sonidos de abordaje/salida")
language.Add("npcpassengers.section.ambient_sounds", "Sonidos ambientales")
language.Add("npcpassengers.section.gesture_animations", "Animaciones de gestos")
language.Add("npcpassengers.section.threat_awareness", "Conciencia de amenazas")
language.Add("npcpassengers.section.emotional_states", "Estados emocionales")
language.Add("npcpassengers.section.turret_control", "Control de torreta (Experimental)")
language.Add("npcpassengers.section.turret_blacklist", "Lista negra de torreta de NPC")
language.Add("npcpassengers.section.idle_chatter", "Charla inactiva")
language.Add("npcpassengers.section.body_physics", "Física del cuerpo")
language.Add("npcpassengers.section.npc_auto_driver", "Conductor automático de NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Abajo izquierda")
language.Add("npcpassengers.hud.bottom_right", "Abajo derecha")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Activar HUD de pasajeros")
language.Add("npcpassengers.ui.cover_face", "Cubrir cara")
language.Add("npcpassengers.ui.apply_keybinds", "Aplicar atajos recomendados")
language.Add("npcpassengers.ui.clear_keybinds", "Borrar todos los atajos")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Probar gesto de encogimiento")
language.Add("npcpassengers.ui.test_random", "Probar gesto aleatorio")
language.Add("npcpassengers.ui.reset_states", "Restablecer todos los estados")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Activar todas las opciones del menú contextual")
language.Add("npcpassengers.ui.hide_context", "Ocultar todas las opciones del menú contextual")
language.Add("npcpassengers.ui.set_compact", "Establecer tamaño de panel compacto")
language.Add("npcpassengers.ui.set_default", "Establecer tamaño de panel predeterminado")
language.Add("npcpassengers.ui.set_large", "Establecer tamaño de panel grande")
language.Add("npcpassengers.ui.center_panel", "Centrar panel ahora")
language.Add("npcpassengers.ui.reset_ui", "Restablecer toda la configuración de UI a predeterminado")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Ciudadano (F)")
language.Add("npcpassengers.role.citizen_male", "Ciudadano (M)")
language.Add("npcpassengers.role.medic", "Médico")
language.Add("npcpassengers.role.rebel", "Rebelde")
language.Add("npcpassengers.role.passenger", "Pasajero")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Mostrar solo cuando en vehículo")
language.Add("npcpassengers.hud.show_calm", "Mostrar pasajeros calmados")
language.Add("npcpassengers.hud.show_hints", "Mostrar sugerencias contextuales")
language.Add("npcpassengers.hud.show_target_debug", "Mostrar depuración de objetivo")
language.Add("npcpassengers.hud.play_cues", "Reproducir señales de éxito/fracaso")
language.Add("npcpassengers.debug.enable_mode", "Activar modo de depuración")
language.Add("npcpassengers.ui.enable_sounds", "Activar sonidos de UI")
language.Add("npcpassengers.ui.hover_sounds", "Sonidos de botón al pasar")
language.Add("npcpassengers.ui.click_sounds", "Sonidos de botón al hacer clic")
language.Add("npcpassengers.ui.enable_animations", "Activar animaciones de UI")
language.Add("npcpassengers.ui.show_tooltips", "Mostrar descripciones emergentes")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Ocultar automáticamente la barra de desplazamiento")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Suavidad de desplazamiento de barra lateral")
language.Add("npcpassengers.ui.color_theme", "Tema de color")
language.Add("npcpassengers.ui.font_scale", "Escala de fuente")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Cancelar selección de NPC")
language.Add("npcpassengers.context.remove_passenger", "Eliminar pasajero")
language.Add("npcpassengers.context.blacklist_passenger", "Poner en lista negra")
language.Add("npcpassengers.context.whitelist_passenger", "Poner en lista blanca")
language.Add("npcpassengers.context.taxi_passenger", "Asignar como pasajero de taxi")

-- Tool labels
language.Add("tool.npcpassengers_taxi_station.name", "Estación de taxi")
language.Add("tool.npcpassengers_taxi_station.desc", "Crear una estación de taxi para el sistema de taxi NPC")
language.Add("tool.npcpassengers_taxi_station.0", "Clic izquierdo para colocar una estación de taxi. Clic derecho para eliminar.")
language.Add("tool.npcpassengers_taxi_station.left", "Colocar estación")
language.Add("tool.npcpassengers_taxi_station.right", "Eliminar estación")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Atajos")
language.Add("npcpassengers.keybinds.desc", "Configura atajos de teclado para acciones rápidas.")
language.Add("npcpassengers.keybind.attach", "Abordar NPC más cercano")
language.Add("npcpassengers.keybind.attach.help", "Aborda el NPC amigable más cercano a tu vehículo.")
language.Add("npcpassengers.keybind.detach_all", "Desconectar todos los NPC")
language.Add("npcpassengers.keybind.detach_all.help", "Elimina todos los pasajeros de tu vehículo.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Alternar unión automática")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Activa/desactiva rápidamente la unión automática.")
language.Add("npcpassengers.keybind.menu", "Abrir menú de configuración")
language.Add("npcpassengers.keybind.menu.help", "Abre el panel de configuración.")
language.Add("npcpassengers.keybind.exit_all", "Salida de todos los pasajeros")
language.Add("npcpassengers.keybind.exit_all.help", "Haz que todos los pasajeros abandonen el vehículo.")
language.Add("npcpassengers.keybind.toggle_hud", "Alternar HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Muestra/oculta el HUD de pasajeros.")
language.Add("npcpassengers.keybind.quick_attach", "Modo de abordaje rápido")
language.Add("npcpassengers.keybind.quick_attach.help", "Mantén presionado para abordar rápidamente los NPC que estás mirando")
language.Add("npcpassengers.keybind.hold_fire", "NPC mantienen fuego")
language.Add("npcpassengers.keybind.hold_fire.help", "Decir a los artilleros NPC que dejen de disparar")
language.Add("npcpassengers.keybind.open_fire", "NPC abren fuego")
language.Add("npcpassengers.keybind.open_fire.help", "Decir a los artilleros NPC que ataquen objetivos")
language.Add("npcpassengers.keybind.cycle_view", "Ciclo de vista de pasajeros")
language.Add("npcpassengers.keybind.cycle_view.help", "Cambiar cíclicamente la cámara entre pasajeros")
language.Add("npcassengers.keybind.cycle_hud_position", "Ciclo de posición de HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Mover el HUD de pasajeros a las cuatro esquinas")
language.Add("npcpassengers.keybind.toggle_debug", "Alternar depuración de objetivo")
language.Add("npcpassengers.keybind.toggle_debug.help", "Alternar la superposición de depuración de objetivo pequeña")
language.Add("npcpassengers.keybind.test_gesture", "Probar gesto aleatorio")
language.Add("npcpassengers.keybind.test_gesture.help", "Reproducir un gesto aleatorio en el pasajero más cercano")
language.Add("npcpassengers.keybind.reset_all", "Restablecer todos los NPC")
language.Add("npcpassengers.keybind.reset_all.help", "Restablecer estados de animación para todos los pasajeros")

-- HUD Settings
language.Add("npcpassengers.hud.header", "Configuración de HUD")
language.Add("npcpassengers.hud.enable", "Activar HUD")
language.Add("npcpassengers.hud.enable.help", "Muestra la superposición de estado de pasajeros en la pantalla.")
language.Add("npcpassengers.hud.position", "Posición de HUD")
language.Add("npcpassengers.hud.position.help", "Dónde aparece el HUD en la pantalla.")
language.Add("npcpassengers.hud.position.topleft", "Arriba izquierda")
language.Add("npcpassengers.hud.position.topright", "Arriba derecha")
language.Add("npcpassengers.hud.position.bottomleft", "Abajo izquierda")
language.Add("npcpassengers.hud.position.bottomright", "Abajo derecha")
language.Add("npcpassengers.hud.scale", "Escala de HUD")
language.Add("npcpassengers.hud.scale.help", "Multiplicador de tamaño para el HUD.")
language.Add("npcpassengers.hud.opacity", "Opacidad de HUD")
language.Add("npcpassengers.hud.opacity.help", "Transparencia del fondo (0 = invisible, 1 = sólido).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Conductor NPC")
language.Add("npcpassengers.driver.desc", "Permite que los NPC conduzcan vehículos por ti.")
language.Add("npcpassengers.driver.enable", "Activar conductores NPC")
language.Add("npcpassengers.driver.enable.help", "Permite que los NPC tomen el control del vehículo.")
language.Add("npcpassengers.driver.behavior", "Comportamiento de conducción")
language.Add("npcpassengers.driver.behavior.help", "Cómo conduce el NPC el vehículo.")
language.Add("npcpassengers.driver.behavior.cruise", "Crucero aleatorio")
language.Add("npcpassengers.driver.behavior.follow", "Seguir jugador")
language.Add("npcpassengers.driver.behavior.patrol", "Patrulla")
language.Add("npcpassengers.driver.behavior.flee", "Huir")
language.Add("npcpassengers.driver.behavior.parked", "Permanecer estacionado")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Preguntas frecuentes")
language.Add("npcpassengers.help.desc", "Respuestas rápidas a preguntas comunes y solución de problemas.")
language.Add("npcpassengers.help.still_need", "¿Aún necesitas ayuda?")
language.Add("npcpassengers.help.community", "¡Únete a nuestra comunidad de Discord para obtener ayuda!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Tanque/LVS")
language.Add("npcpassengers.nav.debugging", "Depuración")
language.Add("npcpassengers.nav.driver", "Conductor NPC")
language.Add("npcpassengers.nav.interface", "Interfaz")
language.Add("npcpassengers.nav.simulate", "Simular")
language.Add("npcpassengers.nav.modules", "Módulos")
language.Add("npcpassengers.nav.about", "Acerca de")
language.Add("npcpassengers.search.placeholder", "Buscar configuración...")

-- About page
language.Add("npcpassengers.about.description", "Sistema de pasajeros avanzado con IA emocional y física realista")
language.Add("npcpassengers.about.feature_status", "Sistema de estado: CALMA / ALERTA / MIEDO / SOMNOLENCIA / MUERTE")
language.Add("npcpassengers.about.feature_performance", "Rendimiento: caché de asientos, temporizadores limitados, ganchos de cliente optimizados")
language.Add("npcpassengers.about.feature_filtering", "Filtrado de vehículos, enfriamiento de reintentos de abordaje, unión automática solo de escuadrones")
language.Add("npcpassengers.about.actions", "Acciones")
language.Add("npcpassengers.about.show_welcome", "Mostrar pantalla de bienvenida")
language.Add("npcpassengers.about.open_github", "Abrir página de GitHub")
language.Add("npcpassengers.about.reset_settings", "Restablecer TODA la configuración a predeterminados")

-- Status messages
language.Add("npcpassengers.status.calm", "CALMA")
language.Add("npcpassengers.status.alert", "ALERTA")
language.Add("npcpassengers.status.scared", "MIEDO")
language.Add("npcpassengers.status.drowsy", "SOMNOLENCIA")
language.Add("npcpassengers.status.dead", "MUERTE")
language.Add("npcpassengers.status.calm.desc", "Relajado, sin amenazas cercanas")
language.Add("npcpassengers.status.alert.desc", "Enemigo detectado, NPC rastreando amenazas")
language.Add("npcpassengers.status.scared.desc", "Conducción peligrosa (alta velocidad, accidentes)")
language.Add("npcpassengers.status.drowsy.desc", "Viaje tranquilo largo, NPC se vuelve somnoliento")
language.Add("npcpassengers.status.dead.desc", "Salud alcanzó cero")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Unión automática: ON")
language.Add("npcpassengers.chat.autojoin_off", "Unión automática: OFF")
language.Add("npcpassengers.chat.hud_on", "HUD: ON")
language.Add("npcpassengers.chat.hud_off", "HUD: OFF")
language.Add("npcpassengers.chat.prefix", "[Better NPC Passengers]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Sin vehículo cercano")
language.Add("npcpassengers.error.no_npc", "Sin NPC cercano")
language.Add("npcpassengers.error.vehicle_full", "Vehículo lleno")
language.Add("npcpassengers.error.too_far", "NPC demasiado lejos del vehículo")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Cambiar idioma")
language.Add("npcpassengers.tooltip.minimize", "Minimizar panel")
language.Add("npcpassengers.tooltip.expand", "Expandir panel")
language.Add("npcpassengers.tooltip.welcome", "Mostrar pantalla de bienvenida")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Interruptor maestro para toda la voz de NPC. Desactívalo para silenciar completamente a los pasajeros.")
language.Add("npcpassengers.speech_volume.help", "Qué tan fuerte hablan los NPC (0 = silencio, 100 = volumen completo).")
language.Add("npcpassengers.pitch_variation.help", "Variación aleatoria de tono para voces más naturales. 0 = monótono, más alto = más variedad.")
language.Add("npcpassengers.crash_enable.help", "Los NPC gimotean/gritan cuando el vehículo desacelera bruscamente (accidentes, frenado brusco).")
language.Add("npcpassengers.crash_threshold.help", "Desaceleración necesaria para activar sonidos de accidentes. Más bajo = más sensible.")
language.Add("npcpassengers.crash_cooldown.help", "Segundos mínimos entre sonidos de accidentes por NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "Los NPC ocasionalmente hablan mientras viajan: comentarios, preguntas, observaciones.")
language.Add("npcpassengers.speech_idle_chance.help", "Probabilidad de charla por verificación. 0 = nunca, 1 = siempre intenta hablar.")
language.Add("npcpassengers.speech_idle_interval.help", "Segundos mínimos entre intentos de charla.")
language.Add("npcpassengers.speech_board.help", "Los NPC hablan cuando entran y salen del vehículo.")
language.Add("npcpassengers.ambient_sounds.help", "Toses ocasionales, suspiros, murmullos: sonidos de vida de fondo.")
language.Add("npcpassengers.ambient_interval.help", "Segundos promedio entre sonidos ambientales.")
language.Add("npcpassengers.animation.help", "Ajuste fino de animaciones de NPC y movimiento de cabeza.")
language.Add("npcpassengers.head_look.help", "Los NPC miran naturalmente alrededor, al jugador, por las ventanas, etc.")
language.Add("npcpassengers.head_smooth.help", "Qué tan suavemente se mueve la cabeza. Más bajo = más rápido, más alto = más flotante.")
language.Add("npcpassengers.blink.help", "Los NPC parpadean de manera realista mientras están sentados.")
language.Add("npcpassengers.breathing.help", "Animación de respiración sutil en las cabezas de los NPC.")
language.Add("npcpassengers.walk_timeout.help", "Segundos antes de que el NPC renuncie a caminar hacia el vehículo.")
language.Add("npcpassengers.realism.help", "Reacciones basadas en física y sistemas de conciencia para máxima inmersión.")
language.Add("npcpassengers.talking_gestures.help", "Los NPC reproducen aleatoriamente gestos con las manos y animaciones corporales mientras viajan.")
language.Add("npcpassengers.gesture_chance.help", "Porcentaje de probabilidad de reproducir un gesto cada intervalo.")
language.Add("npcpassengers.gesture_interval.help", "Segundos entre verificaciones de oportunidad de gestos.")
language.Add("npcpassengers.crash_flinch.help", "Los NPC se encogen y se inclinan hacia adelante cuando el vehículo choca o frena bruscamente.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Cambio de velocidad necesario para activar el encogimiento (más bajo = más sensible).")
language.Add("npcpassengers.body_sway.help", "Los NPC se inclinan en giros, se apoyan durante la aceleración/frenado.")
language.Add("npcpassengers.body_sway_amount.help", "Qué tanto se balancean los NPC con el movimiento del vehículo.")
language.Add("npcpassengers.threat_awareness.help", "Los NPC miran automáticamente hacia los enemigos cercanos.")
language.Add("npcpassengers.threat_range.help", "Qué tan lejos pueden detectar amenazas los NPC para el seguimiento de cabeza.")
language.Add("npcpassengers.combat_alert.help", "Los NPC se vuelven tensos y reactivos cuando los enemigos están cerca.")
language.Add("npcpassengers.passenger_combat.help", "Desactivado de forma predeterminada. Actívalo para permitir que los pasajeros armados disparen desde dentro del vehículo.")
language.Add("npcpassengers.passenger_combat_range.help", "Qué tan lejos pueden adquirir objetivos los pasajeros armados.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Valores más altos reducen la dispersión de disparos para pasajeros armados.")
language.Add("npcpassengers.passenger_combat_damage.help", "Escala el daño infligido por disparos de pasajeros.")
language.Add("npcpassengers.passenger_interaction.help", "Múltiples pasajeros se miran y ocasionalmente charlan entre sí.")
language.Add("npcpassengers.fear_reactions.help", "Los NPC tienen miedo de la conducción peligrosa: ojos abiertos, sonidos de pánico.")
language.Add("npcpassengers.fear_speed_threshold.help", "Velocidad (unidades/seg) a la que los NPC empiezan a nervios.")
language.Add("npcpassengers.drowsiness.help", "Los NPC se vuelven somnolientos en viajes tranquilos largos: parpadeos lentos, asentir con la cabeza.")
language.Add("npcpassengers.drowsy_time.help", "Segundos de viaje tranquilo antes de que empiece la somnolencia.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Configuración para tanques, APC y vehículos LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Hace que los pasajeros NPC sean invisibles cuando están dentro de tanques y APC.")
language.Add("npcpassengers.eject_stuck_check.help", "Expulsa automáticamente a los NPC del vehículo cuando se atascan durante la expulsión. Evita que los NPC se metan en el vehículo al salir.")
language.Add("npcpassengers.detach_no_collide.help", "Después de desconectar, los NPC pasan temporalmente a través del vehículo para que puedan alejarse sin clipping o atascarse.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Cuánto tiempo ignoran los NPC la colisión del vehículo después de desconectar.")
language.Add("npcpassengers.die_with_vehicle.help", "Los pasajeros NPC mueren cuando su vehículo es destruido por explosión o fuego (más inmersivo que si salieran ilesos de los restos).")
language.Add("npcpassengers.tank_driver.help", "Permite que los NPC en el asiento del conductor conduzcan automáticamente hacia los enemigos.")
language.Add("npcpassengers.tank_driver_range.help", "Rango máximo para que el conductor detecte enemigos.")
language.Add("npcpassengers.tank_driver_distance.help", "Distancia a mantener de los enemigos.")
language.Add("npcpassengers.tank_driver_throttle.help", "Cantidad de acelerador (0.1 = lento, 1 = velocidad completa).")
language.Add("npcpassengers.tank_driver_reverse.help", "Distancia a la que retroceder de los enemigos.")
language.Add("npcpassengers.tank_turret.help", "Permite que los NPC controlen torretas en vehículos LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Muestra el estado de los pasajeros (emociones, alerta) en la pantalla mientras conduces.")
language.Add("npcpassengers.hud_show_calm.help", "Cuando está desactivado, solo muestra pasajeros con estado no calmado.")
language.Add("npcpassengers.hud_thresholds.desc", "Cuando los niveles de emoción exceden estos umbrales, los pasajeros muestran ese estado en el HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Nivel de alerta necesario para mostrar estado 'ALERTA' (amenaza detectada).")
language.Add("npcpassengers.hud_fear_threshold.help", "Nivel de miedo necesario para mostrar estado 'MIEDO' (conducción peligrosa).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Relación de tiempo tranquilo necesaria para mostrar estado 'SOMNOLENCIA' (viaje tranquilo largo).")
language.Add("npcpassengers.hud_actions.desc", "Elige qué acción toman los pasajeros cuando experimentan cada estado emocional.")
language.Add("npcpassengers.hud_actions_note", "Nota: Algunas acciones pueden no ser visibles dependiendo del soporte del modelo de NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Establece atajos personalizados para acciones de pasajeros NPC. Haz clic en un botón y presiona una tecla para vincular.")
language.Add("npcpassengers.keybinds_hud.desc", "Controles rápidos de HUD para mostrar, mover y depurar la superposición de pasajeros.")
language.Add("npcpassengers.keybinds_debug_note", "Los atajos de depuración solo funcionan cuando el modo de depuración está activado.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Herramientas de depuración avanzadas para probar el comportamiento de NPC. Activa primero el modo de depuración en la configuración.")
language.Add("npcpassengers.debug_mode.help", "Muestra botones de prueba de depuración y activa comandos de depuración.")
language.Add("npcpassengers.debug_status.help", "Establece manualmente el estado del pasajero para pruebas. Haz clic en 'Actualizar lista' para ver los pasajeros actuales.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Configura efectos de sonido para botones, casillas de verificación y otros elementos de UI")
language.Add("npcpassengers.ui_sounds_enabled.help", "Interruptor maestro para todos los efectos de sonido de UI")
language.Add("npcpassengers.ui_sounds_volume.help", "Multiplicador de volumen para sonidos de UI (1.0 = normal, 2.0 = doble)")
language.Add("npcpassengers.ui_hover_enabled.help", "Reproducir sonido al pasar el cursor sobre botones")
language.Add("npcpassengers.ui_click_enabled.help", "Reproducir sonido al hacer clic en botones y casillas de verificación")
language.Add("npcpassengers.context_menu.desc", "Elige qué opciones aparecen al hacer clic derecho en NPC")
language.Add("npcpassengers.context_make_passenger.help", "Añadir NPC como pasajero a tu vehículo actual")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Añadir NPC a un vehículo específico (haz clic en NPC, luego vehículo)")
language.Add("npcpassengers.context_detach.help", "Eliminar NPC del vehículo")
language.Add("npcpassengers.ui_show_welcome.help", "Mostrar panel de bienvenida cuando el complemento se actualiza a una nueva versión")
language.Add("npcpassengers.ui_panel_width.help", "Ancho del panel de configuración")
language.Add("npcpassengers.ui_panel_height.help", "Altura del panel de configuración")
language.Add("npcpassengers.ui_animations.help", "Transiciones suaves y efectos de pasar el cursor (puede afectar el rendimiento)")
language.Add("npcpassengers.ui_tooltips.help", "Mostrar descripciones emergentes útiles al pasar el cursor sobre la configuración")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Mostrar la barra de desplazamiento solo mientras te desplazas o pasas el cursor sobre ella.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Nota: El panel se vuelve 70% transparente al arrastrar cualquier control deslizante para ver el contenido en el fondo.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Valores más bajos = más suave pero más lento el desplazamiento (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Elige un tema de color para el panel de configuración. Los cambios se aplican inmediatamente.")
language.Add("npcpassengers.ui_font_scale.help", "Escalar todos los tamaños de fuente de UI. 1.0 = predeterminado, 0.5 = mitad de tamaño, 2.0 = doble tamaño.")

print("[Better NPC Passengers] Spanish localization loaded!")
