-- Better NPC Passengers - Turkish Localization
-- Türkçe yerelleştirme dosyası

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Daha İyi NPC Yolcuları")
language.Add("npcpassengers.settings", "Ayarlar")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Genel")
language.Add("npcpassengers.nav.autojoin", "Otomatik Katılma")
language.Add("npcpassengers.nav.passengers", "Yolcular")
language.Add("npcpassengers.nav.position", "Konum")
language.Add("npcpassengers.nav.behaviour", "Davranış")
language.Add("npcpassengers.nav.keybinds", "Tuş Atamaları")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Sürücü")
language.Add("npcpassengers.nav.help", "Yardım")

-- General Settings
language.Add("npcassengers.general.header", "Genel Ayarlar")
language.Add("npcpassengers.allow_multiple", "Çoklu Yolcuya İzin Ver")
language.Add("npcpassengers.allow_multiple.help", "Aynı araçta birden fazla NPC'nin seyahat etmesine izin verir.")
language.Add("npcpassengers.exit_behavior", "Çıkış Davranışı")
language.Add("npcpassengers.exit_behavior.help", "NPC yolcular araçtan ne zaman inmeli?")
language.Add("npcassengers.exit_mode.leave_player", "Oyuncu çıktığında ayrıl")
language.Add("npcpassengers.exit_mode.leave_attack", "Araç saldırıya uğradığında ayrıl")
language.Add("npcpassengers.exit_mode.never", "Otomatik olarak asla ayrılma")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Zamanlama")
language.Add("npcpassengers.max_attach_dist", "Maksimum Bağlantı Mesafesi")
language.Add("npcpassengers.max_attach_dist.help", "NPC'yi araca bağlamak için maksimum mesafe (birim).")
language.Add("npcpassengers.detach_delay", "Bağlantı Kesme Gecikmesi")
language.Add("npcpassengers.detach_delay.help", "Oyuncu çıktıktan sonra bağlantıyı kesmeden önce beklenen saniye.")
language.Add("npcpassengers.ai_delay", "Yapay Zeka Geri Yükleme Gecikmesi")
language.Add("npcpassengers.ai_delay.help", "Bağlantı kesildikten sonra NPC'nin yapay zekasını geri yüklemeden önce beklenen saniye.")
language.Add("npcpassengers.cooldown", "Soğuma Süresi")
language.Add("npcpassengers.cooldown.help", "Aynı araçta NPC bağlama arasındaki soğuma süresi.")
language.Add("npcpassengers.passenger_limit", "Yolcu Sınırı")
language.Add("npcpassengers.passenger_limit.help", "Araçta izin verilen maksimum NPC sayısı.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Otomatik Katılma (Takım Davranışı)")
language.Add("npcpassengers.autojoin.desc", "Dost NPC'ler araca bindiğinizde otomatik olarak binecekler, tıpkı Half-Life 2'deki takım mekaniği gibi!")
language.Add("npcpassengers.autojoin.enable", "Otomatik Katılmayı Etkinleştir")
language.Add("npcpassengers.autojoin.enable.help", "Yakındaki dost NPC'ler araca bindiğinizde otomatik olarak katılır.")
language.Add("npcpassengers.autojoin.range", "Otomatik Katılma Menzili")
language.Add("npcpassengers.autojoin.range.help", "Otomatik katılma için NPC bulma maksimum mesafesi.")
language.Add("npcpassengers.autojoin.max", "Maksimum Otomatik Katılma NPC Sayısı")
language.Add("npcpassengers.autojoin.max.help", "Aynı anda otomatik olarak katılabilecek maksimum NPC sayısı.")
language.Add("npcpassengers.autojoin.squad_only", "Sadece Takım Üyeleri")
language.Add("npcpassengers.autojoin.squad_only.help", "Sadece takım adına sahip NPC'ler otomatik olarak katılır (HL2 tarzı takımlar için).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Dost NPC'ler araca bindiğinizde otomatik olarak binecekler, tıpkı Half-Life 2'deki takım mekaniği gibi!")
language.Add("npcpassengers.panel.passengers.header", "Yolcu Kontrolü")
language.Add("npcpassengers.panel.passengers.desc", "Aktif yolcuları yönetin, isme/türe/duruma göre filtreleyin, hata ayıklama bilgilerini kopyalayın, koltukları yeniden atayın ve ayarlar panelinden çıkmadan yolcuları ayırın.")
language.Add("npcpassengers.panel.position.desc", "Araçlardaki NPC konumlarını hassas şekilde ayarlayın. Bu özelliği süzülme veya iç içe geçme sorunlarını çözmek için kullanın.")
language.Add("npcpassengers.panel.angle.desc", "Araçlardaki NPC dönüş açılarını ayarlayın.")
language.Add("npcpassengers.panel.speech.desc", "Araçlarda seyahat ederken NPC'lerin nasıl konuştuğunu yapılandırın. HL2 tarzı vatandaş sesleri!")

-- Position Settings
language.Add("npcpassengers.position.header", "Konum Ofsetleri")
language.Add("npcpassengers.position.desc", "Araçlardaki NPC konumlarını hassas şekilde ayarlayın. Bu özelliği süzülme veya iç içe geçme sorunlarını çözmek için kullanın.")
language.Add("npcpassengers.height_offset", "Yükseklik Ofseti")
language.Add("npcpassengers.forward_offset", "İleri Ofseti")
language.Add("npcpassengers.right_offset", "Sağ Ofseti")
language.Add("npcpassengers.angle.header", "Açı Ofsetleri")
language.Add("npcpassengers.angle.desc", "Araçlardaki NPC dönüş açılarını ayarlayın.")
language.Add("npcpassengers.yaw_offset", "Yunuslama (Dönüş)")
language.Add("npcpassengers.pitch_offset", "Eğim (Öne Eğilme)")
language.Add("npcpassengers.roll_offset", "Yuvarlanma (Yana Eğilme)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "NPC Konuşması (Gelişmiş)")
language.Add("npcpassengers.behaviour.desc", "Araçlarda seyahat ederken NPC'lerin nasıl konuştuğunu yapılandırın. HL2 tarzı vatandaş sesleri!")
language.Add("npcpassengers.speech_enable", "NPC Konuşmasını Etkinleştir")
language.Add("npcpassengers.speech_enable.help", "Tüm NPC konuşması için ana anahtar. Yolcuları tamamen susturmak için devre dışı bırakın.")
language.Add("npcpassengers.speech_volume", "Konuşma Ses Seviyesi")
language.Add("npcpassengers.speech_volume.help", "NPC seslerinin ne kadar yüksek olduğu (0 = sessiz, 100 = tam ses).")
language.Add("npcpassengers.pitch_variation", "Perde Değişimi (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Daha doğal sesler için rastgele perde değişimi. 0 = tek tip, daha yüksek = daha fazla çeşitlilik.")
language.Add("npcpassengers.crash.header", "Çarpışma Tepkileri")
language.Add("npcpassengers.crash_enable", "Çarpışma Seslerini Etkinleştir")
language.Add("npcpassengers.crash_enable.help", "Araç keskin bir şekilde yavaşladığında NPC'ler inleyerek/cegirerek tepki verir (çarpışmalar, sert frenleme).")
language.Add("npcpassengers.crash_threshold", "Çarpışma Hassasiyeti")
language.Add("npcpassengers.crash_threshold.help", "Çarpışma seslerini tetiklemek için gerekli yavaşlama. Daha düşük = daha hassas.")
language.Add("npcpassengers.crash_cooldown", "Çarpışma Sesi Soğuması")
language.Add("npcpassengers.crash_cooldown.help", "Her NPC için çarpışma sesleri arasındaki minimum saniye.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Boş Konuşmayı Etkinleştir")
language.Add("npcpassengers.speech_board", "Biniş/İniş Seslerini Etkinleştir")
language.Add("npcpassengers.ambient_sounds", "Ortam Seslerini Etkinleştir")
language.Add("npcpassengers.head_look", "Kafa/Göz Bakışını Etkinleştir")
language.Add("npcpassengers.blink", "Göz Kırpmayı Etkinleştir")
language.Add("npcpassengers.breathing", "Nefes Almayı Etkinleştir")
language.Add("npcpassengers.talking_gestures", "Konuşma Hareketlerini Etkinleştir")
language.Add("npcpassengers.crash_flinch", "Çarpışma Kıvrılmasını Etkinleştir")
language.Add("npcpassengers.body_sway", "Gövde Sallanmasını Etkinleştir")
language.Add("npcpassengers.threat_awareness", "Tehlike Farkındalığını Etkinleştir")
language.Add("npcpassengers.combat_alert", "Savaş Uyarısı")
language.Add("npcpassengers.passenger_combat", "NPC araçlardan ateş eder (Deneysel)")
language.Add("npcpassengers.passenger_interaction", "Yolcu Etkileşimi")
language.Add("npcpassengers.fear_reactions", "Korku Tepkilerini Etkinleştir")
language.Add("npcassengers.drowsiness", "Uykululuğu Etkinleştir")
language.Add("npcpassengers.hide_in_tanks", "Kapalı Araçlarda NPC'leri Gizle")
language.Add("npcpassengers.eject_stuck_check", "Sıkışmış NPC'leri Otomatik Çıkar")
language.Add("npcpassengers.detach_no_collide", "Bağlantı Kesildikten Sonra Araçla Çarpışma Yok")
language.Add("npcpassengers.die_with_vehicle", "Araç Patladığında Yolcuları Öldür")
language.Add("npcpassengers.driver_enabled", "Otomatik Sürüşü Etkinleştir")
language.Add("npcpassengers.turret_enabled", "Taret Kontrolünü Etkinleştir")
language.Add("npcpassengers.turret_lead_targets", "Hedefleri Tahmin Et")
language.Add("npcpassengers.turret_friendly_fire", "Dost Ateşine İzin Ver")
language.Add("npcpassengers.turret_hold_fire", "Ateşi Tut (Ateş Etmeyi Devre Dışı Bırak)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Konuşma Ses Seviyesi")
language.Add("npcpassengers.pitch_variation", "Perde Değişimi (+/-)")
language.Add("npcpassengers.crash_threshold", "Çarpışma Hassasiyeti")
language.Add("npcpassengers.crash_cooldown", "Çarpışma Sesi Soğuması")
language.Add("npcpassengers.speech_idle_chance", "Konuşma Olasılığı")
language.Add("npcpassengers.speech_idle_interval", "Konuşma Aralığı")
language.Add("npcpassengers.ambient_interval", "Ortam Sesi Aralığı")
language.Add("npcpassengers.head_smooth", "Kafa Yumuşaklığı")
language.Add("npcpassengers.walk_timeout", "Yürüme Zaman Aşımı")
language.Add("npcpassengers.gesture_chance", "Hareket Olasılığı (%)")
language.Add("npcpassengers.gesture_interval", "Hareket Aralığı")
language.Add("npcpassengers.crash_threshold_flinch", "Çarpışma Hassasiyeti")
language.Add("npcassengers.body_sway_amount", "Sallanma Yoğunluğu")
language.Add("npcpassengers.threat_range", "Tehdit Algılama Menzili")
language.Add("npcpassengers.passenger_combat_range", "Yolcu Savaş Menzili")
language.Add("npcpassengers.passenger_combat_accuracy", "Yolcu Doğruluğu")
language.Add("npcpassengers.passenger_combat_damage", "Yolcu Hasar Çarpanı")
language.Add("npcpassengers.fear_speed_threshold", "Korku Hız Eşiği")
language.Add("npcpassengers.drowsy_time", "Uykululuk Süresi")
language.Add("npcpassengers.detach_no_collide_duration", "Çarpışmasız Süre (saniye)")
language.Add("npcpassengers.tank_driver_range", "Algılama Menzili")
language.Add("npcpassengers.tank_driver_engage_distance", "Çatışma Mesafesi")
language.Add("npcpassengers.tank_driver_speed", "Sürüş Hızı")
language.Add("npcpassengers.tank_driver_reverse_distance", "Geri Mesafesi")
language.Add("npcpassengers.turret_range", "Hedef Menzili")
language.Add("npcpassengers.turret_accuracy", "Doğruluk")
language.Add("npcpassengers.turret_reaction_time", "Tepki Süresi")
language.Add("npcpassengers.turret_fire_delay", "Ateş Gecikmesi")
language.Add("npcpassengers.turret_aim_speed", "Nişan Alma Hızı")
language.Add("npcpassengers.hud_scale", "HUD Ölçeği")
language.Add("npcpassengers.hud_opacity", "HUD Opaklığı")
language.Add("npcpassengers.hud_alert_threshold", "Uyarı Eşiği")
language.Add("npcpassengers.hud_fear_threshold", "Korku Eşiği")
language.Add("npcpassengers.hud_drowsy_threshold", "Uykululuk Eşiği")
language.Add("npcpassengers.ui_sounds_volume", "UI Ses Seviyesi")
language.Add("npcpassengers.ui_panel_width", "Panel Genişliği")

-- Section headers
language.Add("npcpassengers.section.animation", "Animasyon ve Davranış")
language.Add("npcpassengers.section.realism", "Gelişmiş Gerçekçilik")
language.Add("npcpassengers.section.hud_position", "HUD Konumu ve Stili")
language.Add("npcpassengers.section.emotion_thresholds", "Duygu Eşikleri")
language.Add("npcpassengers.section.emotion_actions", "Duygu Eylemleri")
language.Add("npcpassengers.section.vehicle_control", "Araç Kontrolü")
language.Add("npcpassengers.section.hud_controls", "HUD Kontrolleri")
language.Add("npcpassengers.section.debug_controls", "Hata Ayıklama Kontrolleri")
language.Add("npcassengers.section.passenger_status", "Yolcu Durumu Kontrolü")
language.Add("npcpassengers.section.quick_test", "Hızlı Test Butonları")
language.Add("npcpassengers.section.driver_system", "NPC Sürücü Sistemi")
language.Add("npcpassengers.section.ui_sounds", "UI Ses Ayarları")
language.Add("npcpassengers.section.appearance", "Görünüm")
language.Add("npcpassengers.section.context_menu", "Bağlam Menüsü Seçenekleri")
language.Add("npcpassengers.section.panel_preferences", "Ayarlar Paneli Tercihleri")
language.Add("npcpassengers.section.performance", "Performans ve Teknik")
language.Add("npcpassengers.section.simulation", "Simülasyon Sistemi")
language.Add("npcpassengers.section.modules", "Modül Sistemi")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Koltuk Ata")
language.Add("npcpassengers.btn.detach", "Ayır")
language.Add("npcpassengers.btn.copy_summary", "Özeti Kopyala")
language.Add("npcpassengers.btn.copy_debug", "Hata Ayıklamayı Kopyala")
language.Add("npcpassengers.btn.enable_all_speech", "Tüm Konuşmayı Etkinleştir")
language.Add("npcpassengers.btn.disable_all_speech", "Tüm Konuşmayı Devre Dışı Bırak")
language.Add("npcpassengers.btn.show_current_vehicle", "Sadece Mevcut Aracı Göster")
language.Add("npcpassengers.btn.auto_refresh", "Görünür Liste Otomatik Yenileme")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Mevcut araç algılanmadı. Bir araca binin veya mevcut araç filtresini devre dışı bırakın.")
language.Add("npcpassengers.status.no_match_filter", "Filtrenizle eşleşen yolcu yok. İsim, sınıf, koltuk numarası, durum veya araç sınıfı ile deneyin.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Mevcut aracınızda yolcu bulunamadı.")
language.Add("npcpassengers.status.no_passengers", "Yolcu bulunamadı. NPC'lerin buradan yönetilebilmesi için araçta seyahat ediyor olmaları gerekir.")
language.Add("npcpassengers.status.all_passengers", "Tüm yolcular")
language.Add("npcpassengers.status.current_vehicle_only", "Sadece mevcut araç")
language.Add("npcpassengers.status.ctrl_f_search", "Aramaya odaklanmak için Ctrl+F")
language.Add("npcengers.status.no_matches", "Eşleşen ayar yok")
language.Add("npcpassengers.status.showing_matches", "%d eşleşmeden %d tanesi gösteriliyor")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Ayarları Aç")
language.Add("npcpassengers.menu.reset_all", "Tüm Ayarları Sıfırla")

-- Button states
language.Add("npcpassengers.state.on", "AÇIK")
language.Add("npcpassengers.state.off", "KAPALI")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Otomatik Katılma")
language.Add("npcpassengers.chat.hud_status", "Yolcu HUD'ı")
language.Add("npcpassengers.chat.hud_position", "HUD Konumu")
language.Add("npcpassengers.chat.target_debug", "Hedef Hata Ayıklaması")
language.Add("npcpassengers.chat.turret_gunners", "Taret Nişancıları")
language.Add("npcpassengers.chat.turret_holding", "ATEŞ TUTUYOR")
language.Add("npcpassengers.chat.turret_fire", "ATEŞ AÇILIYOR")
language.Add("npcpassengers.chat.unknown", "Bilinmiyor")
language.Add("npcpassengers.chat.nothing_copy", "Kopyalanacak bir şey yok.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Bu sürümde panoya erişim kullanılamıyor.")
language.Add("npcpassengers.chat.copied_clipboard", "Panoya kopyalandı.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Bu yolcuyu yeniden atamak için aynı araca binin.")
language.Add("npcpassengers.chat.no_visible_passengers", "Kopyalanacak görünür yolcu yok.")
language.Add("npcpassengers.chat.need_vehicle", "Bunu kullanmak için bir araçta olmanız gerekir.")
language.Add("npcpassengers.chat.keybinds_applied", "Önerilen tuş atamaları uygulandı.")
language.Add("npcpassengers.chat.keybinds_cleared", "Tüm tuş atamaları temizlendi.")
language.Add("npcpassengers.chat.context_enabled", "Tüm bağlam menüsü seçenekleri etkinleştirildi.")
language.Add("npcpassengers.chat.context_hidden", "Tüm bağlam menüsü seçenekleri gizlendi.")
language.Add("npcpassengers.chat.panel_compact", "Panel boyutu kompakt olarak ayarlandı.")
language.Add("npcpassengers.chat.panel_default", "Panel boyutu varsayılan olarak ayarlandı.")
language.Add("npcpassengers.chat.panel_large", "Panel boyutu büyük olarak ayarlandı.")
language.Add("npcpassengers.chat.panel_centered", "Panel ortalandı.")
language.Add("npcpassengers.chat.settings_reset", "Tüm UI ayarları varsayılan değerlere sıfırlandı!")
language.Add("npcpassengers.chat.npc_selected", "NPC seçildi! Şimdi bir araca sağ tıklayın ve 'Seçilen NPC'yi Ekle'yi seçin")
language.Add("npcpassengers.chat.adding_npc", "NPC araca ekleniyor...")
language.Add("npcpassengers.chat.selection_cancelled", "NPC seçimi iptal edildi")
language.Add("npcassengers.chat.summary_copied", "Yolcu özeti kopyalandı.")
language.Add("npcpassengers.chat.debug_copied", "Yolcu hata ayıklama bilgisi kopyalandı.")
language.Add("npcpassengers.chat.no_passengers_found", "Yolcu bulunamadı. NPC'lerin araçta olması gerekir.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Durum yoğunluğu %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Yolcuları filtrele...")
language.Add("npcpassengers.ui.press_key", "Bir tuşa basın...")
language.Add("npcpassengers.ui.work_in_progress", "Geliştiriliyor")
language.Add("npcpassengers.ui.under_development", "Bu özellik şu anda geliştirilmektedir")
language.Add("npcpassengers.ui.check_back_later", "Gelecekteki bir güncellemede tekrar kontrol edin!")
language.Add("npcpassengers.ui.search_desc_passengers", "Aktif yolcuları isme, sınıfa, koltuğa, duruma veya araca göre filtreleyin.")
language.Add("npcpassengers.ui.search_desc_sort", "Görünür yolcu listesini araca, isme, koltuğa, sağlığa veya duruma göre sıralayın.")
language.Add("npcpassengers.ui.search_label_filter", "Yolcu Filtresi")
language.Add("npcpassengers.ui.search_label_sort", "Yolcu Sırası")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "NPC'yi araca nasıl eklerim?")
language.Add("npcpassengers.faq.add_npc.answer", "Bağlam menüsünü (NPC'ye sağ tıklayın) kullanın ve 'Yolcu Yap'ı seçin. Veya 'En Yakın NPC'yi Bağla' tuş atamasını kullanın. NPC'lerin sizinle dost olması gerekir.")
language.Add("npcpassengers.faq.remove_npc", "Araçtaki yolcuları nasıl kaldırırım?")
language.Add("npcpassengers.faq.remove_npc.answer", "Ayarlar panelindeki Yolcular sekmesine gidin, yolcuyu seçin ve Ayır'a tıklayın. Veya 'Tüm Yolcuları Ayır' tuş atamasını kullanın.")
language.Add("npcpassengers.faq.position", "NPC'ler süzülüyor/koltukların içinden geçiyor!")
language.Add("npcpassengers.faq.position.answer", "Konum sekmesine gidin ve Yükseklik/İleri/Sağ ofsetlerini ayarlayın. Her araç modeli farklıdır, bu yüzden bu değerleri ayarlamanız gerekebilir. Gerçek zamanlı konumları test etmek için hata ayıklama panelini kullanın.")
language.Add("npcpassengers.faq.speech", "NPC'ler konuşmuyor!")
language.Add("npcpassengers.faq.speech.answer", "Davranış sekmesini kontrol edin ve 'NPC Konuşmasını Etkinleştir'in etkin olduğunu doğrulayın. Ayrıca Konuşma Ses Seviyesinin 0'ın üzerinde olduğunu doğrulayın. Bazı NPC modellerinin kullanılabilir ses satırları olmayabilir.")
language.Add("npcpassengers.faq.autojoin", "Otomatik Katılma nasıl çalışır?")
language.Add("npcpassengers.faq.autojoin.answer", "Otomatik Katılma sekmesinde etkinleştirildiğinde, dost NPC'ler araca bindiğinizde otomatik olarak binecekler, tıpkı Half-Life 2'deki takım mekaniği gibi! Algılama menzilini ve kaç NPC'nin otomatik olarak katılabileceğini ayarlayabilirsiniz.")
language.Add("npcassengers.faq.death", "Yolcular öldüğünde ne olur?")
language.Add("npcpassengers.faq.death.answer", "Ölü yolcular kırmızı bir parlama efekti gösterecek ve HUD'da bir kafatası ikonu gösterecek. Aracınızın yaklaşın ve gövdelerini kaldırmak için R tuşuna basılı tutun. Gövdeler fizik ile çıkarılacak.")
language.Add("npcpassengers.faq.status", "Yolcu durumları ne anlama geliyor?")
language.Add("npcpassengers.faq.status.answer", "SAKİN: Rahat, yakın tehdit yok. UYARI: Düşman tespit edildi. KORKAK: Tehlikeli sürüş. UYKULU: Uzun ve sakin yolculuk. ÖLÜ: Sağlık sıfıra ulaştı.")
language.Add("npcpassengers.faq.keybinds", "Tuş atamalarım çalışmıyor!")
language.Add("npcpassengers.faq.keybinds.answer", "Tuş Atamaları sekmesine gidin ve gerçekten tuş atamalarını ayarladığınızdan emin olun (varsayılan olarak atanmamışlar). Her eylemin yanındaki butona tıklayın ve istediğiniz tuşa basın. Atamayı kaldırmak için sağ tıklayın.")
language.Add("npcpassengers.faq.errors", "Eklenti hiç çalışmıyor / Hatalar alıyorum!")
language.Add("npcpassengers.faq.errors.answer", "Garry's Mod'un en son sürümünü çalıştırdığınızdan emin olun. Hatalar için konsolu kontrol edin (tilde ~ tuşu). Çakışan eklentileri devre dışı bırakmayı deneyin.")
language.Add("npcpassengers.faq.combat", "Yolcular araçlardan ateş edebilir mi?")
language.Add("npcpassengers.faq.combat.answer", "Şu anda hayır. NPC'ler düşmanları takip edecek ve tehditlere tepki verecek, ancak otururken silah ateş etmeyecekler. Bu özellik gelecekteki güncellemelerde eklenebilir.")
language.Add("npcpassengers.faq.stop_autojoin", "NPC'lerin otomatik katılmasını nasıl durdururum?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Otomatik Katılma sekmesindeki 'Otomatik Katılmayı Etkinleştir' kutusunu devre dışı bırakın veya 'Otomatik Katılmayı Değiştir' tuş atamasını kullanın.")
language.Add("npcpassengers.faq.settings", "Ayarlar nerede saklanıyor?")
language.Add("npcpassengers.faq.settings.answer", "Tüm ayarlar GMod yapılandırmanızdaki ConVar olarak saklanır. Oturumlar arasında kalır ve istemcinize özgüdür.")
language.Add("npcpassengers.faq.vehicles", "Bu tüm araçlarla çalışır mı?")
language.Add("npcassengers.faq.vehicles.answer", "Fiziği olan çoğu araçla çalışır. Tanklar, APC'ler, arabalar, botlar vb. Bazı modlu araçlar konum ayarları gerektirebilir.")
language.Add("npcpassengers.faq.multiple", "Bir araçta birden fazla NPC olabilir mi?")
language.Add("npcpassengers.faq.multiple.answer", "Evet! Genel ayarlarda 'Yolcu Sınırı'nı ayarlayın. Eklenti NPC'leri araç etrafında otomatik olarak dağıtacaktır. Belirli koltuk konumları için Konum sekmesindeki ofsetleri ayarlayın.")
language.Add("npcpassengers.faq.crashes", "Çarpışmalardan sonra NPC'ler garip davranıyor!")
language.Add("npcpassengers.faq.crashes.answer", "Bu normal - tehlikeli sürüşe korku ile tepki verirler. Daha az tepkili olmalarını istiyorsanız HUD ayarlarındaki Korku Eşiğini düşürün.")
language.Add("npcpassengers.faq.reset_setting", "Sadece bir ayarı nasıl sıfırlarım?")
language.Add("npcpassengers.faq.reset_setting.answer", "Bu belirli ayar için konsol komutunu kullanın. Tüm komutlar 'nai_npc_' ile başlar. Kullanılabilir tüm komutları görmek için konsola 'find nai_npc' yazın.")
language.Add("npcpassengers.faq.multiplayer", "Bu çok oyunculu modda çalışır mı?")
language.Add("npcpassengers.faq.multiplayer.answer", "Evet! Eklenti hem tek oyunculu hem de çok oyunculu sunucularda çalışır. Her oyuncu kendi yolcularını kontrol eder.")
language.Add("npcpassengers.faq.lvs", "Bu LVS araçlarıyla çalışır mı?")
language.Add("npcpassengers.faq.lvs.answer", "Evet! Eklenti LVS (Lua Vehicle System) araçları için tam destek sağlar. NPC'ler yolcu olarak binebilir ve NPC Sürücü modu etkinleştirilirse LVS araçlarını sürebilirler.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Bu ayarlar eklentinin kullanıcı arayüzü davranışını kontrol eder")
language.Add("npcpassengers.panel.performance_note1", "Panel boyutu değişiklikleri menüyü kapatıp yeniden açmayı gerektirir")
language.Add("npcpassengers.panel.performance_note2", "Sesleri veya animasyonları devre dışı bırakmak düşük sistemlerde performansı artırabilir")
language.Add("npcpassengers.panel.performance_title", "Arayüz Ayarları Bilgisi")
language.Add("npcpassengers.help.console_title", "Hata Ayıklama İçin Konsol Komutları:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Detaylı bilgi görmek için hata ayıklama modunu etkinleştir")
language.Add("npcpassengers.about.title", "Hakkında")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Merhaba!")
language.Add("npcpassengers.welcome.msg1", "Yolcunun aracın üzerinde oturduğu konusunda şikayet etmeden önce,\nlütfen ayarları açın. Bunu yapabilirsiniz, sana inanıyorum.")
language.Add("npcpassengers.welcome.msg2", "Bu eklenti hala MÜKEMMEL olmaktan çok uzak, lütfen çekinmeden\nhata raporlayın ve yeni özellikler önerin. Tüm yorumlarınızı okuyorum!")
language.Add("npcpassengers.welcome.changelog", "Güncelleme Günlüğü")
language.Add("npcpassengers.welcome.got_it", "Anladım!")
language.Add("npcpassengers.welcome.console_cmd", "Veya konsol komutunu kullanın: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Kara Listeye Alınmış NPC Sınıfları")
language.Add("npcpassengers.ui.blacklist_help", "Taretleri kullanamayan NPC sınıf adlarının virgülle ayrılmış listesi. Mevcut kara listeyi görmek için 'getnpcblacklist' konsol komutunu kullanın.")
language.Add("npcpassengers.ui.hud_position", "HUD Konumu")
language.Add("npcpassengers.ui.not_bound", "Atanmamış")
language.Add("npcpassengers.ui.keybind_tip", "İpucu: Bir tuş atamasını kaldırmak için sağ tıklayın. İptal etmek için atama sırasında ESC tuşuna basın.")
language.Add("npcpassengers.ui.dont_show_again", "Bunu tekrar gösterme")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Yolcu İşlemleri")
language.Add("npcpassengers.hud.filter_prefix", "Filtre: ")
language.Add("npcpassengers.hud.sort_prefix", "Sırala: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Otomatik Yenileme: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Araç: ")
language.Add("npcpassengers.hud.speed_prefix", "Hız: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "AÇIK")
language.Add("npcpassengers.hud.off", "KAPALI")
language.Add("npcpassengers.hud.passengers", "Yolcular")
language.Add("npcpassengers.hud.npc_driver", "NPC Sürücü")
language.Add("npcpassengers.hud.total_prefix", "Toplam: ")
language.Add("npcpassengers.hud.showing_prefix", "Gösteriliyor: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Mevcut Araç: ")
language.Add("npcpassengers.hud.hidden_prefix", "Gizli: ")
language.Add("npcpassengers.hud.dead_prefix", "Ölü: ")
language.Add("npcpassengers.hud.scared_prefix", "Korkmuş: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Uykulu: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Sakin")
language.Add("npcpassengers.status.alert", "Uyarı")
language.Add("npcpassengers.status.scared", "Korkmuş")
language.Add("npcpassengers.status.drowsy", "Uykulu")
language.Add("npcpassengers.status.dead", "Ölü")
language.Add("npcpassengers.status.unknown", "Bilinmiyor")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Vatandaş")
language.Add("npcpassengers.npc.alyx", "Alyx")
language.Add("npcpassengers.npc.barney", "Barney")
language.Add("npcpassengers.npc.monk", "Peder Grigori")
language.Add("npcpassengers.npc.vortigaunt", "Vortigaunt")
language.Add("npcpassengers.npc.eli", "Eli")
language.Add("npcpassengers.npc.kleiner", "Dr. Kleiner")
language.Add("npcpassengers.npc.mossman", "Dr. Mossman")
language.Add("npcpassengers.npc.breen", "Dr. Breen")
language.Add("npcpassengers.npc.dog", "Köpek")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Araç")
language.Add("npcassengers.sort.name", "İsim")
language.Add("npcpassengers.sort.seat", "Koltuk")
language.Add("npcpassengers.sort.health", "Sağlık")
language.Add("npcpassengers.sort.status", "Durum")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Önce Araç")
language.Add("npcpassengers.sort.name_az", "İsim A-Z")
language.Add("npcpassengers.sort.seat_number", "Koltuk Numarası")
language.Add("npcpassengers.sort.highest_health", "En Yüksek Sağlık")
language.Add("npcpassengers.sort.status_priority", "Durum Önceliği")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Araç: Bilinmiyor")
language.Add("npcpassengers.ui.seat_prefix", "Koltuk ")
language.Add("npcpassengers.ui.same_vehicle", "Aynı Araç")
language.Add("npcpassengers.ui.other_vehicle", "Başka Araç")
language.Add("npcpassengers.ui.hidden", "Gizli")
language.Add("npcpassengers.ui.visible", "Görünür")
language.Add("npcpassengers.ui.health_format", "Sağlık %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Yolcu Listesini Yenile")
language.Add("npcpassengers.ui.copy_list", "Görünür Yolcu Listesini Kopyala")
language.Add("npcpassengers.ui.make_exit", "Mevcut Araç Yolcularını Çıkmasını Sağla")
language.Add("npcpassengers.ui.reset_pos", "Konum ve Açıları Sıfırla")
language.Add("npcpassengers.ui.crash_reactions", "Çarpışma Tepkileri")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Biniş/İniş Sesleri")
language.Add("npcpassengers.section.ambient_sounds", "Ortam Sesleri")
language.Add("npcpassengers.section.gesture_animations", "Hareket Animasyonları")
language.Add("npcpassengers.section.threat_awareness", "Tehlike Farkındalığı")
language.Add("npcpassengers.section.emotional_states", "Duygusal Durumlar")
language.Add("npcpassengers.section.turret_control", "Taret Kontrolü (Deneysel)")
language.Add("npcpassengers.section.turret_blacklist", "Taret NPC Kara Listesi")
language.Add("npcpassengers.section.idle_chatter", "Boş Konuşma")
language.Add("npcpassengers.section.body_physics", "Gövde Fiziği")
language.Add("npcpassengers.section.npc_auto_driver", "NPC Otomatik Sürücüsü")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Sol Alt")
language.Add("npcpassengers.hud.bottom_right", "Sağ Alt")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Yolcu HUD'ını Etkinleştir")
language.Add("npcpassengers.ui.cover_face", "Yüzü Kapat")
language.Add("npcpassengers.ui.apply_keybinds", "Önerilen Tuş Atamalarını Uygula")
language.Add("npcpassengers.ui.clear_keybinds", "Tüm Tuş Atamalarını Temizle")

-- Debugging buttons
language.Add("npcpassengers.ui.test_flinch", "Kıvrılma Hareketini Test Et")
language.Add("npcpassengers.ui.test_random", "Rastgele Hareketi Test Et")
language.Add("npcpassengers.ui.reset_states", "Tüm Durumları Sıfırla")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Tüm Bağlam Menüsü Seçeneklerini Etkinleştir")
language.Add("npcpassengers.ui.hide_context", "Tüm Bağlam Menüsü Seçeneklerini Gizle")
language.Add("npcpassengers.ui.set_compact", "Kompakt Panel Boyutu Ayarla")
language.Add("npcpassengers.ui.set_default", "Varsayılan Panel Boyutu Ayarla")
language.Add("npcpassengers.ui.set_large", "Büyük Panel Boyutu Ayarla")
language.Add("npcpassengers.ui.center_panel", "Paneli Şimdi Ortala")
language.Add("npcpassengers.ui.reset_ui", "Tüm UI Ayarlarını Varsayılana Sıfırla")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Vatandaş (K)")
language.Add("npcpassengers.role.citizen_male", "Vatandaş (E)")
language.Add("npcpassengers.role.medic", "Sağlıkçı")
language.Add("npcpassengers.role.rebel", "Isyankar")
language.Add("npcpassengers.role.passenger", "Yolcu")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Sadece Araçtayken Göster")
language.Add("npcpassengers.hud.show_calm", "Sakin Yolcuları Göster")
language.Add("npcpassengers.hud.show_hints", "Bağlam İpuçlarını Göster")
language.Add("npcpassengers.hud.show_target_debug", "Hedef Hata Ayıklamasını Göster")
language.Add("npcpassengers.hud.play_cues", "Başarı/Başarısız Sinyallerini Çal")
language.Add("npcpassengers.debug.enable_mode", "Hata Ayıklama Modunu Etkinleştir")
language.Add("npcpassengers.ui.enable_sounds", "UI Seslerini Etkinleştir")
language.Add("npcpassengers.ui.hover_sounds", "Üzerine Gelme Sesleri")
language.Add("npcpassengers.ui.click_sounds", "Tıklama Sesleri")
language.Add("npcpassengers.ui.enable_animations", "UI Animasyonlarını Etkinleştir")
language.Add("npcpassengers.ui.show_tooltips", "İpuçlarını Göster")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Kaydırma Çubuğunu Otomatik Gizle")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Kenar Çubuğu Kaydırma Yumuşaklığı")
language.Add("npcpassengers.ui.color_theme", "Renk Teması")
language.Add("npcpassengers.ui.font_scale", "Yazı Tipi Ölçeği")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "NPC Seçimini İptal Et")
language.Add("npcpassengers.context.remove_passenger", "Yolcuyu Kaldır")
language.Add("npcpassengers.context.blacklist_passenger", "Kara Listeye Ekle")
language.Add("npcpassengers.context.whitelist_passenger", "Beyaz Listeye Ekle")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Tuş Atamaları")
language.Add("npcpassengers.keybinds.desc", "Hızlı eylemler için klavye kısayollarını yapılandırın.")
language.Add("npcpassengers.keybind.attach", "En Yakın NPC'yi Bağla")
language.Add("npcpassengers.keybind.attach.help", "En yakın dost NPC'yi aracınıza bağlar.")
language.Add("npcpassengers.keybind.detach_all", "Tüm NPC'leri Ayır")
language.Add("npcpassengers.keybind.detach_all.help", "Aracınızdaki tüm yolcuları kaldırır.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Otomatik Katılmayı Değiştir")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Otomatik katılmayı hızlıca etkinleştirir/devre dışı bırakır.")
language.Add("npcpassengers.keybind.menu", "Ayarlar Menüsünü Aç")
language.Add("npcpassengers.keybind.menu.help", "Ayarlar panelini açar.")
language.Add("npcpassengers.keybind.exit_all", "Tüm Yolcular Çıkıyor")
language.Add("npcpassengers.keybind.exit_all.help", "Tüm yolcuların araçtan çıkmasını sağlar.")
language.Add("npcpassengers.keybind.toggle_hud", "HUD'ı Değiştir")
language.Add("npcpassengers.keybind.toggle_hud.help", "Yolcu HUD'ını gösterir/gizler.")
language.Add("npcpassengers.keybind.quick_attach", "Hızlı Bağlama Modu")
language.Add("npcpassengers.keybind.quick_attach.help", "Baktığınız NPC'leri hızlıca bağlamak için basılı tutun")
language.Add("npcpassengers.keybind.hold_fire", "NPC'ler Ateşi Tutuyor")
language.Add("npcpassengers.keybind.hold_fire.help", "Nişancı NPC'lere ateş etmeyi bırakmalarını söyleyin")
language.Add("npcpassengers.keybind.open_fire", "NPC'ler Ateş Açıyor")
language.Add("npcpassengers.keybind.open_fire.help", "Nişancı NPC'lere hedeflere saldırmalarını söyleyin")
language.Add("npcpassengers.keybind.cycle_view", "Yolcu Görüşünü Döngüle")
language.Add("npcpassengers.keybind.cycle_view.help", "Kamerayı yolcular arasında döngüler")
language.Add("npcpassengers.keybind.cycle_hud_position", "HUD Konumunu Döngüle")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Yolcu HUD'ını dört köşe arasında hareket ettirir")
language.Add("npcpassengers.keybind.toggle_debug", "Hedef Hata Ayıklamasını Değiştir")
language.Add("npcpassengers.keybind.toggle_debug.help", "Küçük hedef hata ayıklama katmanını değiştirir")
language.Add("npcpassengers.keybind.test_gesture", "Rastgele Hareketi Test Et")
language.Add("npcpassengers.keybind.test_gesture.help", "En yakın yolcuda rastgele bir hareket oynatır")
language.Add("npcpassengers.keybind.reset_all", "Tüm NPC'leri Sıfırla")
language.Add("npcpassengers.keybind.reset_all.help", "Tüm yolcular için animasyon durumlarını sıfırlar")

-- HUD Settings
language.Add("npcassengers.hud.header", "HUD Ayarları")
language.Add("npcpassengers.hud.enable", "HUD'ı Etkinleştir")
language.Add("npcpassengers.hud.enable.help", "Ekranda yolcu durumu katmanını gösterir.")
language.Add("npcpassengers.hud.position", "HUD Konumu")
language.Add("npcpassengers.hud.position.help", "HUD'ın ekranda nerede göründüğü.")
language.Add("npcpassengers.hud.position.topleft", "Sol Üst")
language.Add("npcpassengers.hud.position.topright", "Sağ Üst")
language.Add("npcpassengers.hud.position.bottomleft", "Sol Alt")
language.Add("npcpassengers.hud.position.bottomright", "Sağ Alt")
language.Add("npcpassengers.hud.scale", "HUD Ölçeği")
language.Add("npcpassengers.hud.scale.help", "HUD için boyut çarpanı.")
language.Add("npcpassengers.hud.opacity", "HUD Opaklığı")
language.Add("npcpassengers.hud.opacity.help", "Arka plan şeffaflığı (0 = görünmez, 1 = katı).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "NPC Sürücü")
language.Add("npcpassengers.driver.desc", "NPC'lerin sizin için araç sürmesine izin verin.")
language.Add("npcpassengers.driver.enable", "NPC Sürücüleri Etkinleştir")
language.Add("npcpassengers.driver.enable.help", "NPC'lerin araçların kontrolünü almasına izin verir.")
language.Add("npcpassengers.driver.behavior", "Sürüş Davranışı")
language.Add("npcpassengers.driver.behavior.help", "NPC'nin aracı nasıl sürdüğü.")
language.Add("npcpassengers.driver.behavior.cruise", "Rastgele Gezi")
language.Add("npcpassengers.driver.behavior.follow", "Oyuncuyu Takip Et")
language.Add("npcpassengers.driver.behavior.patrol", "Devriye")
language.Add("npcpassengers.driver.behavior.flee", "Kaç")
language.Add("npcpassengers.driver.behavior.parked", "Park Edili Kal")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Sıkça Sorulan Sorular")
language.Add("npcpassengers.help.desc", "Yaygın sorulara hızlı yanıtlar ve sorun giderme.")
language.Add("npcpassengers.help.still_need", "Hala Yardıma mı İhtiyacınız Var?")
language.Add("npcpassengers.help.community", "Destek için Discord topluluğumuza katılın!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Tank/LVS")
language.Add("npcpassengers.nav.debugging", "Hata Ayıklama")
language.Add("npcpassengers.nav.driver", "NPC Sürücü")
language.Add("npcpassengers.nav.interface", "Arayüz")
language.Add("npcassengers.nav.simulate", "Simüle Et")
language.Add("npcpassengers.nav.modules", "Modüller")
language.Add("npcpassengers.nav.about", "Hakkında")
language.Add("npcpassengers.search.placeholder", "Ayarları ara...")

-- About page
language.Add("npcpassengers.about.description", "Duygusal yapay zeka ve gerçekçi fizik ile gelişmiş yolcu sistemi")
language.Add("npcpassengers.about.feature_status", "Durum Sistemi: SAKİN / UYARI / KORKAK / UYKULU / ÖLÜ")
language.Add("npcpassengers.about.feature_performance", "Performans: koltuk önbelleği, kısıtlanmış zamanlayıcılar, optimize edilmiş istemci kancaları")
language.Add("npcpassengers.about.feature_filtering", "Araç filtreleme, biniş yeniden deneme soğuması, sadece takım otomatik katılımı")
language.Add("npcpassengers.about.actions", "Eylemler")
language.Add("npcpassengers.about.show_welcome", "Karşılama Ekranını Göster")
language.Add("npcpassengers.about.open_github", "GitHub Sayfasını Aç")
language.Add("npcpassengers.about.reset_settings", "TÜM Ayarları Varsayılana Sıfırla")

-- Status messages
language.Add("npcpassengers.status.calm", "SAKİN")
language.Add("npcpassengers.status.alert", "UYARI")
language.Add("npcpassengers.status.scared", "KORKAK")
language.Add("npcpassengers.status.drowsy", "UYKULU")
language.Add("npcpassengers.status.dead", "ÖLÜ")
language.Add("npcpassengers.status.calm.desc", "Rahat, yakın tehdit yok")
language.Add("npcpassengers.status.alert.desc", "Düşman tespit edildi, NPC tehditleri takip ediyor")
language.Add("npcpassengers.status.scared.desc", "Tehlikeli sürüş (yüksek hız, çarpışmalar)")
language.Add("npcpassengers.status.drowsy.desc", "Uzun ve sakin yolculuk, NPC uykulu hale geliyor")
language.Add("npcpassengers.status.dead.desc", "Sağlık sıfıra ulaştı")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Otomatik Katılma: AÇIK")
language.Add("npcpassengers.chat.autojoin_off", "Otomatik Katılma: KAPALI")
language.Add("npcpassengers.chat.hud_on", "HUD: AÇIK")
language.Add("npcpassengers.chat.hud_off", "HUD: KAPALI")
language.Add("npcpassengers.chat.prefix", "[Daha İyi NPC Yolcuları]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Yakında araç yok")
language.Add("npcpassengers.error.no_npc", "Yakında NPC yok")
language.Add("npcpassengers.error.vehicle_full", "Araç dolu")
language.Add("npcpassengers.error.too_far", "NPC araçtan çok uzak")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Dili değiştir")
language.Add("npcpassengers.tooltip.minimize", "Paneli küçült")
language.Add("npcpassengers.tooltip.expand", "Paneli genişlet")
language.Add("npcpassengers.tooltip.welcome", "Karşılama ekranını göster")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Tüm NPC konuşması için ana anahtar. Yolcuları tamamen susturmak için devre dışı bırakın.")
language.Add("npcpassengers.speech_volume.help", "NPC seslerinin ne kadar yüksek olduğu (0 = sessiz, 100 = tam ses).")
language.Add("npcpassengers.pitch_variation.help", "Daha doğal sesler için rastgele perde değişimi. 0 = tek tip, daha yüksek = daha fazla çeşitlilik.")
language.Add("npcpassengers.crash_enable.help", "Araç keskin bir şekilde yavaşladığında NPC'ler inleyerek/cegirerek tepki verir (çarpışmalar, sert frenleme).")
language.Add("npcpassengers.crash_threshold.help", "Çarpışma seslerini tetiklemek için gerekli yavaşlama. Daha düşük = daha hassas.")
language.Add("npcpassengers.crash_cooldown.help", "Her NPC için çarpışma sesleri arasındaki minimum saniye.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPC'ler seyahat ederken ara sıra konuşur - yorumlar, sorular, gözlemler.")
language.Add("npcpassengers.speech_idle_chance.help", "Kontrol başına konuşma olasılığı. 0 = asla, 1 = her zaman konuşmaya çalışır.")
language.Add("npcpassengers.speech_idle_interval.help", "Boş konuşma girişimleri arasındaki minimum saniye.")
language.Add("npcpassengers.speech_board.help", "NPC'ler araca binerken ve çıkarken konuşur.")
language.Add("npcpassengers.ambient_sounds.help", "Ara sıra öksürükler, iç çekmeler, mırıldanmalar - arka plan yaşam sesleri.")
language.Add("npcpassengers.ambient_interval.help", "Ortam sesleri arasındaki ortalama saniye.")
language.Add("npcpassengers.animation.help", "NPC animasyonlarını ve kafa hareketini hassas şekilde ayarlayın.")
language.Add("npcpassengers.head_look.help", "NPC'ler doğal olarak etrafına, oyuncuya, pencerelere bakar vb.")
language.Add("npcpassengers.head_smooth.help", "Kafa ne kadar yumuşak hareket eder. Daha düşük = daha hızlı, daha yüksek = daha yüzen.")
language.Add("npcpassengers.blink.help", "NPC'ler otururken gerçekçi bir şekilde göz kırpırlar.")
language.Add("npcpassengers.breathing.help", "NPC kafalarında ince nefes alma animasyonu.")
language.Add("npcpassengers.walk_timeout.help", "NPC'nin araca yürümeyi bırakmadan önceki saniye.")
language.Add("npcpassengers.realism.help", "Maksimum sürükleyicilik için fizik tabanlı tepkiler ve farkındalık sistemleri.")
language.Add("npcpassengers.talking_gestures.help", "NPC'ler seyahat ederken rastgele el hareketleri ve gövde animasyonları oynatır.")
language.Add("npcpassengers.gesture_chance.help", "Her aralıkta hareket oynatma yüzdesi olasılığı.")
language.Add("npcpassengers.gesture_interval.help", "Hareket fırsat kontrolleri arasındaki saniye.")
language.Add("npcpassengers.crash_flinch.help", "NPC'ler araç çarptığında veya sert frenlediğinde kıvrılır ve öne fırlar.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Kıvrılmayı tetiklemek için gerekli hız değişimi (daha düşük = daha hassas).")
language.Add("npcpassengers.body_sway.help", "NPC'ler dönüşlerde eğilir, hızlanma/frenleme sırasında destek alır.")
language.Add("npcpassengers.body_sway_amount.help", "NPC'lerin araç hareketiyle ne kadar sallandığı.")
language.Add("npcpassengers.threat_awareness.help", "NPC'ler otomatik olarak yakındaki düşmanlara bakar.")
language.Add("npcpassengers.threat_range.help", "NPC'lerin kafa takibi için tehditleri ne kadar uzakta algılayabileceği.")
language.Add("npcpassengers.combat_alert.help", "NPC'ler düşmanlar yakında olduğunda gergin ve tepkili olurlar.")
language.Add("npcpassengers.passenger_combat.help", "Varsayılan olarak devre dışı. Silahlı yolcuların araçlardan ateş etmesine izin vermek için bunu etkinleştirin.")
language.Add("npcpassengers.passenger_combat_range.help", "Silahlı yolcuların hedefleri ne kadar uzağa alabileceği.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Daha yüksek değerler silahlı yolcular için atış yayılmasını daraltır.")
language.Add("npcpassengers.passenger_combat_damage.help", "Yolcu ateşlenen atışlar tarafından verilen hasarı ölçeklendirir.")
language.Add("npcpassengers.passenger_interaction.help", "Birden fazla yolcu birbirine bakar ve ara sıra birbirleriyle konuşur.")
language.Add("npcpassengers.fear_reactions.help", "NPC'ler tehlikeli sürüşten korkar - gözler geniş, pani sesleri.")
language.Add("npcpassengers.fear_speed_threshold.help", "NPC'lerin sinirli olmaya başladığı hız (birim/saniye).")
language.Add("npcpassengers.drowsiness.help", "NPC'ler uzun ve sakin yolculuklarda uyku hali alır - yavaş göz kırpmalar, kafa sallamaları.")
language.Add("npcpassengers.drowsy_time.help", "Uykululuk başlamadan önceki sakin sürüş saniyesi.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Tanklar, APC'ler ve LVS araçları için ayarlar.")
language.Add("npcpassengers.hide_in_tanks.help", "Tanklar ve APC'lerin içindeyken NPC yolcularını görünmez yapar.")
language.Add("npcpassengers.eject_stuck_check.help", "NPC'ler çıkarılırken sıkıştığında otomatik olarak araçlardan dışarı iter. NPC'lerin çıkarken araçların içinden geçmesini önler.")
language.Add("npcpassengers.detach_no_collide.help", "Bağlantı kesildikten sonra, NPC'ler uzaklaşabilmeleri için araçla geçici olarak geçebilirler, böylece çarpışmadan veya sıkışmadan yürüyebilirler.")
language.Add("npcpassengers.detach_no_collide_duration.help", "NPC'lerin bağlantı kesildikten sonra araç çarpışmasını görmezden geleceği süre.")
language.Add("npcpassengers.die_with_vehicle.help", "NPC yolcular araçları bir patlama veya yangın tarafından yok edildiğinde ölür (kazadan sağ çıkmaları daha sürükleyici).")
language.Add("npcpassengers.tank_driver.help", "Sürücü koltuğundaki NPC'lerin düşmanlara doğru otomatik olarak sürmesine izin verir.")
language.Add("npcpassengers.tank_driver_range.help", "Sürücünün düşmanları algılayabileceği maksimum menzil.")
language.Add("npcpassengers.tank_driver_distance.help", "Düşmanlardan korunacak mesafe.")
language.Add("npcpassengers.tank_driver_throttle.help", "Gaz miktarı (0.1 = yavaş, 1 = tam hız).")
language.Add("npcpassengers.tank_driver_reverse.help", "Düşmanlardan uzaklaşmak için geri vites mesafesi.")
language.Add("npcpassengers.tank_turret.help", "NPC'lerin LVS araçlarında taretleri kontrol etmesine izin verir.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Sürerken ekranda yolcu durumunu (duygular, uyarı) gösterir.")
language.Add("npcpassengers.hud_show_calm.help", "Devre dışı bırakıldığında, sadece sakin olmayan durumlu yolcuları gösterir.")
language.Add("npcpassengers.hud_thresholds.desc", "Duygu seviyeleri bu eşikleri aştığında, yolcular HUD'da o durumu gösterir.")
language.Add("npcpassengers.hud_alert_threshold.help", "'UYARI' durumunu göstermek için gerekli uyarı seviyesi (tehdit tespit edildi).")
language.Add("npcpassengers.hud_fear_threshold.help", "'KORKAK' durumunu göstermek için gerekli korku seviyesi (tehlikeli sürüş).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "'UYKULU' durumunu göstermek için gerekli sakin zaman oranı (uzun sakin yolculuk).")
language.Add("npcpassengers.hud_actions.desc", "Yolcuların her duygusal durumu deneyimlediklerinde hangi eylemi alacaklarını seçin.")
language.Add("npcpassengers.hud_actions_note", "Not: Bazı eylemler NPC model desteğine bağlı olarak görünmeyebilir.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Yolcu eylemleri için özel tuş atamaları ayarlayın. Bir butona tıklayın ve atamak için bir tuşa basın.")
language.Add("npcpassengers.keybinds_hud.desc", "Yolcu katmanını göstermek, taşımak ve hata ayıklamak için hızlı HUD kontrolleri.")
language.Add("npcpassengers.keybinds_debug_note", "Hata ayıklama tuş atamaları sadece Hata Ayıklama Modu etkinleştirildiğinde çalışır.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "NPC davranışını test etmek için gelişmiş hata ayıklama araçları. Önce ayarlarda Hata Ayıklama Modunu etkinleştirin.")
language.Add("npcpassengers.debug_mode.help", "Hata ayıklama test butonlarını gösterir ve hata ayıklama komutlarını etkinleştirir.")
language.Add("npcpassengers.debug_status.help", "Test için manuel olarak yolcu durumunu ayarlayın. Mevcut yolcuları görmek için 'Listeyi Yenile'ye tıklayın.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Butonlar, onay kutuları ve diğer UI öğeleri için ses efektlerini yapılandırın")
language.Add("npcpassengers.ui_sounds_enabled.help", "Tüm UI ses efektleri için ana anahtar")
language.Add("npcpassengers.ui_sounds_volume.help", "UI sesleri için ses çarpanı (1.0 = normal, 2.0 = iki katı)")
language.Add("npcpassengers.ui_hover_enabled.help", "Butonların üzerine gelindiğinde ses çal")
language.Add("npcpassengers.ui_click_enabled.help", "Butonlara ve onay kutularına tıklandığında ses çal")
language.Add("npcpassengers.context_menu.desc", "NPC'lere sağ tıklandığında hangi seçeneklerin görüneceğini seçin")
language.Add("npcpassengers.context_make_passenger.help", "NPC'yi mevcut aracınıza yolcu olarak ekler")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "NPC'yi belirli bir araca ekler (NPC'ye tıklayın, sonra araca)")
language.Add("npcpassengers.context_detach.help", "NPC'yi araçtan kaldırır")
language.Add("npcpassengers.ui_show_welcome.help", "Eklenti yeni bir sürüme güncellendiğinde karşılama panelini göster")
language.Add("npcpassengers.ui_panel_width.help", "Ayarlar panelinin genişliği")
language.Add("npcpassengers.ui_panel_height.help", "Ayarlar panelinin yüksekliği")
language.Add("npcpassengers.ui_animations.help", "Yumuşak geçişler ve geçiş efektleri (performansı etkileyebilir)")
language.Add("npcpassengers.ui_tooltips.help", "Ayarların üzerine gelindiğinde yararlı ipuçlarını göster")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Kaydırma çubuğunu sadece kaydırırken veya üzerine gelindiğinde göster.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Not: Herhangi bir kaydırıcıyı sürüklerken panel arka plandaki içeriği görmek için %70 şeffaf olur.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Daha düşük değerler = daha yumuşak ama daha yavaş (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Ayarlar paneli için bir renk teması seçin. Değişiklikler hemen uygulanır.")
language.Add("npcpassengers.ui_font_scale.help", "Tüm UI yazı tipi boyutlarını ölçeklendirir. 1.0 = varsayılan, 0.5 = yarım boyut, 2.0 = iki kat boyut.")

print("[Better NPC Passengers] Turkish localization loaded!")
