-- Better NPC Passengers - Ukrainian Localization
-- Файл української локалізації

local L = language and language.GetPhrase or function(s) return s end

-- Addon name
language.Add("npcpassengers.name", "Покращені NPC Пасажири")
language.Add("npcpassengers.settings", "Налаштування")

-- Navigation / Tab names
language.Add("npcpassengers.nav.general", "Загальне")
language.Add("npcpassengers.nav.autojoin", "Автоприєднання")
language.Add("npcpassengers.nav.passengers", "Пасажири")
language.Add("npcpassengers.nav.position", "Позиція")
language.Add("npcpassengers.nav.behaviour", "Поведінка")
language.Add("npcpassengers.nav.keybinds", "Прив'язки клавіш")
language.Add("npcpassengers.nav.hud", "HUD")
language.Add("npcpassengers.nav.driver", "Водій")
language.Add("npcpassengers.nav.help", "Допомога")

-- General Settings
language.Add("npcassengers.general.header", "Загальні налаштування")
language.Add("npcpassengers.allow_multiple", "Дозволити кількох пасажирів")
language.Add("npcpassengers.allow_multiple.help", "Дозволяє кільком NPC подорожувати в одному транспорті.")
language.Add("npcpassengers.exit_behavior", "Поведінка виходу")
language.Add("npcpassengers.exit_behavior.help", "Коли пасажири NPC повинні залишити транспорт?")
language.Add("npcassengers.exit_mode.leave_player", "Покинути коли гравець виходить")
language.Add("npcpassengers.exit_mode.leave_attack", "Покинути при атаці транспорту")
language.Add("npcpassengers.exit_mode.never", "Не виходити автоматично")

-- Timing Settings
language.Add("npcpassengers.timing.header", "Час")
language.Add("npcpassengers.max_attach_dist", "Макс. відстань кріплення")
language.Add("npcpassengers.max_attach_dist.help", "Максимальна відстань (одиниці) для кріплення NPC до транспорту.")
language.Add("npcpassengers.detach_delay", "Затримка відкріплення")
language.Add("npcpassengers.detach_delay.help", "Секунди очікування перед відкріпленням після виходу гравця.")
language.Add("npcpassengers.ai_delay", "Затримка відновлення ШІ")
language.Add("npcpassengers.ai_delay.help", "Секунди очікування перед відновленням інтелекту NPC після відкріплення.")
language.Add("npcpassengers.cooldown", "Час відновлення")
language.Add("npcpassengers.cooldown.help", "Час відновлення між підйомом NPC до того ж транспорту.")
language.Add("npcpassengers.passenger_limit", "Ліміт пасажирів")
language.Add("npcpassengers.passenger_limit.help", "Максимальна кількість NPC дозволена в транспорті.")

-- Auto-Join Settings
language.Add("npcpassengers.autojoin.header", "Автоприєднання (поведінка команди)")
language.Add("npcpassengers.autojoin.desc", "Дружні NPC автоматично сядуть у ваш транспорт коли ви сядете, точно як механіка команди в Half-Life 2!")
language.Add("npcpassengers.autojoin.enable", "Увімкнути автоприєднання")
language.Add("npcpassengers.autojoin.enable.help", "Дружні NPC поблизу автоматично сядуть коли ви сядете в транспорт.")
language.Add("npcpassengers.autojoin.range", "Діапазон автоприєднання")
language.Add("npcpassengers.autojoin.range.help", "Максимальна відстань для пошуку NPC для автоприєднання.")
language.Add("npcpassengers.autojoin.max", "Макс. NPC для автоприєднання")
language.Add("npcpassengers.autojoin.max.help", "Максимальна кількість NPC які можуть автоматично приєднатися одночасно.")
language.Add("npcpassengers.autojoin.squad_only", "Тільки члени команди")
language.Add("npcpassengers.autojoin.squad_only.help", "Тільки NPC з назвою команди приєднаються автоматично (для команд стилю HL2).")

-- Panel descriptions
language.Add("npcpassengers.panel.autojoin.desc", "Дружні NPC поблизу автоматично сядуть у ваш транспорт коли ви сядете, точно як механіка команди в Half-Life 2!")
language.Add("npcpassengers.panel.passengers.header", "Керування пасажирами")
language.Add("npcpassengers.panel.passengers.desc", "Керування активними пасажирами, фільтрація за назвою/класом/станом, копіювання інформації налагодження, скидання сидінь, відкріплення пасажирів без виходу з панелі налаштувань.")
language.Add("npcpassengers.panel.position.desc", "Точне налаштування позиції NPC в транспорті. Використовуйте це для виправлення проблем з плаванням або перекриттям.")
language.Add("npcpassengers.panel.angle.desc", "Налаштування обертання NPC в транспорті.")
language.Add("npcpassengers.panel.speech.desc", "Налаштування як NPC говорять під час подорожі в транспорті. Звуки громадян стилю HL2!")

-- Position Settings
language.Add("npcpassengers.position.header", "Зсув позиції")
language.Add("npcpassengers.position.desc", "Точне налаштування позиції NPC в транспорті. Використовуйте це для виправлення проблем з плаванням або перекриттям.")
language.Add("npcpassengers.height_offset", "Зсув висоти")
language.Add("npcpassengers.forward_offset", "Зсув вперед")
language.Add("npcpassengers.right_offset", "Зсув вправо")
language.Add("npcpassengers.angle.header", "Зсув кута")
language.Add("npcpassengers.angle.desc", "Налаштування обертання NPC в транспорті.")
language.Add("npcpassengers.yaw_offset", "Рискання (поворот)")
language.Add("npcpassengers.pitch_offset", "Тангаж (нахил вперед)")
language.Add("npcpassengers.roll_offset", "Крен (нахил убік)")

-- Behaviour Settings
language.Add("npcpassengers.behaviour.header", "Звук NPC (розширений)")
language.Add("npcpassengers.behaviour.desc", "Налаштування як NPC говорять під час подорожі в транспорті. Звуки громадян стилю HL2!")
language.Add("npcpassengers.speech_enable", "Увімкнути звук NPC")
language.Add("npcpassengers.speech_enable.help", "Головний перемикач для всіх звуків NPC. Вимкніть щоб пасажири були повністю тихими.")
language.Add("npcpassengers.speech_volume", "Гучність звуку")
language.Add("npcpassengers.speech_volume.help", "Наскільки голосно NPC говорять (0 = тихо, 100 = повна гучність).")
language.add("npcpassengers.pitch_variation", "Варіація висоти звуку (+/-)")
language.Add("npcpassengers.pitch_variation.help", "Випадкова зміна висоти звуку для більш природних звуків. 0 = однаковий, вище = більше різноманітності.")
language.Add("npcpassengers.crash.header", "Реакції на аварії")
language.Add("npcpassengers.crash_enable", "Увімкнути звуки аварій")
language.Add("npcpassengers.crash_enable.help", "NPC стогнуть/кричать коли транспорт різко сповільнюється (аварія, різке гальмування).")
language.Add("npcpassengers.crash_threshold", "Чутливість аварії")
language.Add("npcpassengers.crash_threshold.help", "Сповільнення необхідне для виклику звуків аварії. Менше = більш чутливий.")
language.Add("npcpassengers.crash_cooldown", "Відновлення звуку аварії")
language.Add("npcpassengers.crash_cooldown.help", "Мінімум секунд між звуками аварії для кожного NPC.")

-- Additional checkbox labels
language.Add("npcpassengers.speech_idle", "Увімкнути розмови бездіяльності")
language.add("npcpassengers.speech_board", "Увімкнути звуки посадки/виходу")
language.Add("npcpassengers.ambient_sounds", "Увімкнути фонові звуки")
language.Add("npcpassengers.head_look", "Увімкнути погляд голови/очей")
language.Add("npcpassengers.blink", "Увімкнути моргання")
language.Add("npcpassengers.breathing", "Увімкнути дихання")
language.Add("npcpassengers.talking_gestures", "Увімкнути жести розмови")
language.Add("npcpassengers.crash_flinch", "Увімкнути реакцію на аварію")
language.Add("npcpassengers.body_sway", "Увімкнути хитання тіла")
language.Add("npcpassengers.threat_awareness", "Увімкнути усвідомлення загрози")
language.Add("npcpassengers.combat_alert", "Тривога бою")
language.Add("npcpassengers.passenger_combat", "NPC стріляють з транспорту (експериментально)")
language.Add("npcpassengers.passenger_interaction", "Взаємодія пасажирів")
language.Add("npcpassengers.fear_reactions", "Увімкнути реакції страху")
language.Add("npcassengers.drowsiness", "Увімкнути сонливість")
language.Add("npcpassengers.hide_in_tanks", "Приховати NPC в закритому транспорті")
language.Add("npcpassengers.eject_stuck_check", "Автоматичне викидання застряглих NPC")
language.Add("npcpassengers.detach_no_collide", "Без зіткнення з транспортом після відкріплення")
language.Add("npcpassengers.die_with_vehicle", "Вбивати пасажирів коли транспорт вибухає")
language.Add("npcpassengers.driver_enabled", "Увімкнути автопілот")
language.Add("npcpassengers.turret_enabled", "Увімкнути керування туреллю")
language.Add("npcpassengers.turret_lead_targets", "Передбачення цілей")
language.Add("npcpassengers.turret_friendly_fire", "Дозволити вогонь по своїх")
language.Add("npcpassengers.turret_hold_fire", "Утримувати вогонь (вимкнути стрільбу)")

-- Slider labels
language.Add("npcpassengers.speech_volume", "Гучність звуку")
language.Add("npcpassengers.pitch_variation", "Варіація висоти звуку (+/-)")
language.Add("npcpassengers.crash_threshold", "Чутливість аварії")
language.Add("npcpassengers.crash_cooldown", "Відновлення звуку аварії")
language.Add("npcpassengers.speech_idle_chance", "Ймовірність розмови")
language.Add("npcpassengers.speech_idle_interval", "Інтервал розмови")
language.Add("npcpassengers.ambient_interval", "Інтервал фонового звуку")
language.Add("npcpassengers.head_smooth", "Плавність голови")
language.Add("npcpassengers.walk_timeout", "Тайм-аут ходьби")
language.Add("npcpassengers.gesture_chance", "Ймовірність жесту (%)")
language.Add("npcpassengers.gesture_interval", "Інтервал жесту")
language.Add("npcpassengers.crash_threshold_flinch", "Чутливість аварії")
language.Add("npcassengers.body_sway_amount", "Інтенсивність хитання")
language.Add("npcpassengers.threat_range", "Діапазон виявлення загрози")
language.Add("npcpassengers.passenger_combat_range", "Діапазон бою пасажирів")
language.Add("npcpassengers.passenger_combat_accuracy", "Точність пасажирів")
language.Add("npcpassengers.passenger_combat_damage", "Множник шкоди пасажирів")
language.Add("npcpassengers.fear_speed_threshold", "Поріг швидкості страху")
language.Add("npcpassengers.drowsy_time", "Час сонливості")
language.Add("npcpassengers.detach_no_collide_duration", "Тривалість без зіткнення (секунди)")
language.Add("npcpassengers.tank_driver_range", "Діапазон виявлення")
language.Add("npcpassengers.tank_driver_engage_distance", "Дистанція вступу в бій")
language.Add("npcpassengers.tank_driver_speed", "Швидкість водіння")
language.Add("npcpassengers.tank_driver_reverse_distance", "Дистанція заднього ходу")
language.Add("npcpassengers.turret_range", "Діапазон цілі")
language.Add("npcpassengers.turret_accuracy", "Точність")
language.Add("npcpassengers.turret_reaction_time", "Час реакції")
language.Add("npcpassengers.turret_fire_delay", "Затримка стрільби")
language.Add("npcpassengers.turret_aim_speed", "Швидкість прицілювання")
language.Add("npcpassengers.hud_scale", "Масштаб HUD")
language.Add("npcpassengers.hud_opacity", "Прозорість HUD")
language.Add("npcpassengers.hud_alert_threshold", "Поріг тривоги")
language.Add("npcpassengers.hud_fear_threshold", "Поріг страху")
language.Add("npcpassengers.hud_drowsy_threshold", "Поріг сонливості")
language.Add("npcpassengers.ui_sounds_volume", "Гучність звуків інтерфейсу")
language.Add("npcpassengers.ui_panel_width", "Ширина панелі")

-- Section headers
language.Add("npcpassengers.section.animation", "Анімація та поведінка")
language.Add("npcpassengers.section.realism", "Розширений реалізм")
language.Add("npcpassengers.section.hud_position", "Розташування та стиль HUD")
language.Add("npcpassengers.section.emotion_thresholds", "Пороги емоцій")
language.Add("npcpassengers.section.emotion_actions", "Дії емоцій")
language.Add("npcpassengers.section.vehicle_control", "Керування транспортом")
language.Add("npcpassengers.section.hud_controls", "Елементи керування HUD")
language.Add("npcpassengers.section.debug_controls", "Елементи керування налагодження")
language.Add("npcassengers.section.passenger_status", "Керування станом пасажирів")
language.Add("npcpassengers.section.quick_test", "Кнопки швидкого тестування")
language.Add("npcpassengers.section.driver_system", "Система водія NPC")
language.Add("npcpassengers.section.ui_sounds", "Налаштування звуків інтерфейсу")
language.Add("npcpassengers.section.appearance", "Зовнішній вигляд")
language.Add("npcpassengers.section.context_menu", "Опції контекстного меню")
language.Add("npcpassengers.section.panel_preferences", "Налаштування панелі")
language.Add("npcpassengers.section.performance", "Продуктивність та технічне")
language.Add("npcpassengers.section.simulation", "Система симуляції")
language.Add("npcpassengers.section.modules", "Система модулів")

-- Button labels
language.Add("npcpassengers.btn.assign_seat", "Призначити сидіння")
language.Add("npcpassengers.btn.detach", "Відкріпити")
language.Add("npcpassengers.btn.copy_summary", "Копіювати підсумок")
language.Add("npcpassengers.btn.copy_debug", "Копіювати налагодження")
language.Add("npcpassengers.btn.enable_all_speech", "Увімкнути весь звук")
language.Add("npcpassengers.btn.disable_all_speech", "Вимкнути весь звук")
language.Add("npcpassengers.btn.show_current_vehicle", "Показати тільки поточний транспорт")
language.Add("npcpassengers.btn.auto_refresh", "Автоматичне оновлення видимого списку")

-- Status messages
language.Add("npcpassengers.status.no_vehicle", "Поточний транспорт не виявлено. Сядьте в транспорт або вимкніть фільтр поточного транспорту.")
language.Add("npcpassengers.status.no_match_filter", "Немає пасажирів які відповідають вашому фільтру. Спробуйте назву, клас, номер сидіння, стан або клас транспорту.")
language.Add("npcpassengers.status.no_passengers_vehicle", "Пасажирів не знайдено в вашому поточному транспорті.")
language.Add("npcpassengers.status.no_passengers", "Пасажирів не знайдено. NPC повинні подорожувати в транспорті перед тим як ними можна керувати тут.")
language.Add("npcpassengers.status.all_passengers", "Всі пасажири")
language.Add("npcpassengers.status.current_vehicle_only", "Тільки поточний транспорт")
language.Add("npcpassengers.status.ctrl_f_search", "Ctrl+F для фокусу на пошуку")
language.Add("npcengers.status.no_matches", "Немає відповідних налаштувань")
language.Add("npcpassengers.status.showing_matches", "Показ перших %d з %d відповідей")

-- Menu options
language.Add("npcpassengers.menu.open_settings", "Відкрити налаштування")
language.Add("npcpassengers.menu.reset_all", "Скинути всі налаштування")

-- Button states
language.Add("npcpassengers.state.on", "Увімкнено")
language.Add("npcpassengers.state.off", "Вимкнено")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_status", "Автоприєднання")
language.Add("npcpassengers.chat.hud_status", "HUD пасажирів")
language.Add("npcpassengers.chat.hud_position", "Позиція HUD")
language.Add("npcpassengers.chat.target_debug", "Налагодження цілі")
language.Add("npcpassengers.chat.turret_gunners", "Турельні стрільці")
language.Add("npcpassengers.chat.turret_holding", "Утримувати вогонь")
language.Add("npcpassengers.chat.turret_fire", "Відкрити вогонь")
language.Add("npcpassengers.chat.unknown", "Невідомо")
language.Add("npcpassengers.chat.nothing_copy", "Нічого для копіювання.")
language.Add("npcpassengers.chat.clipboard_unavailable", "Доступ до буфера обміну недоступний в цій версії.")
language.Add("npcpassengers.chat.copied_clipboard", "Скопійовано в буфер обміну.")
language.Add("npcpassengers.chat.sit_vehicle_reassign", "Сядьте в той же транспорт щоб скинути цього пасажира.")
language.Add("npcpassengers.chat.no_visible_passengers", "Немає видимих пасажирів для копіювання.")
language.Add("npcpassengers.chat.need_vehicle", "Ви повинні бути в транспорті щоб використовувати це.")
language.Add("npcpassengers.chat.keybinds_applied", "Рекомендовані прив'язки клавіш застосовано.")
language.Add("npcpassengers.chat.keybinds_cleared", "Всі прив'язки клавіш очищено.")
language.Add("npcpassengers.chat.context_enabled", "Усі опції контекстного меню увімкнено.")
language.Add("npcpassengers.chat.context_hidden", "Усі опції контекстного меню приховано.")
language.Add("npcpassengers.chat.panel_compact", "Розмір панелі встановлено на компактний.")
language.Add("npcpassengers.chat.panel_default", "Розмір панелі встановлено на стандартний.")
language.Add("npcpassengers.chat.panel_large", "Розмір панелі встановлено на великий.")
language.Add("npcpassengers.chat.panel_centered", "Панель центровано.")
language.Add("npcpassengers.chat.settings_reset", "Всі налаштування інтерфейсу скинуто до значень за замовчуванням!")
language.Add("npcpassengers.chat.npc_selected", "NPC вибрано! Тепер клікніть правою кнопкою миші на транспорт і виберіть 'Додати вибраний NPC'")
language.Add("npcpassengers.chat.adding_npc", "Додавання NPC до транспорту...")
language.Add("npcpassengers.chat.selection_cancelled", "Вибір NPC скасовано")
language.Add("npcassengers.chat.summary_copied", "Підсумок пасажирів скопійовано.")
language.Add("npcpassengers.chat.debug_copied", "Інформацію налагодження пасажирів скопійовано.")
language.Add("npcpassengers.chat.no_passengers_found", "Пасажирів не знайдено. NPC повинні бути в транспорті.")

-- Additional UI strings
language.Add("npcpassengers.ui.status_intensity", "Інтенсивність стану %.0f%%")
language.Add("npcpassengers.ui.filter_placeholder", "Фільтр пасажирів...")
language.Add("npcpassengers.ui.press_key", "Натисніть клавішу...")
language.Add("npcpassengers.ui.work_in_progress", "В роботі")
language.Add("npcpassengers.ui.under_development", "Ця функція зараз в розробці")
language.Add("npcpassengers.ui.check_back_later", "Перевірте в майбутньому оновленні!")
language.Add("npcpassengers.ui.search_desc_passengers", "Фільтрувати активних пасажирів за назвою, класом, сидінням, станом або транспортом.")
language.Add("npcpassengers.ui.search_desc_sort", "Сортувати видимий список пасажирів за транспортом, назвою, сидінням, здоров'ям або станом.")
language.Add("npcpassengers.ui.search_label_filter", "Фільтр пасажирів")
language.Add("npcpassengers.ui.search_label_sort", "Сортування пасажирів")

-- FAQ content
language.Add("npcpassengers.faq.add_npc", "Як додати NPC до мого транспорту?")
language.Add("npcassengers.faq.add_npc.answer", "Використовуйте контекстне меню (клік правою кнопкою миші на NPC) і виберіть 'Зробити пасажиром'. Або використовуйте прив'язку 'Прикріпити найближчий NPC'. NPC повинні бути дружніми до вас.")
language.Add("npcpassengers.faq.remove_npc", "Як видалити пасажирів з мого транспорту?")
language.Add("npcpassengers.faq.remove_npc.answer", "Перейдіть на вкладку Пасажири в налаштуваннях, виберіть пасажира і клікніть на відкріпити. Або використовуйте прив'язку 'Відкріпити всіх пасажирів'.")
language.Add("npcpassengers.faq.position", "NPC плавають/проходять крізь сидіння!")
language.Add("npcpassengers.faq.position.answer", "Перейдіть на вкладку Позиція і налаштуйте зсуви висоти/вперед/вправо. Кожна модель транспорту різна, тому вам може знадобитися налаштувати ці значення. Використовуйте панель налагодження для тестування позицій в реальному часі.")
language.Add("npcpassengers.faq.speech", "NPC не говорять!")
language.Add("npcpassengers.faq.speech.answer", "Перевірте вкладку Поведінка і переконайтеся що 'Увімкнути звук NPC' увімкнено. Також перевірте що гучність звуку більше 0. Деякі моделі NPC можуть не мати доступних звукових ліній.")
language.Add("npcpassengers.faq.autojoin", "Як працює автоприєднання?")
language.Add("npcpassengers.faq.autojoin.answer", "Коли увімкнено на вкладці Автоприєднання, дружні NPC поблизу автоматично сядуть коли ви сядете, точно як механіка команди в Half-Life 2! Ви можете встановити діапазон виявлення та вказати скільки NPC можуть автоматично приєднатися.")
language.Add("npcassengers.faq.death", "Що відбувається коли пасажири вмирають?")
language.Add("npcpassengers.faq.death.answer", "Мертві пасажири покажуть червоне світіння та відобразять іконку черепа в HUD. Підійдіть до вашого транспорту і натисніть R щоб видалити їхні тіла. Тіла будуть викинуті з фізикою.")
language.Add("npcpassengers.faq.status", "Що означають стани пасажирів?")
language.Add("npcpassengers.faq.status.answer", "Спокійний: розслаблений, немає близьких загроз. Тривога: ворог виявлено. Страх: небезпечне водіння (висока швидкість, аварія). Сонливий: довга тиха поїздка. Мертвий: здоров'я досягло нуля.")
language.Add("npcpassengers.faq.keybinds", "Мої прив'язки клавіш не працюють!")
language.Add("npcpassengers.faq.keybinds.answer", "Перейдіть на вкладку Прив'язки клавіш і переконайтеся що ви прив'язали клавіші (не призначені за замовчуванням). Клікніть на кнопку поруч з кожною дією і натисніть бажану клавішу. Клікніть правою кнопкою миші щоб скасувати прив'язку.")
language.Add("npcpassengers.faq.errors", "Додаток не працює взагалі / я отримую помилки!")
language.Add("npcpassengers.faq.errors.answer", "Переконайтеся що ви запускаєте останню версію Garry's Mod. Перевірте консоль на помилки (клавіша тильда ~). Спробуйте вимкнути конфліктуючі додатки.")
language.Add("npcpassengers.faq.combat", "Чи можуть пасажири стріляти з транспорту?")
language.Add("npcpassengers.faq.combat.answer", "Наразі ні. NPC будуть відстежувати ворогів і реагувати на загрози, але не стрілятимуть зброєю під час сидіння. Ця функція може бути додана в майбутніх оновленнях.")
language.Add("npcpassengers.faq.stop_autojoin", "Як зупинити NPC від автоматичного приєднання?")
language.Add("npcpassengers.faq.stop_autojoin.answer", "Зніміть прапорець 'Увімкнути автоприєднання' на вкладці Автоприєднання, або використовуйте прив'язку 'Перемкнути автоприєднання'.")
language.Add("npcpassengers.faq.settings", "Де зберігаються налаштування?")
language.Add("npcassengers.faq.settings.answer", "Всі налаштування зберігаються як ConVars в конфігурації GMod. Вони зберігаються між сесіями і є унікальними для вашого клієнта.")
language.Add("npcpassengers.faq.vehicles", "Чи працює це з усіма транспортами?")
language.Add("npcassengers.faq.vehicles.answer", "Працює з більшістю транспорту який має фізику. Танки, APCs, автомобілі, човни, тощо. Деякі модифіковані транспортні засоби можуть вимагати налаштування позиції.")
language.Add("npcpassengers.faq.multiple", "Чи можу я мати кілька NPC в одному транспорті?")
language.Add("npcpassengers.faq.multiple.answer", "Так! Встановіть 'Ліміт пасажирів' в загальних налаштуваннях. Додаток автоматично розподілить NPC навколо транспорту. Для конкретних місць сидіння налаштуйте зсуви на вкладці Позиція.")
language.Add("npcpassengers.faq.crashes", "NPC поводяться дивно після аварії!")
language.Add("npcpassengers.faq.crashes.answer", "Це нормально - вони реагують зі страхом на небезпечне водіння. Зменште поріг страху в налаштуваннях HUD якщо хочете щоб вони були менш реактивними.")
language.Add("npcpassengers.faq.reset_setting", "Як скинути одне налаштування?")
language.Add("npcassengers.faq.reset_setting.answer", "Використовуйте команду консолі для цього конкретного налаштування. Всі команди починаються з 'nai_npc_'. Введіть 'find nai_npc' в консолі щоб побачити всі доступні команди.")
language.Add("npcpassengers.faq.multiplayer", "Чи працює це в мультиплеєрі?")
language.Add("npcpassengers.faq.multiplayer.answer", "Так! Додаток працює як на серверах одиночної гри так і мультиплеєру. Кожен гравець керує своїми пасажирами.")
language.Add("npcpassengers.faq.lvs", "Чи працює це з транспортом LVS?")
language.Add("npcpassengers.faq.lvs.answer", "Так! Додаток має повну підтримку транспорту LVS (Lua Vehicle System). NPC можуть подорожувати як пасажири і навіть можуть керувати транспортом LVS якщо режим водія NPC увімкнено.")

-- Panel descriptions
language.Add("npcpassengers.panel.performance_desc", "Ці налаштування керують поведінкою інтерфейсу користувача додатку")
language.Add("npcpassengers.panel.performance_note1", "Зміни розміру панелі вимагають закриття і повторного відкриття меню")
language.Add("npcpassengers.panel.performance_note2", "Вимкнення звуків або анімації може покращити продуктивність на системах низького рівня")
language.Add("npcpassengers.panel.performance_title", "Інформація про конфігурацію інтерфейсу")
language.Add("npcpassengers.help.console_title", "Консольні команди для налагодження:")
language.Add("npcpassengers.help.console_command", "nai_npc_debug_mode 1")
language.Add("npcpassengers.help.console_desc", "- Увімкнути режим налагодження для перегляду детальної інформації")
language.Add("npcpassengers.about.title", "Про")

-- Language change messages
language.Add("npcpassengers.lang.changed_english", "Language changed to English. Panel will refresh automatically.")
language.Add("npcpassengers.lang.changed_russian", "Язык изменен на Русский. Панель обновится автоматически.")
language.Add("npcpassengers.lang.changed_chinese", "语言已更改为中文。面板将自动刷新。")
language.Add("npcpassengers.lang.changed_spanish", "Idioma cambiado a español. El panel se actualizará automáticamente.")
language.Add("npcpassengers.lang.changed_turkish", "Dil Türkçe olarak değiştirildi. Panel otomatik olarak yenilenecek.")
language.Add("npcpassengers.lang.changed_portuguese", "Idioma alterado para português. O painel será atualizado automaticamente.")
language.Add("npcpassengers.lang.changed_german", "Sprache auf Deutsch geändert. Das Panel wird automatisch aktualisiert.")
language.Add("npcpassengers.lang.changed_french", "Langue changée en français. Le panneau s'actualisera automatiquement.")
language.Add("npcpassengers.lang.changed_japanese", "言語が日本語に変更されました。パネルは自動的に更新されます。")
language.Add("npcpassengers.lang.changed_arabic", "تم تغيير اللغة إلى العربية. سيتم تحديث اللوحة تلقائياً.")
language.Add("npcpassengers.lang.changed_ukrainian", "Мову змінено на українську. Панель оновиться автоматично.")

-- Welcome screen strings
language.Add("npcpassengers.welcome.header", "Вітаємо!")
language.Add("npcpassengers.welcome.msg1", "Перш ніж скаржитися що пасажири сидять на транспорті,\nбудь ласка відкрийте налаштування. Ви можете це зробити, я вірю вам.")
language.Add("npcpassengers.welcome.msg2", "Цей додаток все ще далеко від ідеалу, не соромтеся\nповідомляти про помилки та пропонувати нові функції. Я ціную всі ваші коментарі!")
language.Add("npcpassengers.welcome.changelog", "Журнал змін")
language.Add("npcpassengers.welcome.got_it", "Зрозумів!")
language.Add("npcpassengers.welcome.console_cmd", "Або використовуйте консольну команду: nai_passengers_menu")

-- Additional UI strings
language.Add("npcpassengers.ui.blacklist_label", "Чорний список класів NPC")
language.Add("npcassengers.ui.blacklist_help", "Список розділений комами назв класів NPC які не можуть використовувати турель. Використовуйте консольну команду 'getnpcblacklist' щоб побачити поточний чорний список.")
language.Add("npcpassengers.ui.hud_position", "Позиція HUD")
language.Add("npcpassengers.ui.not_bound", "Не прив'язано")
language.Add("npcpassengers.ui.keybind_tip", "Підказка: клікніть правою кнопкою миші на прив'язку щоб відв'язати. Натисніть ESC під час прив'язки щоб скасувати.")
language.Add("npcpassengers.ui.dont_show_again", "Не показувати це знову")

-- HUD and status strings
language.Add("npcpassengers.hud.passenger_operations", "Операції пасажирів")
language.Add("npcpassengers.hud.filter_prefix", "Фільтр: ")
language.Add("npcpassengers.hud.sort_prefix", "Сортування: ")
language.Add("npcpassengers.hud.auto_refresh_prefix", "  |  Автооновлення: ")
language.Add("npcpassengers.hud.vehicle_prefix", "Транспорт: ")
language.Add("npcpassengers.hud.speed_prefix", "Швидкість: ")
language.Add("npcpassengers.hud.npc_prefix", "NPC: ")
language.Add("npcpassengers.hud.on", "Увімкнено")
language.Add("npcpassengers.hud.off", "Вимкнено")
language.Add("npcpassengers.hud.passengers", "Пасажири")
language.Add("npcpassengers.hud.npc_driver", "Водій NPC")
language.Add("npcpassengers.hud.total_prefix", "Всього: ")
language.Add("npcpassengers.hud.showing_prefix", "Показано: ")
language.Add("npcpassengers.hud.current_vehicle_prefix", "Поточний транспорт: ")
language.Add("npcpassengers.hud.hidden_prefix", "Приховано: ")
language.Add("npcpassengers.hud.dead_prefix", "Мертвий: ")
language.Add("npcpassengers.hud.scared_prefix", "Наляканий: ")
language.Add("npcpassengers.hud.drowsy_prefix", "Сонливий: ")

-- Status labels
language.Add("npcpassengers.status.calm", "Спокійний")
language.Add("npcpassengers.status.alert", "Тривога")
language.Add("npcpassengers.status.scared", "Наляканий")
language.Add("npcpassengers.status.drowsy", "Сонливий")
language.Add("npcpassengers.status.dead", "Мертвий")
language.Add("npcpassengers.status.unknown", "Невідомо")

-- NPC display names
language.Add("npcpassengers.npc.citizen", "Громадянин")
language.Add("npcpassengers.npc.alyx", "Алікс")
language.Add("npcpassengers.npc.barney", "Барні")
language.Add("npcpassengers.npc.monk", "Отець Грегорі")
language.Add("npcpassengers.npc.vortigaunt", "Вортігонт")
language.Add("npcpassengers.npc.eli", "Елай")
language.Add("npcpassengers.npc.kleiner", "Доктор Кляйнер")
language.Add("npcpassengers.npc.mossman", "Доктор Моссман")
language.Add("npcpassengers.npc.breen", "Доктор Брін")
language.Add("npcpassengers.npc.dog", "Собака")

-- Sort labels
language.Add("npcpassengers.sort.vehicle", "Транспорт")
language.Add("npcassengers.sort.name", "Назва")
language.Add("npcpassengers.sort.seat", "Сидіння")
language.Add("npcpassengers.sort.health", "Здоров'я")
language.Add("npcpassengers.sort.status", "Стан")

-- Sort options
language.Add("npcpassengers.sort.vehicle_first", "Транспорт першим")
language.Add("npcpassengers.sort.name_az", "Назва А-Я")
language.Add("npcpassengers.sort.seat_number", "Номер сидіння")
language.Add("npcpassengers.sort.highest_health", "Найвище здоров'я")
language.Add("npcpassengers.sort.status_priority", "Пріоритет стану")

-- Additional UI strings
language.Add("npcpassengers.ui.vehicle_unknown", "Транспорт: Невідомо")
language.Add("npcpassengers.ui.seat_prefix", "Сидіння ")
language.Add("npcpassengers.ui.same_vehicle", "Той самий транспорт")
language.Add("npcpassengers.ui.other_vehicle", "Інший транспорт")
language.Add("npcpassengers.ui.hidden", "Приховано")
language.Add("npcpassengers.ui.visible", "Видимо")
language.Add("npcpassengers.ui.health_format", "Здоров'я %d / %d")
language.Add("npcpassengers.ui.refresh_list", "Оновити список пасажирів")
language.Add("npcpassengers.ui.copy_list", "Копіювати видимий список пасажирів")
language.Add("npcpassengers.ui.make_exit", "Змусити пасажирів поточного транспорту вийти")
language.Add("npcpassengers.ui.reset_pos", "Скинути позицію та кути")
language.Add("npcpassengers.ui.crash_reactions", "Реакції на аварії")

-- Section headers
language.Add("npcpassengers.section.board_exit_sounds", "Звуки посадки/виходу")
language.Add("npcpassengers.section.ambient_sounds", "Фонові звуки")
language.Add("npcpassengers.section.gesture_animations", "Анімації жестів")
language.Add("npcpassengers.section.threat_awareness", "Усвідомлення загрози")
language.Add("npcpassengers.section.emotional_states", "Емоційні стани")
language.Add("npcpassengers.section.turret_control", "Керування туреллю (експериментально)")
language.Add("npcpassengers.section.turret_blacklist", "Чорний список NPC турелі")
language.Add("npcpassengers.section.idle_chatter", "Розмови бездіяльності")
language.Add("npcpassengers.section.body_physics", "Фізика тіла")
language.Add("npcpassengers.section.npc_auto_driver", "Автопілот NPC")

-- HUD positions
language.Add("npcpassengers.hud.bottom_left", "Знизу зліва")
language.Add("npcpassengers.hud.bottom_right", "Знизу справа")

-- Button labels
language.Add("npcpassengers.ui.enable_hud", "Увімкнути HUD пасажирів")
language.Add("npcpassengers.ui.cover_face", "Закрити обличчя")
language.Add("npcpassengers.ui.apply_keybinds", "Застосувати рекомендовані прив'язки клавіш")
language.Add("npcpassengers.ui.clear_keybinds", "Очистити всі прив'язки клавіш")

-- Debugging buttons
language.add("npcpassengers.ui.test_flinch", "Тестувати реакцію на удар")
language.Add("npcpassengers.ui.test_random", "Тестувати випадковий жест")
language.Add("npcpassengers.ui.reset_states", "Скинути всі стани")

-- Interface buttons
language.Add("npcpassengers.ui.enable_context", "Увімкнути всі опції контекстного меню")
language.Add("npcpassengers.ui.hide_context", "Приховати всі опції контекстного меню")
language.Add("npcpassengers.ui.set_compact", "Встановити компактний розмір панелі")
language.Add("npcpassengers.ui.set_default", "Встановити стандартний розмір панелі")
language.Add("npcpassengers.ui.set_large", "Встановити великий розмір панелі")
language.Add("npcpassengers.ui.center_panel", "Центрувати панель зараз")
language.Add("npcpassengers.ui.reset_ui", "Скинути всі налаштування інтерфейсу до стандартних")

-- Role names
language.Add("npcpassengers.role.citizen_female", "Громадянка")
language.Add("npcpassengers.role.citizen_male", "Громадянин")
language.Add("npcpassengers.role.medic", "Медик")
language.Add("npcpassengers.role.rebel", "Повстанець")
language.Add("npcpassengers.role.passenger", "Пасажир")

-- Final checkbox labels
language.Add("npcpassengers.hud.only_when_in_vehicle", "Показувати тільки коли ви в транспорті")
language.Add("npcpassengers.hud.show_calm", "Показувати спокійних пасажирів")
language.Add("npcpassengers.hud.show_hints", "Показувати контекстні підказки")
language.Add("npcpassengers.hud.show_target_debug", "Показувати налагодження цілі")
language.Add("npcpassengers.hud.play_cues", "Відтворювати сигнали успіху/невдачі")
language.Add("npcpassengers.debug.enable_mode", "Увімкнути режим налагодження")
language.Add("npcpassengers.ui.enable_sounds", "Увімкнути звуки інтерфейсу")
language.Add("npcpassengers.ui.hover_sounds", "Звуки наведення")
language.Add("npcpassengers.ui.click_sounds", "Звуки кліку")
language.Add("npcpassengers.ui.enable_animations", "Увімкнути анімації інтерфейсу")
language.Add("npcpassengers.ui.show_tooltips", "Показувати підказки")
language.Add("npcpassengers.ui.auto_hide_scrollbar", "Автоматично ховати смугу прокрутки")
language.Add("npcpassengers.ui.sidebar_scroll_smoothness", "Плавність прокрутки бічної панелі")
language.Add("npcpassengers.ui.color_theme", "Система кольорів")
language.Add("npcpassengers.ui.font_scale", "Масштаб шрифту")

-- Context menu labels
language.Add("npcpassengers.context.cancel_selection", "Скасувати вибір NPC")
language.Add("npcpassengers.context.remove_passenger", "Видалити пасажира")
language.Add("npcpassengers.context.blacklist_passenger", "Додати до чорного списку")
language.Add("npcpassengers.context.whitelist_passenger", "Додати до білого списку")

-- Keybinds
language.Add("npcpassengers.keybinds.header", "Прив'язки клавіш")
language.Add("npcpassengers.keybinds.desc", "Налаштування клавіатурних скорочень для швидких дій.")
language.Add("npcpassengers.keybind.attach", "Прикріпити найближчий NPC")
language.Add("npcpassengers.keybind.attach.help", "Прикріплює найближчий дружній NPC до вашого транспорту.")
language.Add("npcpassengers.keybind.detach_all", "Відкріпити всіх NPC")
language.Add("npcpassengers.keybind.detach_all.help", "Видаляє всіх пасажирів з вашого транспорту.")
language.Add("npcpassengers.keybind.toggle_autojoin", "Перемкнути автоприєднання")
language.Add("npcpassengers.keybind.toggle_autojoin.help", "Швидко увімкнути/вимкнути автоприєднання.")
language.Add("npcpassengers.keybind.menu", "Відкрити меню налаштувань")
language.Add("npcpassengers.keybind.menu.help", "Відкриває панель налаштувань.")
language.Add("npcpassengers.keybind.exit_all", "Всі пасажири виходять")
language.Add("npcpassengers.keybind.exit_all.help", "Змушує всіх пасажирів покинути транспорт.")
language.Add("npcpassengers.keybind.toggle_hud", "Перемкнути HUD")
language.Add("npcpassengers.keybind.toggle_hud.help", "Показує/ховає HUD пасажирів.")
language.Add("npcpassengers.keybind.quick_attach", "Режим швидкого кріплення")
language.Add("npcpassengers.keybind.quick_attach.help", "Натисніть щоб швидко підняти NPC на яких ви дивитесь")
language.Add("npcpassengers.keybind.hold_fire", "NPC утримують вогонь")
language.Add("npcpassengers.keybind.hold_fire.help", "Скажіть турельним стрільцям NPC припинити стрільбу")
language.Add("npcpassengers.keybind.open_fire", "NPC відкривають вогонь")
language.Add("npcpassengers.keybind.open_fire.help", "Скажіть турельним стрільцям NPC вести вогонь по цілях")
language.Add("npcpassengers.keybind.cycle_view", "Цикл перегляду пасажира")
language.Add("npcpassengers.keybind.cycle_view.help", "Циклічно перемикає камеру між пасажирами")
language.Add("npcpassengers.keybind_cycle_hud_position", "Цикл позиції HUD")
language.Add("npcpassengers.keybind.cycle_hud_position.help", "Переміщує HUD пасажирів між чотирма кутами")
language.Add("npcpassengers.keybind.toggle_debug", "Перемкнути налагодження цілі")
language.Add("npcpassengers.keybind.toggle_debug.help", "Перемикає невелике накладання для налагодження цілі")
language.Add("npcpassengers.keybind.test_gesture", "Тестувати випадковий жест")
language.Add("npcpassengers.keybind.test_gesture.help", "Відтворює випадковий жест на найближчому пасажирі")
language.Add("npcpassengers.keybind.reset_all", "Скинути всі NPC")
language.Add("npcpassengers.keybind.reset_all.help", "Скидає стани анімації для всіх пасажирів")

-- HUD Settings
language.Add("npcassengers.hud.header", "Налаштування HUD")
language.Add("npcpassengers.hud.enable", "Увімкнути HUD")
language.Add("npcpassengers.hud.enable.help", "Відображає накладення стану пасажирів на екрані.")
language.Add("npcpassengers.hud.position", "Позиція HUD")
language.Add("npcpassengers.hud.position.help", "Де показувати HUD на екрані.")
language.Add("npcpassengers.hud.position.topleft", "Зверху зліва")
language.Add("npcpassengers.hud.position.topright", "Зверху справа")
language.Add("npcpassengers.hud.position.bottomleft", "Знизу зліва")
language.Add("npcpassengers.hud.position.bottomright", "Знизу справа")
language.Add("npcpassengers.hud.scale", "Масштаб HUD")
language.Add("npcpassengers.hud.scale.help", "Множник розміру для HUD.")
language.Add("npcpassengers.hud.opacity", "Прозорість HUD")
language.Add("npcpassengers.hud.opacity.help", "Прозорість фону (0 = невидимий, 1 = суцільний).")

-- Driver Settings
language.Add("npcpassengers.driver.header", "Водій NPC")
language.Add("npcpassengers.driver.desc", "Дозволити NPC керувати транспортом для вас.")
language.Add("npcpassengers.driver.enable", "Увімкнути водіїв NPC")
language.Add("npcpassengers.driver.enable.help", "Дозволяє NPC керувати транспортами.")
language.Add("npcpassengers.driver.behavior", "Поведінка водіння")
language.Add("npcpassengers.driver.behavior.help", "Як NPC керує транспортом.")
language.Add("npcpassengers.driver.behavior.cruise", "Випадкова поїздка")
language.Add("npcpassengers.driver.behavior.follow", "Слідувати за гравцем")
language.Add("npcpassengers.driver.behavior.patrol", "Патрулювання")
language.Add("npcpassengers.driver.behavior.flee", "Втеча")
language.Add("npcpassengers.driver.behavior.parked", "Припарковано")

-- Help / FAQ
language.Add("npcpassengers.help.header", "Часті питання")
language.Add("npcpassengers.help.desc", "Швидкі відповіді на поширені питання та усунення несправностей.")
language.Add("npcpassengers.help.still_need", "Все ще потрібна допомога?")
language.Add("npcpassengers.help.community", "Приєднуйтеся до нашого спільноти Discord для підтримки!")

-- Additional navigation tabs
language.Add("npcpassengers.nav.tank", "Танк/LVS")
language.Add("npcpassengers.nav.debugging", "Налагодження")
language.Add("npcpassengers.nav.driver", "Водій NPC")
language.Add("npcpassengers.nav.interface", "Інтерфейс")
language.Add("npcassengers.nav.simulate", "Симуляція")
language.Add("npcpassengers.nav.modules", "Модулі")
language.Add("npcpassengers.nav.about", "Про")
language.Add("npcpassengers.search.placeholder", "Пошук налаштувань...")

-- About page
language.Add("npcpassengers.about.description", "Розширена система пасажирів з емоційним інтелектом та реалістичною фізикою")
language.Add("npcassengers.about.feature_status", "Система станів: спокійний / тривога / страх / сонливий / мертвий")
language.Add("npcpassengers.about.feature_performance", "Продуктивність: кешування сидінь, обмежені таймери, покращені клієнтські гаки")
language.Add("npcpassengers.about.feature_filtering", "Фільтрація транспорту, відновлення повторних спроб, автоприєднання тільки для команд")
language.Add("npcpassengers.about.actions", "Дії")
language.Add("npcassengers.about.show_welcome", "Показати вітальний екран")
language.Add("npcpassengers.about.open_github", "Відкрити сторінку GitHub")
language.Add("npcpassengers.about.reset_settings", "Скинути всі налаштування до стандартних")

-- Status messages
language.Add("npcpassengers.status.calm", "Спокійний")
language.Add("npcpassengers.status.alert", "Тривога")
language.Add("npcpassengers.status.scared", "Наляканий")
language.Add("npcpassengers.status.drowsy", "Сонливий")
language.Add("npcpassengers.status.dead", "Мертвий")
language.Add("npcpassengers.status.calm.desc", "Розслаблений, немає близьких загроз")
language.Add("npcpassengers.status.alert.desc", "Ворог виявлено, NPC відстежує загрози")
language.Add("npcpassengers.status.scared.desc", "Небезпечне водіння (висока швидкість, аварія)")
language.Add("npcpassengers.status.drowsy.desc", "Довга тиха поїздка, NPC стають сонними")
language.Add("npcpassengers.status.dead.desc", "Здоров'я досягло нуля")

-- Chat messages
language.Add("npcpassengers.chat.autojoin_on", "Автоприєднання: Увімкнено")
language.Add("npcpassengers.chat.autojoin_off", "Автоприєднання: Вимкнено")
language.Add("npcpassengers.chat.hud_on", "HUD: Увімкнено")
language.Add("npcpassengers.chat.hud_off", "HUD: Вимкнено")
language.Add("npcpassengers.chat.prefix", "[Покращені NPC Пасажири]")

-- Error messages
language.Add("npcpassengers.error.no_vehicle", "Немає транспорту поблизу")
language.Add("npcpassengers.error.no_npc", "Немає NPC поблизу")
language.Add("npcpassengers.error.vehicle_full", "Транспорт заповнений")
language.Add("npcpassengers.error.too_far", "NPC занадто далеко від транспорту")

-- UI tooltips
language.Add("npcpassengers.tooltip.changelang", "Змінити мову")
language.Add("npcpassengers.tooltip.minimize", "Згорнути панель")
language.Add("npcpassengers.tooltip.expand", "Розгорнути панель")
language.Add("npcpassengers.tooltip.welcome", "Показати вітальний екран")

-- Additional help text for individual settings
language.Add("npcpassengers.speech_enable.help", "Головний перемикач для всіх звуків NPC. Вимкніть щоб пасажири були повністю тихими.")
language.Add("npcpassengers.speech_volume.help", "Наскільки голосно NPC говорять (0 = тихо, 100 = повна гучність).")
language.Add("npcpassengers.pitch_variation.help", "Випадкова зміна висоти звуку для більш природних звуків. 0 = однаковий, вище = більше різноманітності.")
language.Add("npcpassengers.crash_enable.help", "NPC стогнуть/кричать коли транспорт різко сповільнюється (аварія, різке гальмування).")
language.Add("npcpassengers.crash_threshold.help", "Сповільнення необхідне для виклику звуків аварії. Менше = більш чутливий.")
language.Add("npcpassengers.crash_cooldown.help", "Мінімум секунд між звуками аварії для кожного NPC.")

-- Speech/Behaviour panel additional help text
language.Add("npcpassengers.speech_idle.help", "NPC іноді розмовляють під час подорожі - коментарі, питання, зауваження.")
language.Add("npcpassengers.speech_idle_chance.help", "Ймовірність розмови для кожної перевірки. 0 = ніколи, 1 = завжди намагається говорити.")
language.Add("npcpassengers.speech_idle_interval.help", "Мінімум секунд між спробами розмови бездіяльності.")
language.Add("npcpassengers.speech_board.help", "NPC говорять при вході та виході з транспорту.")
language.Add("npcpassengers.ambient_sounds_help", "Періодичний кашель, зітхання, бурмотіння - фонові звуки життя.")
language.Add("npcpassengers.ambient_interval.help", "Середні секунди між фоновими звуками.")
language.Add("npcpassengers.animation.help", "Точне налаштування анімації NPC та руху голови.")
language.Add("npcpassengers.head_look.help", "NPC природно дивляться навколо, на гравця, крізь вікна, тощо.")
language.Add("npcpassengers.head_smooth.help", "Наскільки плавно рухається голова. Менше = швидше, більше = більш плавно.")
language.Add("npcpassengers.blink.help", "NPC моргають реалістично під час сидіння.")
language.Add("npcpassengers.breathing.help", "Непомітна анімація дихання на головах NPC.")
language.Add("npcpassengers.walk_timeout.help", "Секунди перед тим як NPC припинить йти до транспорту.")
language.Add("npcpassengers.realism.help", "Реакції на основі фізики та системи усвідомлення для максимального занурення.")
language.Add("npcpassengers.talking_gestures.help", "NPC відтворюють випадкові жести рук та тіла під час подорожі.")
language.Add("npcpassengers.gesture_chance.help", "Відсоток відтворення жесту для кожного інтервалу.")
language.Add("npcpassengers.gesture_interval.help", "Секунди між перевірками шансу жесту.")
language.Add("npcpassengers.crash_flinch.help", "NPC реагують і нахиляються вперед коли транспорт зазнає аварії або різко гальмує.")
language.Add("npcpassengers.crash_threshold_flinch.help", "Зміна швидкості необхідна для виклику реакції на удар (менше = більш чутливий).")
language.Add("npcpassengers.body_sway.help", "NPC нахиляються на поворотах, підтримуються під час прискорення/гальмування.")
language.Add("npcpassengers.body_sway_amount.help", "Наскільки NPC нахиляються з рухом транспорту.")
language.Add("npcpassengers.threat_awareness.help", "NPC автоматично дивляться в бік близьких ворогів.")
language.Add("npcpassengers.threat_range.help", "Наскільки NPC можуть виявити загрозу для відстеження голови.")
language.Add("npcpassengers.combat_alert.help", "NPC стають напруженими та реактивними коли вороги поруч.")
language.Add("npcpassengers.passenger_combat.help", "За замовчуванням вимкнено. Увімкніть це щоб дозволити озброєним пасажирам стріляти зсередини транспорту.")
language.Add("npcpassengers.passenger_combat_range.help", "Наскільки озброєні пасажири можуть отримати цілі.")
language.Add("npcpassengers.passenger_combat_accuracy.help", "Більш високі значення зменшують розкид пострілів для озброєних пасажирів.")
language.Add("npcpassengers.passenger_combat.damage.help", "Масштабує шкоду від пострілів пасажирів.")
language.Add("npcpassengers.passenger_interaction.help", "Кілька пасажирів дивляться і іноді розмовляють один з одним.")
language.Add("npcpassengers.fear_reactions.help", "NPC бояться небезпечного водіння - відкриті очі, звуки паніки.")
language.Add("npcpassengers.fear_speed_threshold.help", "Швидкість (одиниці/сек) при якій NPC починають хвилюватися.")
language.Add("npcpassengers.drowsiness.help", "NPC стають сонними під час довгих тихих поїздок - повільне моргання, хитання голови.")
language.Add("npcpassengers.drowsy_time.help", "Секунди тихого водіння перед початком сонливості.")

-- Tank/LVS panel help text
language.Add("npcpassengers.panel.tank.desc", "Налаштування для танків, APCs та транспорту LVS.")
language.Add("npcpassengers.hide_in_tanks.help", "Зробить пасажирів NPC невидимими коли вони всередині танків та APCs.")
language.Add("npcpassengers.eject_stuck_check.help", "Автоматично штовхає NPC з транспорту коли вони застрягають під час виходу. Запобігає проходженню NPC крізь транспорт при виході.")
language.Add("npcpassengers.detach_no_collide.help", "Після відкріплення NPC тимчасово проходять крізь транспорт щоб вони могли йти без зіткнення або застрягання.")
language.Add("npcpassengers.detach_no_collide_duration.help", "Як довго NPC ігнорують зіткнення з транспортом після відкріплення.")
language.Add("npcpassengers.die_with_vehicle.help", "Пасажири NPC вмирають коли їх транспорт знищується вибухом або вогнем (більш занурююче ніж їх вихід з уламків без шкоди).")
language.Add("npcpassengers.tank_driver.help", "Дозволяє NPC на сидінні водія автоматично керувати до ворогів.")
language.Add("npcpassengers.tank_driver_range.help", "Максимальна дальність водія для виявлення ворогів.")
language.Add("npcpassengers.tank_driver_distance.help", "Дистанція для утримання від ворогів.")
language.Add("npcpassengers.tank_driver_throttle.help", "Кількість дроселя (0.1 = повільно, 1 = повна швидкість).")
language.Add("npcpassengers.tank_driver_reverse.help", "Дистанція для заднього ходу від ворогів.")
language.Add("npcpassengers.tank_turret.help", "Дозволяє NPC керувати туреллю на транспорті LVS.")

-- HUD panel help text
language.Add("npcpassengers.panel.hud.desc", "Відображає стан пасажирів (емоції, тривога) на екрані під час водіння.")
language.Add("npcpassengers.hud_show_calm.help", "Коли вимкнено, показує тільки пасажирів зі станом відмінним від спокійного.")
language.Add("npcpassengers.hud_thresholds.desc", "Коли рівні емоцій перевищують ці пороги, пасажири відображають цей стан в HUD.")
language.Add("npcpassengers.hud_alert_threshold.help", "Рівень тривоги необхідний для відображення стану 'Тривога' (ворог виявлено).")
language.Add("npcpassengers.hud_fear_threshold.help", "Рівень страху необхідний для відображення стану 'Наляканий' (небезпечне водіння).")
language.Add("npcpassengers.hud_drowsy_threshold.help", "Відсоток спокійного часу необхідний для відображення стану 'Сонливий' (довга тиха поїздка).")
language.Add("npcpassengers.hud_actions.desc", "Виберіть яку дію вживають пасажири при кожній емоційній реакції.")
language.Add("npcpassengers.hud_actions_note", "Примітка: деякі дії можуть бути невидимі залежно від підтримки моделі NPC.")

-- Keybinds panel help text
language.Add("npcpassengers.panel.keybinds.desc", "Визначте кастомні прив'язки для дій пасажирів. Клікніть на кнопку і натисніть клавішу для прив'язки.")
language.Add("npcpassengers.keybinds_hud.desc", "Швидке керування HUD для відображення та переміщення накладання пасажирів.")
language.Add("npcpassengers.keybinds_debug_note", "Прив'язки налагодження працюють тільки коли режим налагодження увімкнено.")

-- Debugging panel help text
language.Add("npcpassengers.panel.debugging.desc", "Розширені інструменти налагодження для тестування поведінки NPC. Спочатку увімкніть режим налагодження в налаштуваннях.")
language.Add("npcpassengers.debug_mode.help", "Відображає кнопки тестування налагодження та дозволяє команди налагодження.")
language.Add("npcpassengers.debug_status.help", "Вручну встановлює стан пасажира для тестування. Клікніть 'Оновити список' щоб побачити поточних пасажирів.")

-- Interface panel help text
language.Add("npcpassengers.panel.interface.desc", "Налаштування звукових ефектів для кнопок, прапорців та інших елементів інтерфейсу")
language.Add("npcpassengers.ui_sounds_enabled.help", "Головний перемикач для всіх звукових ефектів інтерфейсу")
language.Add("npcpassengers.ui_sounds_volume.help", "Множник гучності для звуків інтерфейсу (1.0 = норма, 2.0 = подвійна)")
language.Add("npcpassengers.ui_hover_enabled.help", "Відтворювати звук при наведенні на кнопки")
language.Add("npcpassengers.ui_click_enabled.help", "Відтворювати звук при натисканні кнопок та прапорців")
language.Add("npcpassengers.context_menu.desc", "Виберіть які опції з'являються при кліку правою кнопкою миші на NPC")
language.Add("npcpassengers.context_make_passenger.help", "Додає NPC як пасажира до вашого поточного транспорту")
language.Add("npcpassengers.context_make_passenger_vehicle.help", "Додає NPC до певного транспорту (клік на NPC, потім на транспорт)")
language.Add("npcpassengers.context_detach.help", "Видаляє NPC з транспорту")
language.Add("npcpassengers.ui_show_welcome.help", "Показувати вітальну панель при оновленні додатку до нової версії")
language.Add("npcpassengers.ui_panel_width.help", "Ширина панелі налаштувань")
language.Add("npcpassengers.ui_panel_height.help", "Висота панелі налаштувань")
language.Add("npcpassengers.ui_animations.help", "Плавні переходи та ефекти прокрутки (може вплинути на продуктивність)")
language.Add("npcpassengers.ui_tooltips.help", "Показувати корисні підказки при наведенні на налаштування")
language.Add("npcpassengers.ui_scrollbar_autohide.help", "Показувати смугу прокрутки тільки під час прокрутки або наведення на неї.")
language.Add("npcpassengers.ui_scroll_smoothness_note", "Примітка: панель стає 70% прозорою при перетягуванні будь-якого повзунка щоб показати вміст на фоні.")
language.Add("npcpassengers.ui_scroll_smoothness.help", "Менші значення = більш плавно але повільніше (0.01-1)")
language.Add("npcpassengers.ui_color_theme.help", "Виберіть систему кольорів панелі налаштувань. Зміни застосовуються миттєво.")
language.Add("npcpassengers.ui_font_scale.help", "Множить всі розміри шрифту інтерфейсу. 1.0 = за замовчуванням, 0.5 = половина розміру, 2.0 = подвоєний розмір.")

print("[Better NPC Passengers] Ukrainian localization loaded!")
